// Spec-audit probes for [atomics.order], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <atomic>
#define SPEC_PROBE_atomic
#include "../../probe_support.hpp"
namespace p0 { using namespace std; static_assert(std::is_enum_v<std::memory_order> && !std::is_convertible_v<std::memory_order, int>); } // atomics.order#1 enum scoped
namespace p1 { using namespace std; static_assert(spec_probe::same<decltype(std::memory_order::relaxed), std::memory_order>); } // atomics.order#2 enumerator relaxed
namespace p2 { using namespace std; static_assert(spec_probe::same<decltype(std::memory_order::acquire), std::memory_order>); } // atomics.order#3 enumerator acquire
namespace p3 { using namespace std; static_assert(spec_probe::same<decltype(std::memory_order::release), std::memory_order>); } // atomics.order#4 enumerator release
namespace p4 { using namespace std; static_assert(spec_probe::same<decltype(std::memory_order::acq_rel), std::memory_order>); } // atomics.order#5 enumerator acq_rel
namespace p5 { using namespace std; static_assert(spec_probe::same<decltype(std::memory_order::seq_cst), std::memory_order>); } // atomics.order#6 enumerator seq_cst
