// Spec-audit probes for [rand.synopsis], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <random>
#define SPEC_PROBE_random
#include "../../probe_support.hpp"
namespace p0 { using namespace std; using std::uniform_random_bit_generator; } // rand.synopsis#1 presence
namespace p1 { using namespace std; using std::linear_congruential_engine; } // rand.synopsis#2 presence
namespace p2 { using namespace std; using std::subtract_with_carry_engine; } // rand.synopsis#4 presence
namespace p3 { using namespace std; using std::discard_block_engine; } // rand.synopsis#5 presence
namespace p4 { using namespace std; using std::independent_bits_engine; } // rand.synopsis#6 presence
namespace p5 { using namespace std; using std::philox_engine; } // rand.synopsis#8 presence
namespace p6 { using namespace std; using T = std::minstd_rand0; } // rand.synopsis#9 type exists (exposition-only or unspecified: see below)
namespace p7 { using namespace std; using T = std::minstd_rand; } // rand.synopsis#10 type exists (exposition-only or unspecified: see below)
namespace p8 { using namespace std; using T = std::mt19937; } // rand.synopsis#11 type exists (exposition-only or unspecified: see below)
namespace p9 { using namespace std; using T = std::mt19937_64; } // rand.synopsis#12 type exists (exposition-only or unspecified: see below)
namespace p10 { using namespace std; using T = std::ranlux24_base; } // rand.synopsis#13 type exists (exposition-only or unspecified: see below)
namespace p11 { using namespace std; using T = std::ranlux48_base; } // rand.synopsis#14 type exists (exposition-only or unspecified: see below)
namespace p12 { using namespace std; using T = std::ranlux24; } // rand.synopsis#15 type exists (exposition-only or unspecified: see below)
namespace p13 { using namespace std; using T = std::ranlux48; } // rand.synopsis#16 type exists (exposition-only or unspecified: see below)
namespace p14 { using namespace std; using T = std::philox4x32; } // rand.synopsis#18 type exists (exposition-only or unspecified: see below)
namespace p15 { using namespace std; using T = std::philox4x64; } // rand.synopsis#19 type exists (exposition-only or unspecified: see below)
namespace p16 { using namespace std; using std::uniform_int_distribution; } // rand.synopsis#24 presence
