// Spec-audit probes for [version.syn@cwchar], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <cwchar>
#define SPEC_PROBE_cwchar
#include "../../probe_support.hpp"
#if !defined(__cpp_lib_freestanding_cwchar) || (__cpp_lib_freestanding_cwchar) != 202306L
static_assert(false, "__cpp_lib_freestanding_cwchar"); // version.syn@cwchar#1 macro value 202306L
#endif
