// libycxx core: the Unicode algorithms of <format>: decoding code unit sequences, the field
// width of [format.string.std]/12-13 (the width of the first code point of each extended
// grapheme cluster, UAX #29) and the escaped representation of [format.string.escaped].
//
// char strings are UTF-8 when the ordinary literal encoding is UTF-8, wchar_t strings UTF-32
// (or UTF-16 where wchar_t has 16 bits); in any other encoding a code unit is a character of
// width 1. The property tables (format_unicode_tables.hpp) are generated by
// tools/gen_unicode_tables.py from the Unicode Character Database.
#pragma once

#include <ycxx/config.hpp>
#include <ycxx/core/cstddef.hpp>
#include <ycxx/core/format_unicode_tables.hpp>

namespace [[gnu::visibility("hidden")]] ycxx { namespace detail::uni {

// The encoding form of charT's literals: 8, 16 or 32 (UTF-8/16/32), 0 for anything else.
consteval int literal_encoding_char() {
  constexpr char s[] = "é";
  return sizeof(s) == 3 && static_cast<unsigned char>(s[0]) == 0xc3 && static_cast<unsigned char>(s[1]) == 0xa9 ? 8 : 0;
}
consteval int literal_encoding_wchar() {
  constexpr wchar_t s[] = L"\U0001F600";
  if constexpr (sizeof(wchar_t) >= 4)
    return sizeof(s) / sizeof(wchar_t) == 2 && static_cast<unsigned long>(s[0]) == 0x1F600 ? 32 : 0;
  else
    return sizeof(s) / sizeof(wchar_t) == 3 && static_cast<unsigned long>(s[0]) == 0xD83D ? 16 : 0;
}
template <class charT>
inline constexpr int encoding = __is_same(charT, char) ? literal_encoding_char() : literal_encoding_wchar();

// One code unit sequence: a code point (`ok`), or a maximal ill-formed subsequence of `len`
// code units (Unicode 3.9, U+FFFD substitution of maximal subparts).
struct decoded {
  char32_t cp;
  unsigned len;
  bool ok;
};

template <class charT>
constexpr decoded decode(const charT* p, const charT* e) noexcept {
  if constexpr (encoding<charT> == 8) {
    const unsigned b0 = static_cast<unsigned char>(*p);
    if (b0 < 0x80)
      return {b0, 1, true};
    unsigned n;
    unsigned lo = 0x80, hi = 0xbf;
    if (b0 < 0xc2)
      return {0, 1, false};
    else if (b0 < 0xe0)
      n = 2;
    else if (b0 < 0xf0) {
      n = 3;
      if (b0 == 0xe0)
        lo = 0xa0;
      else if (b0 == 0xed)
        hi = 0x9f; // no surrogates
    } else if (b0 < 0xf5) {
      n = 4;
      if (b0 == 0xf0)
        lo = 0x90;
      else if (b0 == 0xf4)
        hi = 0x8f; // nothing above U+10FFFF
    } else
      return {0, 1, false};
    char32_t cp = b0 & (0x7f >> n);
    for (unsigned i = 1; i != n; ++i) {
      if (p + i == e)
        return {0, i, false};
      const unsigned b = static_cast<unsigned char>(p[i]);
      if (b < lo || b > hi)
        return {0, i, false};
      lo = 0x80;
      hi = 0xbf;
      cp = cp << 6 | (b & 0x3f);
    }
    return {cp, n, true};
  } else if constexpr (encoding<charT> == 16) {
    const char32_t u = static_cast<char16_t>(*p);
    if (u < 0xd800 || u > 0xdfff)
      return {u, 1, true};
    if (u < 0xdc00 && p + 1 != e) {
      const char32_t v = static_cast<char16_t>(p[1]);
      if (v >= 0xdc00 && v <= 0xdfff)
        return {0x10000 + ((u - 0xd800) << 10) + (v - 0xdc00), 2, true};
    }
    return {0, 1, false};
  } else if constexpr (encoding<charT> == 32) {
    const char32_t u = static_cast<char32_t>(*p);
    return {u, 1, u <= 0x10ffff && (u < 0xd800 || u > 0xdfff)};
  } else {
    return {static_cast<unsigned char>(*p), 1, true};
  }
}

// A code unit's value as an unsigned number.
template <class charT>
constexpr unsigned long unit_value(charT c) noexcept {
  if constexpr (sizeof(charT) == 1)
    return static_cast<unsigned char>(c);
  else if constexpr (sizeof(charT) == 2)
    return static_cast<char16_t>(c);
  else
    return static_cast<char32_t>(c);
}

// The property byte of the run containing c (tables: first code point << 8 | properties).
template <std::size_t N>
constexpr unsigned run_lookup(const unsigned (&t)[N], char32_t c) noexcept {
  const unsigned key = static_cast<unsigned>(c) << 8 | 0xff;
  std::size_t lo = 0, hi = N; // t[0] starts at U+0000
  while (hi - lo > 1) {
    const std::size_t mid = lo + (hi - lo) / 2;
    if (t[mid] <= key)
      lo = mid;
    else
      hi = mid;
  }
  return t[lo] & 0xff;
}

// cluster_runs properties of c, with the Hangul syllables' LV / LVT computed.
constexpr unsigned cluster_props(char32_t c) noexcept {
  unsigned p = ::ycxx::detail::uni::run_lookup(cluster_runs, c);
  if (c >= 0xac00 && c <= 0xd7a3)
    p = (p & ~0xfu) | ((c - 0xac00) % 28 == 0 ? gcb_lv : gcb_lvt);
  return p;
}
// An ill-formed sequence counts as U+FFFD: Grapheme_Cluster_Break Other, field width 1.
inline constexpr unsigned replacement_props = gcb_other;

// The extended grapheme cluster boundary rules of UAX #29 (GB3-GB13, GB999), applied to one
// code point after another.
class cluster_breaker {
  unsigned prev_ = 0;
  bool started_ = false;
  bool ri_odd_ = false;   // an odd number of Regional_Indicator code points precedes
  unsigned char xpict_ = 0; // 1: ExtPict Extend*, 2: ExtPict Extend* ZWJ precedes
  bool linker_ = false;   // InCB=Linker InCB=Extend* precedes

public:
  // Whether a cluster starts at a code point with properties p.
  constexpr bool next(unsigned p) noexcept {
    const unsigned cur = p & 0xf, prev = prev_ & 0xf;
    const unsigned incb = (p >> 5) & 3;
    const bool pict = (p >> 4) & 1;
    bool brk;
    if (!started_)
      brk = true;
    else if (prev == gcb_cr && cur == gcb_lf)
      brk = false; // GB3
    else if (prev == gcb_cr || prev == gcb_lf || prev == gcb_control || cur == gcb_cr || cur == gcb_lf ||
             cur == gcb_control)
      brk = true; // GB4, GB5
    else if (prev == gcb_l && (cur == gcb_l || cur == gcb_v || cur == gcb_lv || cur == gcb_lvt))
      brk = false; // GB6
    else if ((prev == gcb_lv || prev == gcb_v) && (cur == gcb_v || cur == gcb_t))
      brk = false; // GB7
    else if ((prev == gcb_lvt || prev == gcb_t) && cur == gcb_t)
      brk = false; // GB8
    else if (cur == gcb_extend || cur == gcb_zwj || cur == gcb_spacingmark || prev == gcb_prepend)
      brk = false; // GB9, GB9a, GB9b
    else if (linker_ && incb == incb_consonant)
      brk = false; // GB9c
    else if (xpict_ == 2 && pict)
      brk = false; // GB11
    else if (cur == gcb_regional_indicator && prev == gcb_regional_indicator && ri_odd_)
      brk = false; // GB12, GB13
    else
      brk = true; // GB999
    ri_odd_ = cur == gcb_regional_indicator && !(prev == gcb_regional_indicator && ri_odd_ && started_);
    if (pict)
      xpict_ = 1;
    else if (xpict_ == 1 && cur == gcb_extend)
      xpict_ = 1;
    else if (xpict_ == 1 && cur == gcb_zwj)
      xpict_ = 2;
    else
      xpict_ = 0;
    linker_ = incb == incb_linker || (linker_ && incb == incb_extend);
    prev_ = p;
    started_ = true;
    return brk;
  }
};

// The field width of [p, p + n), and of its longest prefix of whole clusters whose width does not
// exceed max_width: {code units of the prefix, its width}.
struct width_result {
  std::size_t units;
  std::size_t width;
};
template <class charT>
constexpr width_result width_prefix(const charT* p, std::size_t n, std::size_t max_width) noexcept {
  if constexpr (encoding<charT> == 0) {
    const std::size_t k = n < max_width ? n : max_width;
    return {k, k};
  } else {
    const charT* const b = p;
    const charT* const e = p + n;
    // Printable ASCII: one cluster of width 1 per code unit (CR LF is the only ASCII pair that
    // forms one cluster, and it is handled below).
    std::size_t width = 0;
    while (p != e && static_cast<char32_t>(*p) >= 0x20 && static_cast<char32_t>(*p) < 0x7f) {
      if (width == max_width)
        return {static_cast<std::size_t>(p - b), width};
      ++width;
      ++p;
    }
    if (p == e)
      return {n, width};
    cluster_breaker brk;
    if (p != b)
      brk.next(::ycxx::detail::uni::cluster_props(static_cast<char32_t>(p[-1])));
    while (p != e) {
      const decoded d = ::ycxx::detail::uni::decode(p, e);
      const unsigned props = d.ok ? ::ycxx::detail::uni::cluster_props(d.cp) : replacement_props;
      if (brk.next(props)) {
        const std::size_t w = (props & 0x80) ? 2 : 1;
        if (width + w > max_width)
          return {static_cast<std::size_t>(p - b), width};
        width += w;
      }
      p += d.len;
    }
    return {n, width};
  }
}
template <class charT>
constexpr std::size_t width(const charT* p, std::size_t n) noexcept {
  return ::ycxx::detail::uni::width_prefix(p, n, static_cast<std::size_t>(-1)).width;
}

// The escaped string ([format.string.escaped]/2) or character (/3) representation of
// [p, p + n), written through put(const charT*, size_t).
template <class charT, class Put>
constexpr void escape(const charT* p, std::size_t n, bool is_char, Put&& put) {
  const charT quote = is_char ? charT('\'') : charT('"');
  put(&quote, 1);
  const charT* const e = p + n;
  bool prev_plain = false; // the previous character was appended without translation
  const auto put_hex = [&put](char kind, unsigned long v) {
    charT buf[16];
    int i = 15;
    buf[i--] = charT('}');
    do {
      buf[i--] = charT("0123456789abcdef"[v & 0xf]);
      v >>= 4;
    } while (v != 0);
    buf[i--] = charT('{');
    buf[i--] = charT(kind);
    buf[i] = charT('\\');
    put(buf + i, static_cast<std::size_t>(16 - i));
  };
  while (p != e) {
    const decoded d = ::ycxx::detail::uni::decode(p, e);
    if (!d.ok) {
      for (unsigned i = 0; i != d.len; ++i)
        put_hex('x', ::ycxx::detail::uni::unit_value(p[i]));
      prev_plain = false;
      p += d.len;
      continue;
    }
    const char32_t c = d.cp;
    charT esc = 0;
    switch (c) {
    case U'\t': esc = charT('t'); break;
    case U'\n': esc = charT('n'); break;
    case U'\r': esc = charT('r'); break;
    case U'\\': esc = charT('\\'); break;
    case U'"': esc = is_char ? charT(0) : charT('"'); break;
    case U'\'': esc = is_char ? charT('\'') : charT(0); break;
    default: break;
    }
    if (esc != 0) {
      const charT two[2] = {charT('\\'), esc};
      put(two, 2);
      prev_plain = false;
    } else {
      bool hex;
      if constexpr (encoding<charT> == 0) {
        hex = c < 0x20 || c == 0x7f;
      } else {
        const unsigned props = c < 0x7f ? (c < 0x20 ? 1u : 0u) : ::ycxx::detail::uni::run_lookup(escape_runs, c);
        hex = c != U' ' && ((props & 1) || ((props & 2) && !prev_plain));
      }
      if (hex) {
        put_hex('u', static_cast<unsigned long>(c));
        prev_plain = false;
      } else {
        put(p, d.len);
        prev_plain = true;
      }
    }
    p += d.len;
  }
  put(&quote, 1);
}

}} // namespace ycxx::detail::uni
