"""Mapping of library areas to source files in each implementation.

Paths are globs relative to each implementation's root (see IMPLS). Only file
paths of the other implementations appear here; no content.

Roots:
  ycxx  : libycxx at the audited commit (git archive of include/ and src/)
  gnu   : gcc-<ver>/libstdc++-v3 (plus libiberty's demangler, taken from the GCC tarball)
  llvm  : llvm-project at the release tag (libcxx/ and libcxxabi/ only)
  msvc  : microsoft/STL (stl/inc and stl/src only)
  cxxrt : libcxxrt (optional; ABI runtime areas only)
"""

IMPL_NAMES = {
    "ycxx": "libycxx",
    "gnu": "libstdc++",
    "llvm": "libc++/libc++abi",
    "msvc": "MSVC STL",
    "cxxrt": "libcxxrt",
    "llvm03": "libc++ C++03 fork",
    "kokkos": "Kokkos mdspan",
    "beman": "Beman project",
}

FOREIGN = ["gnu", "llvm", "msvc"]

# Everything that is "the library" for whole-corpus fingerprints.
CORPUS = {
    "ycxx": ["include/**/*", "src/**/*"],
    "gnu": ["include/**/*", "src/**/*", "libsupc++/**/*", "config/**/*", "@extra/libiberty/cp-demangle.c",
            "@extra/libiberty/cp-demangle.h"],
    "llvm": ["libcxx/include/**/*", "libcxx/src/**/*", "libcxxabi/include/**/*", "libcxxabi/src/**/*"],
    "msvc": ["stl/inc/**/*", "stl/src/**/*"],
    "cxxrt": ["src/**/*"],
    "llvm03": ["libcxx/include/__cxx03/**/*"],
    "kokkos": ["include/mdspan/*.hpp", "include/experimental/**/*.hpp"],
    "beman": ["optional/include/**/*.hpp", "inplace_vector/include/**/*.hpp"],
}

# Directories / files never compared (frozen duplicates, generated tables of
# data that are not code, build files, tests).
EXCLUDE = {
    "ycxx": [],
    "gnu": ["include/tr1/**", "include/tr2/**", "include/ext/pb_ds/**", "include/parallel/**",
            "include/debug/**", "include/backward/**", "include/decimal/**", "include/experimental/**",
            "include/profile/**", "src/c++17/fast_float/**", "**/Makefile*", "**/*.am", "**/*.in",
            "**/*.zi", "include/bits/version.def", "include/bits/version.tpl", "config/abi/**",
            "config/os/**", "config/cpu/**", "config/io/**", "config/allocator/**", "config/**/*.ver",
            "src/c++23/std*.cc.in", "src/libbacktrace/**", "src/filesystem/**", "src/experimental/**"],
    "llvm": ["libcxx/include/__cxx03/**", "libcxx/include/experimental/**", "libcxx/include/ext/**",
             "libcxx/src/support/ibm/**", "libcxx/src/support/win32/**", "**/CMakeLists.txt",
             "**/*.modulemap*", "libcxx/include/__config_site.in", "libcxxabi/src/aix_state_tab_eh.inc"],
    "msvc": ["stl/src/*.asm", "stl/src/*.src", "stl/inc/header-units.json"],
    "cxxrt": ["**/CMakeLists.txt"],
    "llvm03": ["**/*.modulemap*", "**/__config_site.in"],
}

SOURCE_SUFFIXES = (".h", ".hpp", ".hh", ".tcc", ".c", ".cc", ".cpp", ".cxx", ".inc", "")

# area -> impl -> globs. Files may appear in several areas.
AREAS = {
    "vector": {
        "ycxx": ["include/ycxx/core/vector.hpp", "include/ycxx/core/vector_bool.hpp"],
        "gnu": ["include/bits/stl_vector.h", "include/bits/vector.tcc", "include/bits/stl_bvector.h"],
        "llvm": ["libcxx/include/__vector/*", "libcxx/include/vector", "libcxx/include/__bit_reference",
                 "libcxx/include/__split_buffer"],
        "msvc": ["stl/inc/vector"],
    },
    "string": {
        "ycxx": ["include/ycxx/core/basic_string.hpp", "include/ycxx/core/char_traits.hpp",
                 "src/hosted/string.cpp", "src/hosted/string_io.cpp"],
        "gnu": ["include/bits/basic_string.h", "include/bits/basic_string.tcc", "include/bits/char_traits.h"],
        "llvm": ["libcxx/include/string", "libcxx/include/__string/*", "libcxx/src/string.cpp"],
        "msvc": ["stl/inc/xstring", "stl/inc/string"],
    },
    "string_view": {
        "ycxx": ["include/ycxx/core/string_view.hpp"],
        "gnu": ["include/std/string_view", "include/bits/string_view.tcc"],
        "llvm": ["libcxx/include/string_view"],
        "msvc": ["stl/inc/__msvc_string_view.hpp"],
    },
    "algorithm": {
        "ycxx": ["include/ycxx/core/algo_base.hpp", "include/ycxx/core/algo_mutate.hpp",
                 "include/ycxx/core/algo_nonmod.hpp", "include/ycxx/core/algo_results.hpp",
                 "include/ycxx/core/compare_alg.hpp"],
        "gnu": ["include/bits/stl_algo.h", "include/bits/stl_algobase.h", "include/bits/ranges_algo.h",
                "include/bits/ranges_algobase.h", "include/bits/ranges_util.h", "include/bits/predefined_ops.h"],
        "llvm": ["libcxx/include/__algorithm/*"],
        "msvc": ["stl/inc/algorithm", "stl/inc/xutility", "stl/inc/__msvc_minmax.hpp"],
    },
    "sort_heap": {
        "ycxx": ["include/ycxx/core/algo_sort.hpp"],
        "gnu": ["include/bits/stl_algo.h", "include/bits/stl_heap.h", "include/bits/stl_tempbuf.h"],
        "llvm": ["libcxx/include/__algorithm/sort.h", "libcxx/include/__algorithm/stable_sort.h",
                 "libcxx/include/__algorithm/partial_sort*.h", "libcxx/include/__algorithm/nth_element.h",
                 "libcxx/include/__algorithm/inplace_merge.h", "libcxx/include/__algorithm/*heap*.h",
                 "libcxx/include/__algorithm/sift_down.h", "libcxx/include/__algorithm/ranges_sort.h",
                 "libcxx/include/__algorithm/ranges_stable_sort.h", "libcxx/include/__memory/*temporary_buffer.h",
                 "libcxx/src/algorithm.cpp"],
        "msvc": ["stl/inc/algorithm", "stl/inc/__msvc_heap_algorithms.hpp"],
    },
    "parallel_algorithms": {
        "ycxx": ["include/ycxx/core/algo_parallel.hpp", "include/ycxx/core/algo_ranges_parallel.hpp",
                 "include/ycxx/core/numeric_parallel.hpp", "include/ycxx/core/uninitialized_parallel.hpp",
                 "include/ycxx/core/execution_policy.hpp"],
        "gnu": ["include/pstl/*"],
        "llvm": ["libcxx/include/__pstl/**/*", "libcxx/include/__algorithm/pstl*.h",
                 "libcxx/include/__numeric/pstl*.h", "libcxx/src/pstl/**/*"],
        "msvc": ["stl/inc/execution", "stl/src/parallel_algorithms.cpp"],
    },
    "type_traits": {
        "ycxx": ["include/ycxx/core/type_traits.hpp", "include/ycxx/core/type_traits_depr.hpp",
                 "include/ycxx/core/prim_traits.hpp", "include/ycxx/core/meta_base.hpp"],
        "gnu": ["include/std/type_traits", "include/bits/cpp_type_traits.h"],
        "llvm": ["libcxx/include/__type_traits/*", "libcxx/include/type_traits"],
        "msvc": ["stl/inc/type_traits", "stl/inc/xtr1common"],
    },
    "tuple": {
        "ycxx": ["include/ycxx/core/tuple.hpp", "include/ycxx/core/tuple_like.hpp"],
        "gnu": ["include/std/tuple"],
        "llvm": ["libcxx/include/tuple", "libcxx/include/__tuple/*"],
        "msvc": ["stl/inc/tuple"],
    },
    "variant": {
        "ycxx": ["include/ycxx/core/variant.hpp"],
        "gnu": ["include/std/variant"],
        "llvm": ["libcxx/include/variant", "libcxx/include/__variant/*"],
        "msvc": ["stl/inc/variant"],
    },
    "optional_expected": {
        "ycxx": ["include/ycxx/core/optional.hpp", "include/ycxx/core/expected.hpp"],
        "gnu": ["include/std/optional", "include/std/expected"],
        "llvm": ["libcxx/include/optional", "libcxx/include/__expected/*"],
        "msvc": ["stl/inc/optional", "stl/inc/expected"],
    },
    "functional": {
        "ycxx": ["include/ycxx/core/function_wrappers.hpp", "include/ycxx/core/bind.hpp",
                 "include/ycxx/core/functional_base.hpp", "include/ycxx/core/invoke.hpp",
                 "include/ycxx/core/searcher.hpp"],
        "gnu": ["include/std/functional", "include/bits/std_function.h", "include/bits/funcwrap.h",
                "include/bits/mofunc_impl.h", "include/bits/cpyfunc_impl.h", "include/bits/funcref_impl.h",
                "include/bits/refwrap.h", "include/bits/invoke.h", "include/bits/stl_function.h"],
        "llvm": ["libcxx/include/__functional/*", "libcxx/include/functional"],
        "msvc": ["stl/inc/functional"],
    },
    "smart_pointers": {
        "ycxx": ["include/ycxx/core/shared_ptr.hpp", "include/ycxx/core/unique_ptr.hpp",
                 "include/ycxx/core/atomic_smart_ptr.hpp", "include/ycxx/core/out_ptr.hpp",
                 "include/ycxx/core/indirect.hpp", "include/ycxx/core/polymorphic.hpp"],
        "gnu": ["include/bits/shared_ptr.h", "include/bits/shared_ptr_base.h", "include/bits/shared_ptr_atomic.h",
                "include/bits/unique_ptr.h", "include/bits/out_ptr.h", "include/bits/indirect.h",
                "src/c++11/shared_ptr.cc"],
        "llvm": ["libcxx/include/__memory/shared_ptr.h", "libcxx/include/__memory/shared_count.h",
                 "libcxx/include/__memory/unique_ptr.h", "libcxx/include/__memory/*out_ptr.h",
                 "libcxx/src/memory.cpp"],
        "msvc": ["stl/inc/memory"],
    },
    "allocators_memory": {
        "ycxx": ["include/ycxx/core/memory_base.hpp", "include/ycxx/core/uninitialized.hpp",
                 "include/ycxx/core/scoped_allocator.hpp", "include/ycxx/core/memory_resource.hpp",
                 "include/ycxx/hosted/memory_resource.hpp", "src/hosted/memory_resource.cpp"],
        "gnu": ["include/bits/alloc_traits.h", "include/bits/allocator.h", "include/bits/new_allocator.h",
                "include/bits/ptr_traits.h", "include/bits/stl_uninitialized.h", "include/bits/stl_construct.h",
                "include/std/scoped_allocator", "include/bits/memory_resource.h", "include/std/memory_resource",
                "src/c++17/memory_resource.cc", "include/bits/uses_allocator*.h"],
        "llvm": ["libcxx/include/__memory/allocat*.h", "libcxx/include/__memory/pointer_traits.h",
                 "libcxx/include/__memory/uninitialized_algorithms.h", "libcxx/include/__memory/construct_at.h",
                 "libcxx/include/scoped_allocator", "libcxx/include/__memory_resource/*",
                 "libcxx/src/memory_resource.cpp", "libcxx/include/__memory/uses_allocator*.h"],
        "msvc": ["stl/inc/xmemory", "stl/inc/scoped_allocator", "stl/inc/memory_resource",
                 "stl/inc/xpolymorphic_allocator.h", "stl/src/memory_resource.cpp"],
    },
    "hash_tables": {
        "ycxx": ["include/ycxx/core/hash_table.hpp", "include/ycxx/core/unordered_map.hpp",
                 "include/ycxx/core/unordered_set.hpp", "include/ycxx/core/hash.hpp"],
        "gnu": ["include/bits/hashtable.h", "include/bits/hashtable_policy.h", "include/bits/unordered_map.h",
                "include/bits/unordered_set.h", "src/c++11/hashtable_c++0x.cc", "src/shared/hashtable-aux.cc",
                "include/bits/functional_hash.h", "libsupc++/hash_bytes.cc"],
        "llvm": ["libcxx/include/__hash_table", "libcxx/include/unordered_map", "libcxx/include/unordered_set",
                 "libcxx/src/hash.cpp", "libcxx/include/__functional/hash.h"],
        "msvc": ["stl/inc/xhash", "stl/inc/unordered_map", "stl/inc/unordered_set"],
    },
    "rb_tree_map_set": {
        "ycxx": ["include/ycxx/core/rb_tree.hpp", "include/ycxx/core/map.hpp", "include/ycxx/core/set.hpp",
                 "include/ycxx/core/assoc_support.hpp", "include/ycxx/core/node_handle.hpp"],
        "gnu": ["include/bits/stl_tree.h", "include/bits/stl_map.h", "include/bits/stl_multimap.h",
                "include/bits/stl_set.h", "include/bits/stl_multiset.h", "src/c++98/tree.cc",
                "include/bits/node_handle.h"],
        "llvm": ["libcxx/include/__tree", "libcxx/include/map", "libcxx/include/set", "libcxx/include/__node_handle"],
        "msvc": ["stl/inc/xtree", "stl/inc/map", "stl/inc/set", "stl/inc/xnode_handle.h"],
    },
    "deque": {
        "ycxx": ["include/ycxx/core/deque.hpp"],
        "gnu": ["include/bits/stl_deque.h", "include/bits/deque.tcc"],
        "llvm": ["libcxx/include/deque"],
        "msvc": ["stl/inc/deque"],
    },
    "list_forward_list": {
        "ycxx": ["include/ycxx/core/list.hpp", "include/ycxx/core/forward_list.hpp"],
        "gnu": ["include/bits/stl_list.h", "include/bits/list.tcc", "include/bits/forward_list.h",
                "include/bits/forward_list.tcc", "src/c++98/list.cc"],
        "llvm": ["libcxx/include/list", "libcxx/include/forward_list"],
        "msvc": ["stl/inc/list", "stl/inc/forward_list"],
    },
    "flat_containers": {
        "ycxx": ["include/ycxx/core/flat_map.hpp", "include/ycxx/core/flat_set.hpp",
                 "include/ycxx/core/flat_support.hpp"],
        "gnu": ["include/std/flat_map", "include/std/flat_set"],
        "llvm": ["libcxx/include/__flat_map/*", "libcxx/include/__flat_set/*"],
        "msvc": ["stl/inc/flat_map", "stl/inc/flat_set"],
    },
    "charconv": {
        "ycxx": ["include/ycxx/core/charconv.hpp", "src/runtime/charconv/*", "src/hosted/strfrom.cpp"],
        "gnu": ["include/bits/charconv.h", "include/std/charconv", "src/c++17/floating_from_chars.cc",
                "src/c++17/floating_to_chars.cc", "src/c++17/ryu/*", "src/c++11/charconv*.cc"],
        "llvm": ["libcxx/include/__charconv/*", "libcxx/include/charconv", "libcxx/src/charconv.cpp",
                 "libcxx/src/include/ryu/*", "libcxx/src/ryu/*", "libcxx/src/include/to_chars_floating_point.h",
                 "libcxx/src/include/from_chars_floating_point.h"],
        "msvc": ["stl/inc/charconv", "stl/inc/xcharconv*.h", "stl/src/charconv.cpp", "stl/src/xcharconv*.cpp"],
    },
    "format_print": {
        "ycxx": ["include/ycxx/core/format_*.hpp", "include/ycxx/hosted/format_locale.hpp",
                 "include/ycxx/hosted/print.hpp", "include/ycxx/hosted/ostream_print.hpp",
                 "src/hosted/format*.cpp", "src/hosted/print*.cpp"],
        "gnu": ["include/std/format", "include/bits/formatfwd.h", "include/bits/unicode.h",
                "include/bits/unicode-data.h", "src/c++20/format.cc", "include/std/print", "include/bits/print.h",
                "include/bits/ostream_print.h", "src/c++23/print.cc"],
        "llvm": ["libcxx/include/__format/*", "libcxx/include/format", "libcxx/include/print",
                 "libcxx/src/print.cpp"],
        "msvc": ["stl/inc/format", "stl/inc/__msvc_formatter.hpp", "stl/inc/__msvc_format_ucd_tables.hpp",
                 "stl/inc/print", "stl/inc/__msvc_print.hpp", "stl/src/format.cpp", "stl/src/print.cpp",
                 "stl/inc/__msvc_ranges_tuple_formatter.hpp"],
    },
    "regex": {
        "ycxx": ["include/ycxx/hosted/regex*.hpp", "src/hosted/regex.cpp"],
        "gnu": ["include/bits/regex*.h", "include/bits/regex*.tcc", "include/std/regex", "src/c++11/regex.cc"],
        "llvm": ["libcxx/include/regex", "libcxx/src/regex.cpp"],
        "msvc": ["stl/inc/regex", "stl/src/regex.cpp"],
    },
    "chrono": {
        "ycxx": ["include/ycxx/core/chrono_*.hpp", "include/ycxx/hosted/chrono_*.hpp",
                 "include/ycxx/hosted/file_clock.hpp", "src/hosted/chrono.cpp", "src/hosted/tzdb.cpp",
                 "src/hosted/time.cpp", "src/hosted/ctime.cpp"],
        "gnu": ["include/std/chrono", "include/bits/chrono.h", "include/bits/chrono_io.h", "src/c++20/tzdb.cc",
                "src/c++20/clock.cc", "src/c++11/chrono.cc"],
        "llvm": ["libcxx/include/__chrono/*", "libcxx/include/chrono", "libcxx/src/chrono.cpp",
                 "libcxx/src/experimental/tzdb*.cpp", "libcxx/src/experimental/time_zone.cpp",
                 "libcxx/src/experimental/include/**/*"],
        "msvc": ["stl/inc/chrono", "stl/inc/__msvc_chrono.hpp", "stl/inc/__msvc_tzdb.hpp", "stl/src/tzdb.cpp",
                 "stl/inc/xtimec.h", "stl/src/xtime.cpp"],
    },
    "atomic_sync": {
        "ycxx": ["include/ycxx/core/atomic*.hpp", "src/runtime/atomic/*", "src/freestanding/pal/wa*.cpp",
                 "include/ycxx/hosted/semaphore.hpp", "include/ycxx/hosted/latch.hpp",
                 "include/ycxx/core/stop_token.hpp"],
        "gnu": ["include/std/atomic", "include/bits/atomic_base.h", "include/bits/atomic_wait.h",
                "include/bits/atomic_timed_wait.h", "include/bits/semaphore_base.h", "src/c++20/atomic.cc",
                "include/std/stop_token", "include/std/latch", "include/std/semaphore", "include/std/barrier",
                "include/bits/atomic_futex.h", "src/c++11/futex.cc"],
        "llvm": ["libcxx/include/__atomic/*", "libcxx/include/atomic", "libcxx/src/atomic.cpp",
                 "libcxx/include/__stop_token/*", "libcxx/include/latch", "libcxx/include/semaphore",
                 "libcxx/include/barrier", "libcxx/src/barrier.cpp", "libcxx/src/include/atomic_support.h"],
        "msvc": ["stl/inc/atomic", "stl/inc/xatomic*.h", "stl/src/atomic*.cpp", "stl/inc/stop_token",
                 "stl/inc/latch", "stl/inc/semaphore", "stl/inc/barrier"],
    },
    "threads": {
        "ycxx": ["include/ycxx/hosted/thread*.hpp", "include/ycxx/hosted/mutex.hpp",
                 "include/ycxx/hosted/shared_mutex.hpp", "include/ycxx/hosted/condition_variable.hpp",
                 "include/ycxx/hosted/future.hpp", "src/hosted/thread.cpp", "src/hosted/future.cpp"],
        "gnu": ["include/std/thread", "include/bits/std_thread.h", "include/std/mutex", "include/bits/std_mutex.h",
                "include/bits/unique_lock.h", "include/std/shared_mutex", "include/std/condition_variable",
                "include/std/future", "src/c++11/thread.cc", "src/c++11/future.cc", "src/c++11/mutex.cc",
                "src/c++11/condition_variable.cc"],
        "llvm": ["libcxx/include/__thread/*", "libcxx/include/thread", "libcxx/include/__mutex/*",
                 "libcxx/include/mutex", "libcxx/include/shared_mutex", "libcxx/include/__condition_variable/*",
                 "libcxx/include/condition_variable", "libcxx/include/future", "libcxx/src/thread.cpp",
                 "libcxx/src/future.cpp", "libcxx/src/mutex.cpp", "libcxx/src/condition_variable.cpp",
                 "libcxx/src/shared_mutex.cpp"],
        "msvc": ["stl/inc/thread", "stl/inc/mutex", "stl/inc/shared_mutex", "stl/inc/condition_variable",
                 "stl/inc/future", "stl/src/cthread.cpp", "stl/src/thread0.cpp", "stl/src/mutex.cpp",
                 "stl/src/cond.cpp", "stl/src/future.cpp", "stl/src/sharedmutex.cpp"],
    },
    "random": {
        "ycxx": ["include/ycxx/core/random_*.hpp", "include/ycxx/core/urbg.hpp", "src/hosted/random.cpp"],
        "gnu": ["include/bits/random.h", "include/bits/random.tcc", "include/bits/uniform_int_dist.h",
                "include/std/random", "src/c++11/random.cc"],
        "llvm": ["libcxx/include/__random/*", "libcxx/include/random", "libcxx/src/random.cpp"],
        "msvc": ["stl/inc/random", "stl/src/xrngdev.cpp", "stl/src/xrngabort.cpp"],
    },
    "iostreams": {
        "ycxx": ["include/ycxx/hosted/ios.hpp", "include/ycxx/hosted/istream.hpp", "include/ycxx/hosted/ostream.hpp",
                 "include/ycxx/hosted/streambuf.hpp", "include/ycxx/hosted/sstream.hpp",
                 "include/ycxx/hosted/fstream.hpp", "include/ycxx/hosted/iomanip.hpp",
                 "include/ycxx/hosted/syncstream.hpp", "include/ycxx/hosted/spanstream.hpp",
                 "src/hosted/ios.cpp", "src/hosted/iostream.cpp", "src/hosted/fstream*.cpp",
                 "src/hosted/syncstream.cpp"],
        "gnu": ["include/bits/basic_ios.*", "include/bits/ios_base.h", "include/std/istream",
                "include/bits/istream.tcc", "include/std/ostream", "include/bits/ostream.*",
                "include/std/streambuf", "include/bits/streambuf.tcc", "include/std/sstream",
                "include/bits/sstream.tcc", "include/std/fstream", "include/bits/fstream.tcc",
                "include/std/iomanip", "include/std/syncstream", "include/std/spanstream",
                "src/c++98/ios*.cc", "src/c++11/ios.cc", "src/c++98/streambuf.cc", "src/c++20/syncbuf.cc",
                "config/io/basic_file_stdio.cc"],
        "llvm": ["libcxx/include/__ios/*", "libcxx/include/ios", "libcxx/include/istream",
                 "libcxx/include/__ostream/*", "libcxx/include/ostream", "libcxx/include/streambuf",
                 "libcxx/include/sstream", "libcxx/include/fstream", "libcxx/include/iomanip",
                 "libcxx/include/syncstream", "libcxx/src/ios.cpp", "libcxx/src/iostream.cpp",
                 "libcxx/src/fstream.cpp", "libcxx/src/ostream.cpp"],
        "msvc": ["stl/inc/xiosbase", "stl/inc/ios", "stl/inc/istream", "stl/inc/ostream",
                 "stl/inc/__msvc_ostream.hpp", "stl/inc/streambuf", "stl/inc/sstream", "stl/inc/fstream",
                 "stl/inc/__msvc_filebuf.hpp", "stl/inc/iomanip", "stl/inc/syncstream", "stl/inc/spanstream",
                 "stl/src/ios.cpp", "stl/src/iostream.cpp", "stl/src/syncstream.cpp", "stl/src/fiopen.cpp"],
    },
    "locale": {
        "ycxx": ["include/ycxx/hosted/locale_*.hpp", "src/hosted/locale*.cpp", "src/hosted/num.cpp"],
        "gnu": ["include/bits/locale_*.h", "include/bits/locale_*.tcc", "include/bits/localefwd.h",
                "include/std/locale", "include/bits/codecvt.h", "src/c++98/locale*.cc", "src/c++11/locale_init.cc",
                "src/c++11/localename.cc", "src/c++11/codecvt.cc", "src/c++11/ctype.cc",
                "config/locale/gnu/*", "config/locale/generic/*"],
        "llvm": ["libcxx/include/__locale", "libcxx/include/__locale_dir/**/*", "libcxx/include/locale",
                 "libcxx/src/locale.cpp", "libcxx/include/codecvt"],
        "msvc": ["stl/inc/xlocale", "stl/inc/xloc*", "stl/inc/locale", "stl/inc/xfacet", "stl/src/locale*.cpp",
                 "stl/src/xlocale.cpp", "stl/src/wlocale.cpp", "stl/src/ulocale.cpp"],
    },
    "filesystem": {
        "ycxx": ["include/ycxx/hosted/filesystem*.hpp", "src/hosted/filesystem.cpp"],
        "gnu": ["include/bits/fs_*.h", "include/std/filesystem", "src/c++17/fs_*.cc"],
        "llvm": ["libcxx/include/__filesystem/*", "libcxx/include/filesystem", "libcxx/src/filesystem/*"],
        "msvc": ["stl/inc/filesystem", "stl/src/filesystem.cpp", "stl/inc/xfilesystem_abi.h"],
    },
    "ranges": {
        "ycxx": ["include/ycxx/core/ranges_*.hpp", "include/ycxx/core/range_access.hpp"],
        "gnu": ["include/std/ranges", "include/bits/ranges_base.h", "include/bits/ranges_util.h",
                "include/bits/range_access.h"],
        "llvm": ["libcxx/include/__ranges/*", "libcxx/include/ranges"],
        "msvc": ["stl/inc/ranges", "stl/inc/__msvc_ranges_to.hpp"],
    },
    "iterator": {
        "ycxx": ["include/ycxx/core/iterator_*.hpp", "include/ycxx/core/stream_iterators.hpp"],
        "gnu": ["include/bits/stl_iterator*.h", "include/bits/iterator_concepts.h", "include/bits/stream_iterator.h",
                "include/bits/streambuf_iterator.h"],
        "llvm": ["libcxx/include/__iterator/*", "libcxx/include/iterator"],
        "msvc": ["stl/inc/iterator", "stl/inc/__msvc_iter_core.hpp"],
    },
    "mdspan": {
        "ycxx": ["include/ycxx/core/mdspan*.hpp"],
        "gnu": ["include/std/mdspan"],
        "llvm": ["libcxx/include/__mdspan/*", "libcxx/include/mdspan"],
        "msvc": ["stl/inc/mdspan"],
    },
    "complex_valarray": {
        "ycxx": ["include/ycxx/core/complex.hpp", "include/ycxx/core/valarray.hpp"],
        "gnu": ["include/std/complex", "include/std/valarray", "include/bits/valarray_*.h",
                "include/bits/valarray_array.tcc", "include/bits/*slice_array.h", "include/bits/gslice*.h",
                "include/bits/mask_array.h", "include/bits/indirect_array.h"],
        "llvm": ["libcxx/include/complex", "libcxx/include/valarray", "libcxx/src/valarray.cpp"],
        "msvc": ["stl/inc/complex", "stl/inc/valarray"],
    },
    "cmath_special": {
        "ycxx": ["include/ycxx/core/cmath*.hpp", "include/ycxx/core/math_*.hpp", "src/hosted/cmath*.cpp"],
        "gnu": ["include/c_global/cmath", "include/bits/specfun.h", "include/bits/std_abs.h",
                "include/tr1/*.tcc", "include/tr1/special_function_util.h"],
        "llvm": ["libcxx/include/__math/*", "libcxx/include/cmath"],
        "msvc": ["stl/inc/cmath", "stl/src/special_math.cpp", "stl/inc/__msvc_math.hpp"],
    },
    "bitset_bit": {
        "ycxx": ["include/ycxx/core/bitset.hpp", "include/ycxx/core/bit.hpp"],
        "gnu": ["include/std/bitset", "include/std/bit"],
        "llvm": ["libcxx/include/bitset", "libcxx/include/__bit/*", "libcxx/include/bit"],
        "msvc": ["stl/inc/bitset", "stl/inc/bit", "stl/inc/__msvc_bit_utils.hpp"],
    },
    "simd": {
        "ycxx": ["include/ycxx/core/simd*.hpp"],
        "gnu": ["include/bits/simd_*.h", "include/std/simd", "include/bits/vec_ops.h"],
        "llvm": [],
        "msvc": [],
    },
    "stacktrace": {
        "ycxx": ["include/ycxx/hosted/stacktrace*.hpp", "src/hosted/stacktrace.cpp"],
        "gnu": ["include/std/stacktrace", "src/c++23/stacktrace.cc"],
        "llvm": [],
        "msvc": ["stl/inc/stacktrace", "stl/src/stacktrace.cpp"],
    },
    "exceptions_errors": {
        "ycxx": ["include/ycxx/core/exception*.hpp", "include/ycxx/core/stdexcept*.hpp",
                 "include/ycxx/core/system_error.hpp", "include/ycxx/core/errc.hpp", "src/hosted/stdexcept.cpp",
                 "src/hosted/system_error.cpp"],
        "gnu": ["libsupc++/exception*.h", "libsupc++/nested_exception.*", "include/std/stdexcept",
                "include/std/system_error", "src/c++11/system_error.cc", "src/c++98/stdexcept.cc",
                "src/c++11/cxx11-stdexcept.cc", "src/c++11/functexcept.cc", "libsupc++/eh_ptr.cc"],
        "llvm": ["libcxx/include/__exception/*", "libcxx/include/stdexcept", "libcxx/include/__system_error/*",
                 "libcxx/include/system_error", "libcxx/src/stdexcept.cpp", "libcxx/src/system_error.cpp",
                 "libcxx/src/exception.cpp", "libcxx/src/support/runtime/*"],
        "msvc": ["stl/inc/exception", "stl/inc/stdexcept", "stl/inc/system_error", "stl/src/syserror.cpp",
                 "stl/src/excptptr.cpp", "stl/src/xthrow.cpp"],
    },
    "new_delete": {
        "ycxx": ["src/freestanding/new/*", "src/hosted/new/*", "src/runtime/new/*", "include/ycxx/core/new.hpp"],
        "gnu": ["libsupc++/new*", "libsupc++/del_*", "libsupc++/new_handler.cc"],
        "llvm": ["libcxx/src/new*.cpp", "libcxxabi/src/stdlib_new_delete.cpp", "libcxx/include/new",
                 "libcxx/include/__new/*"],
        "msvc": ["stl/inc/new", "stl/src/nothrow.cpp", "stl/src/stdhndlr.cpp"],
    },
    "abi_runtime": {
        "ycxx": ["src/abi/*"],
        "gnu": ["libsupc++/eh_*.cc", "libsupc++/eh_*.h", "libsupc++/unwind-cxx.h", "libsupc++/*type_info.cc",
                "libsupc++/dyncast.cc", "libsupc++/tinfo*", "libsupc++/guard*.cc", "libsupc++/vec.cc",
                "libsupc++/pure.cc", "libsupc++/cxxabi.h", "libsupc++/atexit_thread.cc", "libsupc++/vterminate.cc"],
        "llvm": ["libcxxabi/src/cxa_*.cpp", "libcxxabi/src/cxa_*.h", "libcxxabi/src/private_typeinfo.*",
                 "libcxxabi/src/fallback_malloc.*", "libcxxabi/src/abort_message.*", "libcxxabi/include/cxxabi.h",
                 "libcxxabi/src/stdlib_typeinfo.cpp", "libcxxabi/src/stdlib_exception.cpp"],
        "msvc": [],
        "cxxrt": ["src/*.cc", "src/*.h", "src/*.c"],
    },
    "demangler": {
        "ycxx": ["src/hosted/demangle.cpp", "src/hosted/demangle.hpp", "src/hosted/cxa_demangle.cpp"],
        "gnu": ["@extra/libiberty/cp-demangle.c", "@extra/libiberty/cp-demangle.h"],
        "llvm": ["libcxxabi/src/demangle/*", "libcxxabi/src/cxa_demangle.cpp"],
        "msvc": [],
        "cxxrt": ["src/libelftc_dem_gnu3.c"],
    },
    "text_encoding": {
        "ycxx": ["include/ycxx/core/text_encoding*.hpp", "src/hosted/text_encoding.cpp"],
        "gnu": ["include/std/text_encoding", "include/bits/text_encoding-data.h", "src/c++26/text_encoding.cc"],
        "llvm": ["libcxx/include/text_encoding", "libcxx/include/__text_encoding/*", "libcxx/src/text_encoding.cpp"],
        "msvc": [],
    },
    "utility_pair_compare": {
        "ycxx": ["include/ycxx/core/pair.hpp", "include/ycxx/core/utility_base.hpp", "include/ycxx/core/compare.hpp",
                 "include/ycxx/core/concepts.hpp", "include/ycxx/core/integer_sequence.hpp",
                 "include/ycxx/core/swap.hpp", "include/ycxx/core/move.hpp"],
        "gnu": ["include/bits/stl_pair.h", "include/std/utility", "include/bits/utility.h", "libsupc++/compare",
                "include/std/concepts", "include/bits/move.h", "include/bits/intcmp.h"],
        "llvm": ["libcxx/include/__utility/*", "libcxx/include/utility", "libcxx/include/__compare/*",
                 "libcxx/include/compare", "libcxx/include/__concepts/*", "libcxx/include/concepts"],
        "msvc": ["stl/inc/utility", "stl/inc/compare", "stl/inc/concepts"],
    },
    "any_span_array_misc": {
        "ycxx": ["include/ycxx/hosted/any.hpp", "include/ycxx/core/span.hpp", "include/ycxx/core/array.hpp",
                 "include/ycxx/core/inplace_vector.hpp", "include/ycxx/core/generator.hpp",
                 "include/ycxx/core/coroutine.hpp", "include/ycxx/core/ratio.hpp", "include/ycxx/core/limits.hpp",
                 "include/ycxx/core/numeric.hpp", "include/ycxx/core/source_location.hpp"],
        "gnu": ["include/std/any", "include/std/span", "include/std/array", "include/std/inplace_vector",
                "include/std/generator", "include/std/coroutine", "include/std/ratio", "include/std/limits",
                "include/bits/stl_numeric.h", "include/std/numeric", "include/std/source_location"],
        "llvm": ["libcxx/include/any", "libcxx/include/span", "libcxx/include/array", "libcxx/include/coroutine",
                 "libcxx/include/__coroutine/*", "libcxx/include/ratio", "libcxx/include/limits",
                 "libcxx/include/__numeric/*", "libcxx/include/source_location"],
        "msvc": ["stl/inc/any", "stl/inc/span", "stl/inc/array", "stl/inc/generator", "stl/inc/coroutine",
                 "stl/inc/ratio", "stl/inc/limits", "stl/inc/numeric", "stl/inc/source_location"],
    },
}


# ---------------------------------------------------------------------------------------------
# The style control (docs/similarity/METHOD.md, "Style control"). Kept apart from AREAS so the
# main matrices are unchanged.
#
# era_*: components every library wrote fresh for C++20 or later, restricted to those files.
#   Left out for shared lineage or forced content: charconv (Ryu), parallel algorithms (PSTL),
#   text_encoding (IANA registry data). mdspan is kept, but libc++'s mdspan comes from the Kokkos
#   reference implementation (its files carry the Kokkos header), which the control below shows.
# ctl_*: the same components compared with independent modern implementations outside the
#   standard libraries: the Kokkos mdspan reference implementation (the origin of libc++'s, so
#   libc++ with Kokkos is a derived pair) and the Beman project's optional and inplace_vector.
STYLE_AREAS = {
    "era_ranges": AREAS["ranges"],
    "era_mdspan": AREAS["mdspan"],
    "era_flat": AREAS["flat_containers"],
    "era_format": AREAS["format_print"],
    "era_expected": {
        "ycxx": ["include/ycxx/core/expected.hpp"],
        "gnu": ["include/std/expected"],
        "llvm": ["libcxx/include/__expected/*"],
        "msvc": ["stl/inc/expected"],
    },
    "era_span": {
        "ycxx": ["include/ycxx/core/span.hpp"],
        "gnu": ["include/std/span"],
        "llvm": ["libcxx/include/span"],
        "msvc": ["stl/inc/span"],
    },
    "era_concepts_compare": {
        "ycxx": ["include/ycxx/core/concepts.hpp", "include/ycxx/core/compare.hpp", "include/ycxx/core/compare_alg.hpp"],
        "gnu": ["include/std/concepts", "libsupc++/compare"],
        "llvm": ["libcxx/include/__concepts/*", "libcxx/include/__compare/*"],
        "msvc": ["stl/inc/concepts", "stl/inc/compare"],
    },
    "era_bit": {
        "ycxx": ["include/ycxx/core/bit.hpp"],
        "gnu": ["include/std/bit"],
        "llvm": ["libcxx/include/__bit/*"],
        "msvc": ["stl/inc/bit", "stl/inc/__msvc_bit_utils.hpp"],
    },
    "era_stop_token": {
        "ycxx": ["include/ycxx/core/stop_token.hpp"],
        "gnu": ["include/std/stop_token"],
        "llvm": ["libcxx/include/__stop_token/*"],
        "msvc": ["stl/inc/stop_token"],
    },
    "era_generator": {
        "ycxx": ["include/ycxx/core/generator.hpp"],
        "gnu": ["include/std/generator"],
        "msvc": ["stl/inc/generator"],
    },
    "ctl_mdspan": dict(AREAS["mdspan"], kokkos=[
        "include/mdspan/mdspan.hpp", "include/experimental/__p0009_bits/*.hpp",
        "include/experimental/__p2630_bits/*.hpp", "include/experimental/__p2642_bits/*.hpp",
        "include/experimental/__p2389_bits/*.hpp"]),
    "ctl_optional": {
        "ycxx": ["include/ycxx/core/optional.hpp"],
        "gnu": ["include/std/optional"],
        "llvm": ["libcxx/include/optional"],
        "msvc": ["stl/inc/optional"],
        "beman": ["optional/include/beman/optional/optional.hpp"],
    },
    "ctl_inplace_vector": {
        "ycxx": ["include/ycxx/core/inplace_vector.hpp"],
        "gnu": ["include/std/inplace_vector"],
        "beman": ["inplace_vector/include/beman/inplace_vector/inplace_vector.hpp"],
    },
}
ERA_AREAS = [a for a in STYLE_AREAS if a.startswith("era_")]
CONTROL_AREAS = [a for a in STYLE_AREAS if a.startswith("ctl_")]
