#!/usr/bin/env python3
"""The tables of docs/SPEC_COVERAGE.md, part 3, from the last probe run (tools/spec_audit/part3).

    tools/spec_audit/part3/report.py [--regions cache/regions.json]

Reads inventory.tsv, checks.tsv, results-gcc.tsv, results-clang.tsv and gaps.tsv and replaces
the text between `<!-- part3:tables:begin -->` and `<!-- part3:tables:end -->` in
docs/SPEC_COVERAGE.md: a summary per clause and a table per clause with a row per subclause.

Columns: declarations (each declaration of a synopsis is one entity; an overload is its own),
present (every check of the declaration that is about its existence passes on both compilers),
shape (every check passes on both: signature, return type, noexcept, constraints, constexpr,
explicit, base classes, values), presence-only (the signature names exposition-only types or
`see below`, so only the name is probed), not probed (no sample, a hidden friend with an
exposition-only signature, or optional), checks, failures per compiler (known gaps included),
undecided constexpr checks.
"""
import argparse, collections, json, pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[2]
DOC = REPO / "docs" / "SPEC_COVERAGE.md"
CLAUSES = [("text", "[text] Text processing"), ("numerics", "[numerics] Numerics"), ("time", "[time] Time"),
           ("input.output", "[input.output] Input/output"), ("thread", "[thread] Concurrency support"),
           ("exec", "[exec] Execution control"), ("depr", "Annex D [depr]"),
           ("version.syn", "[version.syn] feature-test macros of these headers"),
           ("zombie.names", "[zombie.names]")]


def tsv(path, skip_comment=True):
    if not path.exists():
        return []
    return [l.split("\t") for l in path.read_text().splitlines() if l and not (skip_comment and l.startswith("#"))]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--regions", default=str(HERE / "cache" / "regions.json"))
    a = ap.parse_args()
    data = json.loads(pathlib.Path(a.regions).read_text())
    parent = {s["id"]: s["parent"] for s in data["sections"]}
    num = {s["id"]: s["num"] for s in data["sections"]}

    def clause(sec):
        base = sec.split("@")[0]
        while base in parent and parent[base] is not None and base not in dict(CLAUSES):
            base = parent[base]
        return base if base in dict(CLAUSES) else ("version.syn" if sec.startswith("version.syn") else base)

    inv = tsv(HERE / "inventory.tsv")
    checks = tsv(HERE / "checks.tsv")
    res = {cc: {r[0]: r[1] for r in tsv(HERE / f"results-{cc}.tsv")} for cc in ("gcc", "clang")}
    by_decl = collections.defaultdict(list)
    by_sec_checks = collections.defaultdict(list)
    for c in checks:
        by_sec_checks[c[1]].append(c)
        if len(c) > 6 and c[6] != "":
            by_decl[c[6]].append(c)

    def status(cid, cc):
        return res[cc].get(cid) or res[cc].get("fs:" + cid)

    def failed(cid):
        return any(status(cid, cc) == "FAIL" for cc in res)

    rows = collections.OrderedDict()
    for e in inv:
        did, sec, hdr, ent, kind, n, note = e[0], e[1], e[2], e[3], e[4], int(e[5]), e[6]
        r = rows.setdefault(sec, collections.Counter())
        r["decls"] += 1
        cs = by_decl.get(did, [])
        if note.startswith("not probed") or not cs:
            r["not"] += 1
            continue
        if note.startswith("presence only"):
            r["ponly"] += 1
        pres = [c for c in cs if c[4].startswith(("presence", "type exists", "var exists", "specialization"))]
        if not any(failed(c[0]) for c in (pres or cs[:1])):
            r["present"] += 1
        if not any(failed(c[0]) for c in cs):
            r["shape"] += 1
    for sec, cs in by_sec_checks.items():
        r = rows.setdefault(sec, collections.Counter())
        r["checks"] = len(cs)
        for c in cs:
            if c[4] == "macro" or c[4].startswith(("macro value", "not declared", "not a macro", "header absent")):
                r["macros"] += 1
                if not failed(c[0]):
                    r["macros_ok"] += 1
        for cc in res:
            r["fail_" + cc] = sum(1 for c in cs if status(c[0], cc) == "FAIL")
            r["und_" + cc] = sum(1 for c in cs if status(c[0], cc) == "UNDECIDED")
        r["fs"] = sum(1 for c in cs if len(c) > 7 and c[7] == "freestanding")

    out = ["<!-- part3:tables:begin (generated by tools/spec_audit/part3/report.py; do not edit) -->", ""]
    tot = collections.defaultdict(collections.Counter)
    for sec, r in rows.items():
        tot[clause(sec)].update(r)
    out += ["| Clause | Declarations | Present | Correct shape | Presence only | Not probed | Macros (ok/all) | "
            "Checks | Fail GCC | Fail Clang | constexpr undecided (GCC/Clang) |",
            "|---|---|---|---|---|---|---|---|---|---|---|"]
    allt = collections.Counter()
    for key, title in CLAUSES:
        t = tot.get(key)
        if not t:
            continue
        allt.update(t)
        out.append(f"| {title} | {t['decls']} | {t['present']} | {t['shape']} | {t['ponly']} | {t['not']} | "
                   f"{t['macros_ok']}/{t['macros']} | {t['checks']} | {t['fail_gcc']} | {t['fail_clang']} | "
                   f"{t['und_gcc']}/{t['und_clang']} |")
    out.append(f"| **Total** | {allt['decls']} | {allt['present']} | {allt['shape']} | {allt['ponly']} | {allt['not']} | "
               f"{allt['macros_ok']}/{allt['macros']} | {allt['checks']} | {allt['fail_gcc']} | {allt['fail_clang']} | "
               f"{allt['und_gcc']}/{allt['und_clang']} |")
    out.append("")
    for key, title in CLAUSES:
        secs = [s for s in rows if clause(s) == key]
        if not secs:
            continue
        out += [f"<details><summary>{title}: {len(secs)} subclauses</summary>", "",
                "| Subclause | Decls | Present | Shape | Presence only | Not probed | Checks (freestanding) | Fail GCC/Clang | Probes |",
                "|---|---|---|---|---|---|---|---|---|"]
        def order(s):
            n = num.get(s.split("@")[0], "")
            return ([int(x) if x.isdigit() else x for x in re.split(r"\.", n)] if n else [9999], s)
        for s in sorted(secs, key=lambda s: (str(order(s)[0]), s)):
            r = rows[s]
            link = f"[probe](../tools/spec_audit/part3/probes/{s}.cpp)" if (HERE / "probes" / f"{s}.cpp").exists() else ""
            fs = f" ({r['fs']})" if r["fs"] else ""
            out.append(f"| [{s}] {num.get(s.split('@')[0], '')} | {r['decls']} | {r['present']} | {r['shape']} | "
                       f"{r['ponly']} | {r['not']} | {r['checks']}{fs} | {r['fail_gcc']}/{r['fail_clang']} | {link} |")
        out += ["", "</details>", ""]
    out.append("<!-- part3:tables:end -->")
    text = DOC.read_text() if DOC.exists() else ""
    m = re.search(r"<!-- part3:tables:begin.*?<!-- part3:tables:end -->", text, re.S)
    if not m:
        raise SystemExit(f"{DOC}: no <!-- part3:tables:begin --> ... <!-- part3:tables:end --> markers")
    DOC.write_text(text[:m.start()] + "\n".join(out) + text[m.end():])
    print(f"{DOC}: part 3 tables, {allt['decls']} declarations, {allt['checks']} checks")


if __name__ == "__main__":
    sys.exit(main())
