// GENERATED by tools/gen_transitive_includes.py from tools/data/transitive-includes.txt; do not edit.
// DECISIONS §19: by default <future> provides what tools/data/transitive-includes.txt lists for it
// (each header's primary probe item, and the item a reason names; the snippets are
// tools/data/transitive-probe/items.txt's). The strict mode is undone for this test.
#undef YCXX_NO_TRANSITIVE_INCLUDES
#include <future>

namespace probe_1 { // algorithm:std::min
int probe() { return std::min(1, 2); }
}
namespace probe_2 { // cctype:std::isspace
int probe() { return std::isspace(' '); }
}
namespace probe_3 { // cerrno:errno
int probe() { return errno; }
}
namespace probe_4 { // charconv:std::to_chars
void probe(char* b) { auto r = std::to_chars(b, b + 8, 1); (void)r; }
}
namespace probe_5 { // compare:std::strong_ordering
std::strong_ordering probe() { return std::strong_ordering::equal; }
}
namespace probe_6 { // concepts:std::same_as
static_assert(std::same_as<int, int>);
}
namespace probe_7 { // condition_variable:std::condition_variable
void probe() { std::condition_variable cv; }
}
namespace probe_8 { // cstddef:std::byte
std::byte probe_v{};
}
namespace probe_9 { // cstdint:std::uint32_t
std::uint32_t probe_v = 0;
}
namespace probe_10 { // cstdio:std::printf
int probe() { return std::printf(""); }
}
namespace probe_11 { // ctime:std::time
std::time_t probe() { return std::time(nullptr); }
}
namespace probe_12 { // cwchar:std::wcslen
std::size_t probe() { return std::wcslen(L""); }
}
namespace probe_13 { // cwctype:std::iswspace
int probe() { return std::iswspace(L' '); }
}
namespace probe_14 { // exception:std::exception_ptr
std::exception_ptr probe_v;
}
namespace probe_15 { // initializer_list:std::initializer_list
std::initializer_list<int> probe_v;
}
namespace probe_16 { // iosfwd:std::ostream
std::ostream* probe_v = nullptr;
}
namespace probe_17 { // limits:std::numeric_limits
int probe() { return std::numeric_limits<int>::max(); }
}
namespace probe_18 { // memory:std::unique_ptr
std::unique_ptr<int> probe_v;
}
namespace probe_19 { // mutex:std::mutex
std::mutex probe_v;
}
namespace probe_20 { // ratio:std::ratio
using probe_t = std::ratio<1, 2>; static_assert(probe_t::num == 1);
}
namespace probe_21 { // stdexcept:std::runtime_error
void probe() { throw std::runtime_error("x"); }
}
namespace probe_22 { // string:std::string
std::string probe_v;
}
namespace probe_23 { // string_view:std::string_view
std::string_view probe_v;
}
namespace probe_24 { // system_error:std::error_code
std::error_code probe_v;
}
namespace probe_25 { // thread:std::thread
std::thread probe_v;
}
namespace probe_26 { // tuple:std::tuple
std::tuple<int> probe_v;
}
namespace probe_27 { // type_traits:std::is_same_v
static_assert(std::is_same_v<int, int>);
}
namespace probe_28 { // typeinfo:std::type_info
const std::type_info& probe() { return typeid(int); }
}
namespace probe_29 { // utility:std::pair
std::pair<int, int> probe_v;
}

int main() {}
