// GENERATED by tools/gen_transitive_includes.py from tools/data/transitive-includes.txt; do not edit.
// DECISIONS §19: by default <shared_mutex> provides what tools/data/transitive-includes.txt lists for it
// (each header's primary probe item, and the item a reason names; the snippets are
// tools/data/transitive-probe/items.txt's). The strict mode is undone for this test.
#undef YCXX_NO_TRANSITIVE_INCLUDES
#include <shared_mutex>

namespace probe_1 { // cerrno:errno
int probe() { return errno; }
}
namespace probe_2 { // compare:std::strong_ordering
std::strong_ordering probe() { return std::strong_ordering::equal; }
}
namespace probe_3 { // concepts:std::same_as
static_assert(std::same_as<int, int>);
}
namespace probe_4 { // cstdint:std::uint32_t
std::uint32_t probe_v = 0;
}
namespace probe_5 { // ctime:std::time
std::time_t probe() { return std::time(nullptr); }
}
namespace probe_6 { // limits:std::numeric_limits
int probe() { return std::numeric_limits<int>::max(); }
}
namespace probe_7 { // mutex:std::mutex
std::mutex probe_v;
}
namespace probe_8 { // ratio:std::ratio
using probe_t = std::ratio<1, 2>; static_assert(probe_t::num == 1);
}
namespace probe_9 { // type_traits:std::is_same_v
static_assert(std::is_same_v<int, int>);
}

int main() {}
