// GENERATED by tools/gen_transitive_includes.py from tools/data/transitive-includes.txt; do not edit.
// DECISIONS §19: by default <stacktrace> provides what tools/data/transitive-includes.txt lists for it
// (each header's primary probe item, and the item a reason names; the snippets are
// tools/data/transitive-probe/items.txt's). The strict mode is undone for this test.
#undef YCXX_NO_TRANSITIVE_INCLUDES
#include <stacktrace>

namespace probe_1 { // cstdio:std::printf
int probe() { return std::printf(""); }
}
namespace probe_2 { // cstdio:EOF
int probe() { return EOF; }
}

int main() {}
