// GENERATED by tools/gen_transitive_includes.py from tools/data/transitive-includes.txt; do not edit.
// DECISIONS §19: by default <string> provides what tools/data/transitive-includes.txt lists for it
// (each header's primary probe item, and the item a reason names; the snippets are
// tools/data/transitive-probe/items.txt's). The strict mode is undone for this test.
#undef YCXX_NO_TRANSITIVE_INCLUDES
#include <string>

namespace probe_1 { // algorithm:std::min
int probe() { return std::min(1, 2); }
}
namespace probe_2 { // cctype:std::isspace
int probe() { return std::isspace(' '); }
}
namespace probe_3 { // cerrno:errno
int probe() { return errno; }
}
namespace probe_4 { // concepts:std::same_as
static_assert(std::same_as<int, int>);
}
namespace probe_5 { // cstddef:std::byte
std::byte probe_v{};
}
namespace probe_6 { // cstdio:std::printf
int probe() { return std::printf(""); }
}
namespace probe_7 { // cstdlib:std::abort
void probe() { std::abort(); }
}
namespace probe_8 { // cwchar:std::wcslen
std::size_t probe() { return std::wcslen(L""); }
}
namespace probe_9 { // iosfwd:std::ostream
std::ostream* probe_v = nullptr;
}
namespace probe_10 { // limits:std::numeric_limits
int probe() { return std::numeric_limits<int>::max(); }
}
namespace probe_11 { // stdexcept:std::runtime_error
std::runtime_error probe() { return std::runtime_error("x"); }
}
namespace probe_12 { // string_view:std::string_view
std::string_view probe_v;
}
namespace probe_13 { // tuple:std::tuple
std::tuple<int> probe_v;
}
namespace probe_14 { // type_traits:std::is_same_v
static_assert(std::is_same_v<int, int>);
}
namespace probe_15 { // utility:std::pair
std::pair<int, int> probe_v;
}

int main() {}
