// Spec-audit probes for [cinttypes.syn], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <cinttypes>
#define SPEC_PROBE_cinttypes
#include "../probe_support.hpp"
namespace p0 { using namespace std; using T = std::imaxdiv_t; } // cinttypes.syn#1 type exists (exposition-only or unspecified: see below)
namespace p1 { using namespace std; template<class Z> concept c = requires { { std::imaxabs(spec_probe::dv<spec_probe::dep<Z, intmax_t>>()) } -> spec_probe::same<intmax_t>; }; static_assert(c<void>); } // cinttypes.syn#2 call ret
namespace p2 { using namespace std; template<class Z> concept c = requires { { std::imaxdiv(spec_probe::dv<spec_probe::dep<Z, intmax_t>>(), spec_probe::dv<spec_probe::dep<Z, intmax_t>>()) } -> spec_probe::same<imaxdiv_t>; }; static_assert(c<void>); } // cinttypes.syn#3 call ret
namespace p3 { using namespace std; template<class Z> concept c = requires { { std::strtoimax(spec_probe::dv<spec_probe::dep<Z, const char*>>(), spec_probe::dv<spec_probe::dep<Z, char**>>(), spec_probe::dv<spec_probe::dep<Z, int>>()) } -> spec_probe::same<intmax_t>; }; static_assert(c<void>); } // cinttypes.syn#4 call ret
namespace p4 { using namespace std; template<class Z> concept c = requires { { std::strtoumax(spec_probe::dv<spec_probe::dep<Z, const char*>>(), spec_probe::dv<spec_probe::dep<Z, char**>>(), spec_probe::dv<spec_probe::dep<Z, int>>()) } -> spec_probe::same<uintmax_t>; }; static_assert(c<void>); } // cinttypes.syn#5 call ret
namespace p5 { using namespace std; template<class Z> concept c = requires { { std::wcstoimax(spec_probe::dv<spec_probe::dep<Z, const wchar_t*>>(), spec_probe::dv<spec_probe::dep<Z, wchar_t**>>(), spec_probe::dv<spec_probe::dep<Z, int>>()) } -> spec_probe::same<intmax_t>; }; static_assert(c<void>); } // cinttypes.syn#6 call ret
namespace p6 { using namespace std; template<class Z> concept c = requires { { std::wcstoumax(spec_probe::dv<spec_probe::dep<Z, const wchar_t*>>(), spec_probe::dv<spec_probe::dep<Z, wchar_t**>>(), spec_probe::dv<spec_probe::dep<Z, int>>()) } -> spec_probe::same<uintmax_t>; }; static_assert(c<void>); } // cinttypes.syn#7 call ret
#ifndef __STDC_VERSION_INTTYPES_H__
static_assert(false, "__STDC_VERSION_INTTYPES_H__"); // cinttypes.syn#8 macro
#endif
#ifndef PRId8
static_assert(false, "PRId8"); // cinttypes.syn#9 macro
#endif
#ifndef PRId16
static_assert(false, "PRId16"); // cinttypes.syn#10 macro
#endif
#ifndef PRId32
static_assert(false, "PRId32"); // cinttypes.syn#11 macro
#endif
#ifndef PRId64
static_assert(false, "PRId64"); // cinttypes.syn#12 macro
#endif
#ifndef PRIi8
static_assert(false, "PRIi8"); // cinttypes.syn#13 macro
#endif
#ifndef PRIi16
static_assert(false, "PRIi16"); // cinttypes.syn#14 macro
#endif
#ifndef PRIi32
static_assert(false, "PRIi32"); // cinttypes.syn#15 macro
#endif
#ifndef PRIi64
static_assert(false, "PRIi64"); // cinttypes.syn#16 macro
#endif
#ifndef PRIo8
static_assert(false, "PRIo8"); // cinttypes.syn#17 macro
#endif
#ifndef PRIo16
static_assert(false, "PRIo16"); // cinttypes.syn#18 macro
#endif
#ifndef PRIo32
static_assert(false, "PRIo32"); // cinttypes.syn#19 macro
#endif
#ifndef PRIo64
static_assert(false, "PRIo64"); // cinttypes.syn#20 macro
#endif
#ifndef PRIu8
static_assert(false, "PRIu8"); // cinttypes.syn#21 macro
#endif
#ifndef PRIu16
static_assert(false, "PRIu16"); // cinttypes.syn#22 macro
#endif
#ifndef PRIu32
static_assert(false, "PRIu32"); // cinttypes.syn#23 macro
#endif
#ifndef PRIu64
static_assert(false, "PRIu64"); // cinttypes.syn#24 macro
#endif
#ifndef PRIx8
static_assert(false, "PRIx8"); // cinttypes.syn#25 macro
#endif
#ifndef PRIx16
static_assert(false, "PRIx16"); // cinttypes.syn#26 macro
#endif
#ifndef PRIx32
static_assert(false, "PRIx32"); // cinttypes.syn#27 macro
#endif
#ifndef PRIx64
static_assert(false, "PRIx64"); // cinttypes.syn#28 macro
#endif
#ifndef PRIX8
static_assert(false, "PRIX8"); // cinttypes.syn#29 macro
#endif
#ifndef PRIX16
static_assert(false, "PRIX16"); // cinttypes.syn#30 macro
#endif
#ifndef PRIX32
static_assert(false, "PRIX32"); // cinttypes.syn#31 macro
#endif
#ifndef PRIX64
static_assert(false, "PRIX64"); // cinttypes.syn#32 macro
#endif
#ifndef PRIb8
static_assert(false, "PRIb8"); // cinttypes.syn#33 macro
#endif
#ifndef PRIb16
static_assert(false, "PRIb16"); // cinttypes.syn#34 macro
#endif
#ifndef PRIb32
static_assert(false, "PRIb32"); // cinttypes.syn#35 macro
#endif
#ifndef PRIb64
static_assert(false, "PRIb64"); // cinttypes.syn#36 macro
#endif
#ifndef PRIB8
static_assert(false, "PRIB8"); // cinttypes.syn#37 macro
#endif
#ifndef PRIB16
static_assert(false, "PRIB16"); // cinttypes.syn#38 macro
#endif
#ifndef PRIB32
static_assert(false, "PRIB32"); // cinttypes.syn#39 macro
#endif
#ifndef PRIB64
static_assert(false, "PRIB64"); // cinttypes.syn#40 macro
#endif
#ifndef SCNd8
static_assert(false, "SCNd8"); // cinttypes.syn#41 macro
#endif
#ifndef SCNd16
static_assert(false, "SCNd16"); // cinttypes.syn#42 macro
#endif
#ifndef SCNd32
static_assert(false, "SCNd32"); // cinttypes.syn#43 macro
#endif
#ifndef SCNd64
static_assert(false, "SCNd64"); // cinttypes.syn#44 macro
#endif
#ifndef SCNi8
static_assert(false, "SCNi8"); // cinttypes.syn#45 macro
#endif
#ifndef SCNi16
static_assert(false, "SCNi16"); // cinttypes.syn#46 macro
#endif
#ifndef SCNi32
static_assert(false, "SCNi32"); // cinttypes.syn#47 macro
#endif
#ifndef SCNi64
static_assert(false, "SCNi64"); // cinttypes.syn#48 macro
#endif
#ifndef SCNo8
static_assert(false, "SCNo8"); // cinttypes.syn#49 macro
#endif
#ifndef SCNo16
static_assert(false, "SCNo16"); // cinttypes.syn#50 macro
#endif
#ifndef SCNo32
static_assert(false, "SCNo32"); // cinttypes.syn#51 macro
#endif
#ifndef SCNo64
static_assert(false, "SCNo64"); // cinttypes.syn#52 macro
#endif
#ifndef SCNu8
static_assert(false, "SCNu8"); // cinttypes.syn#53 macro
#endif
#ifndef SCNu16
static_assert(false, "SCNu16"); // cinttypes.syn#54 macro
#endif
#ifndef SCNu32
static_assert(false, "SCNu32"); // cinttypes.syn#55 macro
#endif
#ifndef SCNu64
static_assert(false, "SCNu64"); // cinttypes.syn#56 macro
#endif
#ifndef SCNx8
static_assert(false, "SCNx8"); // cinttypes.syn#57 macro
#endif
#ifndef SCNx16
static_assert(false, "SCNx16"); // cinttypes.syn#58 macro
#endif
#ifndef SCNx32
static_assert(false, "SCNx32"); // cinttypes.syn#59 macro
#endif
#ifndef SCNx64
static_assert(false, "SCNx64"); // cinttypes.syn#60 macro
#endif
#ifndef SCNb8
static_assert(false, "SCNb8"); // cinttypes.syn#61 macro
#endif
#ifndef SCNb16
static_assert(false, "SCNb16"); // cinttypes.syn#62 macro
#endif
#ifndef SCNb32
static_assert(false, "SCNb32"); // cinttypes.syn#63 macro
#endif
#ifndef SCNb64
static_assert(false, "SCNb64"); // cinttypes.syn#64 macro
#endif
#ifndef PRIdLEAST8
static_assert(false, "PRIdLEAST8"); // cinttypes.syn#65 macro
#endif
#ifndef PRIdLEAST16
static_assert(false, "PRIdLEAST16"); // cinttypes.syn#66 macro
#endif
#ifndef PRIdLEAST32
static_assert(false, "PRIdLEAST32"); // cinttypes.syn#67 macro
#endif
#ifndef PRIdLEAST64
static_assert(false, "PRIdLEAST64"); // cinttypes.syn#68 macro
#endif
#ifndef PRIiLEAST8
static_assert(false, "PRIiLEAST8"); // cinttypes.syn#69 macro
#endif
#ifndef PRIiLEAST16
static_assert(false, "PRIiLEAST16"); // cinttypes.syn#70 macro
#endif
#ifndef PRIiLEAST32
static_assert(false, "PRIiLEAST32"); // cinttypes.syn#71 macro
#endif
#ifndef PRIiLEAST64
static_assert(false, "PRIiLEAST64"); // cinttypes.syn#72 macro
#endif
#ifndef PRIoLEAST8
static_assert(false, "PRIoLEAST8"); // cinttypes.syn#73 macro
#endif
#ifndef PRIoLEAST16
static_assert(false, "PRIoLEAST16"); // cinttypes.syn#74 macro
#endif
#ifndef PRIoLEAST32
static_assert(false, "PRIoLEAST32"); // cinttypes.syn#75 macro
#endif
#ifndef PRIoLEAST64
static_assert(false, "PRIoLEAST64"); // cinttypes.syn#76 macro
#endif
#ifndef PRIuLEAST8
static_assert(false, "PRIuLEAST8"); // cinttypes.syn#77 macro
#endif
#ifndef PRIuLEAST16
static_assert(false, "PRIuLEAST16"); // cinttypes.syn#78 macro
#endif
#ifndef PRIuLEAST32
static_assert(false, "PRIuLEAST32"); // cinttypes.syn#79 macro
#endif
#ifndef PRIuLEAST64
static_assert(false, "PRIuLEAST64"); // cinttypes.syn#80 macro
#endif
#ifndef PRIxLEAST8
static_assert(false, "PRIxLEAST8"); // cinttypes.syn#81 macro
#endif
#ifndef PRIxLEAST16
static_assert(false, "PRIxLEAST16"); // cinttypes.syn#82 macro
#endif
#ifndef PRIxLEAST32
static_assert(false, "PRIxLEAST32"); // cinttypes.syn#83 macro
#endif
#ifndef PRIxLEAST64
static_assert(false, "PRIxLEAST64"); // cinttypes.syn#84 macro
#endif
#ifndef PRIXLEAST8
static_assert(false, "PRIXLEAST8"); // cinttypes.syn#85 macro
#endif
#ifndef PRIXLEAST16
static_assert(false, "PRIXLEAST16"); // cinttypes.syn#86 macro
#endif
#ifndef PRIXLEAST32
static_assert(false, "PRIXLEAST32"); // cinttypes.syn#87 macro
#endif
#ifndef PRIXLEAST64
static_assert(false, "PRIXLEAST64"); // cinttypes.syn#88 macro
#endif
#ifndef PRIbLEAST8
static_assert(false, "PRIbLEAST8"); // cinttypes.syn#89 macro
#endif
#ifndef PRIbLEAST16
static_assert(false, "PRIbLEAST16"); // cinttypes.syn#90 macro
#endif
#ifndef PRIbLEAST32
static_assert(false, "PRIbLEAST32"); // cinttypes.syn#91 macro
#endif
#ifndef PRIbLEAST64
static_assert(false, "PRIbLEAST64"); // cinttypes.syn#92 macro
#endif
#ifndef PRIBLEAST8
static_assert(false, "PRIBLEAST8"); // cinttypes.syn#93 macro
#endif
#ifndef PRIBLEAST16
static_assert(false, "PRIBLEAST16"); // cinttypes.syn#94 macro
#endif
#ifndef PRIBLEAST32
static_assert(false, "PRIBLEAST32"); // cinttypes.syn#95 macro
#endif
#ifndef PRIBLEAST64
static_assert(false, "PRIBLEAST64"); // cinttypes.syn#96 macro
#endif
#ifndef SCNdLEAST8
static_assert(false, "SCNdLEAST8"); // cinttypes.syn#97 macro
#endif
#ifndef SCNdLEAST16
static_assert(false, "SCNdLEAST16"); // cinttypes.syn#98 macro
#endif
#ifndef SCNdLEAST32
static_assert(false, "SCNdLEAST32"); // cinttypes.syn#99 macro
#endif
#ifndef SCNdLEAST64
static_assert(false, "SCNdLEAST64"); // cinttypes.syn#100 macro
#endif
#ifndef SCNiLEAST8
static_assert(false, "SCNiLEAST8"); // cinttypes.syn#101 macro
#endif
#ifndef SCNiLEAST16
static_assert(false, "SCNiLEAST16"); // cinttypes.syn#102 macro
#endif
#ifndef SCNiLEAST32
static_assert(false, "SCNiLEAST32"); // cinttypes.syn#103 macro
#endif
#ifndef SCNiLEAST64
static_assert(false, "SCNiLEAST64"); // cinttypes.syn#104 macro
#endif
#ifndef SCNoLEAST8
static_assert(false, "SCNoLEAST8"); // cinttypes.syn#105 macro
#endif
#ifndef SCNoLEAST16
static_assert(false, "SCNoLEAST16"); // cinttypes.syn#106 macro
#endif
#ifndef SCNoLEAST32
static_assert(false, "SCNoLEAST32"); // cinttypes.syn#107 macro
#endif
#ifndef SCNoLEAST64
static_assert(false, "SCNoLEAST64"); // cinttypes.syn#108 macro
#endif
#ifndef SCNuLEAST8
static_assert(false, "SCNuLEAST8"); // cinttypes.syn#109 macro
#endif
#ifndef SCNuLEAST16
static_assert(false, "SCNuLEAST16"); // cinttypes.syn#110 macro
#endif
#ifndef SCNuLEAST32
static_assert(false, "SCNuLEAST32"); // cinttypes.syn#111 macro
#endif
#ifndef SCNuLEAST64
static_assert(false, "SCNuLEAST64"); // cinttypes.syn#112 macro
#endif
#ifndef SCNxLEAST8
static_assert(false, "SCNxLEAST8"); // cinttypes.syn#113 macro
#endif
#ifndef SCNxLEAST16
static_assert(false, "SCNxLEAST16"); // cinttypes.syn#114 macro
#endif
#ifndef SCNxLEAST32
static_assert(false, "SCNxLEAST32"); // cinttypes.syn#115 macro
#endif
#ifndef SCNxLEAST64
static_assert(false, "SCNxLEAST64"); // cinttypes.syn#116 macro
#endif
#ifndef SCNbLEAST8
static_assert(false, "SCNbLEAST8"); // cinttypes.syn#117 macro
#endif
#ifndef SCNbLEAST16
static_assert(false, "SCNbLEAST16"); // cinttypes.syn#118 macro
#endif
#ifndef SCNbLEAST32
static_assert(false, "SCNbLEAST32"); // cinttypes.syn#119 macro
#endif
#ifndef SCNbLEAST64
static_assert(false, "SCNbLEAST64"); // cinttypes.syn#120 macro
#endif
#ifndef PRIdFAST8
static_assert(false, "PRIdFAST8"); // cinttypes.syn#121 macro
#endif
#ifndef PRIdFAST16
static_assert(false, "PRIdFAST16"); // cinttypes.syn#122 macro
#endif
#ifndef PRIdFAST32
static_assert(false, "PRIdFAST32"); // cinttypes.syn#123 macro
#endif
#ifndef PRIdFAST64
static_assert(false, "PRIdFAST64"); // cinttypes.syn#124 macro
#endif
#ifndef PRIiFAST8
static_assert(false, "PRIiFAST8"); // cinttypes.syn#125 macro
#endif
#ifndef PRIiFAST16
static_assert(false, "PRIiFAST16"); // cinttypes.syn#126 macro
#endif
#ifndef PRIiFAST32
static_assert(false, "PRIiFAST32"); // cinttypes.syn#127 macro
#endif
#ifndef PRIiFAST64
static_assert(false, "PRIiFAST64"); // cinttypes.syn#128 macro
#endif
#ifndef PRIoFAST8
static_assert(false, "PRIoFAST8"); // cinttypes.syn#129 macro
#endif
#ifndef PRIoFAST16
static_assert(false, "PRIoFAST16"); // cinttypes.syn#130 macro
#endif
#ifndef PRIoFAST32
static_assert(false, "PRIoFAST32"); // cinttypes.syn#131 macro
#endif
#ifndef PRIoFAST64
static_assert(false, "PRIoFAST64"); // cinttypes.syn#132 macro
#endif
#ifndef PRIuFAST8
static_assert(false, "PRIuFAST8"); // cinttypes.syn#133 macro
#endif
#ifndef PRIuFAST16
static_assert(false, "PRIuFAST16"); // cinttypes.syn#134 macro
#endif
#ifndef PRIuFAST32
static_assert(false, "PRIuFAST32"); // cinttypes.syn#135 macro
#endif
#ifndef PRIuFAST64
static_assert(false, "PRIuFAST64"); // cinttypes.syn#136 macro
#endif
#ifndef PRIxFAST8
static_assert(false, "PRIxFAST8"); // cinttypes.syn#137 macro
#endif
#ifndef PRIxFAST16
static_assert(false, "PRIxFAST16"); // cinttypes.syn#138 macro
#endif
#ifndef PRIxFAST32
static_assert(false, "PRIxFAST32"); // cinttypes.syn#139 macro
#endif
#ifndef PRIxFAST64
static_assert(false, "PRIxFAST64"); // cinttypes.syn#140 macro
#endif
#ifndef PRIXFAST8
static_assert(false, "PRIXFAST8"); // cinttypes.syn#141 macro
#endif
#ifndef PRIXFAST16
static_assert(false, "PRIXFAST16"); // cinttypes.syn#142 macro
#endif
#ifndef PRIXFAST32
static_assert(false, "PRIXFAST32"); // cinttypes.syn#143 macro
#endif
#ifndef PRIXFAST64
static_assert(false, "PRIXFAST64"); // cinttypes.syn#144 macro
#endif
#ifndef PRIbFAST8
static_assert(false, "PRIbFAST8"); // cinttypes.syn#145 macro
#endif
#ifndef PRIbFAST16
static_assert(false, "PRIbFAST16"); // cinttypes.syn#146 macro
#endif
#ifndef PRIbFAST32
static_assert(false, "PRIbFAST32"); // cinttypes.syn#147 macro
#endif
#ifndef PRIbFAST64
static_assert(false, "PRIbFAST64"); // cinttypes.syn#148 macro
#endif
#ifndef PRIBFAST8
static_assert(false, "PRIBFAST8"); // cinttypes.syn#149 macro
#endif
#ifndef PRIBFAST16
static_assert(false, "PRIBFAST16"); // cinttypes.syn#150 macro
#endif
#ifndef PRIBFAST32
static_assert(false, "PRIBFAST32"); // cinttypes.syn#151 macro
#endif
#ifndef PRIBFAST64
static_assert(false, "PRIBFAST64"); // cinttypes.syn#152 macro
#endif
#ifndef SCNdFAST8
static_assert(false, "SCNdFAST8"); // cinttypes.syn#153 macro
#endif
#ifndef SCNdFAST16
static_assert(false, "SCNdFAST16"); // cinttypes.syn#154 macro
#endif
#ifndef SCNdFAST32
static_assert(false, "SCNdFAST32"); // cinttypes.syn#155 macro
#endif
#ifndef SCNdFAST64
static_assert(false, "SCNdFAST64"); // cinttypes.syn#156 macro
#endif
#ifndef SCNiFAST8
static_assert(false, "SCNiFAST8"); // cinttypes.syn#157 macro
#endif
#ifndef SCNiFAST16
static_assert(false, "SCNiFAST16"); // cinttypes.syn#158 macro
#endif
#ifndef SCNiFAST32
static_assert(false, "SCNiFAST32"); // cinttypes.syn#159 macro
#endif
#ifndef SCNiFAST64
static_assert(false, "SCNiFAST64"); // cinttypes.syn#160 macro
#endif
#ifndef SCNoFAST8
static_assert(false, "SCNoFAST8"); // cinttypes.syn#161 macro
#endif
#ifndef SCNoFAST16
static_assert(false, "SCNoFAST16"); // cinttypes.syn#162 macro
#endif
#ifndef SCNoFAST32
static_assert(false, "SCNoFAST32"); // cinttypes.syn#163 macro
#endif
#ifndef SCNoFAST64
static_assert(false, "SCNoFAST64"); // cinttypes.syn#164 macro
#endif
#ifndef SCNuFAST8
static_assert(false, "SCNuFAST8"); // cinttypes.syn#165 macro
#endif
#ifndef SCNuFAST16
static_assert(false, "SCNuFAST16"); // cinttypes.syn#166 macro
#endif
#ifndef SCNuFAST32
static_assert(false, "SCNuFAST32"); // cinttypes.syn#167 macro
#endif
#ifndef SCNuFAST64
static_assert(false, "SCNuFAST64"); // cinttypes.syn#168 macro
#endif
#ifndef SCNxFAST8
static_assert(false, "SCNxFAST8"); // cinttypes.syn#169 macro
#endif
#ifndef SCNxFAST16
static_assert(false, "SCNxFAST16"); // cinttypes.syn#170 macro
#endif
#ifndef SCNxFAST32
static_assert(false, "SCNxFAST32"); // cinttypes.syn#171 macro
#endif
#ifndef SCNxFAST64
static_assert(false, "SCNxFAST64"); // cinttypes.syn#172 macro
#endif
#ifndef SCNbFAST8
static_assert(false, "SCNbFAST8"); // cinttypes.syn#173 macro
#endif
#ifndef SCNbFAST16
static_assert(false, "SCNbFAST16"); // cinttypes.syn#174 macro
#endif
#ifndef SCNbFAST32
static_assert(false, "SCNbFAST32"); // cinttypes.syn#175 macro
#endif
#ifndef SCNbFAST64
static_assert(false, "SCNbFAST64"); // cinttypes.syn#176 macro
#endif
#ifndef PRIdMAX
static_assert(false, "PRIdMAX"); // cinttypes.syn#177 macro
#endif
#ifndef PRIiMAX
static_assert(false, "PRIiMAX"); // cinttypes.syn#178 macro
#endif
#ifndef PRIoMAX
static_assert(false, "PRIoMAX"); // cinttypes.syn#179 macro
#endif
#ifndef PRIuMAX
static_assert(false, "PRIuMAX"); // cinttypes.syn#180 macro
#endif
#ifndef PRIxMAX
static_assert(false, "PRIxMAX"); // cinttypes.syn#181 macro
#endif
#ifndef PRIXMAX
static_assert(false, "PRIXMAX"); // cinttypes.syn#182 macro
#endif
#ifndef PRIbMAX
static_assert(false, "PRIbMAX"); // cinttypes.syn#183 macro
#endif
#ifndef PRIBMAX
static_assert(false, "PRIBMAX"); // cinttypes.syn#184 macro
#endif
#ifndef SCNdMAX
static_assert(false, "SCNdMAX"); // cinttypes.syn#185 macro
#endif
#ifndef SCNiMAX
static_assert(false, "SCNiMAX"); // cinttypes.syn#186 macro
#endif
#ifndef SCNoMAX
static_assert(false, "SCNoMAX"); // cinttypes.syn#187 macro
#endif
#ifndef SCNuMAX
static_assert(false, "SCNuMAX"); // cinttypes.syn#188 macro
#endif
#ifndef SCNxMAX
static_assert(false, "SCNxMAX"); // cinttypes.syn#189 macro
#endif
#ifndef SCNbMAX
static_assert(false, "SCNbMAX"); // cinttypes.syn#190 macro
#endif
#ifndef PRIdPTR
static_assert(false, "PRIdPTR"); // cinttypes.syn#191 macro
#endif
#ifndef PRIiPTR
static_assert(false, "PRIiPTR"); // cinttypes.syn#192 macro
#endif
#ifndef PRIoPTR
static_assert(false, "PRIoPTR"); // cinttypes.syn#193 macro
#endif
#ifndef PRIuPTR
static_assert(false, "PRIuPTR"); // cinttypes.syn#194 macro
#endif
#ifndef PRIxPTR
static_assert(false, "PRIxPTR"); // cinttypes.syn#195 macro
#endif
#ifndef PRIXPTR
static_assert(false, "PRIXPTR"); // cinttypes.syn#196 macro
#endif
#ifndef PRIbPTR
static_assert(false, "PRIbPTR"); // cinttypes.syn#197 macro
#endif
#ifndef PRIBPTR
static_assert(false, "PRIBPTR"); // cinttypes.syn#198 macro
#endif
#ifndef SCNdPTR
static_assert(false, "SCNdPTR"); // cinttypes.syn#199 macro
#endif
#ifndef SCNiPTR
static_assert(false, "SCNiPTR"); // cinttypes.syn#200 macro
#endif
#ifndef SCNoPTR
static_assert(false, "SCNoPTR"); // cinttypes.syn#201 macro
#endif
#ifndef SCNuPTR
static_assert(false, "SCNuPTR"); // cinttypes.syn#202 macro
#endif
#ifndef SCNxPTR
static_assert(false, "SCNxPTR"); // cinttypes.syn#203 macro
#endif
#ifndef SCNbPTR
static_assert(false, "SCNbPTR"); // cinttypes.syn#204 macro
#endif
