// Spec-audit probes for [ctime.syn], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <ctime>
#define SPEC_PROBE_ctime
#include "../probe_support.hpp"
namespace p0 { using namespace std; using T = std::size_t; } // ctime.syn#1 type exists (exposition-only or unspecified: see [support.types.layout])
namespace p1 { using namespace std; using T = std::clock_t; } // ctime.syn#2 type exists (exposition-only or unspecified: see below)
namespace p2 { using namespace std; using T = std::time_t; } // ctime.syn#3 type exists (exposition-only or unspecified: see below)
namespace p3 { using namespace std; using std::timespec; } // ctime.syn#4 presence
namespace p4 { using namespace std; using std::tm; } // ctime.syn#5 presence
namespace p5 { using namespace std; template<class Z> concept c = requires { { std::clock() } -> spec_probe::same<clock_t>; }; static_assert(c<void>); } // ctime.syn#6 call ret
namespace p6 { using namespace std; template<class Z> concept c = requires { { std::difftime(spec_probe::dv<spec_probe::dep<Z, time_t>>(), spec_probe::dv<spec_probe::dep<Z, time_t>>()) } -> spec_probe::same<double>; }; static_assert(c<void>); } // ctime.syn#7 call ret
namespace p7 { using namespace std; template<class Z> concept c = requires { { std::mktime(spec_probe::dv<spec_probe::dep<Z, tm*>>()) } -> spec_probe::same<time_t>; }; static_assert(c<void>); } // ctime.syn#8 call ret
namespace p8 { using namespace std; template<class Z> concept c = requires { { std::timegm(spec_probe::dv<spec_probe::dep<Z, tm*>>()) } -> spec_probe::same<time_t>; }; static_assert(c<void>); } // ctime.syn#9 call ret
namespace p9 { using namespace std; template<class Z> concept c = requires { { std::time(spec_probe::dv<spec_probe::dep<Z, time_t*>>()) } -> spec_probe::same<time_t>; }; static_assert(c<void>); } // ctime.syn#10 call ret
namespace p10 { using namespace std; template<class Z> concept c = requires { { std::timespec_get(spec_probe::dv<spec_probe::dep<Z, timespec*>>(), spec_probe::dv<spec_probe::dep<Z, int>>()) } -> spec_probe::same<int>; }; static_assert(c<void>); } // ctime.syn#11 call ret
namespace p11 { using namespace std; template<class Z> concept c = requires { { std::timespec_getres(spec_probe::dv<spec_probe::dep<Z, timespec*>>(), spec_probe::dv<spec_probe::dep<Z, int>>()) } -> spec_probe::same<int>; }; static_assert(c<void>); } // ctime.syn#12 call ret
namespace p12 { using namespace std; template<class Z> concept c = requires { { std::gmtime(spec_probe::dv<spec_probe::dep<Z, const time_t*>>()) } -> spec_probe::same<tm*>; }; static_assert(c<void>); } // ctime.syn#13 call ret
namespace p13 { using namespace std; template<class Z> concept c = requires { { std::gmtime_r(spec_probe::dv<spec_probe::dep<Z, const time_t*>>(), spec_probe::dv<spec_probe::dep<Z, tm*>>()) } -> spec_probe::same<tm*>; }; static_assert(c<void>); } // ctime.syn#14 call ret
namespace p14 { using namespace std; template<class Z> concept c = requires { { std::localtime(spec_probe::dv<spec_probe::dep<Z, const time_t*>>()) } -> spec_probe::same<tm*>; }; static_assert(c<void>); } // ctime.syn#15 call ret
namespace p15 { using namespace std; template<class Z> concept c = requires { { std::localtime_r(spec_probe::dv<spec_probe::dep<Z, const time_t*>>(), spec_probe::dv<spec_probe::dep<Z, tm*>>()) } -> spec_probe::same<tm*>; }; static_assert(c<void>); } // ctime.syn#16 call ret
namespace p16 { using namespace std; template<class Z> concept c = requires { { std::strftime(spec_probe::dv<spec_probe::dep<Z, char*>>(), spec_probe::dv<spec_probe::dep<Z, size_t>>(), spec_probe::dv<spec_probe::dep<Z, const char*>>(), spec_probe::dv<spec_probe::dep<Z, const tm*>>()) } -> spec_probe::same<size_t>; }; static_assert(c<void>); } // ctime.syn#17 call ret
#ifndef __STDC_VERSION_TIME_H__
static_assert(false, "__STDC_VERSION_TIME_H__"); // ctime.syn#18 macro
#endif
#ifndef NULL
static_assert(false, "NULL"); // ctime.syn#19 macro
#endif
#ifndef CLOCKS_PER_SEC
static_assert(false, "CLOCKS_PER_SEC"); // ctime.syn#20 macro
#endif
#ifndef TIME_UTC
static_assert(false, "TIME_UTC"); // ctime.syn#21 macro
#endif
