// Spec-audit probes for [depr.numeric.limits.has.denorm], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <limits>
#define SPEC_PROBE_limits
#include "../probe_support.hpp"
namespace p0 { using namespace std; static_assert(std::is_enum_v<std::float_denorm_style>); } // depr.numeric.limits.has.denorm#1 enum
namespace p1 { using namespace std; static_assert(spec_probe::same<decltype(std::denorm_indeterminate), std::float_denorm_style>); } // depr.numeric.limits.has.denorm#2 enumerator denorm_indeterminate
namespace p2 { using namespace std; static_assert(spec_probe::same<decltype(std::denorm_absent), std::float_denorm_style>); } // depr.numeric.limits.has.denorm#3 enumerator denorm_absent
namespace p3 { using namespace std; static_assert(spec_probe::same<decltype(std::denorm_present), std::float_denorm_style>); } // depr.numeric.limits.has.denorm#4 enumerator denorm_present
