// Spec-audit probes for [depr.c.macros], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <cfloat>
#include <stdbool.h>
#define SPEC_PROBE_cfloat
#define SPEC_PROBE_stdbool_h
#include "../probe_support.hpp"
#ifndef FLT_HAS_SUBNORM
static_assert(false, "FLT_HAS_SUBNORM"); // depr.c.macros#1 macro
#endif
#ifndef DBL_HAS_SUBNORM
static_assert(false, "DBL_HAS_SUBNORM"); // depr.c.macros#2 macro
#endif
#ifndef LDBL_HAS_SUBNORM
static_assert(false, "LDBL_HAS_SUBNORM"); // depr.c.macros#3 macro
#endif
#ifndef DECIMAL_DIG
static_assert(false, "DECIMAL_DIG"); // depr.c.macros#4 macro
#endif
#ifndef __bool_true_false_are_defined
static_assert(false, "__bool_true_false_are_defined"); // depr.c.macros#5 macro
#endif
