// Spec-audit probes for [depr.move.iter.elem], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <iterator>
#define SPEC_PROBE_iterator
#include "../probe_support.hpp"
namespace p0 { using namespace std; using std::move_iterator; } // depr.move.iter.elem#1 presence
namespace p1 { using namespace std; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, const std::move_iterator<int*>&>>().operator->() } -> spec_probe::same<typename std::move_iterator<int*>::pointer>; }; static_assert(c<void>); } // depr.move.iter.elem#2 call ret
namespace p2 { using namespace std; static_assert([]() consteval { auto o = spec_probe::sample<std::move_iterator<int*>>(); (void)(static_cast<const std::move_iterator<int*>&>(o).operator->()); return true; }()); } // depr.move.iter.elem#3 constexpr
