// Spec-audit probes for [exec.recv.concepts], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <execution>
#define SPEC_PROBE_execution
#include "../probe_support.hpp"
namespace p0 { using namespace std; using namespace std::execution; using std::execution::receiver; } // exec.recv.concepts#1 presence
namespace p1 { using namespace std; using namespace std::execution; using std::execution::inlinable_receiver; } // exec.recv.concepts#2 presence
