// Spec-audit probes for [exec.par.scheduler], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <execution>
#define SPEC_PROBE_execution
#include "../probe_support.hpp"
namespace p0 { using namespace std; using namespace std::execution; using std::execution::parallel_scheduler; } // exec.par.scheduler#1 presence
