// Spec-audit probes for [exec.inline.scheduler], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <execution>
#include "../probe_support.hpp"
namespace p0 { using namespace std; using namespace std::execution; using std::execution::inline_scheduler; } // exec.inline.scheduler#1 presence
namespace p1 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<std::execution::inline_scheduler::scheduler_concept, scheduler_tag>); } // exec.inline.scheduler#2 type
namespace p2 { using namespace std; using namespace std::execution; template<class Z> concept c = requires { spec_probe::dv<spec_probe::dep<Z, std::execution::inline_scheduler&>>().schedule(); requires noexcept(spec_probe::dv<spec_probe::dep<Z, std::execution::inline_scheduler&>>().schedule()); }; static_assert(c<void>); } // exec.inline.scheduler#3 call noexcept
namespace p3 { using namespace std; using namespace std::execution; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, const std::execution::inline_scheduler&>>().operator==(spec_probe::dv<spec_probe::dep<Z, const std::execution::inline_scheduler&>>()) } -> spec_probe::same<bool>; requires noexcept(spec_probe::dv<spec_probe::dep<Z, const std::execution::inline_scheduler&>>().operator==(spec_probe::dv<spec_probe::dep<Z, const std::execution::inline_scheduler&>>())); }; static_assert(c<void>); } // exec.inline.scheduler#4 call ret noexcept
