// Spec-audit probes for [execution.syn], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <execution>
#include "../probe_support.hpp"
namespace p0 { using namespace std; using std::is_execution_policy; } // execution.syn#1 presence
namespace p1 { using namespace std; static_assert(spec_probe::same<decltype(std::is_execution_policy_v<int>), const bool>); } // execution.syn#2 var
namespace p2 { using namespace std; using namespace std::execution; using std::execution::sequenced_policy; } // execution.syn#3 presence
namespace p3 { using namespace std; using namespace std::execution; using std::execution::parallel_policy; } // execution.syn#4 presence
namespace p4 { using namespace std; using namespace std::execution; using std::execution::parallel_unsequenced_policy; } // execution.syn#5 presence
namespace p5 { using namespace std; using namespace std::execution; using std::execution::unsequenced_policy; } // execution.syn#6 presence
namespace p6 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::seq), const sequenced_policy>); } // execution.syn#7 var
namespace p7 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::par), const parallel_policy>); } // execution.syn#8 var
namespace p8 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::par_unseq), const parallel_unsequenced_policy>); } // execution.syn#9 var
namespace p9 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::unseq), const unsequenced_policy>); } // execution.syn#10 var
namespace p10 { using namespace std; using std::forwarding_query_t; } // execution.syn#11 presence
namespace p11 { using namespace std; using std::get_allocator_t; } // execution.syn#12 presence
namespace p12 { using namespace std; using std::get_stop_token_t; } // execution.syn#13 presence
namespace p13 { using namespace std; static_assert(spec_probe::same<decltype(std::forwarding_query), const forwarding_query_t>); } // execution.syn#14 var
namespace p14 { using namespace std; static_assert(spec_probe::same<decltype(std::get_allocator), const get_allocator_t>); } // execution.syn#15 var
namespace p15 { using namespace std; static_assert(spec_probe::same<decltype(std::get_stop_token), const get_stop_token_t>); } // execution.syn#16 var
namespace p16 { using namespace std; using T = std::stop_token_of_t<int>; } // execution.syn#17 type exists  (deduced type)
namespace p17 { using namespace std; using namespace std::execution; using std::execution::get_domain_t; } // execution.syn#18 presence
namespace p18 { using namespace std; using namespace std::execution; using std::execution::get_scheduler_t; } // execution.syn#19 presence
namespace p19 { using namespace std; using namespace std::execution; using std::execution::get_start_scheduler_t; } // execution.syn#20 presence
namespace p20 { using namespace std; using namespace std::execution; using std::execution::get_delegation_scheduler_t; } // execution.syn#21 presence
namespace p21 { using namespace std; using namespace std::execution; using std::execution::get_forward_progress_guarantee_t; } // execution.syn#22 presence
namespace p22 { using namespace std; using namespace std::execution; using std::execution::get_completion_scheduler_t; } // execution.syn#23 presence
namespace p23 { using namespace std; using namespace std::execution; using std::execution::get_completion_domain_t; } // execution.syn#24 presence
namespace p24 { using namespace std; using namespace std::execution; using std::execution::get_await_completion_adaptor_t; } // execution.syn#25 presence
namespace p25 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::get_domain), const get_domain_t>); } // execution.syn#26 var
namespace p26 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::get_scheduler), const get_scheduler_t>); } // execution.syn#27 var
namespace p27 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::get_start_scheduler), const get_start_scheduler_t>); } // execution.syn#28 var
namespace p28 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::get_delegation_scheduler), const get_delegation_scheduler_t>); } // execution.syn#29 var
namespace p29 { using namespace std; using namespace std::execution; using std::execution::forward_progress_guarantee; } // execution.syn#30 presence
namespace p30 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::get_forward_progress_guarantee), const get_forward_progress_guarantee_t>); } // execution.syn#31 var
namespace p31 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::get_completion_scheduler<execution::set_value_t>), const get_completion_scheduler_t<execution::set_value_t>>); } // execution.syn#32 var
namespace p32 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::get_completion_domain<execution::set_value_t>), const get_completion_domain_t<execution::set_value_t>>); } // execution.syn#33 var
namespace p33 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::get_await_completion_adaptor), const get_await_completion_adaptor_t>); } // execution.syn#34 var
namespace p34 { using namespace std; using namespace std::execution; using std::execution::get_env_t; } // execution.syn#35 presence
namespace p35 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::get_env), const get_env_t>); } // execution.syn#36 var
namespace p36 { using namespace std; using namespace std::execution; using T = std::execution::env_of_t<int>; } // execution.syn#37 type exists  (deduced type)
namespace p37 { using namespace std; using namespace std::execution; using std::execution::indeterminate_domain; } // execution.syn#38 presence
namespace p38 { using namespace std; using namespace std::execution; using std::execution::default_domain; } // execution.syn#39 presence
namespace p39 { using namespace std; using namespace std::execution; using std::execution::scheduler_tag; } // execution.syn#40 presence
namespace p40 { using namespace std; using namespace std::execution; using std::execution::scheduler; } // execution.syn#41 presence
namespace p41 { using namespace std; using namespace std::execution; using std::execution::receiver_tag; } // execution.syn#42 presence
namespace p42 { using namespace std; using namespace std::execution; using std::execution::receiver; } // execution.syn#43 presence
namespace p43 { using namespace std; using namespace std::execution; using std::execution::inlinable_receiver; } // execution.syn#44 presence
namespace p44 { using namespace std; using namespace std::execution; using std::execution::set_value_t; } // execution.syn#45 presence
namespace p45 { using namespace std; using namespace std::execution; using std::execution::set_error_t; } // execution.syn#46 presence
namespace p46 { using namespace std; using namespace std::execution; using std::execution::set_stopped_t; } // execution.syn#47 presence
namespace p47 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::set_value), const set_value_t>); } // execution.syn#48 var
namespace p48 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::set_error), const set_error_t>); } // execution.syn#49 var
namespace p49 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::set_stopped), const set_stopped_t>); } // execution.syn#50 var
namespace p50 { using namespace std; using namespace std::execution; using std::execution::operation_state_tag; } // execution.syn#51 presence
namespace p51 { using namespace std; using namespace std::execution; using std::execution::operation_state; } // execution.syn#52 presence
namespace p52 { using namespace std; using namespace std::execution; using std::execution::start_t; } // execution.syn#53 presence
namespace p53 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::start), const start_t>); } // execution.syn#54 var
namespace p54 { using namespace std; using namespace std::execution; using std::execution::sender_tag; } // execution.syn#55 presence
namespace p55 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::enable_sender<spec_probe::sndr>), const bool>); } // execution.syn#56 var
namespace p56 { using namespace std; using namespace std::execution; using std::execution::sender; } // execution.syn#57 presence
namespace p57 { using namespace std; using namespace std::execution; using std::execution::sender_in; } // execution.syn#58 presence
namespace p58 { using namespace std; using namespace std::execution; using std::execution::dependent_sender; } // execution.syn#59 presence
namespace p59 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::sends_stopped<spec_probe::sndr, execution::env<>>), const bool>); } // execution.syn#60 var
namespace p60 { using namespace std; using namespace std::execution; using T = std::execution::tag_of_t<spec_probe::sndr>; } // execution.syn#61 type exists  (exposition-only or unspecified: see below)
namespace p61 { using namespace std; using namespace std::execution; template<class Z> concept c = requires { std::execution::transform_sender(spec_probe::dv<spec_probe::dep<Z, spec_probe::sndr&&>>(), spec_probe::dv<spec_probe::dep<Z, const execution::env<>&>>()); }; static_assert(c<void>); } // execution.syn#62 call
namespace p62 { using namespace std; using namespace std::execution; template<class Z> concept c = requires { std::execution::apply_sender(spec_probe::dv<spec_probe::dep<Z, execution::default_domain>>(), spec_probe::dv<spec_probe::dep<Z, execution::set_value_t>>(), spec_probe::dv<spec_probe::dep<Z, spec_probe::sndr&&>>(), spec_probe::dv<spec_probe::dep<Z, int&&>>()); }; static_assert(c<void>); } // execution.syn#63 call
namespace p63 { using namespace std; using namespace std::execution; template<class Z> concept c = requires { std::execution::get_completion_signatures<spec_probe::sndr>(); }; static_assert(c<void>); } // execution.syn#64 call
namespace p64 { using namespace std; using namespace std::execution; using T = std::execution::completion_signatures_of_t<spec_probe::sndr, >; } // execution.syn#65 type exists  (deduced type)
namespace p65 { using namespace std; using namespace std::execution; using std::execution::connect_t; } // execution.syn#66 presence
namespace p66 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::connect), const connect_t>); } // execution.syn#67 var
namespace p67 { using namespace std; using namespace std::execution; using T = std::execution::connect_result_t<spec_probe::sndr, spec_probe::rcvr>; } // execution.syn#68 type exists  (deduced type)
namespace p68 { using namespace std; using namespace std::execution; using std::execution::just_t; } // execution.syn#69 presence
namespace p69 { using namespace std; using namespace std::execution; using std::execution::just_error_t; } // execution.syn#70 presence
namespace p70 { using namespace std; using namespace std::execution; using std::execution::just_stopped_t; } // execution.syn#71 presence
namespace p71 { using namespace std; using namespace std::execution; using std::execution::schedule_t; } // execution.syn#72 presence
namespace p72 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::just), const just_t>); } // execution.syn#73 var
namespace p73 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::just_error), const just_error_t>); } // execution.syn#74 var
namespace p74 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::just_stopped), const just_stopped_t>); } // execution.syn#75 var
namespace p75 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::schedule), const schedule_t>); } // execution.syn#76 var
namespace p76 { using namespace std; using namespace std::execution; using T = decltype(std::execution::read_env); } // execution.syn#77 var exists (exposition-only or unspecified: unspecified)
namespace p77 { using namespace std; using namespace std::execution; using T = std::execution::schedule_result_t<execution::inline_scheduler>; } // execution.syn#78 type exists  (deduced type)
namespace p78 { using namespace std; using namespace std::execution; using std::execution::sender_adaptor_closure; } // execution.syn#79 presence
namespace p79 { using namespace std; using namespace std::execution; using std::execution::starts_on_t; } // execution.syn#80 presence
namespace p80 { using namespace std; using namespace std::execution; using std::execution::continues_on_t; } // execution.syn#81 presence
namespace p81 { using namespace std; using namespace std::execution; using std::execution::on_t; } // execution.syn#82 presence
namespace p82 { using namespace std; using namespace std::execution; using std::execution::schedule_from_t; } // execution.syn#83 presence
namespace p83 { using namespace std; using namespace std::execution; using std::execution::then_t; } // execution.syn#84 presence
namespace p84 { using namespace std; using namespace std::execution; using std::execution::upon_error_t; } // execution.syn#85 presence
namespace p85 { using namespace std; using namespace std::execution; using std::execution::upon_stopped_t; } // execution.syn#86 presence
namespace p86 { using namespace std; using namespace std::execution; using std::execution::let_value_t; } // execution.syn#87 presence
namespace p87 { using namespace std; using namespace std::execution; using std::execution::let_error_t; } // execution.syn#88 presence
namespace p88 { using namespace std; using namespace std::execution; using std::execution::let_stopped_t; } // execution.syn#89 presence
namespace p89 { using namespace std; using namespace std::execution; using std::execution::bulk_t; } // execution.syn#90 presence
namespace p90 { using namespace std; using namespace std::execution; using std::execution::bulk_chunked_t; } // execution.syn#91 presence
namespace p91 { using namespace std; using namespace std::execution; using std::execution::bulk_unchunked_t; } // execution.syn#92 presence
namespace p92 { using namespace std; using namespace std::execution; using std::execution::when_all_t; } // execution.syn#93 presence
namespace p93 { using namespace std; using namespace std::execution; using std::execution::when_all_with_variant_t; } // execution.syn#94 presence
namespace p94 { using namespace std; using namespace std::execution; using std::execution::into_variant_t; } // execution.syn#95 presence
namespace p95 { using namespace std; using namespace std::execution; using std::execution::stopped_as_optional_t; } // execution.syn#96 presence
namespace p96 { using namespace std; using namespace std::execution; using std::execution::stopped_as_error_t; } // execution.syn#97 presence
namespace p97 { using namespace std; using namespace std::execution; using std::execution::associate_t; } // execution.syn#98 presence
namespace p98 { using namespace std; using namespace std::execution; using std::execution::spawn_future_t; } // execution.syn#99 presence
namespace p99 { using namespace std; using namespace std::execution; using T = decltype(std::execution::write_env); } // execution.syn#100 var exists (exposition-only or unspecified: unspecified)
namespace p100 { using namespace std; using namespace std::execution; using T = decltype(std::execution::unstoppable); } // execution.syn#101 var exists (exposition-only or unspecified: unspecified)
namespace p101 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::starts_on), const starts_on_t>); } // execution.syn#102 var
namespace p102 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::continues_on), const continues_on_t>); } // execution.syn#103 var
namespace p103 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::on), const on_t>); } // execution.syn#104 var
namespace p104 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::schedule_from), const schedule_from_t>); } // execution.syn#105 var
namespace p105 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::then), const then_t>); } // execution.syn#106 var
namespace p106 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::upon_error), const upon_error_t>); } // execution.syn#107 var
namespace p107 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::upon_stopped), const upon_stopped_t>); } // execution.syn#108 var
namespace p108 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::let_value), const let_value_t>); } // execution.syn#109 var
namespace p109 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::let_error), const let_error_t>); } // execution.syn#110 var
namespace p110 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::let_stopped), const let_stopped_t>); } // execution.syn#111 var
namespace p111 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::bulk), const bulk_t>); } // execution.syn#112 var
namespace p112 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::bulk_chunked), const bulk_chunked_t>); } // execution.syn#113 var
namespace p113 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::bulk_unchunked), const bulk_unchunked_t>); } // execution.syn#114 var
namespace p114 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::when_all), const when_all_t>); } // execution.syn#115 var
namespace p115 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::when_all_with_variant), const when_all_with_variant_t>); } // execution.syn#116 var
namespace p116 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::into_variant), const into_variant_t>); } // execution.syn#117 var
namespace p117 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::stopped_as_optional), const stopped_as_optional_t>); } // execution.syn#118 var
namespace p118 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::stopped_as_error), const stopped_as_error_t>); } // execution.syn#119 var
namespace p119 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::associate), const associate_t>); } // execution.syn#120 var
namespace p120 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::spawn_future), const spawn_future_t>); } // execution.syn#121 var
namespace p121 { using namespace std; using namespace std::this_thread; using std::this_thread::sync_wait_t; } // execution.syn#122 presence
namespace p122 { using namespace std; using namespace std::this_thread; using std::this_thread::sync_wait_with_variant_t; } // execution.syn#123 presence
namespace p123 { using namespace std; using namespace std::this_thread; static_assert(spec_probe::same<decltype(std::this_thread::sync_wait), const sync_wait_t>); } // execution.syn#124 var
namespace p124 { using namespace std; using namespace std::this_thread; static_assert(spec_probe::same<decltype(std::this_thread::sync_wait_with_variant), const sync_wait_with_variant_t>); } // execution.syn#125 var
namespace p125 { using namespace std; using namespace std::execution; using std::execution::spawn_t; } // execution.syn#126 presence
namespace p126 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::spawn), const spawn_t>); } // execution.syn#127 var
namespace p127 { using namespace std; using namespace std::execution; using std::execution::completion_signatures; } // execution.syn#128 presence
namespace p128 { using namespace std; using namespace std::execution; using std::execution::dependent_sender_error; } // execution.syn#129 presence
namespace p129 { using namespace std; using namespace std::execution; static_assert(std::is_base_of_v<exception, std::execution::dependent_sender_error> && std::is_convertible_v<std::execution::dependent_sender_error*, exception*>); } // execution.syn#130 base exception
namespace p130 { using namespace std; using namespace std::execution; using std::execution::prop; } // execution.syn#131 presence
namespace p131 { using namespace std; using namespace std::execution; using std::execution::env; } // execution.syn#132 presence
namespace p132 { using namespace std; using namespace std::execution; using std::execution::run_loop; } // execution.syn#133 presence
namespace p133 { using namespace std; using namespace std::execution; using std::execution::as_awaitable_t; } // execution.syn#134 presence
namespace p134 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::as_awaitable), const as_awaitable_t>); } // execution.syn#135 var
namespace p135 { using namespace std; using namespace std::execution; using std::execution::with_awaitable_senders; } // execution.syn#136 presence
namespace p136 { using namespace std; using namespace std::execution; using std::execution::affine_t; } // execution.syn#137 presence
namespace p137 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::affine), const affine_t>); } // execution.syn#138 var
namespace p138 { using namespace std; using namespace std::execution; using std::execution::inline_scheduler; } // execution.syn#139 presence
namespace p139 { using namespace std; using namespace std::execution; using std::execution::task_scheduler; } // execution.syn#140 presence
namespace p140 { using namespace std; using namespace std::execution; using std::execution::with_error; } // execution.syn#141 presence
namespace p141 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<std::execution::with_error<int>::type, remove_cvref_t<int>>); } // execution.syn#142 type
namespace p142 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::with_error<int>::error), std::execution::with_error<int>::type>); } // execution.syn#143 var
namespace p143 { using namespace std; using namespace std::execution; template<class Z> concept c = requires { requires spec_probe::same<decltype(std::execution::with_error(spec_probe::dv<spec_probe::dep<Z, int>>())), with_error<int>>; }; static_assert(c<void>); } // execution.syn#144 deduction guide
namespace p144 { using namespace std; using namespace std::execution; using std::execution::task; } // execution.syn#145 presence
namespace p145 { using namespace std; using namespace std::execution; using std::execution::scope_association; } // execution.syn#146 presence
namespace p146 { using namespace std; using namespace std::execution; using std::execution::scope_token; } // execution.syn#147 presence
namespace p147 { using namespace std; using namespace std::execution; using std::execution::simple_counting_scope; } // execution.syn#148 presence
namespace p148 { using namespace std; using namespace std::execution; using std::execution::counting_scope; } // execution.syn#149 presence
namespace p149 { using namespace std; using namespace std::execution; using std::execution::parallel_scheduler; } // execution.syn#150 presence
namespace p150 { using namespace std; using namespace std::execution; template<class Z> concept c = requires { { std::execution::get_parallel_scheduler() } -> spec_probe::same<parallel_scheduler>; }; static_assert(c<void>); } // execution.syn#151 call ret
namespace p151 { using namespace std; using namespace std::execution; using namespace std::execution::parallel_scheduler_replacement; using std::execution::parallel_scheduler_replacement::receiver_proxy; } // execution.syn#152 presence
namespace p152 { using namespace std; using namespace std::execution; using namespace std::execution::parallel_scheduler_replacement; using std::execution::parallel_scheduler_replacement::bulk_item_receiver_proxy; } // execution.syn#153 presence
namespace p153 { using namespace std; using namespace std::execution; using namespace std::execution::parallel_scheduler_replacement; using std::execution::parallel_scheduler_replacement::parallel_scheduler_backend; } // execution.syn#154 presence
namespace p154 { using namespace std; using namespace std::execution; using namespace std::execution::parallel_scheduler_replacement; template<class Z> concept c = requires { { std::execution::parallel_scheduler_replacement::query_parallel_scheduler_backend() } -> spec_probe::same<shared_ptr<parallel_scheduler_backend>>; }; static_assert(c<void>); } // execution.syn#155 call ret
