// Spec-audit probes for [exec.cmplsig], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <execution>
#define SPEC_PROBE_execution
#include "../probe_support.hpp"
namespace p0 { using namespace std; using namespace std::execution; using std::execution::completion_signatures; } // exec.cmplsig#1 presence
namespace p1 { using namespace std; using namespace std::execution; static_assert(spec_probe::same<decltype(std::execution::sends_stopped<spec_probe::sndr, execution::env<>>), const bool>); } // exec.cmplsig#2 var
