// Spec-audit probes for [futures.promise], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <future>
#define SPEC_PROBE_future
#include "../probe_support.hpp"
namespace p0 { using namespace std; using std::promise; } // futures.promise#1 presence
namespace p1 { using namespace std; static_assert(std::is_constructible_v<std::promise<int>>); } // futures.promise#2 ctor
namespace p2 { using namespace std; static_assert(std::is_constructible_v<std::promise<int>, allocator_arg_t, const allocator<int>&>); } // futures.promise#3 ctor
namespace p3 { using namespace std; static_assert(std::is_constructible_v<std::promise<int>, std::promise<int>&&> && std::is_nothrow_constructible_v<std::promise<int>, std::promise<int>&&> && std::is_convertible_v<std::promise<int>&&, std::promise<int>>); } // futures.promise#4 ctor noexcept
namespace p4 { using namespace std; static_assert(!std::is_constructible_v<std::promise<int>, const std::promise<int>&>); } // futures.promise#5 deleted ctor
namespace p5 { using namespace std; static_assert(std::is_nothrow_destructible_v<std::promise<int>>); } // futures.promise#6 destructor
namespace p6 { using namespace std; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, std::promise<int>&>>().operator=(spec_probe::dv<spec_probe::dep<Z, std::promise<int>&&>>()) } -> spec_probe::same<std::promise<int>&>; requires noexcept(spec_probe::dv<spec_probe::dep<Z, std::promise<int>&>>().operator=(spec_probe::dv<spec_probe::dep<Z, std::promise<int>&&>>())); }; static_assert(c<void>); } // futures.promise#7 call ret noexcept
namespace p7 { using namespace std; template<class Z> concept c = !requires { spec_probe::dv<spec_probe::dep<Z, std::promise<int>&>>().operator=(spec_probe::dv<spec_probe::dep<Z, const std::promise<int>&>>()); }; static_assert(c<void>); } // futures.promise#8 deleted call
namespace p8 { using namespace std; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, std::promise<int>&>>().swap(spec_probe::dv<spec_probe::dep<Z, std::promise<int>&>>()) } -> spec_probe::same<void>; requires noexcept(spec_probe::dv<spec_probe::dep<Z, std::promise<int>&>>().swap(spec_probe::dv<spec_probe::dep<Z, std::promise<int>&>>())); }; static_assert(c<void>); } // futures.promise#9 call ret noexcept
namespace p9 { using namespace std; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, std::promise<int>&>>().get_future() } -> spec_probe::same<future<int>>; }; static_assert(c<void>); } // futures.promise#10 call ret
namespace p10 { using namespace std; struct D : std::promise<int> { using std::promise<int>::set_value; }; } // futures.promise#11 presence (exposition-only or unspecified: see below)
namespace p11 { using namespace std; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, std::promise<int>&>>().set_exception(spec_probe::dv<spec_probe::dep<Z, exception_ptr>>()) } -> spec_probe::same<void>; }; static_assert(c<void>); } // futures.promise#12 call ret
namespace p12 { using namespace std; struct D : std::promise<int> { using std::promise<int>::set_value_at_thread_exit; }; } // futures.promise#13 presence (exposition-only or unspecified: see below)
namespace p13 { using namespace std; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, std::promise<int>&>>().set_exception_at_thread_exit(spec_probe::dv<spec_probe::dep<Z, exception_ptr>>()) } -> spec_probe::same<void>; }; static_assert(c<void>); } // futures.promise#14 call ret
