// Spec-audit probes for [futures.future.error], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <future>
#include "../probe_support.hpp"
namespace p0 { using namespace std; using std::future_error; } // futures.future.error#1 presence
namespace p1 { using namespace std; static_assert(std::is_base_of_v<logic_error, std::future_error> && std::is_convertible_v<std::future_error*, logic_error*>); } // futures.future.error#2 base logic_error
namespace p2 { using namespace std; static_assert(std::is_constructible_v<std::future_error, future_errc> && !std::is_convertible_v<future_errc, std::future_error>); } // futures.future.error#3 ctor explicit
namespace p3 { using namespace std; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, const std::future_error&>>().code() } -> spec_probe::same<const error_code&>; requires noexcept(spec_probe::dv<spec_probe::dep<Z, const std::future_error&>>().code()); }; static_assert(c<void>); } // futures.future.error#4 call ret noexcept
namespace p4 { using namespace std; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, const std::future_error&>>().what() } -> spec_probe::same<const char*>; requires noexcept(spec_probe::dv<spec_probe::dep<Z, const std::future_error&>>().what()); }; static_assert(c<void>); } // futures.future.error#5 call ret noexcept
