// Spec-audit probes for [ios.syn], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <ios>
#include "../probe_support.hpp"
namespace p0 { using namespace std; using T = std::streamoff; } // ios.syn#1 type exists (exposition-only or unspecified: implementation-defined)
namespace p1 { using namespace std; using T = std::streamsize; } // ios.syn#2 type exists (exposition-only or unspecified: implementation-defined)
namespace p2 { using namespace std; using std::fpos; } // ios.syn#3 presence
namespace p3 { using namespace std; using std::ios_base; } // ios.syn#4 presence
namespace p4 { using namespace std; using std::basic_ios; } // ios.syn#5 presence
namespace p5 { using namespace std; template<class Z> concept c = requires { { std::boolalpha(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#6 call ret
namespace p6 { using namespace std; template<class Z> concept c = requires { { std::noboolalpha(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#7 call ret
namespace p7 { using namespace std; template<class Z> concept c = requires { { std::showbase(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#8 call ret
namespace p8 { using namespace std; template<class Z> concept c = requires { { std::noshowbase(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#9 call ret
namespace p9 { using namespace std; template<class Z> concept c = requires { { std::showpoint(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#10 call ret
namespace p10 { using namespace std; template<class Z> concept c = requires { { std::noshowpoint(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#11 call ret
namespace p11 { using namespace std; template<class Z> concept c = requires { { std::showpos(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#12 call ret
namespace p12 { using namespace std; template<class Z> concept c = requires { { std::noshowpos(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#13 call ret
namespace p13 { using namespace std; template<class Z> concept c = requires { { std::skipws(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#14 call ret
namespace p14 { using namespace std; template<class Z> concept c = requires { { std::noskipws(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#15 call ret
namespace p15 { using namespace std; template<class Z> concept c = requires { { std::uppercase(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#16 call ret
namespace p16 { using namespace std; template<class Z> concept c = requires { { std::nouppercase(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#17 call ret
namespace p17 { using namespace std; template<class Z> concept c = requires { { std::unitbuf(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#18 call ret
namespace p18 { using namespace std; template<class Z> concept c = requires { { std::nounitbuf(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#19 call ret
namespace p19 { using namespace std; template<class Z> concept c = requires { { std::internal(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#20 call ret
namespace p20 { using namespace std; template<class Z> concept c = requires { { std::left(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#21 call ret
namespace p21 { using namespace std; template<class Z> concept c = requires { { std::right(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#22 call ret
namespace p22 { using namespace std; template<class Z> concept c = requires { { std::dec(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#23 call ret
namespace p23 { using namespace std; template<class Z> concept c = requires { { std::hex(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#24 call ret
namespace p24 { using namespace std; template<class Z> concept c = requires { { std::oct(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#25 call ret
namespace p25 { using namespace std; template<class Z> concept c = requires { { std::fixed(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#26 call ret
namespace p26 { using namespace std; template<class Z> concept c = requires { { std::scientific(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#27 call ret
namespace p27 { using namespace std; template<class Z> concept c = requires { { std::hexfloat(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#28 call ret
namespace p28 { using namespace std; template<class Z> concept c = requires { { std::defaultfloat(spec_probe::dv<spec_probe::dep<Z, ios_base&>>()) } -> spec_probe::same<ios_base&>; }; static_assert(c<void>); } // ios.syn#29 call ret
namespace p29 { using namespace std; static_assert(std::is_enum_v<std::io_errc> && !std::is_convertible_v<std::io_errc, int>); } // ios.syn#30 enum scoped
namespace p30 { using namespace std; static_assert(spec_probe::same<decltype(std::io_errc::stream), std::io_errc>); } // ios.syn#31 enumerator stream
namespace p31 { using namespace std; template<class Z> concept c = requires { sizeof(spec_probe::dep<Z, std::is_error_code_enum<io_errc>>); }; static_assert(c<void>); } // ios.syn#32 specialization complete
namespace p32 { using namespace std; template<class Z> concept c = requires { { std::make_error_code(spec_probe::dv<spec_probe::dep<Z, io_errc>>()) } -> spec_probe::same<error_code>; requires noexcept(std::make_error_code(spec_probe::dv<spec_probe::dep<Z, io_errc>>())); }; static_assert(c<void>); } // ios.syn#33 call ret noexcept
namespace p33 { using namespace std; template<class Z> concept c = requires { { std::make_error_condition(spec_probe::dv<spec_probe::dep<Z, io_errc>>()) } -> spec_probe::same<error_condition>; requires noexcept(std::make_error_condition(spec_probe::dv<spec_probe::dep<Z, io_errc>>())); }; static_assert(c<void>); } // ios.syn#34 call ret noexcept
namespace p34 { using namespace std; template<class Z> concept c = requires { { std::iostream_category() } -> spec_probe::same<const error_category&>; requires noexcept(std::iostream_category()); }; static_assert(c<void>); } // ios.syn#35 call ret noexcept
