// Spec-audit probes for [iosfwd.syn], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <iosfwd>
#define SPEC_PROBE_iosfwd
#include "../probe_support.hpp"
namespace p0 { using namespace std; using std::char_traits; } // iosfwd.syn#1 presence
namespace p1 { using namespace std; template<class Z> concept c = requires { sizeof(spec_probe::dep<Z, std::char_traits<char>>); }; static_assert(c<void>); } // iosfwd.syn#2 specialization complete
namespace p2 { using namespace std; template<class Z> concept c = requires { sizeof(spec_probe::dep<Z, std::char_traits<char8_t>>); }; static_assert(c<void>); } // iosfwd.syn#3 specialization complete
namespace p3 { using namespace std; template<class Z> concept c = requires { sizeof(spec_probe::dep<Z, std::char_traits<char16_t>>); }; static_assert(c<void>); } // iosfwd.syn#4 specialization complete
namespace p4 { using namespace std; template<class Z> concept c = requires { sizeof(spec_probe::dep<Z, std::char_traits<char32_t>>); }; static_assert(c<void>); } // iosfwd.syn#5 specialization complete
namespace p5 { using namespace std; template<class Z> concept c = requires { sizeof(spec_probe::dep<Z, std::char_traits<wchar_t>>); }; static_assert(c<void>); } // iosfwd.syn#6 specialization complete
namespace p6 { using namespace std; using std::allocator; } // iosfwd.syn#7 presence
namespace p7 { using namespace std; using std::basic_ios; } // iosfwd.syn#8 presence
namespace p8 { using namespace std; using std::basic_streambuf; } // iosfwd.syn#9 presence
namespace p9 { using namespace std; using std::basic_istream; } // iosfwd.syn#10 presence
namespace p10 { using namespace std; using std::basic_ostream; } // iosfwd.syn#11 presence
namespace p11 { using namespace std; using std::basic_iostream; } // iosfwd.syn#12 presence
namespace p12 { using namespace std; using std::basic_stringbuf; } // iosfwd.syn#13 presence
namespace p13 { using namespace std; using std::basic_istringstream; } // iosfwd.syn#14 presence
namespace p14 { using namespace std; using std::basic_ostringstream; } // iosfwd.syn#15 presence
namespace p15 { using namespace std; using std::basic_stringstream; } // iosfwd.syn#16 presence
namespace p16 { using namespace std; using std::basic_spanbuf; } // iosfwd.syn#17 presence
namespace p17 { using namespace std; using std::basic_ispanstream; } // iosfwd.syn#18 presence
namespace p18 { using namespace std; using std::basic_ospanstream; } // iosfwd.syn#19 presence
namespace p19 { using namespace std; using std::basic_spanstream; } // iosfwd.syn#20 presence
namespace p20 { using namespace std; using std::basic_filebuf; } // iosfwd.syn#21 presence
namespace p21 { using namespace std; using std::basic_ifstream; } // iosfwd.syn#22 presence
namespace p22 { using namespace std; using std::basic_ofstream; } // iosfwd.syn#23 presence
namespace p23 { using namespace std; using std::basic_fstream; } // iosfwd.syn#24 presence
namespace p24 { using namespace std; using std::basic_syncbuf; } // iosfwd.syn#25 presence
namespace p25 { using namespace std; using std::basic_osyncstream; } // iosfwd.syn#26 presence
namespace p26 { using namespace std; using std::istreambuf_iterator; } // iosfwd.syn#27 presence
namespace p27 { using namespace std; using std::ostreambuf_iterator; } // iosfwd.syn#28 presence
namespace p28 { using namespace std; static_assert(spec_probe::same<std::ios, basic_ios<char>>); } // iosfwd.syn#29 type
namespace p29 { using namespace std; static_assert(spec_probe::same<std::wios, basic_ios<wchar_t>>); } // iosfwd.syn#30 type
namespace p30 { using namespace std; static_assert(spec_probe::same<std::streambuf, basic_streambuf<char>>); } // iosfwd.syn#31 type
namespace p31 { using namespace std; static_assert(spec_probe::same<std::istream, basic_istream<char>>); } // iosfwd.syn#32 type
namespace p32 { using namespace std; static_assert(spec_probe::same<std::ostream, basic_ostream<char>>); } // iosfwd.syn#33 type
namespace p33 { using namespace std; static_assert(spec_probe::same<std::iostream, basic_iostream<char>>); } // iosfwd.syn#34 type
namespace p34 { using namespace std; static_assert(spec_probe::same<std::stringbuf, basic_stringbuf<char>>); } // iosfwd.syn#35 type
namespace p35 { using namespace std; static_assert(spec_probe::same<std::istringstream, basic_istringstream<char>>); } // iosfwd.syn#36 type
namespace p36 { using namespace std; static_assert(spec_probe::same<std::ostringstream, basic_ostringstream<char>>); } // iosfwd.syn#37 type
namespace p37 { using namespace std; static_assert(spec_probe::same<std::stringstream, basic_stringstream<char>>); } // iosfwd.syn#38 type
namespace p38 { using namespace std; static_assert(spec_probe::same<std::spanbuf, basic_spanbuf<char>>); } // iosfwd.syn#39 type
namespace p39 { using namespace std; static_assert(spec_probe::same<std::ispanstream, basic_ispanstream<char>>); } // iosfwd.syn#40 type
namespace p40 { using namespace std; static_assert(spec_probe::same<std::ospanstream, basic_ospanstream<char>>); } // iosfwd.syn#41 type
namespace p41 { using namespace std; static_assert(spec_probe::same<std::spanstream, basic_spanstream<char>>); } // iosfwd.syn#42 type
namespace p42 { using namespace std; static_assert(spec_probe::same<std::filebuf, basic_filebuf<char>>); } // iosfwd.syn#43 type
namespace p43 { using namespace std; static_assert(spec_probe::same<std::ifstream, basic_ifstream<char>>); } // iosfwd.syn#44 type
namespace p44 { using namespace std; static_assert(spec_probe::same<std::ofstream, basic_ofstream<char>>); } // iosfwd.syn#45 type
namespace p45 { using namespace std; static_assert(spec_probe::same<std::fstream, basic_fstream<char>>); } // iosfwd.syn#46 type
namespace p46 { using namespace std; static_assert(spec_probe::same<std::syncbuf, basic_syncbuf<char>>); } // iosfwd.syn#47 type
namespace p47 { using namespace std; static_assert(spec_probe::same<std::osyncstream, basic_osyncstream<char>>); } // iosfwd.syn#48 type
namespace p48 { using namespace std; static_assert(spec_probe::same<std::wstreambuf, basic_streambuf<wchar_t>>); } // iosfwd.syn#49 type
namespace p49 { using namespace std; static_assert(spec_probe::same<std::wistream, basic_istream<wchar_t>>); } // iosfwd.syn#50 type
namespace p50 { using namespace std; static_assert(spec_probe::same<std::wostream, basic_ostream<wchar_t>>); } // iosfwd.syn#51 type
namespace p51 { using namespace std; static_assert(spec_probe::same<std::wiostream, basic_iostream<wchar_t>>); } // iosfwd.syn#52 type
namespace p52 { using namespace std; static_assert(spec_probe::same<std::wstringbuf, basic_stringbuf<wchar_t>>); } // iosfwd.syn#53 type
namespace p53 { using namespace std; static_assert(spec_probe::same<std::wistringstream, basic_istringstream<wchar_t>>); } // iosfwd.syn#54 type
namespace p54 { using namespace std; static_assert(spec_probe::same<std::wostringstream, basic_ostringstream<wchar_t>>); } // iosfwd.syn#55 type
namespace p55 { using namespace std; static_assert(spec_probe::same<std::wstringstream, basic_stringstream<wchar_t>>); } // iosfwd.syn#56 type
namespace p56 { using namespace std; static_assert(spec_probe::same<std::wspanbuf, basic_spanbuf<wchar_t>>); } // iosfwd.syn#57 type
namespace p57 { using namespace std; static_assert(spec_probe::same<std::wispanstream, basic_ispanstream<wchar_t>>); } // iosfwd.syn#58 type
namespace p58 { using namespace std; static_assert(spec_probe::same<std::wospanstream, basic_ospanstream<wchar_t>>); } // iosfwd.syn#59 type
namespace p59 { using namespace std; static_assert(spec_probe::same<std::wspanstream, basic_spanstream<wchar_t>>); } // iosfwd.syn#60 type
namespace p60 { using namespace std; static_assert(spec_probe::same<std::wfilebuf, basic_filebuf<wchar_t>>); } // iosfwd.syn#61 type
namespace p61 { using namespace std; static_assert(spec_probe::same<std::wifstream, basic_ifstream<wchar_t>>); } // iosfwd.syn#62 type
namespace p62 { using namespace std; static_assert(spec_probe::same<std::wofstream, basic_ofstream<wchar_t>>); } // iosfwd.syn#63 type
namespace p63 { using namespace std; static_assert(spec_probe::same<std::wfstream, basic_fstream<wchar_t>>); } // iosfwd.syn#64 type
namespace p64 { using namespace std; static_assert(spec_probe::same<std::wsyncbuf, basic_syncbuf<wchar_t>>); } // iosfwd.syn#65 type
namespace p65 { using namespace std; static_assert(spec_probe::same<std::wosyncstream, basic_osyncstream<wchar_t>>); } // iosfwd.syn#66 type
namespace p66 { using namespace std; using std::fpos; } // iosfwd.syn#67 presence
namespace p67 { using namespace std; static_assert(spec_probe::same<std::streampos, fpos<char_traits<char>::state_type>>); } // iosfwd.syn#68 type
namespace p68 { using namespace std; static_assert(spec_probe::same<std::wstreampos, fpos<char_traits<wchar_t>::state_type>>); } // iosfwd.syn#69 type
namespace p69 { using namespace std; static_assert(spec_probe::same<std::u8streampos, fpos<char_traits<char8_t>::state_type>>); } // iosfwd.syn#70 type
namespace p70 { using namespace std; static_assert(spec_probe::same<std::u16streampos, fpos<char_traits<char16_t>::state_type>>); } // iosfwd.syn#71 type
namespace p71 { using namespace std; static_assert(spec_probe::same<std::u32streampos, fpos<char_traits<char32_t>::state_type>>); } // iosfwd.syn#72 type
