// Spec-audit probes for [istream.sentry], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <istream>
#include "../probe_support.hpp"
namespace p0 { using namespace std; template<class Z> concept c = requires { sizeof(spec_probe::dep<Z, std::basic_istream<char,char_traits<char>>>); }; static_assert(c<void>); } // istream.sentry#1 specialization complete
namespace p1 { using namespace std; template<class Z> concept c = requires { spec_probe::dv<spec_probe::dep<Z, std::basic_istream<char,char_traits<char>>&>>().sentry(spec_probe::dv<spec_probe::dep<Z, std::basic_istream<char,char_traits<char>>&>>(), spec_probe::dv<spec_probe::dep<Z, bool>>()); }; static_assert(c<void>); } // istream.sentry#2 call
namespace p2 { using namespace std; template<class Z> concept c = requires { spec_probe::dv<spec_probe::dep<Z, std::basic_istream<char,char_traits<char>>&>>().sentry(spec_probe::dv<spec_probe::dep<Z, std::basic_istream<char,char_traits<char>>&>>()); }; static_assert(c<void>); } // istream.sentry#3 call (defaults)
namespace p3 { using namespace std; static_assert(std::is_nothrow_destructible_v<std::basic_istream<char,char_traits<char>>>); } // istream.sentry#4 destructor
namespace p4 { using namespace std; template<class Z> concept c = requires { static_cast<bool>(spec_probe::dv<spec_probe::dep<Z, const std::basic_istream<char,char_traits<char>>&>>()); }; static_assert(c<void>); } // istream.sentry#5 call
namespace p5 { using namespace std; static_assert(!std::is_convertible_v<const std::basic_istream<char,char_traits<char>>&, bool>); } // istream.sentry#6 explicit
namespace p6 { using namespace std; template<class Z> concept c = !requires { spec_probe::dv<spec_probe::dep<Z, std::basic_istream<char,char_traits<char>>&>>().sentry(spec_probe::dv<spec_probe::dep<Z, const std::basic_istream<char,char_traits<char>>::sentry&>>()); }; static_assert(c<void>); } // istream.sentry#7 deleted call
namespace p7 { using namespace std; template<class Z> concept c = !requires { spec_probe::dv<spec_probe::dep<Z, std::basic_istream<char,char_traits<char>>&>>().operator=(spec_probe::dv<spec_probe::dep<Z, const std::basic_istream<char,char_traits<char>>::sentry&>>()); }; static_assert(c<void>); } // istream.sentry#8 deleted call
