// Spec-audit probes for [istream.syn], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <istream>
#include "../probe_support.hpp"
namespace p0 { using namespace std; using std::basic_istream; } // istream.syn#1 presence
namespace p1 { using namespace std; static_assert(spec_probe::same<std::istream, basic_istream<char>>); } // istream.syn#2 type
namespace p2 { using namespace std; static_assert(spec_probe::same<std::wistream, basic_istream<wchar_t>>); } // istream.syn#3 type
namespace p3 { using namespace std; using std::basic_iostream; } // istream.syn#4 presence
namespace p4 { using namespace std; static_assert(spec_probe::same<std::iostream, basic_iostream<char>>); } // istream.syn#5 type
namespace p5 { using namespace std; static_assert(spec_probe::same<std::wiostream, basic_iostream<wchar_t>>); } // istream.syn#6 type
namespace p6 { using namespace std; template<class Z> concept c = requires { { std::ws(spec_probe::dv<spec_probe::dep<Z, basic_istream<char,char_traits<char>>&>>()) } -> spec_probe::same<basic_istream<char,char_traits<char>>&>; }; static_assert(c<void>); } // istream.syn#7 call ret
namespace p7 { using namespace std; template<class Z> concept c = requires { { (spec_probe::dv<spec_probe::dep<Z, istream&&>>() >> spec_probe::dv<spec_probe::dep<Z, int&&>>()) } -> spec_probe::same<istream&&>; }; static_assert(c<void>); } // istream.syn#8 call ret
