// Spec-audit probes for [rand.synopsis], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <random>
#include "../probe_support.hpp"
namespace p0 { using namespace std; using std::uniform_random_bit_generator; } // rand.synopsis#1 presence
namespace p1 { using namespace std; using std::linear_congruential_engine; } // rand.synopsis#2 presence
namespace p2 { using namespace std; using std::mersenne_twister_engine; } // rand.synopsis#3 presence
namespace p3 { using namespace std; using std::subtract_with_carry_engine; } // rand.synopsis#4 presence
namespace p4 { using namespace std; using std::discard_block_engine; } // rand.synopsis#5 presence
namespace p5 { using namespace std; using std::independent_bits_engine; } // rand.synopsis#6 presence
namespace p6 { using namespace std; using std::shuffle_order_engine; } // rand.synopsis#7 presence
namespace p7 { using namespace std; using std::philox_engine; } // rand.synopsis#8 presence
namespace p8 { using namespace std; using T = std::minstd_rand0; } // rand.synopsis#9 type exists (exposition-only or unspecified: see below)
namespace p9 { using namespace std; using T = std::minstd_rand; } // rand.synopsis#10 type exists (exposition-only or unspecified: see below)
namespace p10 { using namespace std; using T = std::mt19937; } // rand.synopsis#11 type exists (exposition-only or unspecified: see below)
namespace p11 { using namespace std; using T = std::mt19937_64; } // rand.synopsis#12 type exists (exposition-only or unspecified: see below)
namespace p12 { using namespace std; using T = std::ranlux24_base; } // rand.synopsis#13 type exists (exposition-only or unspecified: see below)
namespace p13 { using namespace std; using T = std::ranlux48_base; } // rand.synopsis#14 type exists (exposition-only or unspecified: see below)
namespace p14 { using namespace std; using T = std::ranlux24; } // rand.synopsis#15 type exists (exposition-only or unspecified: see below)
namespace p15 { using namespace std; using T = std::ranlux48; } // rand.synopsis#16 type exists (exposition-only or unspecified: see below)
namespace p16 { using namespace std; using T = std::knuth_b; } // rand.synopsis#17 type exists (exposition-only or unspecified: see below)
namespace p17 { using namespace std; using T = std::philox4x32; } // rand.synopsis#18 type exists (exposition-only or unspecified: see below)
namespace p18 { using namespace std; using T = std::philox4x64; } // rand.synopsis#19 type exists (exposition-only or unspecified: see below)
namespace p19 { using namespace std; using T = std::default_random_engine; } // rand.synopsis#20 type exists (exposition-only or unspecified: see below)
namespace p20 { using namespace std; using std::random_device; } // rand.synopsis#21 presence
namespace p21 { using namespace std; using std::seed_seq; } // rand.synopsis#22 presence
namespace p22 { using namespace std; template<class Z> concept c = requires { { std::generate_canonical<double, 4>(spec_probe::dv<spec_probe::dep<Z, mt19937&>>()) } -> spec_probe::same<double>; }; static_assert(c<void>); } // rand.synopsis#23 call ret
namespace p23 { using namespace std; using std::uniform_int_distribution; } // rand.synopsis#24 presence
namespace p24 { using namespace std; using std::uniform_real_distribution; } // rand.synopsis#25 presence
namespace p25 { using namespace std; using std::bernoulli_distribution; } // rand.synopsis#26 presence
namespace p26 { using namespace std; using std::binomial_distribution; } // rand.synopsis#27 presence
namespace p27 { using namespace std; using std::geometric_distribution; } // rand.synopsis#28 presence
namespace p28 { using namespace std; using std::negative_binomial_distribution; } // rand.synopsis#29 presence
namespace p29 { using namespace std; using std::poisson_distribution; } // rand.synopsis#30 presence
namespace p30 { using namespace std; using std::exponential_distribution; } // rand.synopsis#31 presence
namespace p31 { using namespace std; using std::gamma_distribution; } // rand.synopsis#32 presence
namespace p32 { using namespace std; using std::weibull_distribution; } // rand.synopsis#33 presence
namespace p33 { using namespace std; using std::extreme_value_distribution; } // rand.synopsis#34 presence
namespace p34 { using namespace std; using std::normal_distribution; } // rand.synopsis#35 presence
namespace p35 { using namespace std; using std::lognormal_distribution; } // rand.synopsis#36 presence
namespace p36 { using namespace std; using std::chi_squared_distribution; } // rand.synopsis#37 presence
namespace p37 { using namespace std; using std::cauchy_distribution; } // rand.synopsis#38 presence
namespace p38 { using namespace std; using std::fisher_f_distribution; } // rand.synopsis#39 presence
namespace p39 { using namespace std; using std::student_t_distribution; } // rand.synopsis#40 presence
namespace p40 { using namespace std; using std::discrete_distribution; } // rand.synopsis#41 presence
namespace p41 { using namespace std; using std::piecewise_constant_distribution; } // rand.synopsis#42 presence
namespace p42 { using namespace std; using std::piecewise_linear_distribution; } // rand.synopsis#43 presence
