// Spec-audit probes for [stdckdint.h.syn], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <stdckdint.h>
#include "../probe_support.hpp"
#ifndef __STDC_VERSION_STDCKDINT_H__
static_assert(false, "__STDC_VERSION_STDCKDINT_H__"); // stdckdint.h.syn#1 macro
#endif
