// Spec-audit probes for [streambuf.syn], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <streambuf>
#include "../probe_support.hpp"
namespace p0 { using namespace std; using std::basic_streambuf; } // streambuf.syn#1 presence
namespace p1 { using namespace std; static_assert(spec_probe::same<std::streambuf, basic_streambuf<char>>); } // streambuf.syn#2 type
namespace p2 { using namespace std; static_assert(spec_probe::same<std::wstreambuf, basic_streambuf<wchar_t>>); } // streambuf.syn#3 type
