// Spec-audit probes for [thread.barrier.class], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <barrier>
#define SPEC_PROBE_barrier
#include "../probe_support.hpp"
namespace p0 { using namespace std; using std::barrier; } // thread.barrier.class#1 presence
namespace p1 { using namespace std; using T = std::barrier<spec_probe::completion>::arrival_token; } // thread.barrier.class#2 type exists  (exposition-only or unspecified: see below)
namespace p2 { using namespace std; template<class Z> concept c = requires { { std::barrier<spec_probe::completion>::max() } -> spec_probe::same<ptrdiff_t>; requires noexcept(std::barrier<spec_probe::completion>::max()); }; static_assert(c<void>); } // thread.barrier.class#3 call ret noexcept
namespace p3 { using namespace std; static_assert(std::is_constructible_v<std::barrier<spec_probe::completion>, ptrdiff_t, spec_probe::completion>); } // thread.barrier.class#4 ctor
namespace p4 { using namespace std; static_assert(std::is_constructible_v<std::barrier<spec_probe::completion>, ptrdiff_t>); } // thread.barrier.class#5 ctor (defaults) explicit
namespace p5 { using namespace std; static_assert(std::is_nothrow_destructible_v<std::barrier<spec_probe::completion>>); } // thread.barrier.class#6 destructor
namespace p6 { using namespace std; static_assert(!std::is_constructible_v<std::barrier<spec_probe::completion>, const std::barrier<spec_probe::completion>&>); } // thread.barrier.class#7 deleted ctor
namespace p7 { using namespace std; template<class Z> concept c = !requires { spec_probe::dv<spec_probe::dep<Z, std::barrier<spec_probe::completion>&>>().operator=(spec_probe::dv<spec_probe::dep<Z, const std::barrier<spec_probe::completion>&>>()); }; static_assert(c<void>); } // thread.barrier.class#8 deleted call
namespace p8 { using namespace std; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, std::barrier<spec_probe::completion>&>>().arrive(spec_probe::dv<spec_probe::dep<Z, ptrdiff_t>>()) } -> spec_probe::same<std::barrier<spec_probe::completion>::arrival_token>; }; static_assert(c<void>); } // thread.barrier.class#9 call ret
namespace p9 { using namespace std; template<class Z> concept c = requires { spec_probe::dv<spec_probe::dep<Z, std::barrier<spec_probe::completion>&>>().arrive(); }; static_assert(c<void>); } // thread.barrier.class#10 call (defaults)
namespace p10 { using namespace std; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, const std::barrier<spec_probe::completion>&>>().wait(spec_probe::dv<spec_probe::dep<Z, std::barrier<spec_probe::completion>::arrival_token&&>>()) } -> spec_probe::same<void>; }; static_assert(c<void>); } // thread.barrier.class#11 call ret
namespace p11 { using namespace std; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, std::barrier<spec_probe::completion>&>>().arrive_and_wait() } -> spec_probe::same<void>; }; static_assert(c<void>); } // thread.barrier.class#12 call ret
namespace p12 { using namespace std; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, std::barrier<spec_probe::completion>&>>().arrive_and_drop() } -> spec_probe::same<void>; }; static_assert(c<void>); } // thread.barrier.class#13 call ret
