// Spec-audit probes for [thread.syn], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <thread>
#define SPEC_PROBE_thread
#include "../probe_support.hpp"
namespace p0 { using namespace std; using std::thread; } // thread.syn#1 presence
namespace p1 { using namespace std; template<class Z> concept c = requires { { std::swap(spec_probe::dv<spec_probe::dep<Z, thread&>>(), spec_probe::dv<spec_probe::dep<Z, thread&>>()) } -> spec_probe::same<void>; requires noexcept(std::swap(spec_probe::dv<spec_probe::dep<Z, thread&>>(), spec_probe::dv<spec_probe::dep<Z, thread&>>())); }; static_assert(c<void>); } // thread.syn#2 call ret noexcept
namespace p2 { using namespace std; using std::jthread; } // thread.syn#3 presence
namespace p3 { using namespace std; using namespace std::this_thread; template<class Z> concept c = requires { { std::this_thread::get_id() } -> spec_probe::same<thread::id>; requires noexcept(std::this_thread::get_id()); }; static_assert(c<void>); } // thread.syn#4 call ret noexcept
namespace p4 { using namespace std; using namespace std::this_thread; template<class Z> concept c = requires { { std::this_thread::yield() } -> spec_probe::same<void>; requires noexcept(std::this_thread::yield()); }; static_assert(c<void>); } // thread.syn#5 call ret noexcept
namespace p5 { using namespace std; using namespace std::this_thread; template<class Z> concept c = requires { { std::this_thread::sleep_until(spec_probe::dv<spec_probe::dep<Z, const chrono::time_point<chrono::system_clock,chrono::seconds>&>>()) } -> spec_probe::same<void>; }; static_assert(c<void>); } // thread.syn#6 call ret
namespace p6 { using namespace std; using namespace std::this_thread; template<class Z> concept c = requires { { std::this_thread::sleep_for(spec_probe::dv<spec_probe::dep<Z, const chrono::duration<long long,ratio<1>>&>>()) } -> spec_probe::same<void>; }; static_assert(c<void>); } // thread.syn#7 call ret
