// Spec-audit probes for [thread.lock.general], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <mutex>
#define SPEC_PROBE_mutex
#include "../probe_support.hpp"
namespace p0 { using namespace std; using std::defer_lock_t; } // thread.lock.general#1 presence
namespace p1 { using namespace std; using std::try_to_lock_t; } // thread.lock.general#2 presence
namespace p2 { using namespace std; using std::adopt_lock_t; } // thread.lock.general#3 presence
namespace p3 { using namespace std; static_assert(spec_probe::same<decltype(std::defer_lock), const defer_lock_t>); } // thread.lock.general#4 var
namespace p4 { using namespace std; static_assert(spec_probe::same<decltype(std::try_to_lock), const try_to_lock_t>); } // thread.lock.general#5 var
namespace p5 { using namespace std; static_assert(spec_probe::same<decltype(std::adopt_lock), const adopt_lock_t>); } // thread.lock.general#6 var
