// Spec-audit probes for [time.zone.zonedtraits], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <chrono>
#include "../probe_support.hpp"
namespace p0 { using namespace std; using namespace std::chrono; using std::chrono::zoned_traits; } // time.zone.zonedtraits#1 presence
namespace p1 { using namespace std; using namespace std::chrono; template<class Z> concept c = requires { sizeof(spec_probe::dep<Z, std::chrono::zoned_traits<const time_zone*>>); }; static_assert(c<void>); } // time.zone.zonedtraits#2 specialization complete
namespace p2 { using namespace std; using namespace std::chrono; template<class Z> concept c = requires { { std::chrono::zoned_traits<const time_zone*>::default_zone() } -> spec_probe::same<const time_zone*>; }; static_assert(c<void>); } // time.zone.zonedtraits#3 call ret
namespace p3 { using namespace std; using namespace std::chrono; template<class Z> concept c = requires { { std::chrono::zoned_traits<const time_zone*>::locate_zone(spec_probe::dv<spec_probe::dep<Z, string_view>>()) } -> spec_probe::same<const time_zone*>; }; static_assert(c<void>); } // time.zone.zonedtraits#4 call ret
