// Spec-audit probes for [time.cal.wdlast.overview], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <chrono>
#define SPEC_PROBE_chrono
#include "../probe_support.hpp"
namespace p0 { using namespace std; using namespace std::chrono; using std::chrono::weekday_last; } // time.cal.wdlast.overview#1 presence
namespace p1 { using namespace std; using namespace std::chrono; static_assert(std::is_constructible_v<std::chrono::weekday_last, const chrono::weekday&> && std::is_nothrow_constructible_v<std::chrono::weekday_last, const chrono::weekday&> && !std::is_convertible_v<const chrono::weekday&, std::chrono::weekday_last>); } // time.cal.wdlast.overview#2 ctor noexcept explicit
namespace p2 { using namespace std; using namespace std::chrono; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, const std::chrono::weekday_last&>>().weekday() } -> spec_probe::same<chrono::weekday>; requires noexcept(spec_probe::dv<spec_probe::dep<Z, const std::chrono::weekday_last&>>().weekday()); }; static_assert(c<void>); } // time.cal.wdlast.overview#3 call ret noexcept
namespace p3 { using namespace std; using namespace std::chrono; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, const std::chrono::weekday_last&>>().ok() } -> spec_probe::same<bool>; requires noexcept(spec_probe::dv<spec_probe::dep<Z, const std::chrono::weekday_last&>>().ok()); }; static_assert(c<void>); } // time.cal.wdlast.overview#4 call ret noexcept
