// Spec-audit probes for [time.cal.mdlast], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <chrono>
#define SPEC_PROBE_chrono
#include "../probe_support.hpp"
namespace p0 { using namespace std; using namespace std::chrono; using std::chrono::month_day_last; } // time.cal.mdlast#1 presence
namespace p1 { using namespace std; using namespace std::chrono; static_assert(std::is_constructible_v<std::chrono::month_day_last, const chrono::month&> && std::is_nothrow_constructible_v<std::chrono::month_day_last, const chrono::month&> && !std::is_convertible_v<const chrono::month&, std::chrono::month_day_last>); } // time.cal.mdlast#2 ctor noexcept explicit
namespace p2 { using namespace std; using namespace std::chrono; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, const std::chrono::month_day_last&>>().month() } -> spec_probe::same<chrono::month>; requires noexcept(spec_probe::dv<spec_probe::dep<Z, const std::chrono::month_day_last&>>().month()); }; static_assert(c<void>); } // time.cal.mdlast#3 call ret noexcept
namespace p3 { using namespace std; using namespace std::chrono; template<class Z> concept c = requires { { spec_probe::dv<spec_probe::dep<Z, const std::chrono::month_day_last&>>().ok() } -> spec_probe::same<bool>; requires noexcept(spec_probe::dv<spec_probe::dep<Z, const std::chrono::month_day_last&>>().ok()); }; static_assert(c<void>); } // time.cal.mdlast#4 call ret noexcept
