// Spec-audit probes for [time.zone.exception.ambig], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <chrono>
#define SPEC_PROBE_chrono
#include "../probe_support.hpp"
namespace p0 { using namespace std; using namespace std::chrono; using std::chrono::ambiguous_local_time; } // time.zone.exception.ambig#1 presence
namespace p1 { using namespace std; using namespace std::chrono; static_assert(std::is_base_of_v<runtime_error, std::chrono::ambiguous_local_time> && std::is_convertible_v<std::chrono::ambiguous_local_time*, runtime_error*>); } // time.zone.exception.ambig#2 base runtime_error
namespace p2 { using namespace std; using namespace std::chrono; static_assert(std::is_constructible_v<std::chrono::ambiguous_local_time, const std::chrono::local_time<chrono::seconds>&, const std::chrono::local_info&>); } // time.zone.exception.ambig#3 ctor
