// Spec-audit probes for [time.cal.last], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <chrono>
#define SPEC_PROBE_chrono
#include "../probe_support.hpp"
namespace p0 { using namespace std; using namespace std::chrono; using std::chrono::last_spec; } // time.cal.last#1 presence
namespace p1 { using namespace std; using namespace std::chrono; template<class Z> concept c = requires { ::new std::chrono::last_spec(); }; static_assert(c<void>); } // time.cal.last#2 ctor
