// Spec-audit probes for [time.clock.utc.overview], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <chrono>
#include "../probe_support.hpp"
namespace p0 { using namespace std; using namespace std::chrono; using std::chrono::utc_clock; } // time.clock.utc.overview#1 presence
namespace p1 { using namespace std; using namespace std::chrono; using T = std::chrono::utc_clock::rep; } // time.clock.utc.overview#2 type exists  (exposition-only or unspecified: a signed arithmetic type)
namespace p2 { using namespace std; using namespace std::chrono; using T = std::chrono::utc_clock::period; } // time.clock.utc.overview#3 type exists  (exposition-only or unspecified: unspecified)
namespace p3 { using namespace std; using namespace std::chrono; static_assert(spec_probe::same<std::chrono::utc_clock::duration, chrono::duration<std::chrono::utc_clock::rep,std::chrono::utc_clock::period>>); } // time.clock.utc.overview#4 type
namespace p4 { using namespace std; using namespace std::chrono; static_assert(spec_probe::same<std::chrono::utc_clock::time_point, chrono::time_point<std::chrono::utc_clock>>); } // time.clock.utc.overview#5 type
namespace p5 { using namespace std; using namespace std::chrono; static_assert(spec_probe::same<decltype(std::chrono::utc_clock::is_steady), const bool>); } // time.clock.utc.overview#6 var
namespace p6 { using namespace std; using namespace std::chrono; template<class Z> concept c = requires { { std::chrono::utc_clock::now() } -> spec_probe::same<std::chrono::utc_clock::time_point>; }; static_assert(c<void>); } // time.clock.utc.overview#7 call ret
namespace p7 { using namespace std; using namespace std::chrono; template<class Z> concept c = requires { { std::chrono::utc_clock::to_sys(spec_probe::dv<spec_probe::dep<Z, const utc_time<chrono::seconds>&>>()) } -> spec_probe::same<sys_time<common_type_t<chrono::seconds,seconds> >>; }; static_assert(c<void>); } // time.clock.utc.overview#8 call ret
namespace p8 { using namespace std; using namespace std::chrono; template<class Z> concept c = requires { { std::chrono::utc_clock::from_sys(spec_probe::dv<spec_probe::dep<Z, const sys_time<chrono::seconds>&>>()) } -> spec_probe::same<utc_time<common_type_t<chrono::seconds,seconds> >>; }; static_assert(c<void>); } // time.clock.utc.overview#9 call ret
