// Spec-audit probes for [version.syn@iomanip], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <iomanip>
#define SPEC_PROBE_iomanip
#include "../probe_support.hpp"
#if !defined(__cpp_lib_quoted_string_io) || (__cpp_lib_quoted_string_io) != 201304L
static_assert(false, "__cpp_lib_quoted_string_io"); // version.syn@iomanip#1 macro value 201304L
#endif
