// Spec-audit probes for [version.syn@iosfwd], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <iosfwd>
#define SPEC_PROBE_iosfwd
#include "../probe_support.hpp"
#if !defined(__cpp_lib_char8_t) || (__cpp_lib_char8_t) != 201907L
static_assert(false, "__cpp_lib_char8_t"); // version.syn@iosfwd#1 macro value 201907L
#endif
#if !defined(__cpp_lib_spanstream) || (__cpp_lib_spanstream) != 202106L
static_assert(false, "__cpp_lib_spanstream"); // version.syn@iosfwd#2 macro value 202106L
#endif
#if !defined(__cpp_lib_syncbuf) || (__cpp_lib_syncbuf) != 201803L
static_assert(false, "__cpp_lib_syncbuf"); // version.syn@iosfwd#3 macro value 201803L
#endif
