// Spec-audit probes for [version.syn@fstream], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <fstream>
#define SPEC_PROBE_fstream
#include "../probe_support.hpp"
#if !defined(__cpp_lib_fstream_native_handle) || (__cpp_lib_fstream_native_handle) != 202306L
static_assert(false, "__cpp_lib_fstream_native_handle"); // version.syn@fstream#1 macro value 202306L
#endif
