// Spec-audit probes for [version.syn@spanstream], generated by tools/spec_audit/part3/gen.py; do not edit.
// One check per line (see gen.py); the runner maps diagnostics to the check IDs below.
#include <spanstream>
#define SPEC_PROBE_spanstream
#include "../probe_support.hpp"
#if !defined(__cpp_lib_spanstream) || (__cpp_lib_spanstream) != 202106L
static_assert(false, "__cpp_lib_spanstream"); // version.syn@spanstream#1 macro value 202106L
#endif
