#!/usr/bin/env python3
"""Generate libycxx's hosted C-library wrapper headers (<cstdlib>, <cstring>, ...).

Each wrapper includes the C library's header and brings the C names into namespace std with
using-declarations. The data table below is the single source of truth; re-run after editing.
Types that libycxx already defines in std (size_t, ...) are not re-declared.
"""
import pathlib

HEADERS = {
    "cstdlib": ("stdlib.h", "div_t ldiv_t lldiv_t "
                "abort atexit at_quick_exit _Exit exit quick_exit getenv system malloc calloc realloc free "
                "aligned_alloc atof atoi atol atoll strtod strtof strtold strtol strtoll strtoul strtoull "
                "mblen mbtowc wctomb mbstowcs wcstombs bsearch qsort rand srand abs labs llabs div ldiv lldiv",
                """inline long abs(long x) noexcept { return x < 0 ? -x : x; }
inline long long abs(long long x) noexcept { return x < 0 ? -x : x; }
inline ldiv_t div(long a, long b) noexcept { return ::ldiv(a, b); }
inline lldiv_t div(long long a, long long b) noexcept { return ::lldiv(a, b); }
inline float abs(float x) noexcept { return __builtin_fabsf(x); }
inline double abs(double x) noexcept { return __builtin_fabs(x); }
inline long double abs(long double x) noexcept { return __builtin_fabsl(x); }"""),
    "cstring": ("string.h", "memcpy memmove strcpy strncpy strcat strncat memcmp strcmp strcoll strncmp strxfrm "
                "memchr strchr strcspn strpbrk strrchr strspn strstr strtok memset strerror strlen", ""),
    "cstdio": ("stdio.h", "FILE fpos_t remove rename tmpfile tmpnam fclose fflush fopen freopen setbuf setvbuf "
               "fprintf fscanf printf scanf snprintf sprintf sscanf vfprintf vfscanf vprintf vscanf vsnprintf "
               "vsprintf vsscanf fgetc fgets fputc fputs getc getchar putc putchar puts ungetc fread fwrite "
               "fgetpos fseek fsetpos ftell rewind clearerr feof ferror perror", ""),
    "cctype": ("ctype.h", "isalnum isalpha isblank iscntrl isdigit isgraph islower isprint ispunct isspace "
               "isupper isxdigit tolower toupper", ""),
    "cwctype": ("wctype.h", "wint_t wctrans_t wctype_t iswalnum iswalpha iswblank iswcntrl iswdigit iswgraph "
                "iswlower iswprint iswpunct iswspace iswupper iswxdigit iswctype towctrans towlower towupper "
                "wctrans wctype", ""),
    "cwchar": ("wchar.h", "mbstate_t wint_t tm fwprintf fwscanf swprintf swscanf vfwprintf vfwscanf vswprintf "
               "vswscanf vwprintf vwscanf wprintf wscanf fgetwc fgetws fputwc fputws fwide getwc getwchar "
               "putwc putwchar ungetwc wcstod wcstof wcstold wcstol wcstoll wcstoul wcstoull wcscpy wcsncpy "
               "wmemcpy wmemmove wcscat wcsncat wcscmp wcscoll wcsncmp wcsxfrm wmemcmp wcschr wcscspn wcspbrk "
               "wcsrchr wcsspn wcsstr wcstok wmemchr wcslen wmemset wcsftime btowc wctob mbsinit mbrlen "
               "mbrtowc wcrtomb mbsrtowcs wcsrtombs", ""),
    "cerrno": ("errno.h", "", ""),
    "csignal": ("signal.h", "sig_atomic_t signal raise", ""),
    "ctime": ("time.h", "clock_t time_t tm timespec clock difftime mktime time timespec_get asctime ctime "
              "gmtime localtime strftime", ""),
    "clocale": ("locale.h", "lconv setlocale localeconv", ""),
    "cinttypes": ("inttypes.h", "imaxdiv_t imaxabs imaxdiv strtoimax strtoumax wcstoimax wcstoumax", ""),
    "csetjmp": ("setjmp.h", "jmp_buf longjmp", ""),
    "cstdarg": ("stdarg.h", "va_list", ""),
    "cfenv": ("fenv.h", "fenv_t fexcept_t feclearexcept fegetexceptflag feraiseexcept fesetexceptflag "
              "fetestexcept fegetround fesetround fegetenv feholdexcept fesetenv feupdateenv", ""),
    "cuchar": ("uchar.h", "mbstate_t mbrtoc8 c8rtomb mbrtoc16 c16rtomb mbrtoc32 c32rtomb", ""),
}
EXTRA_INCLUDES = {"cinttypes": ["<cstdint>"]}

root = pathlib.Path(__file__).resolve().parent.parent / "include"
for name, (cheader, names, extra) in HEADERS.items():
    lines = [f"// -*- C++ -*-  libycxx: <{name}>   [hosted]  (generated by tools/gen_cheaders.py)",
             "#pragma once", "", "#include <ycxx/config.hpp>", "#include <ycxx/core/version.hpp>",
             "#include <ycxx/core/cstddef.hpp>"]
    lines += [f"#include {h}" for h in EXTRA_INCLUDES.get(name, [])]
    lines += [f"#include <{cheader}>", ""]
    if names or extra:
        lines.append("namespace std {")
        lines += [f"using ::{n};" for n in names.split()]
        if extra:
            lines += ["", extra]
        lines.append("} // namespace std")
    (root / name).write_text("\n".join(lines) + "\n")
print("generated", len(HEADERS), "headers")
