#!/usr/bin/env python3
"""Generate include/ycxx/core/text_encoding_table.hpp: the IANA Character Sets registry for
std::text_encoding ([text.encoding]).

Input: tools/data/iana-character-sets.csv, the registry as IANA publishes it
(https://www.iana.org/assignments/character-sets/character-sets-1.csv; the copy here is the
registry last updated 2026-10-02). Re-run after replacing that file.

Output tables (namespace ycxx::detail):
  te_names  the primary name and the aliases of every known registered encoding, grouped by
            MIBenum in ascending order, the primary name first; no duplicates (strcmp) within
            a group. [text.encoding.general]/4 adds "ASCII" to US-ASCII.
  te_keys   one entry per name: its comp-name canonical form ([text.encoding.members]/19:
            letters and digits only, lower case, zeros dropped unless a numeric prefix
            precedes them) and its MIBenum, sorted by key for binary search. The script
            checks that no two encodings share a key.
"""
import csv, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from uglify import uglify_text  # noqa: E402  (the headers spell reserved names, DECISIONS §2)

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'tools' / 'data' / 'iana-character-sets.csv'
OUT = ROOT / 'include' / 'ycxx' / 'core' / 'text_encoding_table.hpp'

EXCLUDED = {33, 34}  # [text.encoding.general]/2: NATS-DANO, NATS-DANO-ADD
EXTRA = {3: ['ASCII']}  # [text.encoding.general]/4


def canon(s):
    """The comp-name canonical form (the same algorithm as text_encoding.hpp's te_canon)."""
    out, prefix, prev, keep = [], False, '', False
    for c in s:
        if c == '0':
            if prev != '0':
                keep = prefix
            if keep:
                out.append('0')
            prefix = False
        elif '1' <= c <= '9':
            out.append(c)
            prefix = True
        elif c.isascii() and c.isalpha():
            out.append(c.lower())
            prefix = False
        prev = c
    return ''.join(out)


def main():
    groups = {}
    for row in csv.DictReader(SRC.open(newline='', encoding='utf-8')):
        mib = int(row['MIBenum'])
        if mib in EXCLUDED:
            continue
        names = [row['Name'].strip()]
        for a in row['Aliases'].split('\n'):
            a = a.strip()
            # Free-text notes in the aliases column ("(Aliases are provided for ...)").
            if not a or ' ' in a or a.startswith('('):
                continue
            names.append(a)
        names += EXTRA.get(mib, [])
        uniq = []
        for n in names:
            if n not in uniq:
                uniq.append(n)
        for n in uniq:
            assert 0 < len(n) <= 63 and all(c.isascii() and (c.isalnum() or c in '_.:()+-') for c in n), n
        groups[mib] = uniq

    keys = {}
    for mib, names in groups.items():
        for n in names:
            k = canon(n)
            if k in keys and keys[k] != mib:
                sys.exit(f'comp-name collision: {n!r} ({mib}) and MIBenum {keys[k]}')
            keys[k] = mib

    lines = ['// Generated by tools/gen_text_encoding.py from tools/data/iana-character-sets.csv (the IANA',
             '// Character Sets registry, last updated 2026-10-02). Do not edit.',
             '#pragma once', '', '#include <ycxx/core/cstdint.hpp>', '', 'namespace ycxx::detail {', '',
             'struct te_name {', '  std::int_least32_t mib;', '  const char* name;', '};', '',
             f'inline constexpr te_name te_names[{sum(len(v) for v in groups.values())}] = {{']
    for mib in sorted(groups):
        lines.append('    ' + ' '.join(f'{{{mib}, "{n}"}},' for n in groups[mib]))
    lines += ['};', '', 'struct te_key {', '  const char* key;', '  std::int_least32_t mib;', '};', '',
              f'inline constexpr te_key te_keys[{len(keys)}] = {{']
    for k in sorted(keys):
        lines.append(f'    {{"{k}", {keys[k]}}},')
    lines += ['};', '', '} // namespace ycxx::detail', '']
    OUT.write_text(uglify_text('\n'.join(lines)))
    print(f'{OUT.relative_to(ROOT)}: {len(groups)} encodings, {len(keys)} names')


main()
