#!/usr/bin/env python3
"""Generate include/ycxx/core/cmath_builtins.hpp: the compiler builtins behind <cmath>.

For each C function f, ycxx::detail::fpm::bi::f<C>(args) calls __builtin_f{f,,l,f128} for the
"carrier" type C (float, double, long double or binary128): at run time that is the C library
(libm) or an inline instruction. For the transcendental functions, folds_f<C> tells whether the
compiler can evaluate the builtin during constant evaluation (a concept over a template argument
that is constant only if the builtin folds: DECISIONS §1.4, probing without the preprocessor).
"""
import pathlib
import re

T = "C"
UNARY = ("acos asin atan cos sin tan acosh asinh atanh cosh sinh tanh exp exp2 expm1 log log10 log1p log2 "
         "logb cbrt sqrt erf erfc lgamma tgamma ceil floor round trunc fabs nearbyint rint").split()
BINARY = "atan2 hypot pow fmod remainder copysign nextafter fdim fmax fmin".split()
# name: (return type, parameter list, call arguments)
OTHER = {
    "fma": (T, f"{T} x, {T} y, {T} z", "x, y, z"),
    "ilogb": ("int", f"{T} x", "x"),
    "lround": ("long", f"{T} x", "x"),
    "llround": ("long long", f"{T} x", "x"),
    "lrint": ("long", f"{T} x", "x"),
    "llrint": ("long long", f"{T} x", "x"),
    "frexp": (T, f"{T} x, int* e", "x, e"),
    "ldexp": (T, f"{T} x, int e", "x, e"),
    "scalbn": (T, f"{T} x, int e", "x, e"),
    "scalbln": (T, f"{T} x, long e", "x, e"),
    "modf": (T, f"{T} x, {T}* i", "x, i"),
    "remquo": (T, f"{T} x, {T} y, int* q", "x, y, q"),
    "nexttoward": (T, f"{T} x, long double y", "x, y"),
}
# Transcendental functions whose folding is probed, with probe arguments.
PROBES = {f: "C(0.5)" for f in "acos asin atan cos sin tan asinh atanh cosh sinh tanh exp exp2 expm1 log log10 log1p log2 erf erfc".split()}
PROBES.update({"acosh": "C(1.5)", "lgamma": "C(2.5)", "tgamma": "C(2.5)", "pow": "C(0.5), C(0.25)", "atan2": "C(0.5), C(0.25)"})

funcs = {}
for f in UNARY:
    funcs[f] = (T, f"{T} x", "x")
for f in BINARY:
    funcs[f] = (T, f"{T} x, {T} y", "x, y")
funcs.update(OTHER)

out = ["// libycxx core: the compiler builtins behind <cmath>, by carrier type.",
       "// Generated by tools/gen_cmath.py; do not edit.",
       "#pragma once", "", "#include <ycxx/config.hpp>", "",
       "namespace ycxx::detail::fpm::bi {", "",
       "template <bool>", "struct fold_probe {};", ""]
for f, (ret, params, args) in funcs.items():
    out.append(f"template <class C>")
    out.append(f"constexpr {ret} {f}({params}) noexcept {{")
    out.append(f"  if constexpr (__is_same(C, float))")
    out.append(f"    return __builtin_{f}f({args});")
    out.append(f"  else if constexpr (__is_same(C, double))")
    out.append(f"    return __builtin_{f}({args});")
    out.append(f"  else if constexpr (__is_same(C, long double))")
    out.append(f"    return __builtin_{f}l({args});")
    if f != "nexttoward":
        out.append(f"  else")
        out.append(f"    return __builtin_{f}f128({args});")
    out.append("}")
for f, a in PROBES.items():
    out.append(f"template <class C>")
    out.append(f"concept folds_{f} = requires {{ typename fold_probe<(bi::{f}<C>({a}) == bi::{f}<C>({a}))>; }};")
out += ["", "} // namespace ycxx::detail::fpm::bi", ""]
path = pathlib.Path(__file__).resolve().parent.parent / "include" / "ycxx" / "core" / "cmath_builtins.hpp"
path.write_text("\n".join(out))
print("wrote", path)

# ---------------------------------------------------------------------------------------------
# include/ycxx/core/cmath_std.hpp: the std:: overload sets of [cmath.syn] and [sf.cmath].
#
# Every function is a template: the overloads for the floating-point types and the "sufficient
# additional overloads" of [cmath.syn]/3 are one constrained template per function, and the
# f/l-suffixed names are `template <class = void>` functions. A non-template C function of the
# same name (::sin from <math.h>, visible after `using namespace std;`) then wins every tie
# instead of making unqualified calls ambiguous (as in <cwchar>).
# IMPL uses T (the promoted type) and X, Y, Z (the converted arguments).
CM = "ycxx::detail::cm::"
FPM = "ycxx::detail::fpm::"
SF = "ycxx::detail::sf::"


def tr(op, args="X"):
    return f"{CM}transcendental<{CM}op::{op}, T>({args})"


STD = []  # (name, signature, return type, impl, constexpr, has f/l forms)
for f in ("acos asin atan cos sin tan acosh asinh atanh cosh sinh tanh exp exp2 expm1 log log10 log1p log2 "
          "erf erfc lgamma tgamma").split():
    STD.append((f, "x", "T", tr(f), True, True))
STD += [
    ("atan2", "xy", "T", tr("atan2", "X, Y"), True, True),
    ("pow", "xy", "T", tr("pow", "X, Y"), True, True),
    ("frexp", "x_pint", "T", f"{CM}frexp<T>(X, e)", True, True),
    ("ilogb", "x", "int", f"{CM}ilogb<T>(X, FP_ILOGB0, FP_ILOGBNAN)", True, True),
    ("ldexp", "x_int", "T", f"{CM}scalbln<T>(X, e)", True, True),
    ("logb", "x", "T", f"{CM}logb<T>(X)", True, True),
    ("modf", "x_pT", "T", f"{CM}modf<T>(x, iptr)", True, True),
    ("scalbn", "x_int", "T", f"{CM}scalbln<T>(X, e)", True, True),
    ("scalbln", "x_long", "T", f"{CM}scalbln<T>(X, e)", True, True),
    ("cbrt", "x", "T", f"{CM}cbrt<T>(X)", True, True),
    ("fabs", "x", "T", f"{CM}fabs<T>(X)", True, True),
    ("hypot", "xy", "T", f"{CM}hypot<T>(X, Y)", True, True),
    ("hypot", "xyz", "T", f"{CM}hypot3<T>(X, Y, Z)", True, False),
    ("sqrt", "x", "T", f"{CM}sqrt<T>(X)", True, True),
    ("ceil", "x", "T", f"{CM}round_integral<{CM}rint_op::ceil, T>(X)", True, True),
    ("floor", "x", "T", f"{CM}round_integral<{CM}rint_op::floor, T>(X)", True, True),
    ("nearbyint", "x", "T", f"{CM}nearbyint<T>(X)", False, True),
    ("rint", "x", "T", f"{CM}rint<T>(X)", False, True),
    ("lrint", "x", "long", f"{CM}lrint<long, T>(X)", False, True),
    ("llrint", "x", "long long", f"{CM}lrint<long long, T>(X)", False, True),
    ("round", "x", "T", f"{CM}round_integral<{CM}rint_op::round, T>(X)", True, True),
    ("lround", "x", "long", f"{CM}lround<long, T>(X)", True, True),
    ("llround", "x", "long long", f"{CM}lround<long long, T>(X)", True, True),
    ("trunc", "x", "T", f"{CM}round_integral<{CM}rint_op::trunc, T>(X)", True, True),
    ("fmod", "xy", "T", f"{CM}fmod<T>(X, Y)", True, True),
    ("remainder", "xy", "T", f"{CM}remainder<T>(X, Y)", True, True),
    ("remquo", "xy_pint", "T", f"{CM}remquo<T>(X, Y, quo)", True, True),
    ("copysign", "xy", "T", f"{CM}copysign<T>(X, Y)", True, True),
    ("nextafter", "xy", "T", f"{CM}nextafter<T>(X, Y)", True, True),
    ("nexttoward", "x_ld", "T", f"{CM}nexttoward<T>(X, y)", True, True),
    ("nextup", "x", "T", f"{FPM}fp_nextup<T>(X)", True, True),
    ("nextdown", "x", "T", f"{FPM}fp_nextdown<T>(X)", True, True),
    ("fdim", "xy", "T", f"{CM}fdim<T>(X, Y)", True, True),
    ("fmax", "xy", "T", f"{CM}fmax<T>(X, Y)", True, True),
    ("fmin", "xy", "T", f"{CM}fmin<T>(X, Y)", True, True),
    ("fmaximum", "xy", "T", f"{FPM}fp_minmax<T>(X, Y, true, false)", True, False),
    ("fmaximum_num", "xy", "T", f"{FPM}fp_minmax<T>(X, Y, true, true)", True, False),
    ("fminimum", "xy", "T", f"{FPM}fp_minmax<T>(X, Y, false, false)", True, False),
    ("fminimum_num", "xy", "T", f"{FPM}fp_minmax<T>(X, Y, false, true)", True, False),
    ("fma", "xyz", "T", f"{CM}fma<T>(X, Y, Z)", True, True),
    ("lerp", "xyz", "T", f"{FPM}fp_lerp<T>(X, Y, Z)", True, False),
    ("fpclassify", "x", "int", "__builtin_fpclassify(FP_NAN, FP_INFINITE, FP_NORMAL, FP_SUBNORMAL, FP_ZERO, X)", True, False),
    ("isfinite", "x", "bool", "__builtin_isfinite(X)", True, False),
    ("isinf", "x", "bool", "__builtin_isinf(X)", True, False),
    ("isnan", "x", "bool", "__builtin_isnan(X)", True, False),
    ("isnormal", "x", "bool", "__builtin_isnormal(X)", True, False),
    ("signbit", "x", "bool", "__builtin_signbit(X)", True, False),
    ("isgreater", "xy", "bool", "__builtin_isgreater(X, Y)", True, False),
    ("isgreaterequal", "xy", "bool", "__builtin_isgreaterequal(X, Y)", True, False),
    ("isless", "xy", "bool", "__builtin_isless(X, Y)", True, False),
    ("islessequal", "xy", "bool", "__builtin_islessequal(X, Y)", True, False),
    ("islessgreater", "xy", "bool", "__builtin_islessgreater(X, Y)", True, False),
    ("isunordered", "xy", "bool", "__builtin_isunordered(X, Y)", True, False),
]
for f, sig in [("assoc_laguerre", "uu_x"), ("assoc_legendre", "uu_x"), ("beta", "xy"), ("comp_ellint_1", "x"),
               ("comp_ellint_2", "x"), ("comp_ellint_3", "xy"), ("cyl_bessel_i", "xy"), ("cyl_bessel_j", "xy"),
               ("cyl_bessel_k", "xy"), ("cyl_neumann", "xy"), ("ellint_1", "xy"), ("ellint_2", "xy"), ("ellint_3", "xyz"),
               ("expint", "x"), ("hermite", "u_x"), ("laguerre", "u_x"), ("legendre", "u_x"), ("riemann_zeta", "x"),
               ("sph_bessel", "u_x"), ("sph_legendre", "uu_x"), ("sph_neumann", "u_x")]:
    args = {"x": "X", "xy": "X, Y", "xyz": "X, Y, Z", "u_x": "n, X", "uu_x": "n, m, X"}[sig]
    STD.append((f, sig, "T", f"{SF}{f}<T>({args})", False, True))

SIGS = {  # deduced template parameters and parameter list
    "x": (["A"], "A x"),
    "xy": (["A", "B"], "A x, B y"),
    "xyz": (["A", "B", "C"], "A x, B y, C z"),
    "x_pint": (["A"], "A x, int* e"),
    "x_int": (["A"], "A x, int e"),
    "x_long": (["A"], "A x, long e"),
    "xy_pint": (["A", "B"], "A x, B y, int* quo"),
    "x_ld": (["A"], "A x, long double y"),
    "u_x": (["A"], "unsigned n, A x"),
    "uu_x": (["A"], "unsigned n, unsigned m, A x"),
}
FIXED = {  # parameter lists of the f/l-suffixed forms (F: float or long double)
    "x": "F x", "xy": "F x, F y", "xyz": "F x, F y, F z", "x_pint": "F x, int* e", "x_int": "F x, int e",
    "x_long": "F x, long e", "xy_pint": "F x, F y, int* quo", "x_ld": "F x, long double y", "x_pT": "F x, F* iptr",
    "u_x": "unsigned n, F x", "uu_x": "unsigned n, unsigned m, F x",
}


def body(impl):
    return re.sub(r"\b([XYZ])\b", lambda m: f"static_cast<T>({m.group(1).lower()})", impl)


FP_TYPES = ["float", "double", "long double", "ycxx::detail::float16", "ycxx::detail::float32",
            "ycxx::detail::float64", "ycxx::detail::float128", "ycxx::detail::bfloat16"]
ONE_FP = {"x", "x_pint", "x_int", "x_long", "x_ld", "u_x", "uu_x"}  # one floating-point-type parameter

std = ["// libycxx core: the std:: functions of <cmath> ([cmath.syn], [sf.cmath]).",
       "// Generated by tools/gen_cmath.py; do not edit. Included by ycxx/core/cmath.hpp after the macros.",
       "//",
       "// Each function has, as templates (see the generator), one overload per floating-point type",
       "// ([cmath.syn]/2: `template <class T = F> requires fp_is<T, F> R f(type_identity_t<T>)`,",
       "// whose parameter type is fixed, so arguments convert to it as to a plain function; the",
       "// overloads of unavailable extended types are never viable), and one constrained template",
       "// for the integer and mixed arguments of [cmath.syn]/3.",
       "#pragma once", "", "namespace std {", ""]
for name, sig, ret, impl, cexpr, fl in STD:
    spec = "constexpr " if cexpr else ""
    # one overload per floating-point type
    for F in FP_TYPES:
        std.append(f"template <class T = {F}>")
        std.append(f"  requires ycxx::detail::fp_is<T, {F}>")
        params = FIXED[sig].replace("F", "type_identity_t<T>")
        if sig == "x_pT":
            params = "type_identity_t<T> x, type_identity_t<T>* iptr"
        std.append(f"{spec}{'T' if ret == 'T' else ret} {name}({params}) noexcept {{")
        if name == "nexttoward":
            std.append("  static_assert(ycxx::detail::fp_std_index<T> >= 0,")
            std.append("                \"[cmath.syn]/4: nexttoward is ill-formed for an argument of extended floating-point type\");")
        std.append(f"  return {body(impl)};")
        std.append("}")
    # the additional overloads
    if sig != "x_pT":
        tps, params = SIGS[sig]
        promoted = f"ycxx::detail::cmath_promote_t<{', '.join(tps)}>"
        std.append("template <" + ", ".join("class " + t for t in tps) + ">")
        if sig in ONE_FP:
            std.append(f"  requires ycxx::detail::is_integral_v<A>")
        else:
            std.append(f"  requires ycxx::detail::cmath_mixed<{', '.join(tps)}>")
        std.append(f"{spec}{promoted if ret == 'T' else ret} {name}({params}) noexcept {{")
        std.append(f"  using T = {promoted};")
        std.append(f"  return {body(impl)};")
        std.append("}")
    if fl:
        for sfx, F in (("f", "float"), ("l", "long double")):
            std.append("template <class = void>")
            std.append(f"{spec}{F if ret == 'T' else ret} {name}{sfx}({FIXED[sig].replace('F', F)}) noexcept {{")
            std.append(f"  using T = {F};")
            std.append(f"  return {body(impl)};")
            std.append("}")
std += ["", "} // namespace std", ""]
path = pathlib.Path(__file__).resolve().parent.parent / "include" / "ycxx" / "core" / "cmath_std.hpp"
path.write_text("\n".join(std))
print("wrote", path)

# ---------------------------------------------------------------------------------------------
# include/math.h: the C library's header plus, in C++, the names of <cmath> in the global
# namespace ([support.c.headers.other]/1).
# Except for the special functions and lerp (/1).
names = []
for name, sig, ret, impl, cexpr, fl in STD:
    if impl.startswith(SF) or name == "lerp":
        continue
    for n in [name] + ([name + "f", name + "l"] if fl else []):
        if n not in names:
            names.append(n)
names += ["abs", "labs", "llabs", "nan", "nanf", "nanl"]
mh = ["// -*- C++ -*-  libycxx: <math.h> ([support.c.headers.other])   [hosted; also usable from C]",
      "// Generated by tools/gen_cmath.py; do not edit.",
      "//",
      "// The C library's <math.h>; in C++ also the names of <cmath> in the global namespace, except",
      "// for the special functions and lerp ([support.c.headers.other]/1). <cmath> itself includes",
      "// the C library's header directly (#include_next), so the two can be included in either order.",
      "#pragma once", "", "#include_next <math.h>", "", "#ifdef __cplusplus", "#  include <cmath>", ""]
mh += [f"using std::{n};" for n in names]
mh += ["#endif", ""]
path = pathlib.Path(__file__).resolve().parent.parent / "include" / "math.h"
path.write_text("\n".join(mh))
print("wrote", path)
