#!/usr/bin/env python3
"""Generate include/ycxx/core/cmath_tables.hpp: the constants of libycxx's constexpr soft math.

Needs mpmath (pip install mpmath). Re-run after changing the parameters below.
- the bits of 2/pi, for the Payne-Hanek reduction of trigonometric arguments (enough for
  binary128 and x87 arguments up to the largest finite value, plus 400 bits);
- the Stirling-series coefficients B(2k) / (2k (2k - 1)) for lgamma/tgamma;
- ln(2 pi) / 2;
- the Taylor coefficients of 1 / Gamma(1 + z) (Temme's method for the Bessel functions).
Each constant is stored as in math_constants.hpp: 0.m (192 bits, truncated) * 2^(exp + 1).
"""
import pathlib
import sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from uglify import uglify_text  # noqa: E402  (the headers spell reserved names, DECISIONS §2)
from mpmath import mp, mpf, bernoulli, log, pi, floor, taylor, gamma

mp.prec = 20000
TWO_OVER_PI_WORDS = 264
STIRLING_TERMS = 32
INV_GAMMA_TERMS = 41


def bits192(c):
    c = mpf(c)
    neg = c < 0
    c = abs(c)
    e = int(floor(mp.log(c, 2)))
    m = int(floor(c * mpf(2) ** (191 - e)))
    if m >> 192:  # log2 rounding at a power of two
        e += 1
        m = int(floor(c * mpf(2) ** (191 - e)))
    assert m >> 191 == 1
    w = [(m >> 128) & (2**64 - 1), (m >> 64) & (2**64 - 1), m & (2**64 - 1)]
    return neg, e, w


def fmt(neg, e, w):
    return "{%s, %d, {0x%016xull, 0x%016xull, 0x%016xull}}" % ("true" if neg else "false", e, *w)


two_over_pi = 2 / pi
bits = int(floor(two_over_pi * mpf(2) ** (64 * TWO_OVER_PI_WORDS)))
words = [(bits >> (64 * (TWO_OVER_PI_WORDS - 1 - i))) & (2**64 - 1) for i in range(TWO_OVER_PI_WORDS)]

out = ["// libycxx core: tables of the constexpr soft math (cmath_mp.hpp).",
       "// Generated by tools/gen_cmath_tables.py (mpmath, 20000-bit arithmetic); do not edit.",
       "#pragma once", "", "namespace ycxx::detail::fpm {", "",
       "// value = (neg ? -1 : 1) * 0.m[0]m[1]m[2] (binary) * 2^(exp + 1)",
       "struct mp_const_bits {", "  bool neg;", "  int exp;", "  unsigned long long m[3];", "};", "",
       f"// The first {64 * TWO_OVER_PI_WORDS} bits of 2/pi after the binary point, most significant first.",
       f"inline constexpr unsigned long long two_over_pi_bits[{TWO_OVER_PI_WORDS}] = {{"]
for i in range(0, TWO_OVER_PI_WORDS, 4):
    out.append("    " + " ".join("0x%016xull," % w for w in words[i:i + 4]))
out += ["};", "", "// B(2k) / (2k (2k - 1)), k = 1, 2, ...: lgamma(x) ~ (x - 1/2) ln x - x + ln(2 pi)/2 + sum c_k x^(1 - 2k).",
        f"inline constexpr mp_const_bits stirling_coefficients[{STIRLING_TERMS}] = {{"]
for k in range(1, STIRLING_TERMS + 1):
    out.append("    " + fmt(*bits192(bernoulli(2 * k) / (2 * k * (2 * k - 1)))) + ",")
out += ["};", "", "inline constexpr mp_const_bits half_ln_2pi = " + fmt(*bits192(log(2 * pi) / 2)) + ";", "",
        f"// 1 / Gamma(1 + z) = sum a_k z^k, k = 0 .. {INV_GAMMA_TERMS - 1}.",
        f"inline constexpr mp_const_bits inv_gamma_taylor[{INV_GAMMA_TERMS}] = {{"]
mp.prec = 600
for c in taylor(lambda z: 1 / gamma(1 + z), 0, INV_GAMMA_TERMS - 1):
    out.append("    " + fmt(*bits192(c)) + ",")
out += ["};", "",
        "} // namespace ycxx::detail::fpm", ""]
path = pathlib.Path(__file__).resolve().parent.parent / "include" / "ycxx" / "core" / "cmath_tables.hpp"
path.write_text(uglify_text("\n".join(out)))
print("wrote", path)
