#!/usr/bin/env python3
"""Generate the shared mode's platform-layer forwarders (DECISIONS §20.6).

Every function of include/ycxx/pal.h is hidden in every image. In shared mode the platform layer
lives in libycxx.so, and an image's inline library code (and its per-image part,
libycxx_nonshared.a) still calls the functions by their pal.h names. So:

  src/pal/export.c        built into libycxx.so: each function exported as __ycxx_abi_pal_<name>,
                          calling the hidden ycxx_pal_<name>
  src/nonshared/pal.c     built into libycxx_nonshared.a: each ycxx_pal_<name>, hidden, calling
                          __ycxx_abi_pal_<name>; and ycxx_pal_single_threaded (data, defined as
                          src/pal/posix/pal.c defines it)

The 'files' layer is left out: the shared library needs YCXX_PAL=posix, which has none (its
files are C stdio's). A forwarder is one tail call. libycxx.so's own references bind to its own definitions, so the
archive's members are linked only into the other images.

    tools/gen_pal_forwarders.py           write both files
    tools/gen_pal_forwarders.py --check   fail (exit 1) if either differs from what pal.h gives
                                          (tools/check-all, policy stage)
"""
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAL_H = os.path.join(REPO, 'include', 'ycxx', 'pal.h')
EXPORT_C = os.path.join(REPO, 'src', 'pal', 'export.c')
NONSHARED_C = os.path.join(REPO, 'src', 'nonshared', 'pal.c')

DECL = re.compile(r'\[\[__gnu__::__visibility__\("hidden"\)\]\]\s*(YCXX_PAL_NORETURN\s+)?'
                  r'([^;{}()]*?)\b(ycxx_pal_\w+)\s*\(([^;{}]*?)\)\s*(YCXX_PAL_NOEXCEPT)?\s*;', re.S)


def strip_comments(text):
    text = re.sub(r'/\*.*?\*/', ' ', text, flags=re.S)
    return re.sub(r'//[^\n]*', ' ', text)


def split_params(params):
    out, depth, cur = [], 0, ''
    for c in params:
        if c == ',' and depth == 0:
            out.append(cur.strip())
            cur = ''
            continue
        depth += c == '('
        depth -= c == ')'
        cur += c
    if cur.strip():
        out.append(cur.strip())
    return out


def rename(param, i):
    """The parameter with its name replaced by __a<i>, and that name."""
    name = f'__a{i}'
    m = re.match(r'^(.*\(\s*\*\s*)(\w+)(\s*\).*)$', param)  # a function pointer: T (*name)(...)
    if m:
        return m.group(1) + name + m.group(3), name
    m = re.match(r'^(.*?[\s*])(\w+)$', param)
    if not m:
        raise SystemExit(f'gen_pal_forwarders: cannot read parameter {param!r}')
    return m.group(1).rstrip() + ('' if m.group(1).endswith('*') else ' ') + name, name


def functions():
    text = strip_comments(open(PAL_H).read())
    found = []
    for m in DECL.finditer(text):
        noreturn, ret, name, params, _ = m.groups()
        ret = ' '.join(ret.split())
        if ret.startswith('extern') or name.startswith('ycxx_pal_file_'):
            continue  # data (single_threaded, below); the 'files' layer, which YCXX_PAL=posix lacks
        plist = [] if params.strip() in ('', 'void') else split_params(' '.join(params.split()))
        renamed = [rename(p, i) for i, p in enumerate(plist)]
        found.append((bool(noreturn), ret, name, renamed))
    if len(found) < 30:
        raise SystemExit(f'gen_pal_forwarders: only {len(found)} functions found in {PAL_H}')
    return found


HEAD = """/* GENERATED by tools/gen_pal_forwarders.py from include/ycxx/pal.h; do not edit.
{what} */
"""


def generate():
    fns = functions()
    exp = [HEAD.format(what=(
        "   libycxx.so (shared mode, DECISIONS §20.6): the platform layer exported under the\n"
        "   names __ycxx_abi_pal_<name>, which libycxx_nonshared.a's ycxx_pal_<name> call. Each\n"
        "   calls this image's hidden ycxx_pal_<name>.")),
           '#include <ycxx/pal.h>\n']
    non = [HEAD.format(what=(
        "   libycxx_nonshared.a (shared mode, DECISIONS §20.6): each image's platform layer, hidden,\n"
        "   forwarding to libycxx.so's (src/pal/export.c).")),
           '#include <ycxx/pal.h>\n',
           '#if __has_include(<sys/single_threaded.h>)\n#  include <sys/single_threaded.h>\n#endif\n']
    for noreturn, ret, name, params in fns:
        plist = ', '.join(p for p, _ in params) or 'void'
        args = ', '.join(a for _, a in params)
        nr = '[[noreturn]] ' if noreturn else ''
        exported = f'__ycxx_abi_{name[len("ycxx_"):]}'
        call = f'{"" if ret == "void" else "return "}'
        exp.append(f'{nr}[[__gnu__::__visibility__("default")]] {ret} {exported}({plist});\n'
                   f'{ret} {exported}({plist}) {{ {call}{name}({args}); }}\n')
        non.append(f'{nr}{ret} {exported}({plist});\n'
                   f'{ret} {name}({plist}) {{ {call}{exported}({args}); }}\n')
    non.append("""
/* As src/pal/posix/pal.c defines it: the C library's flag, else a flag that is never set (a thread
   could be running). */
#if __has_include(<sys/single_threaded.h>)
const char* const ycxx_pal_single_threaded = &__libc_single_threaded;
#else
static const char ycxx_pal_never_single_threaded = 0;
const char* const ycxx_pal_single_threaded = &ycxx_pal_never_single_threaded;
#endif
""")
    return {EXPORT_C: '\n'.join(exp), NONSHARED_C: '\n'.join(non)}


def main(argv):
    out = generate()
    if '--check' in argv:
        bad = [p for p, t in out.items() if not os.path.exists(p) or open(p).read() != t]
        for p in bad:
            print(f'{os.path.relpath(p, REPO)}: out of date with include/ycxx/pal.h (run tools/gen_pal_forwarders.py)')
        return 1 if bad else 0
    for p, t in out.items():
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, 'w') as f:
            f.write(t)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
