#!/usr/bin/env python3
"""The transitive includes of libycxx's public headers (DECISIONS §19).

By default each public C++ header <H> ends with a block that includes the other standard headers
programs commonly rely on getting with <H>; -DYCXX_NO_TRANSITIVE_INCLUDES leaves the blocks out:

    // Transitive includes (DECISIONS §19), generated by tools/gen_transitive_includes.py from
    // tools/data/transitive-includes.txt; -DYCXX_NO_TRANSITIVE_INCLUDES leaves them out.
    #if _YCXX_TRANSITIVE_INCLUDES
    #  include <algorithm>
    #  if _YCXX_HOSTED
    #    include <cstdio>
    #  endif
    #endif

The headers of the hosted layer (tools/headers.py HOSTED) go in the nested `#if _YCXX_HOSTED`, so a
freestanding build (and a hosted-layers build without the C library) reaches only core headers
(DECISIONS §3; tools/check_includes.py walks the core part). The list lives in one place,
tools/data/transitive-includes.txt:

    <H>: <G> <G> ...                  baseline: libstdc++ and libc++ both provide each G's primary
                                      probe item after #include <H> (tools/probe_transitive.py)
    <H>: <G> | <item> <why>           added: <item> (a probe item of <G>) is relied on (a real-world
                                      project, an external suite's test), and libstdc++ or libc++
                                      provides it after #include <H>
    <H>: -<G> | <why>                 a baseline pair deliberately not provided
    *: -<G> ... | <why>               the same for every H (the heavy headers)

    tools/gen_transitive_includes.py            rewrite the blocks from the data file
    tools/gen_transitive_includes.py --check    fail if a block differs from the data file, if the
                                                data file disagrees with the probe results (a
                                                baseline pair neither listed nor excluded, a listed
                                                pair without a reason the probe confirms), or if a
                                                transitive include closes an include cycle
                                                (policy stage of tools/test)
    tools/gen_transitive_includes.py --propose  print the baseline pairs the data file lacks
"""
import argparse, pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
INCLUDE = REPO / "include"
DATA = HERE / "data" / "transitive-includes.txt"
PROBE = HERE / "data" / "transitive-probe"
LIBS = ("libstdc++", "libc++")
sys.path.insert(0, str(HERE))
from headers import CORE, HOSTED, ABI, FREESTANDING_SUBSET  # noqa: E402

PUBLIC = set(CORE + HOSTED + ABI + FREESTANDING_SUBSET)
# The headers that get a block: the C++ headers. Not <cassert> (re-includable, no config.hpp) and
# not the C headers' .h forms (the C library's headers, wrapped).
TARGETS = sorted(h for h in PUBLIC if not h.endswith(".h") and h != "cassert")

MARK = "// Transitive includes (DECISIONS §19)"
BLOCK_RE = re.compile(r"\n*" + re.escape(MARK) + r".*\Z", re.S)
INC = re.compile(r'^\s*#\s*include\s*<([^>]+)>', re.M)


def block(gs):
    core = [g for g in gs if g not in HOSTED]
    hosted = [g for g in gs if g in HOSTED]
    out = [MARK + ", generated by tools/gen_transitive_includes.py from",
           "// tools/data/transitive-includes.txt; -DYCXX_NO_TRANSITIVE_INCLUDES leaves them out.",
           "#if _YCXX_TRANSITIVE_INCLUDES"]
    out += [f"#  include <{g}>" for g in core]
    if hosted:
        out += ["#  if _YCXX_HOSTED"] + [f"#    include <{g}>" for g in hosted] + ["#  endif"]
    return "\n".join(out + ["#endif"]) + "\n"


def read_data(errors):
    """{H: {G: reason or None}}, {H: {G: reason}} (exclusions; H '*' for all)."""
    inc, exc = {}, {}
    for n, raw in enumerate(DATA.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].rstrip() if not raw.lstrip().startswith("#") else ""
        if not line.strip():
            continue
        m = re.match(r"^(\*|[\w.]+):\s*([^|]*?)\s*(?:\|\s*(.+))?$", line)
        if not m:
            errors.append(f"{DATA.name}:{n}: cannot parse: {raw}")
            continue
        h, gs, why = m.group(1), m.group(2).split(), m.group(3)
        if h != "*" and h not in TARGETS:
            errors.append(f"{DATA.name}:{n}: <{h}> is not a public C++ header that takes a block")
            continue
        for g in gs:
            neg = g.startswith("-")
            g = g.lstrip("-")
            if g not in PUBLIC or g.endswith(".h") or g == h:
                errors.append(f"{DATA.name}:{n}: <{g}> cannot be a transitive include of <{h}>")
                continue
            if neg:
                if not why:
                    errors.append(f"{DATA.name}:{n}: exclusion of <{g}> needs a reason")
                exc.setdefault(h, {})[g] = why
            else:
                if h == "*":
                    errors.append(f"{DATA.name}:{n}: '*' takes exclusions only")
                    continue
                if g in inc.get(h, {}):
                    errors.append(f"{DATA.name}:{n}: <{h}>: <{g}> listed twice")
                inc.setdefault(h, {})[g] = why
    return inc, exc


def read_probe():
    """{lib: {H: set(items) or None (n/a)}}, {lib: set(n/a items)}, [(item, G)] in order."""
    items = []
    for line in (PROBE / "items.txt").read_text().splitlines():
        if line.strip() and not line.startswith("#"):
            ident = line.split("|", 1)[0].strip()
            items.append((ident, ident.split(":", 1)[0]))
    res, na = {}, {}
    for lib in LIBS:
        p = PROBE / f"{lib}.txt"
        if not p.exists():
            raise SystemExit(f"{p} missing: run tools/probe_transitive.py")
        res[lib], na[lib] = {}, set()
        for line in p.read_text().splitlines():
            if line.startswith("# n/a items:"):
                na[lib] = set(line[len("# n/a items:"):].split())
            elif line and not line.startswith("#"):
                h, rest = line.split(":", 1)
                rest = rest.split()
                res[lib][h] = None if rest == ["n/a"] else set(rest)
    return res, na, items


def primary(items):
    out = {}
    for ident, g in items:
        out.setdefault(g, ident)
    return out


def baseline(res, items):
    """{H: set(G)}: both libraries provide G's primary item after <H>."""
    prim = primary(items)
    out = {}
    for h in TARGETS:
        got = None
        for lib in LIBS:
            s = res[lib].get(h)
            if s is None:  # the library lacks <h> (or was not probed for it)
                got = set()
                break
            gs = {g for g, i in prim.items() if i in s and g in PUBLIC}
            got = gs if got is None else got & gs
        out[h] = got or set()
    return out


def direct_public_includes(h):
    return {m for m in INC.findall(BLOCK_RE.sub("", (INCLUDE / h).read_text())) if m in PUBLIC}


def graph_edges():
    """{file: [included files]} over include/, the blocks included."""
    g = {}
    for p in INCLUDE.rglob("*"):
        if p.is_file():
            rel = p.relative_to(INCLUDE).as_posix()
            g[rel] = [m for m in INC.findall(p.read_text()) if (INCLUDE / m).is_file()]
    return g


def cycles_through_blocks(inc):
    """Cycles of the include graph that use a transitive include (H -> G of the data file)."""
    g = graph_edges()
    out = []
    for h, gs in inc.items():
        for t in gs:
            # A path from t back to h closes a cycle through the edge h -> t.
            seen, stack = set(), [(t, [h, t])]
            while stack:
                u, path = stack.pop()
                if u == h:
                    out.append(" -> ".join(f"<{x}>" for x in path))
                    break
                if u in seen:
                    continue
                seen.add(u)
                for v in g.get(u, []):
                    stack.append((v, path + [v]))
    return out


TESTS = REPO / "tests" / "ycxx" / "transitive_includes"


def snippets():
    out = {}
    for line in (PROBE / "items.txt").read_text().splitlines():
        if line.strip() and not line.startswith("#"):
            ident, s = line.split("|", 1)
            out[ident.strip()] = s.strip().replace("\\n", "\n")
    return out


def feature_tests(inc, items):
    """{path: text}: per header with a block, a test that every listed G's primary item (and the
    item a reason names) compiles after including only that header, in the default mode."""
    prim, snip, out = primary(items), snippets(), {}
    for h in TARGETS:
        gs = inc.get(h, {})
        if not gs:
            continue
        body, n = [], 0
        for g in sorted(gs):
            want = [prim[g]]
            why = gs[g]
            if why and why.split()[0] not in want:
                want.append(why.split()[0])
            for i in want:
                n += 1
                body.append(f"namespace probe_{n} {{ // {i}\n{snip[i]}\n}}")
        name = h.replace(".", "_")
        out[TESTS / f"{name}.compile.pass.cpp"] = (
            "// GENERATED by tools/gen_transitive_includes.py from tools/data/transitive-includes.txt; do not edit.\n"
            f"// DECISIONS §19: by default <{h}> provides what tools/data/transitive-includes.txt lists for it\n"
            "// (each header's primary probe item, and the item a reason names; the snippets are\n"
            "// tools/data/transitive-probe/items.txt's). The strict mode is undone for this test.\n"
            + "#undef YCXX_NO_TRANSITIVE_INCLUDES\n"
            f"#include <{h}>\n\n" + "\n".join(body) + "\n\nint main() {}\n")
    return out


def expected_text(h, gs):
    text = (INCLUDE / h).read_text()
    if not gs and not BLOCK_RE.search(text):
        return text
    body = BLOCK_RE.sub("", text).rstrip("\n") + "\n"
    if gs:
        body += "\n" + block(gs)
    return body


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--propose", action="store_true")
    a = ap.parse_args()
    errors = []
    inc, exc = read_data(errors)
    res, na, items = read_probe()
    base = baseline(res, items)
    item_g = dict(items)
    order = {g: i for i, g in enumerate(TARGETS)}
    lists = {h: sorted(inc.get(h, {}), key=lambda g: order.get(g, 0)) for h in TARGETS}

    # The data file against the probe.
    for h in TARGETS:
        direct = direct_public_includes(h)
        for g, why in inc.get(h, {}).items():
            if g in direct:
                errors.append(f"<{h}>: <{g}> is already included by the header itself")
            if why is None:
                if g not in base[h]:
                    errors.append(f"<{h}>: <{g}> is not in the probe's baseline (both libraries); "
                                  f"give the item relied on and why ('{h}: {g} | <item> <why>')")
                continue
            item = why.split()[0]
            if item_g.get(item) not in (g, "posix/" + g):
                errors.append(f"<{h}>: <{g}>: the reason must start with a probe item of <{g}> "
                              f"(tools/data/transitive-probe/items.txt), not '{item}'")
            elif not any(item in (res[lib].get(h) or ()) for lib in LIBS):
                errors.append(f"<{h}>: <{g}>: neither libstdc++ nor libc++ provides {item} after <{h}>")
        for g in sorted(base[h]):
            if g in inc.get(h, {}) or g in direct:
                continue
            if g in exc.get(h, {}) or g in exc.get("*", {}):
                continue
            errors.append(f"<{h}>: <{g}> is in the probe's baseline but neither listed nor excluded")
        for g in exc.get(h, {}):
            if g not in base[h]:
                errors.append(f"<{h}>: the exclusion of <{g}> excludes nothing (not in the baseline)")
    for c in cycles_through_blocks({h: lists[h] for h in TARGETS}):
        errors.append(f"include cycle through a transitive include: {c}")

    if a.propose:
        for h in TARGETS:
            miss = sorted(g for g in base[h] if g not in inc.get(h, {}) and g not in direct_public_includes(h)
                          and g not in exc.get(h, {}) and g not in exc.get("*", {}))
            if miss:
                print(f"{h}: {' '.join(miss)}")
        return 0

    stale = []
    tests = feature_tests(inc, items)
    if TESTS.exists():
        for f in TESTS.glob("*.compile.pass.cpp"):
            if f not in tests and f.read_text().startswith("// GENERATED by tools/gen_transitive_includes.py"):
                stale.append(f.relative_to(REPO).as_posix())
                if not a.check:
                    f.unlink()
    for f, text in tests.items():
        if not f.exists() or f.read_text() != text:
            stale.append(f.relative_to(REPO).as_posix())
            if not a.check:
                f.parent.mkdir(parents=True, exist_ok=True)
                f.write_text(text)
    for h in TARGETS:
        want = expected_text(h, lists[h])
        if (INCLUDE / h).read_text() != want:
            stale.append(f"include/{h}")
            if not a.check:
                (INCLUDE / h).write_text(want)
    if a.check:
        errors += [f"{f}: out of date (tools/gen_transitive_includes.py)" for f in stale]
    for e in errors:
        print(e, file=sys.stderr)
    n = sum(len(v) for v in lists.values())
    print(f"transitive includes: {n} in {sum(1 for v in lists.values() if v)} headers"
          + (f", {len(stale)} blocks {'out of date' if a.check else 'rewritten'}" if stale else "")
          + (f", {len(errors)} errors" if errors else ""))
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
