# CMake toolchain file selecting the compilers libycxx needs: GCC 16.2 or Clang 23.1.
# Linux and macOS.
#
#   cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=<libycxx>/cmake/ycxx-toolchain.cmake \
#         [-DYCXX_COMPILER=gcc|clang] [-DYCXX_PROVISION=ON]
#
# It finds the compiler the way tools/toolchain/provision does and shares its cache: the
# toolchains.env file and installations under YCXX_TOOLCHAINS (default
# ~/.local/share/ycxx/toolchains, or $YCXX_TOOLCHAINS / $XDG_DATA_HOME):
#   1. the compiler recorded in toolchains.env, or installed under the cache directory;
#   2. one already installed (g++-16 / clang++-23, unsuffixed g++ / clang++ with the right
#      version, Homebrew's gcc and llvm kegs);
#   3. only with YCXX_PROVISION=ON: download and install it into the cache directory (Clang
#      from the LLVM release tarball; GCC built from source, which takes a while).
# Otherwise a missing or unsupported compiler stops the configuration.
# YCXX_GCC_VERSION / YCXX_LLVM_VERSION select other versions.
include_guard(GLOBAL)

set(YCXX_COMPILER "gcc" CACHE STRING "Compiler family for libycxx: gcc or clang")
set_property(CACHE YCXX_COMPILER PROPERTY STRINGS gcc clang)
option(YCXX_PROVISION "Download and install a missing compiler into the toolchain cache" OFF)
set(YCXX_GCC_VERSION "16.2.0" CACHE STRING "GCC version to use or install")
set(YCXX_LLVM_VERSION "23.1.2" CACHE STRING "LLVM/Clang version to use or install")
if(DEFINED ENV{YCXX_TOOLCHAINS})
  set(_ycxx_default_cache "$ENV{YCXX_TOOLCHAINS}")
elseif(DEFINED ENV{XDG_DATA_HOME})
  set(_ycxx_default_cache "$ENV{XDG_DATA_HOME}/ycxx/toolchains")
else()
  set(_ycxx_default_cache "$ENV{HOME}/.local/share/ycxx/toolchains")
endif()
set(YCXX_TOOLCHAINS "${_ycxx_default_cache}" CACHE PATH "Toolchain cache shared with tools/toolchain/provision")
# try_compile projects run this file again; give them the same settings.
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
     YCXX_COMPILER YCXX_PROVISION YCXX_GCC_VERSION YCXX_LLVM_VERSION YCXX_TOOLCHAINS)

string(REGEX MATCH "^[0-9]+" _ycxx_gcc_major "${YCXX_GCC_VERSION}")
string(REGEX MATCH "^[0-9]+\\.([0-9]+)" _ycxx_m "${YCXX_GCC_VERSION}")
set(_ycxx_gcc_minor "${CMAKE_MATCH_1}")
string(REGEX MATCH "^[0-9]+" _ycxx_llvm_major "${YCXX_LLVM_VERSION}")
set(_ycxx_conf "${YCXX_TOOLCHAINS}/toolchains.env")
set(_ycxx_host "${CMAKE_HOST_SYSTEM_NAME}")
cmake_host_system_information(RESULT _ycxx_arch QUERY OS_PLATFORM)

# ---- toolchains.env ----
function(_ycxx_read_conf)
  if(EXISTS "${_ycxx_conf}")
    file(STRINGS "${_ycxx_conf}" lines REGEX "^YCXX_[A-Z_]+=")
    foreach(line IN LISTS lines)
      string(FIND "${line}" "=" eq)
      string(SUBSTRING "${line}" 0 ${eq} key)
      math(EXPR start "${eq} + 1")
      string(SUBSTRING "${line}" ${start} -1 value)
      set(_ycxx_conf_${key} "${value}" PARENT_SCOPE)
    endforeach()
  endif()
endfunction()

# Rewrites toolchains.env with `entries` (KEY=value items) replacing that toolchain's keys
# (those starting with one of `owned`), keeping the other toolchain's.
function(_ycxx_write_conf owned entries)
  set(kept "")
  if(EXISTS "${_ycxx_conf}")
    file(STRINGS "${_ycxx_conf}" lines REGEX "^YCXX_[A-Z_]+=")
    foreach(line IN LISTS lines)
      set(mine FALSE)
      foreach(o IN LISTS owned)
        string(FIND "${line}" "${o}" at)
        if(at EQUAL 0)
          set(mine TRUE)
        endif()
      endforeach()
      if(NOT mine AND NOT line MATCHES "^YCXX_SDKROOT=")
        list(APPEND kept "${line}")
      endif()
    endforeach()
  endif()
  set(text "# Written by tools/toolchain/provision or cmake/ycxx-toolchain.cmake; read by both and\n# by tools/toolchain/activate.{sh,fish}.\n")
  if(_ycxx_sdk)
    string(APPEND text "YCXX_SDKROOT=${_ycxx_sdk}\n")
  endif()
  foreach(line IN LISTS kept entries)
    string(APPEND text "${line}\n")
  endforeach()
  file(MAKE_DIRECTORY "${YCXX_TOOLCHAINS}")
  file(WRITE "${_ycxx_conf}.tmp" "${text}")
  file(RENAME "${_ycxx_conf}.tmp" "${_ycxx_conf}")
endfunction()

# ---- probing ----
function(_ycxx_version compiler out)
  execute_process(COMMAND "${compiler}" -dumpfullversion OUTPUT_VARIABLE v ERROR_QUIET
                  OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE rc)
  if(NOT rc EQUAL 0 OR v STREQUAL "")
    execute_process(COMMAND "${compiler}" -dumpversion OUTPUT_VARIABLE v ERROR_QUIET
                    OUTPUT_STRIP_TRAILING_WHITESPACE)
  endif()
  set(${out} "${v}" PARENT_SCOPE)
endfunction()

function(_ycxx_gcc_ok gxx out)
  set(ok FALSE)
  if(gxx AND EXISTS "${gxx}")
    _ycxx_version("${gxx}" v)
    if(v MATCHES "^([0-9]+)\\.([0-9]+)" AND CMAKE_MATCH_1 EQUAL _ycxx_gcc_major
       AND NOT CMAKE_MATCH_2 LESS _ycxx_gcc_minor)
      set(ok TRUE)
    endif()
    list(APPEND _ycxx_rejected "${gxx} (${v})")
    set(_ycxx_rejected "${_ycxx_rejected}" PARENT_SCOPE)
  endif()
  set(${out} ${ok} PARENT_SCOPE)
endfunction()

function(_ycxx_clang_ok clangxx out)
  set(ok FALSE)
  if(clangxx AND EXISTS "${clangxx}")
    _ycxx_version("${clangxx}" v)
    if(v MATCHES "^([0-9]+)\\." AND CMAKE_MATCH_1 EQUAL _ycxx_llvm_major)
      set(ok TRUE)
    endif()
    list(APPEND _ycxx_rejected "${clangxx} (${v})")
    set(_ycxx_rejected "${_ycxx_rejected}" PARENT_SCOPE)
  endif()
  set(${out} ${ok} PARENT_SCOPE)
endfunction()

function(_ycxx_brew_prefix formula out)
  set(${out} "" PARENT_SCOPE)
  find_program(_ycxx_brew brew)
  if(_ycxx_brew)
    execute_process(COMMAND "${_ycxx_brew}" --prefix "${formula}" OUTPUT_VARIABLE p ERROR_QUIET
                    OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE rc)
    if(rc EQUAL 0 AND EXISTS "${p}")
      set(${out} "${p}" PARENT_SCOPE)
    endif()
  endif()
endfunction()

# Search PATH for `name` without caching the result.
function(_ycxx_which name out)
  unset(_ycxx_found CACHE)
  find_program(_ycxx_found "${name}" NO_CACHE)
  set(${out} "${_ycxx_found}" PARENT_SCOPE)
endfunction()

function(_ycxx_find_gcc out_gxx)
  set(candidates "${_ycxx_conf_YCXX_GXX}" "${YCXX_TOOLCHAINS}/gcc-${YCXX_GCC_VERSION}/bin/g++")
  foreach(name g++-${_ycxx_gcc_major} g++)
    _ycxx_which(${name} p)
    list(APPEND candidates "${p}")
  endforeach()
  _ycxx_brew_prefix(gcc bp)
  if(bp)
    list(APPEND candidates "${bp}/bin/g++-${_ycxx_gcc_major}")
  endif()
  foreach(c IN LISTS candidates)
    _ycxx_gcc_ok("${c}" ok)
    if(ok)
      set(${out_gxx} "${c}" PARENT_SCOPE)
      set(_ycxx_rejected "" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${out_gxx} "" PARENT_SCOPE)
  set(_ycxx_rejected "${_ycxx_rejected}" PARENT_SCOPE)
endfunction()

function(_ycxx_find_clang out_clangxx)
  set(candidates "${_ycxx_conf_YCXX_CLANGXX}" "${YCXX_TOOLCHAINS}/llvm-${YCXX_LLVM_VERSION}/bin/clang++")
  foreach(name clang++-${_ycxx_llvm_major} clang++)
    _ycxx_which(${name} p)
    list(APPEND candidates "${p}")
  endforeach()
  foreach(keg llvm@${_ycxx_llvm_major} llvm)
    _ycxx_brew_prefix(${keg} bp)
    if(bp)
      list(APPEND candidates "${bp}/bin/clang++")
    endif()
  endforeach()
  foreach(c IN LISTS candidates)
    _ycxx_clang_ok("${c}" ok)
    if(ok)
      set(${out_clangxx} "${c}" PARENT_SCOPE)
      set(_ycxx_rejected "" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${out_clangxx} "" PARENT_SCOPE)
  set(_ycxx_rejected "${_ycxx_rejected}" PARENT_SCOPE)
endfunction()

# ---- provisioning (only with YCXX_PROVISION) ----
function(_ycxx_download url dest)
  message(STATUS "libycxx toolchain: downloading ${url}")
  file(DOWNLOAD "${url}" "${dest}" SHOW_PROGRESS STATUS st)
  list(GET st 0 rc)
  if(NOT rc EQUAL 0)
    file(REMOVE "${dest}")
    list(GET st 1 msg)
    message(FATAL_ERROR "libycxx toolchain: download of ${url} failed: ${msg}")
  endif()
endfunction()

function(_ycxx_install_clang)
  if(_ycxx_host STREQUAL "Linux" AND _ycxx_arch MATCHES "x86_64|AMD64")
    set(asset "LLVM-${YCXX_LLVM_VERSION}-Linux-X64")
  elseif(_ycxx_host STREQUAL "Linux" AND _ycxx_arch MATCHES "aarch64|arm64")
    set(asset "LLVM-${YCXX_LLVM_VERSION}-Linux-ARM64")
  elseif(_ycxx_host STREQUAL "Darwin" AND _ycxx_arch MATCHES "arm64")
    set(asset "LLVM-${YCXX_LLVM_VERSION}-macOS-ARM64")
  elseif(_ycxx_host STREQUAL "Darwin")
    set(asset "LLVM-${YCXX_LLVM_VERSION}-macOS-X64")
  else()
    message(FATAL_ERROR "libycxx toolchain: no LLVM release binary for ${_ycxx_host}-${_ycxx_arch}")
  endif()
  set(dest "${YCXX_TOOLCHAINS}/llvm-${YCXX_LLVM_VERSION}")
  _ycxx_download("https://github.com/llvm/llvm-project/releases/download/llvmorg-${YCXX_LLVM_VERSION}/${asset}.tar.xz"
                 "${YCXX_TOOLCHAINS}/${asset}.tar.xz")
  file(REMOVE_RECURSE "${dest}" "${YCXX_TOOLCHAINS}/${asset}")
  message(STATUS "libycxx toolchain: extracting ${asset}")
  file(ARCHIVE_EXTRACT INPUT "${YCXX_TOOLCHAINS}/${asset}.tar.xz" DESTINATION "${YCXX_TOOLCHAINS}")
  file(RENAME "${YCXX_TOOLCHAINS}/${asset}" "${dest}")
  file(REMOVE "${YCXX_TOOLCHAINS}/${asset}.tar.xz")
endfunction()

function(_ycxx_run what)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE rc OUTPUT_FILE "${_ycxx_log}" ERROR_FILE "${_ycxx_log}.err")
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "libycxx toolchain: ${what} failed; see ${_ycxx_log} and ${_ycxx_log}.err")
  endif()
endfunction()

function(_ycxx_install_gcc)
  set(src "${YCXX_TOOLCHAINS}/src/gcc-${YCXX_GCC_VERSION}")
  set(build "${YCXX_TOOLCHAINS}/src/gcc-build")
  set(dest "${YCXX_TOOLCHAINS}/gcc-${YCXX_GCC_VERSION}")
  if(NOT EXISTS "${src}")
    _ycxx_download("https://ftp.gnu.org/gnu/gcc/gcc-${YCXX_GCC_VERSION}/gcc-${YCXX_GCC_VERSION}.tar.xz"
                   "${YCXX_TOOLCHAINS}/src/gcc.tar.xz")
    file(ARCHIVE_EXTRACT INPUT "${YCXX_TOOLCHAINS}/src/gcc.tar.xz" DESTINATION "${YCXX_TOOLCHAINS}/src")
    file(REMOVE "${YCXX_TOOLCHAINS}/src/gcc.tar.xz")
  endif()
  file(REMOVE_RECURSE "${build}")
  file(MAKE_DIRECTORY "${build}")
  set(_ycxx_log "${build}/build.log")
  cmake_host_system_information(RESULT jobs QUERY NUMBER_OF_LOGICAL_CORES)
  set(extra "")
  if(_ycxx_sdk)
    set(extra "--with-sysroot=${_ycxx_sdk}" "--with-native-system-header-dir=/usr/include")
  endif()
  message(STATUS "libycxx toolchain: building GCC ${YCXX_GCC_VERSION} with ${jobs} jobs (this takes a while)")
  _ycxx_run("fetching GCC prerequisites" sh -c "cd '${src}' && ./contrib/download_prerequisites")
  _ycxx_run("configuring GCC" sh -c "cd '${build}' && '${src}/configure' --prefix='${dest}' --enable-languages=c,c++ --disable-multilib --disable-bootstrap --disable-nls ${extra}")
  _ycxx_run("building GCC" make -C "${build}" -j${jobs})
  _ycxx_run("installing GCC" make -C "${build}" install)
  file(REMOVE_RECURSE "${build}")
endfunction()

# ---- choose the compiler ----
set(_ycxx_sdk "")
if(_ycxx_host STREQUAL "Darwin")
  execute_process(COMMAND xcrun --show-sdk-path OUTPUT_VARIABLE _ycxx_sdk ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
endif()
_ycxx_read_conf()
set(_ycxx_rejected "")

if(YCXX_COMPILER STREQUAL "gcc")
  _ycxx_find_gcc(_ycxx_gxx)
  if(NOT _ycxx_gxx AND YCXX_PROVISION)
    _ycxx_install_gcc()
    _ycxx_find_gcc(_ycxx_gxx)
  endif()
  if(NOT _ycxx_gxx)
    list(JOIN _ycxx_rejected ", " _ycxx_seen)
    message(FATAL_ERROR "libycxx needs GCC ${_ycxx_gcc_major}.${_ycxx_gcc_minor} or later in the ${_ycxx_gcc_major} series; "
            "none found (checked: ${_ycxx_seen}). Configure with -DYCXX_PROVISION=ON to build it into "
            "${YCXX_TOOLCHAINS}, or run tools/toolchain/provision.")
  endif()
  get_filename_component(_ycxx_bin "${_ycxx_gxx}" DIRECTORY)
  get_filename_component(_ycxx_gxx_name "${_ycxx_gxx}" NAME)
  string(REPLACE "g++" "gcc" _ycxx_gcc_name "${_ycxx_gxx_name}")
  execute_process(COMMAND "${_ycxx_gxx}" -print-libgcc-file-name OUTPUT_VARIABLE _ycxx_libgcc OUTPUT_STRIP_TRAILING_WHITESPACE)
  get_filename_component(_ycxx_gcc_dir "${_ycxx_libgcc}" DIRECTORY)
  _ycxx_write_conf("YCXX_GCC;YCXX_GXX" "YCXX_GCC_BIN=${_ycxx_bin};YCXX_GCC=${_ycxx_bin}/${_ycxx_gcc_name};YCXX_GXX=${_ycxx_gxx};YCXX_GCC_INSTALL_DIR=${_ycxx_gcc_dir}")
  set(CMAKE_C_COMPILER "${_ycxx_bin}/${_ycxx_gcc_name}")
  set(CMAKE_CXX_COMPILER "${_ycxx_gxx}")
elseif(YCXX_COMPILER STREQUAL "clang")
  _ycxx_find_clang(_ycxx_clangxx)
  if(NOT _ycxx_clangxx AND YCXX_PROVISION)
    _ycxx_install_clang()
    _ycxx_find_clang(_ycxx_clangxx)
  endif()
  if(NOT _ycxx_clangxx)
    list(JOIN _ycxx_rejected ", " _ycxx_seen)
    message(FATAL_ERROR "libycxx needs Clang ${_ycxx_llvm_major}; none found (checked: ${_ycxx_seen}). "
            "Configure with -DYCXX_PROVISION=ON to download it into ${YCXX_TOOLCHAINS}, or run "
            "tools/toolchain/provision.")
  endif()
  get_filename_component(_ycxx_bin "${_ycxx_clangxx}" DIRECTORY)
  get_filename_component(_ycxx_name "${_ycxx_clangxx}" NAME)
  string(REPLACE "clang++" "" _ycxx_suffix "${_ycxx_name}")
  set(_ycxx_entries "YCXX_CLANG_BIN=${_ycxx_bin};YCXX_CLANG=${_ycxx_bin}/clang${_ycxx_suffix};YCXX_CLANGXX=${_ycxx_clangxx}")
  if(EXISTS "${_ycxx_bin}/ld.lld${_ycxx_suffix}")
    list(APPEND _ycxx_entries "YCXX_LLD=${_ycxx_bin}/ld.lld${_ycxx_suffix}")
  endif()
  if(EXISTS "${_ycxx_bin}/llvm-ar${_ycxx_suffix}")
    list(APPEND _ycxx_entries "YCXX_LLVM_AR=${_ycxx_bin}/llvm-ar${_ycxx_suffix}")
  endif()
  _ycxx_write_conf("YCXX_CLANG;YCXX_LLD;YCXX_LLVM" "${_ycxx_entries}")
  set(CMAKE_C_COMPILER "${_ycxx_bin}/clang${_ycxx_suffix}")
  set(CMAKE_CXX_COMPILER "${_ycxx_clangxx}")
  # Linux: Clang takes the C runtime startup files and libgcc from a GCC installation; prefer
  # the recorded GCC 16 when there is one.
  if(_ycxx_host STREQUAL "Linux" AND _ycxx_conf_YCXX_GCC_INSTALL_DIR AND EXISTS "${_ycxx_conf_YCXX_GCC_INSTALL_DIR}")
    string(APPEND CMAKE_C_FLAGS_INIT " --gcc-install-dir=${_ycxx_conf_YCXX_GCC_INSTALL_DIR}")
    string(APPEND CMAKE_CXX_FLAGS_INIT " --gcc-install-dir=${_ycxx_conf_YCXX_GCC_INSTALL_DIR}")
  endif()
else()
  message(FATAL_ERROR "YCXX_COMPILER must be gcc or clang, not '${YCXX_COMPILER}'")
endif()
if(_ycxx_sdk AND NOT CMAKE_OSX_SYSROOT)
  set(CMAKE_OSX_SYSROOT "${_ycxx_sdk}")
endif()
