# libycxx: the hosted layers (DECISIONS §18).
#
# The hosted library is split into layers of support, each a set of C primitives of ycxx/pal.h
# that an integrator's provider defines. YCXX_PAL=posix (the default) provides every layer from
# src/pal/posix; YCXX_PAL=none provides none, and YCXX_HOSTED_LAYERS names the layers the
# integrator's providers supply:
#
#   set(YCXX_PAL none)
#   set(YCXX_HOSTED_LAYERS memory console clock)   # 'abort' is implied
#   add_subdirectory(libycxx)
#   ycxx_add_hosted_layer(memory  PROVIDER my_heap)   # a target defining the layer's primitives
#   ycxx_add_hosted_layer(console SOURCES uart.c)     # or sources, made into a static library
#   target_link_libraries(app PRIVATE ycxx::ycxx)     # brings the providers
#
# YCXX_PAL_<LAYER>_PROVIDER=<target> (cache variables, e.g. -DYCXX_PAL_MEMORY_PROVIDER=my_heap)
# attach providers the same way. The layer set is fixed when libycxx is configured (it chooses
# sources and writes <ycxx/generated/hosted_layers.hpp>); providers can be attached afterwards.

# Every layer, in the order of ycxx/pal.h. 'clib' is the toolchain's C library (no provider);
# 'filesystem' and 'tzdb' exist with YCXX_PAL=posix only (they call POSIX directly, §8).
set(YCXX_ALL_HOSTED_LAYERS abort memory console clock threads random files environment debug clib filesystem tzdb)
# The layers a YCXX_PAL=none build can select.
set(_ycxx_selectable_layers abort memory console clock threads random files environment debug clib)

# ycxx_hosted_layers_select(<out_layers_var>): validates YCXX_PAL and YCXX_HOSTED_LAYERS and sets
# the selected layers ('abort' added) in the caller's scope.
function(ycxx_hosted_layers_select out_var)
  if(YCXX_PAL STREQUAL "posix")
    if(NOT "${YCXX_HOSTED_LAYERS}" STREQUAL "" AND NOT "${YCXX_HOSTED_LAYERS}" STREQUAL "all")
      message(FATAL_ERROR "libycxx: YCXX_HOSTED_LAYERS (${YCXX_HOSTED_LAYERS}) applies to YCXX_PAL=none; "
                          "YCXX_PAL=posix provides every hosted layer (DECISIONS §18)")
    endif()
    set(${out_var} ${YCXX_ALL_HOSTED_LAYERS} PARENT_SCOPE)
    return()
  endif()
  if(NOT YCXX_PAL STREQUAL "none")
    message(FATAL_ERROR "libycxx: YCXX_PAL must be 'posix' or 'none' (got '${YCXX_PAL}')")
  endif()
  set(layers abort)
  foreach(l IN LISTS YCXX_HOSTED_LAYERS)
    string(STRIP "${l}" l)
    string(TOLOWER "${l}" l)
    if(l STREQUAL "")
      continue()
    endif()
    if(l STREQUAL "filesystem" OR l STREQUAL "tzdb")
      message(FATAL_ERROR "libycxx: the '${l}' hosted layer has no primitives yet: <filesystem> and the time zone "
                          "database call POSIX directly and are built with YCXX_PAL=posix only (DECISIONS §18)")
    endif()
    if(NOT l IN_LIST _ycxx_selectable_layers)
      list(JOIN _ycxx_selectable_layers ", " known)
      message(FATAL_ERROR "libycxx: unknown hosted layer '${l}' in YCXX_HOSTED_LAYERS (known: ${known})")
    endif()
    list(APPEND layers ${l})
  endforeach()
  list(REMOVE_DUPLICATES layers)
  foreach(l IN ITEMS threads debug files)
    if(l IN_LIST layers AND NOT "clib" IN_LIST layers)
      if(l STREQUAL "files")
        set(why "the file streams are iostreams, which need the C library")
      elseif(l STREQUAL "threads")
        set(why "src/hosted/thread.cpp gives each thread its creator's floating-point environment through <cfenv>")
      else()
        set(why "<stacktrace>'s runtime uses the C library")
      endif()
      message(FATAL_ERROR "libycxx: the '${l}' hosted layer needs 'clib' in YCXX_HOSTED_LAYERS: ${why} (DECISIONS §18)")
    endif()
  endforeach()
  if(YCXX_FREESTANDING_RUNTIME)
    message(FATAL_ERROR "libycxx: YCXX_FREESTANDING_RUNTIME builds the runtime of freestanding programs next to a "
                        "YCXX_PAL=posix build; a YCXX_PAL=none build is itself the runtime of its programs")
  endif()
  set(${out_var} ${layers} PARENT_SCOPE)
endfunction()

# ycxx_hosted_layers_header(<file> <layers...>): writes <ycxx/generated/hosted_layers.hpp>, the
# YCXX_LAYER_* switches config.hpp turns into ycxx::detail::cfg::layer (§1 rule 8).
function(ycxx_hosted_layers_header file)
  set(text "// Generated by libycxx's CMake configuration (cmake/ycxx-hosted-layers.cmake): YCXX_PAL=none,\n")
  string(APPEND text "// the hosted layers whose primitives the integrator provides (DECISIONS §18). Read by\n")
  string(APPEND text "// ycxx/config.hpp.\n#pragma once\n\n")
  foreach(l IN LISTS YCXX_ALL_HOSTED_LAYERS)
    string(TOUPPER "${l}" u)
    if(l IN_LIST ARGN)
      string(APPEND text "#define YCXX_LAYER_${u} 1\n")
    else()
      string(APPEND text "#define YCXX_LAYER_${u} 0\n")
    endif()
  endforeach()
  file(CONFIGURE OUTPUT "${file}" CONTENT "${text}")
endfunction()

# ycxx_add_hosted_layer(<layer> [PROVIDER <target>...] [SOURCES <file>...]): attaches a provider of
# one of the selected hosted layers to ycxx::ycxx, so every program linking ycxx::ycxx links it.
# PROVIDER names targets (or libraries) that define the layer's primitives; SOURCES makes a static
# library of the given files (ycxx_layer_<layer>, with ycxx/pal.h on its include path). A provider
# may serve several layers: attach it to each. A provider written in C++ that uses libycxx itself
# links ycxx::ycxx (CMake then orders the archives).
function(ycxx_add_hosted_layer layer)
  cmake_parse_arguments(PARSE_ARGV 1 arg "" "" "PROVIDER;SOURCES")
  if(arg_UNPARSED_ARGUMENTS OR (NOT arg_PROVIDER AND NOT arg_SOURCES))
    message(FATAL_ERROR "ycxx_add_hosted_layer(${layer} ...): usage: ycxx_add_hosted_layer(<layer> PROVIDER <target>... | SOURCES <file>...)")
  endif()
  get_property(selected GLOBAL PROPERTY YCXX_HOSTED_LAYERS_SELECTED)
  get_property(pal GLOBAL PROPERTY YCXX_PAL_SELECTED)
  if(pal STREQUAL "posix")
    message(FATAL_ERROR "ycxx_add_hosted_layer(${layer} ...): libycxx was configured with YCXX_PAL=posix, which "
                        "provides every layer; configure it with -DYCXX_PAL=none to supply your own (DECISIONS §18)")
  endif()
  if(layer STREQUAL "clib")
    message(FATAL_ERROR "ycxx_add_hosted_layer(clib ...): the 'clib' layer is the toolchain's C library, not a provider")
  endif()
  if(NOT layer IN_LIST selected)
    list(JOIN selected " " now)
    message(FATAL_ERROR "ycxx_add_hosted_layer(${layer} ...): the '${layer}' hosted layer is not selected. "
                        "Add it to YCXX_HOSTED_LAYERS (now: ${now}) when configuring libycxx (DECISIONS §18)")
  endif()
  set(providers ${arg_PROVIDER})
  if(arg_SOURCES)
    set(name ycxx_layer_${layer})
    if(TARGET ${name})
      target_sources(${name} PRIVATE ${arg_SOURCES})
    else()
      add_library(${name} STATIC ${arg_SOURCES})
      get_property(inc GLOBAL PROPERTY YCXX_PAL_INCLUDE_DIR)
      target_include_directories(${name} PRIVATE ${inc})
      list(APPEND providers ${name})
    endif()
  endif()
  if(TARGET ycxx_ycxx)
    target_link_libraries(ycxx_ycxx INTERFACE ${providers})
  else()
    set_property(TARGET ycxx::ycxx APPEND PROPERTY INTERFACE_LINK_LIBRARIES ${providers})
  endif()
  set_property(GLOBAL APPEND PROPERTY YCXX_HOSTED_LAYER_PROVIDERS_${layer} ${providers})
endfunction()

# At the end of the configuration: each selected layer and its provider.
function(_ycxx_report_hosted_layers)
  get_property(selected GLOBAL PROPERTY YCXX_HOSTED_LAYERS_SELECTED)
  foreach(l IN LISTS selected)
    if(l STREQUAL "clib")
      message(STATUS "libycxx: hosted layer clib: the toolchain's C library")
      continue()
    endif()
    get_property(p GLOBAL PROPERTY YCXX_HOSTED_LAYER_PROVIDERS_${l})
    if(p)
      list(REMOVE_DUPLICATES p)
      message(STATUS "libycxx: hosted layer ${l}: provided by ${p}")
    else()
      message(STATUS "libycxx: hosted layer ${l}: no provider attached (ycxx_add_hosted_layer); the program must "
                     "define its primitives itself (ycxx/pal.h)")
    endif()
  endforeach()
  foreach(l IN LISTS YCXX_ALL_HOSTED_LAYERS)
    if(NOT l IN_LIST selected)
      list(APPEND absent ${l})
    endif()
  endforeach()
  if(absent)
    list(JOIN absent " " absent)
    message(STATUS "libycxx: hosted layers absent: ${absent} (DECISIONS §18: what each one's absence means)")
  endif()
endfunction()
