# libycxx: the files that let a project that knows nothing about libycxx build against it
# (docs/BUILDING_PROJECTS.md), generated for the build tree and for the installation:
#
#   bin/ycxx-c++          the C++ compiler: the compiler libycxx was built with, its headers in
#                         place of the toolchain's (-nostdinc++, C++26: an older -std= is raised),
#                         its archives and runtime in place of libstdc++/libc++ (cmake/ycxx-c++.in)
#   bin/ycxx-cc           the matching C compiler (Clang on Linux: GCC 16's installation)
#   bin/ycxx-clang-scan-deps  Clang builds: the compiler's clang-scan-deps, where CMake looks for it
#   bin/ycxx-check-binary is a binary built against libycxx alone? (tools/ycxx-check-binary)
#   toolchain.cmake       a CMake toolchain file naming both compilers
#   libycxx.pc            pkg-config: the compile and link flags, for the plain compiler
#   meson-native.ini      a Meson native file naming both compilers
#
# Build tree: <build>/bin/ycxx-c++, <build>/bin/ycxx-cc, <build>/toolchain.cmake,
# <build>/pkgconfig/libycxx.pc, <build>/meson-native.ini (absolute paths).
# Installation: <prefix>/bin/{ycxx-c++,ycxx-cc,ycxx-check-binary},
# <prefix>/lib/cmake/libycxx/toolchain.cmake, <prefix>/lib/pkgconfig/libycxx.pc,
# <prefix>/share/libycxx/meson-native.ini (each finds the prefix relative to itself, so the
# installation can be moved; the compilers' own paths are absolute).
#
# Only for the default platform layer (YCXX_PAL=posix): with YCXX_PAL=none the program's
# providers of the hosted layers are part of the link (ycxx_add_hosted_layer).

function(ycxx_consumer_files link_options)
  set(stage ${CMAKE_CURRENT_BINARY_DIR}/consumer)
  file(MAKE_DIRECTORY ${stage} ${CMAKE_CURRENT_BINARY_DIR}/bin ${CMAKE_CURRENT_BINARY_DIR}/pkgconfig)
  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(family gcc)
  else()
    set(family clang)
  endif()

  # What the compilers need besides libycxx's flags.
  set(gcc_install_dir "")
  set(libgcc "")
  set(cflags_extra "")
  set(libs_extra "")
  if(NOT APPLE)
    if(family STREQUAL "clang" AND YCXX_GCC_INSTALL_DIR)
      set(gcc_install_dir "${YCXX_GCC_INSTALL_DIR}")
      set(cflags_extra " --gcc-install-dir=${gcc_install_dir}")
      set(libs_extra " --gcc-install-dir=${gcc_install_dir}")
    endif()
    # GCC 16's libgcc_s at run time (one unwinder per process), as tools/ycxx-cxx links it.
    set(probe "${CMAKE_CXX_COMPILER}")
    if(gcc_install_dir)
      list(APPEND probe "--gcc-install-dir=${gcc_install_dir}")
    endif()
    execute_process(COMMAND ${probe} -print-file-name=libgcc_s.so.1 OUTPUT_VARIABLE gcc_s
                    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    set(libgcc "-shared-libgcc")
    if(IS_ABSOLUTE "${gcc_s}")
      get_filename_component(gcc_s_dir "${gcc_s}" DIRECTORY)
      get_filename_component(gcc_s_dir "${gcc_s_dir}" REALPATH)
      string(APPEND libgcc " -Wl,-rpath,${gcc_s_dir}")
    endif()
  elseif(family STREQUAL "gcc")
    set(libgcc "-static-libgcc")
  endif()
  if(family STREQUAL "gcc")
    set(cflags_extra "${cflags_extra} -Wno-attributes")
  endif()

  # The link options of ycxx::ycxx that are not archives: the allocation table's, and an
  # instrumented build's sanitizers.
  string(REPLACE "LINKER:" "-Wl," opts "${link_options}")
  list(JOIN opts " " opts)
  if(YCXX_SANITIZE)
    string(APPEND opts " -fsanitize=${YCXX_SANITIZE}")
    if(YCXX_SANITIZE MATCHES "thread" AND family STREQUAL "clang")
      string(APPEND opts " -fno-sanitize-link-c++-runtime")
    endif()
  endif()

  # The wrapper's settings, in sh.
  set(YCXX_W_CXX "${CMAKE_CXX_COMPILER}")
  set(YCXX_W_FAMILY "${family}")
  set(YCXX_W_GCC_INSTALL_DIR "${gcc_install_dir}")
  set(YCXX_W_LIBGCC "${libgcc}")
  set(YCXX_W_LINK_OPTIONS "${opts}")
  set(c_extra "")
  if(gcc_install_dir)
    set(c_extra " '--gcc-install-dir=${gcc_install_dir}'")
  endif()
  set(c_wrapper [=[#!/bin/sh
# ycxx-cc: the C compiler that goes with ycxx-c++ (generated by cmake/ycxx-consumer.cmake): C needs
# nothing of libycxx; on Linux, Clang uses GCC 16's installation for its startup files and libgcc.
# $YCXX_CC: run this compiler instead.
exec ${YCXX_CC:-'@CMAKE_C_COMPILER@'}@c_extra@ "$@"
]=])

  # Build tree: absolute paths.
  set(YCXX_W_LOCATE "include='${YCXX_INCLUDE}' generated='${YCXX_GENERATED_INCLUDE}' libdir='${CMAKE_CURRENT_BINARY_DIR}'")
  set(YCXX_W_INCLUDES [=[-isystem "$include" -isystem "$generated"]=])
  configure_file(${CMAKE_CURRENT_SOURCE_DIR}/cmake/ycxx-c++.in ${CMAKE_CURRENT_BINARY_DIR}/bin/ycxx-c++ @ONLY
                 FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
  file(CONFIGURE OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/bin/ycxx-cc CONTENT "${c_wrapper}" @ONLY)
  file(CHMOD ${CMAKE_CURRENT_BINARY_DIR}/bin/ycxx-cc
       PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)

  # Installation: paths relative to the file's own directory.
  file(RELATIVE_PATH bin_to_prefix "/p/${CMAKE_INSTALL_BINDIR}" "/p")
  file(RELATIVE_PATH cmake_to_prefix "/p/${CMAKE_INSTALL_LIBDIR}/cmake/libycxx" "/p")
  file(RELATIVE_PATH pc_to_prefix "/p/${CMAKE_INSTALL_LIBDIR}/pkgconfig" "/p")
  file(RELATIVE_PATH share_to_prefix "/p/${CMAKE_INSTALL_DATADIR}/libycxx" "/p")
  foreach(v bin_to_prefix cmake_to_prefix pc_to_prefix share_to_prefix)
    string(REGEX REPLACE "/$" "" ${v} "${${v}}")
  endforeach()
  set(YCXX_W_LOCATE "prefix=$(cd \"$here/${bin_to_prefix}\" && pwd)
include=$prefix/${YCXX_INSTALL_INCLUDEDIR} libdir=$prefix/${CMAKE_INSTALL_LIBDIR}")
  set(YCXX_W_INCLUDES [=[-isystem "$include"]=])
  configure_file(${CMAKE_CURRENT_SOURCE_DIR}/cmake/ycxx-c++.in ${stage}/ycxx-c++ @ONLY)
  file(CONFIGURE OUTPUT ${stage}/ycxx-cc CONTENT "${c_wrapper}" @ONLY)

  # The toolchain files.
  set(toolchain_head [=[# libycxx's CMake toolchain file for projects that know nothing about libycxx
# (docs/BUILDING_PROJECTS.md; generated by cmake/ycxx-consumer.cmake):
#   cmake -S <project> -B <build> -DCMAKE_TOOLCHAIN_FILE=<this file>
# The C++ compiler is libycxx's ycxx-c++, which adds libycxx's headers, C++26 (raising an older
# -std=), archives and runtime to every compilation and link of the project: its targets, its
# try_compile checks and the FetchContent projects it builds. ExternalProject builds need it passed
# on (-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}).
]=])
  # Clang: CMake scans C++20 sources for module dependencies with clang-scan-deps, which it looks
  # for next to the compiler; ycxx-c++ has none next to it, so name the compiler's own. (It sees
  # the command line as written, without the wrapper's flags: enough to find module imports.)
  set(scan "")
  if(family STREQUAL "clang")
    get_filename_component(cxx_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
    get_filename_component(cxx_real "${CMAKE_CXX_COMPILER}" REALPATH)
    get_filename_component(cxx_real_dir "${cxx_real}" DIRECTORY)
    string(REGEX MATCH "^[0-9]+" clang_major "${CMAKE_CXX_COMPILER_VERSION}")
    find_program(scan_deps NAMES clang-scan-deps-${clang_major} clang-scan-deps
                 HINTS "${cxx_dir}" "${cxx_real_dir}" NO_CACHE)
    if(scan_deps)
      # bin/ycxx-clang-scan-deps too: CMake looks for <prefix>clang-scan-deps next to the compiler,
      # the prefix taken from its name (ycxx-), when no toolchain file names it (CC/CXX).
      set(scan_wrapper "#!/bin/sh\n# ycxx-clang-scan-deps: the clang-scan-deps of libycxx's Clang, next to ycxx-c++ for CMake's\n# module scanning (generated by cmake/ycxx-consumer.cmake).\nexec '${scan_deps}' \"$@\"\n")
      foreach(out ${CMAKE_CURRENT_BINARY_DIR}/bin/ycxx-clang-scan-deps ${stage}/ycxx-clang-scan-deps)
        file(WRITE ${out} "${scan_wrapper}")
        file(CHMOD ${out} PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
      endforeach()
      if(YCXX_INSTALL)
        install(PROGRAMS ${stage}/ycxx-clang-scan-deps DESTINATION ${CMAKE_INSTALL_BINDIR})
      endif()
      set(scan "set(CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS \"${scan_deps}\" CACHE FILEPATH \"clang-scan-deps of libycxx's Clang\")\n")
    endif()
  endif()
  set(osx "")
  if(APPLE AND CMAKE_OSX_SYSROOT)
    set(osx "if(NOT CMAKE_OSX_SYSROOT)\n  set(CMAKE_OSX_SYSROOT \"${CMAKE_OSX_SYSROOT}\")\nendif()\n")
  endif()
  file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/toolchain.cmake "${toolchain_head}
set(CMAKE_CXX_COMPILER \"${CMAKE_CURRENT_BINARY_DIR}/bin/ycxx-c++\")
set(CMAKE_C_COMPILER \"${CMAKE_CURRENT_BINARY_DIR}/bin/ycxx-cc\")
${scan}${osx}")
  file(WRITE ${stage}/toolchain.cmake "${toolchain_head}
get_filename_component(_ycxx_prefix \"\${CMAKE_CURRENT_LIST_DIR}/${cmake_to_prefix}\" ABSOLUTE)
set(CMAKE_CXX_COMPILER \"\${_ycxx_prefix}/${CMAKE_INSTALL_BINDIR}/ycxx-c++\")
set(CMAKE_C_COMPILER \"\${_ycxx_prefix}/${CMAKE_INSTALL_BINDIR}/ycxx-cc\")
unset(_ycxx_prefix)
${scan}${osx}")

  # pkg-config, for the plain compiler (CXX=${CMAKE_CXX_COMPILER}).
  if(APPLE)
    set(group_begin "")
    set(group_end "")
  else()
    set(group_begin "-Wl,--start-group ")
    set(group_end " -Wl,--end-group")
  endif()
  set(pc_body "Name: libycxx
Description: An independent C++26 standard library, implemented from the working draft (for ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}: ${CMAKE_CXX_COMPILER})
Version: ${PROJECT_VERSION}
Cflags: -std=c++26 -nostdinc++ @PC_INCLUDES@${cflags_extra}
Libs: -nostdlib++ ${opts} ${group_begin}\${libdir}/libycxx.a \${libdir}/libycxx-abi.a${group_end} -lm ${libgcc}${libs_extra}
")
  string(REPLACE "  " " " pc_body "${pc_body}")
  # Build tree: the sources' headers, then the generated ones.
  string(REPLACE "@PC_INCLUDES@" "-isystem \${includedir} -isystem ${YCXX_GENERATED_INCLUDE}" pc "${pc_body}")
  file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/pkgconfig/libycxx.pc
       "includedir=${YCXX_INCLUDE}\nlibdir=${CMAKE_CURRENT_BINARY_DIR}\n\n${pc}")
  string(REPLACE "@PC_INCLUDES@" "-isystem \${includedir}" pc "${pc_body}")
  file(WRITE ${stage}/libycxx.pc "prefix=\${pcfiledir}/${pc_to_prefix}
includedir=\${prefix}/${YCXX_INSTALL_INCLUDEDIR}
libdir=\${prefix}/${CMAKE_INSTALL_LIBDIR}

${pc}")

  # Meson native files.
  set(meson_head "# libycxx's Meson native file (docs/BUILDING_PROJECTS.md; generated by cmake/ycxx-consumer.cmake):
#   meson setup <build> --native-file <this file>
")
  file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/meson-native.ini "${meson_head}
[binaries]
c = '${CMAKE_CURRENT_BINARY_DIR}/bin/ycxx-cc'
cpp = '${CMAKE_CURRENT_BINARY_DIR}/bin/ycxx-c++'
")
  file(WRITE ${stage}/meson-native.ini "${meson_head}
[binaries]
c = '@DIRNAME@' / '${share_to_prefix}/${CMAKE_INSTALL_BINDIR}/ycxx-cc'
cpp = '@DIRNAME@' / '${share_to_prefix}/${CMAKE_INSTALL_BINDIR}/ycxx-c++'
")

  if(YCXX_INSTALL)
    install(PROGRAMS ${stage}/ycxx-c++ ${stage}/ycxx-cc ${CMAKE_CURRENT_SOURCE_DIR}/tools/ycxx-check-binary
            DESTINATION ${CMAKE_INSTALL_BINDIR})
    install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/tools/lib/ycxx_linkage.py
            DESTINATION ${CMAKE_INSTALL_DATADIR}/libycxx/python)
    install(FILES ${stage}/toolchain.cmake DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/libycxx)
    install(FILES ${stage}/libycxx.pc DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)
    install(FILES ${stage}/meson-native.ini DESTINATION ${CMAKE_INSTALL_DATADIR}/libycxx)
  endif()
endfunction()
