// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [array.overview] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
namespace E17 { using std::array; } // @E17 name
struct E18 : std::array<int, 3> { using std::array<int, 3>::value_type; }; // @E18 name
static_assert(std::is_same_v<std::array<int, 3>::value_type, int>); // @E18 type
struct E19 : std::array<int, 3> { using std::array<int, 3>::pointer; }; // @E19 name
static_assert(std::is_same_v<std::array<int, 3>::pointer, int*>); // @E19 type
struct E20 : std::array<int, 3> { using std::array<int, 3>::const_pointer; }; // @E20 name
static_assert(std::is_same_v<std::array<int, 3>::const_pointer, const int*>); // @E20 type
struct E21 : std::array<int, 3> { using std::array<int, 3>::reference; }; // @E21 name
static_assert(std::is_same_v<std::array<int, 3>::reference, int&>); // @E21 type
struct E22 : std::array<int, 3> { using std::array<int, 3>::const_reference; }; // @E22 name
static_assert(std::is_same_v<std::array<int, 3>::const_reference, const int&>); // @E22 type
struct E23 : std::array<int, 3> { using std::array<int, 3>::size_type; }; // @E23 name
static_assert(std::is_same_v<std::array<int, 3>::size_type, std::size_t>); // @E23 type
struct E24 : std::array<int, 3> { using std::array<int, 3>::difference_type; }; // @E24 name
static_assert(std::is_same_v<std::array<int, 3>::difference_type, std::ptrdiff_t>); // @E24 type
struct E25 : std::array<int, 3> { using std::array<int, 3>::iterator; }; // @E25 name
struct E26 : std::array<int, 3> { using std::array<int, 3>::const_iterator; }; // @E26 name
struct E27 : std::array<int, 3> { using std::array<int, 3>::reverse_iterator; }; // @E27 name
static_assert(std::is_same_v<std::array<int, 3>::reverse_iterator, std::reverse_iterator<std::array<int, 3>::iterator>>); // @E27 type
struct E28 : std::array<int, 3> { using std::array<int, 3>::const_reverse_iterator; }; // @E28 name
static_assert(std::is_same_v<std::array<int, 3>::const_reverse_iterator, std::reverse_iterator<std::array<int, 3>::const_iterator>>); // @E28 type
namespace E29 { using t = decltype(std::declval<std::array<int, 3>&>().fill(std::declval<const int&>())); } // @E29 call
static_assert(std::is_same_v<E29::t, void>); // @E29 ret
namespace E30 { using t = decltype(std::declval<std::array<int, 3>&>().swap(std::declval<std::array<int, 3>&>())); } // @E30 call
static_assert(std::is_same_v<E30::t, void>); // @E30 ret
static_assert(!(std::is_nothrow_swappable_v<int>) || noexcept(std::declval<std::array<int, 3>&>().swap(std::declval<std::array<int, 3>&>()))); // @E30 noexcept
namespace E31 { using t = decltype(std::declval<std::array<int, 3>&>().begin()); } // @E31 call
static_assert(std::is_same_v<E31::t, std::array<int, 3>::iterator>); // @E31 ret
static_assert(!(true) || noexcept(std::declval<std::array<int, 3>&>().begin())); // @E31 noexcept
namespace E32 { using t = decltype(std::declval<const std::array<int, 3>&>().begin()); } // @E32 call
static_assert(std::is_same_v<E32::t, std::array<int, 3>::const_iterator>); // @E32 ret
static_assert(!(true) || noexcept(std::declval<const std::array<int, 3>&>().begin())); // @E32 noexcept
namespace E33 { using t = decltype(std::declval<std::array<int, 3>&>().end()); } // @E33 call
static_assert(std::is_same_v<E33::t, std::array<int, 3>::iterator>); // @E33 ret
static_assert(!(true) || noexcept(std::declval<std::array<int, 3>&>().end())); // @E33 noexcept
namespace E34 { using t = decltype(std::declval<const std::array<int, 3>&>().end()); } // @E34 call
static_assert(std::is_same_v<E34::t, std::array<int, 3>::const_iterator>); // @E34 ret
static_assert(!(true) || noexcept(std::declval<const std::array<int, 3>&>().end())); // @E34 noexcept
namespace E35 { using t = decltype(std::declval<std::array<int, 3>&>().rbegin()); } // @E35 call
static_assert(std::is_same_v<E35::t, std::array<int, 3>::reverse_iterator>); // @E35 ret
static_assert(!(true) || noexcept(std::declval<std::array<int, 3>&>().rbegin())); // @E35 noexcept
namespace E36 { using t = decltype(std::declval<const std::array<int, 3>&>().rbegin()); } // @E36 call
static_assert(std::is_same_v<E36::t, std::array<int, 3>::const_reverse_iterator>); // @E36 ret
static_assert(!(true) || noexcept(std::declval<const std::array<int, 3>&>().rbegin())); // @E36 noexcept
namespace E37 { using t = decltype(std::declval<std::array<int, 3>&>().rend()); } // @E37 call
static_assert(std::is_same_v<E37::t, std::array<int, 3>::reverse_iterator>); // @E37 ret
static_assert(!(true) || noexcept(std::declval<std::array<int, 3>&>().rend())); // @E37 noexcept
namespace E38 { using t = decltype(std::declval<const std::array<int, 3>&>().rend()); } // @E38 call
static_assert(std::is_same_v<E38::t, std::array<int, 3>::const_reverse_iterator>); // @E38 ret
static_assert(!(true) || noexcept(std::declval<const std::array<int, 3>&>().rend())); // @E38 noexcept
namespace E39 { using t = decltype(std::declval<const std::array<int, 3>&>().cbegin()); } // @E39 call
static_assert(std::is_same_v<E39::t, std::array<int, 3>::const_iterator>); // @E39 ret
static_assert(!(true) || noexcept(std::declval<const std::array<int, 3>&>().cbegin())); // @E39 noexcept
namespace E40 { using t = decltype(std::declval<const std::array<int, 3>&>().cend()); } // @E40 call
static_assert(std::is_same_v<E40::t, std::array<int, 3>::const_iterator>); // @E40 ret
static_assert(!(true) || noexcept(std::declval<const std::array<int, 3>&>().cend())); // @E40 noexcept
namespace E41 { using t = decltype(std::declval<const std::array<int, 3>&>().crbegin()); } // @E41 call
static_assert(std::is_same_v<E41::t, std::array<int, 3>::const_reverse_iterator>); // @E41 ret
static_assert(!(true) || noexcept(std::declval<const std::array<int, 3>&>().crbegin())); // @E41 noexcept
namespace E42 { using t = decltype(std::declval<const std::array<int, 3>&>().crend()); } // @E42 call
static_assert(std::is_same_v<E42::t, std::array<int, 3>::const_reverse_iterator>); // @E42 ret
static_assert(!(true) || noexcept(std::declval<const std::array<int, 3>&>().crend())); // @E42 noexcept
namespace E43 { using t = decltype(std::declval<const std::array<int, 3>&>().empty()); } // @E43 call
static_assert(std::is_same_v<E43::t, bool>); // @E43 ret
static_assert(!(true) || noexcept(std::declval<const std::array<int, 3>&>().empty())); // @E43 noexcept
namespace E44 { using t = decltype(std::declval<const std::array<int, 3>&>().size()); } // @E44 call
static_assert(std::is_same_v<E44::t, std::array<int, 3>::size_type>); // @E44 ret
static_assert(!(true) || noexcept(std::declval<const std::array<int, 3>&>().size())); // @E44 noexcept
namespace E45 { using t = decltype(std::declval<const std::array<int, 3>&>().max_size()); } // @E45 call
static_assert(std::is_same_v<E45::t, std::array<int, 3>::size_type>); // @E45 ret
static_assert(!(true) || noexcept(std::declval<const std::array<int, 3>&>().max_size())); // @E45 noexcept
namespace E46 { using t = decltype(std::declval<std::array<int, 3>&>().operator[](std::declval<std::array<int, 3>::size_type>())); } // @E46 call
static_assert(std::is_same_v<E46::t, std::array<int, 3>::reference>); // @E46 ret
namespace E47 { using t = decltype(std::declval<const std::array<int, 3>&>().operator[](std::declval<std::array<int, 3>::size_type>())); } // @E47 call
static_assert(std::is_same_v<E47::t, std::array<int, 3>::const_reference>); // @E47 ret
namespace E48 { using t = decltype(std::declval<std::array<int, 3>&>().at(std::declval<std::array<int, 3>::size_type>())); } // @E48 call
static_assert(std::is_same_v<E48::t, std::array<int, 3>::reference>); // @E48 ret
namespace E49 { using t = decltype(std::declval<const std::array<int, 3>&>().at(std::declval<std::array<int, 3>::size_type>())); } // @E49 call
static_assert(std::is_same_v<E49::t, std::array<int, 3>::const_reference>); // @E49 ret
namespace E50 { using t = decltype(std::declval<std::array<int, 3>&>().front()); } // @E50 call
static_assert(std::is_same_v<E50::t, std::array<int, 3>::reference>); // @E50 ret
namespace E51 { using t = decltype(std::declval<const std::array<int, 3>&>().front()); } // @E51 call
static_assert(std::is_same_v<E51::t, std::array<int, 3>::const_reference>); // @E51 ret
namespace E52 { using t = decltype(std::declval<std::array<int, 3>&>().back()); } // @E52 call
static_assert(std::is_same_v<E52::t, std::array<int, 3>::reference>); // @E52 ret
namespace E53 { using t = decltype(std::declval<const std::array<int, 3>&>().back()); } // @E53 call
static_assert(std::is_same_v<E53::t, std::array<int, 3>::const_reference>); // @E53 ret
namespace E54 { using t = decltype(std::declval<std::array<int, 3>&>().data()); } // @E54 call
static_assert(std::is_same_v<E54::t, int*>); // @E54 ret
static_assert(!(true) || noexcept(std::declval<std::array<int, 3>&>().data())); // @E54 noexcept
namespace E55 { using t = decltype(std::declval<const std::array<int, 3>&>().data()); } // @E55 call
static_assert(std::is_same_v<E55::t, const int*>); // @E55 ret
static_assert(!(true) || noexcept(std::declval<const std::array<int, 3>&>().data())); // @E55 noexcept
