// Generated by tools/spec_audit/gen_probes.py; do not edit. Names of [associative.set.syn] with only <set> included.
#include <set>
namespace E968_h { using std::set; } // @E968 header
namespace E971_h { using std::swap; } // @E971 header
namespace E972_h { using std::erase_if; } // @E972 header
namespace E973_h { using std::multiset; } // @E973 header
namespace E976_h { using std::swap; } // @E976 header
namespace E977_h { using std::erase_if; } // @E977 header
namespace E978_h { using std::pmr::set; } // @E978 header
namespace E979_h { using std::pmr::multiset; } // @E979 header
namespace E966_h { using t = std::strong_ordering; } // @E966 include
namespace E967_h { using t = std::initializer_list<int>; } // @E967 include
