// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [char.traits.specializations.wchar.t] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
static_assert(sizeof(std::char_traits<wchar_t>) > 0); // @E5412 spec
struct E5413 : std::char_traits<wchar_t> { using std::char_traits<wchar_t>::char_type; }; // @E5413 name
static_assert(std::is_same_v<std::char_traits<wchar_t>::char_type, wchar_t>); // @E5413 type
struct E5414 : std::char_traits<wchar_t> { using std::char_traits<wchar_t>::int_type; }; // @E5414 name
static_assert(std::is_same_v<std::char_traits<wchar_t>::int_type, std::wint_t>); // @E5414 type
struct E5415 : std::char_traits<wchar_t> { using std::char_traits<wchar_t>::off_type; }; // @E5415 name
static_assert(std::is_same_v<std::char_traits<wchar_t>::off_type, std::streamoff>); // @E5415 type
struct E5416 : std::char_traits<wchar_t> { using std::char_traits<wchar_t>::pos_type; }; // @E5416 name
static_assert(std::is_same_v<std::char_traits<wchar_t>::pos_type, std::wstreampos>); // @E5416 type
struct E5417 : std::char_traits<wchar_t> { using std::char_traits<wchar_t>::state_type; }; // @E5417 name
static_assert(std::is_same_v<std::char_traits<wchar_t>::state_type, std::mbstate_t>); // @E5417 type
struct E5418 : std::char_traits<wchar_t> { using std::char_traits<wchar_t>::comparison_category; }; // @E5418 name
static_assert(std::is_same_v<std::char_traits<wchar_t>::comparison_category, std::strong_ordering>); // @E5418 type
namespace E5419 { using t = decltype(std::char_traits<wchar_t>::assign(std::declval<std::char_traits<wchar_t>::char_type&>(), std::declval<const std::char_traits<wchar_t>::char_type&>())); } // @E5419 call
static_assert(std::is_same_v<E5419::t, void>); // @E5419 ret
static_assert(!(true) || noexcept(std::char_traits<wchar_t>::assign(std::declval<std::char_traits<wchar_t>::char_type&>(), std::declval<const std::char_traits<wchar_t>::char_type&>()))); // @E5419 noexcept
namespace E5420 { using t = decltype(std::char_traits<wchar_t>::eq(std::declval<std::char_traits<wchar_t>::char_type>(), std::declval<std::char_traits<wchar_t>::char_type>())); } // @E5420 call
static_assert(std::is_same_v<E5420::t, bool>); // @E5420 ret
static_assert(!(true) || noexcept(std::char_traits<wchar_t>::eq(std::declval<std::char_traits<wchar_t>::char_type>(), std::declval<std::char_traits<wchar_t>::char_type>()))); // @E5420 noexcept
namespace E5421 { using t = decltype(std::char_traits<wchar_t>::lt(std::declval<std::char_traits<wchar_t>::char_type>(), std::declval<std::char_traits<wchar_t>::char_type>())); } // @E5421 call
static_assert(std::is_same_v<E5421::t, bool>); // @E5421 ret
static_assert(!(true) || noexcept(std::char_traits<wchar_t>::lt(std::declval<std::char_traits<wchar_t>::char_type>(), std::declval<std::char_traits<wchar_t>::char_type>()))); // @E5421 noexcept
namespace E5422 { using t = decltype(std::char_traits<wchar_t>::compare(std::declval<const std::char_traits<wchar_t>::char_type*>(), std::declval<const std::char_traits<wchar_t>::char_type*>(), std::declval<std::size_t>())); } // @E5422 call
static_assert(std::is_same_v<E5422::t, int>); // @E5422 ret
namespace E5423 { using t = decltype(std::char_traits<wchar_t>::length(std::declval<const std::char_traits<wchar_t>::char_type*>())); } // @E5423 call
static_assert(std::is_same_v<E5423::t, std::size_t>); // @E5423 ret
namespace E5424 { using t = decltype(std::char_traits<wchar_t>::find(std::declval<const std::char_traits<wchar_t>::char_type*>(), std::declval<std::size_t>(), std::declval<const std::char_traits<wchar_t>::char_type&>())); } // @E5424 call
static_assert(std::is_same_v<E5424::t, const std::char_traits<wchar_t>::char_type*>); // @E5424 ret
namespace E5425 { using t = decltype(std::char_traits<wchar_t>::move(std::declval<std::char_traits<wchar_t>::char_type*>(), std::declval<const std::char_traits<wchar_t>::char_type*>(), std::declval<std::size_t>())); } // @E5425 call
static_assert(std::is_same_v<E5425::t, std::char_traits<wchar_t>::char_type*>); // @E5425 ret
namespace E5426 { using t = decltype(std::char_traits<wchar_t>::copy(std::declval<std::char_traits<wchar_t>::char_type*>(), std::declval<const std::char_traits<wchar_t>::char_type*>(), std::declval<std::size_t>())); } // @E5426 call
static_assert(std::is_same_v<E5426::t, std::char_traits<wchar_t>::char_type*>); // @E5426 ret
namespace E5427 { using t = decltype(std::char_traits<wchar_t>::assign(std::declval<std::char_traits<wchar_t>::char_type*>(), std::declval<std::size_t>(), std::declval<std::char_traits<wchar_t>::char_type>())); } // @E5427 call
static_assert(std::is_same_v<E5427::t, std::char_traits<wchar_t>::char_type*>); // @E5427 ret
namespace E5428 { using t = decltype(std::char_traits<wchar_t>::not_eof(std::declval<std::char_traits<wchar_t>::int_type>())); } // @E5428 call
static_assert(std::is_same_v<E5428::t, std::char_traits<wchar_t>::int_type>); // @E5428 ret
static_assert(!(true) || noexcept(std::char_traits<wchar_t>::not_eof(std::declval<std::char_traits<wchar_t>::int_type>()))); // @E5428 noexcept
namespace E5429 { using t = decltype(std::char_traits<wchar_t>::to_char_type(std::declval<std::char_traits<wchar_t>::int_type>())); } // @E5429 call
static_assert(std::is_same_v<E5429::t, std::char_traits<wchar_t>::char_type>); // @E5429 ret
static_assert(!(true) || noexcept(std::char_traits<wchar_t>::to_char_type(std::declval<std::char_traits<wchar_t>::int_type>()))); // @E5429 noexcept
namespace E5430 { using t = decltype(std::char_traits<wchar_t>::to_int_type(std::declval<std::char_traits<wchar_t>::char_type>())); } // @E5430 call
static_assert(std::is_same_v<E5430::t, std::char_traits<wchar_t>::int_type>); // @E5430 ret
static_assert(!(true) || noexcept(std::char_traits<wchar_t>::to_int_type(std::declval<std::char_traits<wchar_t>::char_type>()))); // @E5430 noexcept
namespace E5431 { using t = decltype(std::char_traits<wchar_t>::eq_int_type(std::declval<std::char_traits<wchar_t>::int_type>(), std::declval<std::char_traits<wchar_t>::int_type>())); } // @E5431 call
static_assert(std::is_same_v<E5431::t, bool>); // @E5431 ret
static_assert(!(true) || noexcept(std::char_traits<wchar_t>::eq_int_type(std::declval<std::char_traits<wchar_t>::int_type>(), std::declval<std::char_traits<wchar_t>::int_type>()))); // @E5431 noexcept
namespace E5432 { using t = decltype(std::char_traits<wchar_t>::eof()); } // @E5432 call
static_assert(std::is_same_v<E5432::t, std::char_traits<wchar_t>::int_type>); // @E5432 ret
static_assert(!(true) || noexcept(std::char_traits<wchar_t>::eof())); // @E5432 noexcept
