// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [char.traits.specializations.char32.t] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
static_assert(sizeof(std::char_traits<char32_t>) > 0); // @E5391 spec
struct E5392 : std::char_traits<char32_t> { using std::char_traits<char32_t>::char_type; }; // @E5392 name
static_assert(std::is_same_v<std::char_traits<char32_t>::char_type, char32_t>); // @E5392 type
struct E5393 : std::char_traits<char32_t> { using std::char_traits<char32_t>::int_type; }; // @E5393 name
static_assert(std::is_same_v<std::char_traits<char32_t>::int_type, std::uint_least32_t>); // @E5393 type
struct E5394 : std::char_traits<char32_t> { using std::char_traits<char32_t>::off_type; }; // @E5394 name
static_assert(std::is_same_v<std::char_traits<char32_t>::off_type, std::streamoff>); // @E5394 type
struct E5395 : std::char_traits<char32_t> { using std::char_traits<char32_t>::pos_type; }; // @E5395 name
static_assert(std::is_same_v<std::char_traits<char32_t>::pos_type, std::u32streampos>); // @E5395 type
struct E5396 : std::char_traits<char32_t> { using std::char_traits<char32_t>::state_type; }; // @E5396 name
static_assert(std::is_same_v<std::char_traits<char32_t>::state_type, std::mbstate_t>); // @E5396 type
struct E5397 : std::char_traits<char32_t> { using std::char_traits<char32_t>::comparison_category; }; // @E5397 name
static_assert(std::is_same_v<std::char_traits<char32_t>::comparison_category, std::strong_ordering>); // @E5397 type
namespace E5398 { using t = decltype(std::char_traits<char32_t>::assign(std::declval<std::char_traits<char32_t>::char_type&>(), std::declval<const std::char_traits<char32_t>::char_type&>())); } // @E5398 call
static_assert(std::is_same_v<E5398::t, void>); // @E5398 ret
static_assert(!(true) || noexcept(std::char_traits<char32_t>::assign(std::declval<std::char_traits<char32_t>::char_type&>(), std::declval<const std::char_traits<char32_t>::char_type&>()))); // @E5398 noexcept
namespace E5399 { using t = decltype(std::char_traits<char32_t>::eq(std::declval<std::char_traits<char32_t>::char_type>(), std::declval<std::char_traits<char32_t>::char_type>())); } // @E5399 call
static_assert(std::is_same_v<E5399::t, bool>); // @E5399 ret
static_assert(!(true) || noexcept(std::char_traits<char32_t>::eq(std::declval<std::char_traits<char32_t>::char_type>(), std::declval<std::char_traits<char32_t>::char_type>()))); // @E5399 noexcept
namespace E5400 { using t = decltype(std::char_traits<char32_t>::lt(std::declval<std::char_traits<char32_t>::char_type>(), std::declval<std::char_traits<char32_t>::char_type>())); } // @E5400 call
static_assert(std::is_same_v<E5400::t, bool>); // @E5400 ret
static_assert(!(true) || noexcept(std::char_traits<char32_t>::lt(std::declval<std::char_traits<char32_t>::char_type>(), std::declval<std::char_traits<char32_t>::char_type>()))); // @E5400 noexcept
namespace E5401 { using t = decltype(std::char_traits<char32_t>::compare(std::declval<const std::char_traits<char32_t>::char_type*>(), std::declval<const std::char_traits<char32_t>::char_type*>(), std::declval<std::size_t>())); } // @E5401 call
static_assert(std::is_same_v<E5401::t, int>); // @E5401 ret
namespace E5402 { using t = decltype(std::char_traits<char32_t>::length(std::declval<const std::char_traits<char32_t>::char_type*>())); } // @E5402 call
static_assert(std::is_same_v<E5402::t, std::size_t>); // @E5402 ret
namespace E5403 { using t = decltype(std::char_traits<char32_t>::find(std::declval<const std::char_traits<char32_t>::char_type*>(), std::declval<std::size_t>(), std::declval<const std::char_traits<char32_t>::char_type&>())); } // @E5403 call
static_assert(std::is_same_v<E5403::t, const std::char_traits<char32_t>::char_type*>); // @E5403 ret
namespace E5404 { using t = decltype(std::char_traits<char32_t>::move(std::declval<std::char_traits<char32_t>::char_type*>(), std::declval<const std::char_traits<char32_t>::char_type*>(), std::declval<std::size_t>())); } // @E5404 call
static_assert(std::is_same_v<E5404::t, std::char_traits<char32_t>::char_type*>); // @E5404 ret
namespace E5405 { using t = decltype(std::char_traits<char32_t>::copy(std::declval<std::char_traits<char32_t>::char_type*>(), std::declval<const std::char_traits<char32_t>::char_type*>(), std::declval<std::size_t>())); } // @E5405 call
static_assert(std::is_same_v<E5405::t, std::char_traits<char32_t>::char_type*>); // @E5405 ret
namespace E5406 { using t = decltype(std::char_traits<char32_t>::assign(std::declval<std::char_traits<char32_t>::char_type*>(), std::declval<std::size_t>(), std::declval<std::char_traits<char32_t>::char_type>())); } // @E5406 call
static_assert(std::is_same_v<E5406::t, std::char_traits<char32_t>::char_type*>); // @E5406 ret
namespace E5407 { using t = decltype(std::char_traits<char32_t>::not_eof(std::declval<std::char_traits<char32_t>::int_type>())); } // @E5407 call
static_assert(std::is_same_v<E5407::t, std::char_traits<char32_t>::int_type>); // @E5407 ret
static_assert(!(true) || noexcept(std::char_traits<char32_t>::not_eof(std::declval<std::char_traits<char32_t>::int_type>()))); // @E5407 noexcept
namespace E5408 { using t = decltype(std::char_traits<char32_t>::to_char_type(std::declval<std::char_traits<char32_t>::int_type>())); } // @E5408 call
static_assert(std::is_same_v<E5408::t, std::char_traits<char32_t>::char_type>); // @E5408 ret
static_assert(!(true) || noexcept(std::char_traits<char32_t>::to_char_type(std::declval<std::char_traits<char32_t>::int_type>()))); // @E5408 noexcept
namespace E5409 { using t = decltype(std::char_traits<char32_t>::to_int_type(std::declval<std::char_traits<char32_t>::char_type>())); } // @E5409 call
static_assert(std::is_same_v<E5409::t, std::char_traits<char32_t>::int_type>); // @E5409 ret
static_assert(!(true) || noexcept(std::char_traits<char32_t>::to_int_type(std::declval<std::char_traits<char32_t>::char_type>()))); // @E5409 noexcept
namespace E5410 { using t = decltype(std::char_traits<char32_t>::eq_int_type(std::declval<std::char_traits<char32_t>::int_type>(), std::declval<std::char_traits<char32_t>::int_type>())); } // @E5410 call
static_assert(std::is_same_v<E5410::t, bool>); // @E5410 ret
static_assert(!(true) || noexcept(std::char_traits<char32_t>::eq_int_type(std::declval<std::char_traits<char32_t>::int_type>(), std::declval<std::char_traits<char32_t>::int_type>()))); // @E5410 noexcept
namespace E5411 { using t = decltype(std::char_traits<char32_t>::eof()); } // @E5411 call
static_assert(std::is_same_v<E5411::t, std::char_traits<char32_t>::int_type>); // @E5411 ret
static_assert(!(true) || noexcept(std::char_traits<char32_t>::eof())); // @E5411 noexcept
