// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [cstring.syn] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
#ifndef __STDC_VERSION_STRING_H__
#error "__STDC_VERSION_STRING_H__ is not defined" // @E5831 name
#endif
namespace E5832 { using std::size_t; } // @E5832 name
namespace E5833 { using t = decltype(std::memcpy(std::declval<void*>(), std::declval<const void*>(), std::declval<std::size_t>())); } // @E5833 call
static_assert(std::is_same_v<E5833::t, void*>); // @E5833 ret
namespace E5834 { using t = decltype(std::memccpy(std::declval<void*>(), std::declval<const void*>(), std::declval<int>(), std::declval<std::size_t>())); } // @E5834 call
static_assert(std::is_same_v<E5834::t, void*>); // @E5834 ret
namespace E5835 { using t = decltype(std::memmove(std::declval<void*>(), std::declval<const void*>(), std::declval<std::size_t>())); } // @E5835 call
static_assert(std::is_same_v<E5835::t, void*>); // @E5835 ret
namespace E5836 { using t = decltype(std::strcpy(std::declval<char*>(), std::declval<const char*>())); } // @E5836 call
static_assert(std::is_same_v<E5836::t, char*>); // @E5836 ret
namespace E5837 { using t = decltype(std::strncpy(std::declval<char*>(), std::declval<const char*>(), std::declval<std::size_t>())); } // @E5837 call
static_assert(std::is_same_v<E5837::t, char*>); // @E5837 ret
namespace E5838 { using t = decltype(std::strdup(std::declval<const char*>())); } // @E5838 call
static_assert(std::is_same_v<E5838::t, char*>); // @E5838 ret
namespace E5839 { using t = decltype(std::strndup(std::declval<const char*>(), std::declval<std::size_t>())); } // @E5839 call
static_assert(std::is_same_v<E5839::t, char*>); // @E5839 ret
namespace E5840 { using t = decltype(std::strcat(std::declval<char*>(), std::declval<const char*>())); } // @E5840 call
static_assert(std::is_same_v<E5840::t, char*>); // @E5840 ret
namespace E5841 { using t = decltype(std::strncat(std::declval<char*>(), std::declval<const char*>(), std::declval<std::size_t>())); } // @E5841 call
static_assert(std::is_same_v<E5841::t, char*>); // @E5841 ret
namespace E5842 { using t = decltype(std::memcmp(std::declval<const void*>(), std::declval<const void*>(), std::declval<std::size_t>())); } // @E5842 call
static_assert(std::is_same_v<E5842::t, int>); // @E5842 ret
namespace E5843 { using t = decltype(std::strcmp(std::declval<const char*>(), std::declval<const char*>())); } // @E5843 call
static_assert(std::is_same_v<E5843::t, int>); // @E5843 ret
namespace E5844 { using t = decltype(std::strcoll(std::declval<const char*>(), std::declval<const char*>())); } // @E5844 call
static_assert(std::is_same_v<E5844::t, int>); // @E5844 ret
namespace E5845 { using t = decltype(std::strncmp(std::declval<const char*>(), std::declval<const char*>(), std::declval<std::size_t>())); } // @E5845 call
static_assert(std::is_same_v<E5845::t, int>); // @E5845 ret
namespace E5846 { using t = decltype(std::strxfrm(std::declval<char*>(), std::declval<const char*>(), std::declval<std::size_t>())); } // @E5846 call
static_assert(std::is_same_v<E5846::t, std::size_t>); // @E5846 ret
namespace E5847 { using t = decltype(std::memchr(std::declval<const void*>(), std::declval<int>(), std::declval<std::size_t>())); } // @E5847 call
static_assert(std::is_same_v<E5847::t, const void*>); // @E5847 ret
namespace E5848 { using t = decltype(std::memchr(std::declval<void*>(), std::declval<int>(), std::declval<std::size_t>())); } // @E5848 call
static_assert(std::is_same_v<E5848::t, void*>); // @E5848 ret
namespace E5849 { using t = decltype(std::strchr(std::declval<const char*>(), std::declval<int>())); } // @E5849 call
static_assert(std::is_same_v<E5849::t, const char*>); // @E5849 ret
namespace E5850 { using t = decltype(std::strchr(std::declval<char*>(), std::declval<int>())); } // @E5850 call
static_assert(std::is_same_v<E5850::t, char*>); // @E5850 ret
namespace E5851 { using t = decltype(std::strcspn(std::declval<const char*>(), std::declval<const char*>())); } // @E5851 call
static_assert(std::is_same_v<E5851::t, std::size_t>); // @E5851 ret
namespace E5852 { using t = decltype(std::strpbrk(std::declval<const char*>(), std::declval<const char*>())); } // @E5852 call
static_assert(std::is_same_v<E5852::t, const char*>); // @E5852 ret
namespace E5853 { using t = decltype(std::strpbrk(std::declval<char*>(), std::declval<const char*>())); } // @E5853 call
static_assert(std::is_same_v<E5853::t, char*>); // @E5853 ret
namespace E5854 { using t = decltype(std::strrchr(std::declval<const char*>(), std::declval<int>())); } // @E5854 call
static_assert(std::is_same_v<E5854::t, const char*>); // @E5854 ret
namespace E5855 { using t = decltype(std::strrchr(std::declval<char*>(), std::declval<int>())); } // @E5855 call
static_assert(std::is_same_v<E5855::t, char*>); // @E5855 ret
namespace E5856 { using t = decltype(std::strspn(std::declval<const char*>(), std::declval<const char*>())); } // @E5856 call
static_assert(std::is_same_v<E5856::t, std::size_t>); // @E5856 ret
namespace E5857 { using t = decltype(std::strstr(std::declval<const char*>(), std::declval<const char*>())); } // @E5857 call
static_assert(std::is_same_v<E5857::t, const char*>); // @E5857 ret
namespace E5858 { using t = decltype(std::strstr(std::declval<char*>(), std::declval<const char*>())); } // @E5858 call
static_assert(std::is_same_v<E5858::t, char*>); // @E5858 ret
namespace E5859 { using t = decltype(std::strtok(std::declval<char*>(), std::declval<const char*>())); } // @E5859 call
static_assert(std::is_same_v<E5859::t, char*>); // @E5859 ret
namespace E5860 { using t = decltype(std::memset(std::declval<void*>(), std::declval<int>(), std::declval<std::size_t>())); } // @E5860 call
static_assert(std::is_same_v<E5860::t, void*>); // @E5860 ret
namespace E5861 { using t = decltype(std::memset_explicit(std::declval<void*>(), std::declval<int>(), std::declval<std::size_t>())); } // @E5861 call
static_assert(std::is_same_v<E5861::t, void*>); // @E5861 ret
namespace E5862 { using t = decltype(std::strerror(std::declval<int>())); } // @E5862 call
static_assert(std::is_same_v<E5862::t, char*>); // @E5862 ret
namespace E5863 { using t = decltype(std::strlen(std::declval<const char*>())); } // @E5863 call
static_assert(std::is_same_v<E5863::t, std::size_t>); // @E5863 ret
#ifndef NULL
#error "NULL is not defined" // @E5864 name
#endif
