// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [flat.multiset.defn] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
namespace E2300 { using std::flat_multiset; } // @E2300 name
struct E2301 : std::flat_multiset<int, std::less<>> { using std::flat_multiset<int, std::less<>>::key_type; }; // @E2301 name
static_assert(std::is_same_v<std::flat_multiset<int, std::less<>>::key_type, int>); // @E2301 type
struct E2302 : std::flat_multiset<int, std::less<>> { using std::flat_multiset<int, std::less<>>::value_type; }; // @E2302 name
static_assert(std::is_same_v<std::flat_multiset<int, std::less<>>::value_type, int>); // @E2302 type
struct E2303 : std::flat_multiset<int, std::less<>> { using std::flat_multiset<int, std::less<>>::key_compare; }; // @E2303 name
static_assert(std::is_same_v<std::flat_multiset<int, std::less<>>::key_compare, std::less<>>); // @E2303 type
struct E2304 : std::flat_multiset<int, std::less<>> { using std::flat_multiset<int, std::less<>>::value_compare; }; // @E2304 name
static_assert(std::is_same_v<std::flat_multiset<int, std::less<>>::value_compare, std::less<>>); // @E2304 type
struct E2305 : std::flat_multiset<int, std::less<>> { using std::flat_multiset<int, std::less<>>::reference; }; // @E2305 name
static_assert(std::is_same_v<std::flat_multiset<int, std::less<>>::reference, std::flat_multiset<int, std::less<>>::value_type&>); // @E2305 type
struct E2306 : std::flat_multiset<int, std::less<>> { using std::flat_multiset<int, std::less<>>::const_reference; }; // @E2306 name
static_assert(std::is_same_v<std::flat_multiset<int, std::less<>>::const_reference, const std::flat_multiset<int, std::less<>>::value_type&>); // @E2306 type
struct E2307 : std::flat_multiset<int, std::less<>> { using std::flat_multiset<int, std::less<>>::size_type; }; // @E2307 name
static_assert(std::is_same_v<std::flat_multiset<int, std::less<>>::size_type, std::vector<int>::size_type>); // @E2307 type
struct E2308 : std::flat_multiset<int, std::less<>> { using std::flat_multiset<int, std::less<>>::difference_type; }; // @E2308 name
static_assert(std::is_same_v<std::flat_multiset<int, std::less<>>::difference_type, std::vector<int>::difference_type>); // @E2308 type
struct E2309 : std::flat_multiset<int, std::less<>> { using std::flat_multiset<int, std::less<>>::iterator; }; // @E2309 name
struct E2310 : std::flat_multiset<int, std::less<>> { using std::flat_multiset<int, std::less<>>::const_iterator; }; // @E2310 name
struct E2311 : std::flat_multiset<int, std::less<>> { using std::flat_multiset<int, std::less<>>::reverse_iterator; }; // @E2311 name
static_assert(std::is_same_v<std::flat_multiset<int, std::less<>>::reverse_iterator, std::reverse_iterator<std::flat_multiset<int, std::less<>>::iterator>>); // @E2311 type
struct E2312 : std::flat_multiset<int, std::less<>> { using std::flat_multiset<int, std::less<>>::const_reverse_iterator; }; // @E2312 name
static_assert(std::is_same_v<std::flat_multiset<int, std::less<>>::const_reverse_iterator, std::reverse_iterator<std::flat_multiset<int, std::less<>>::const_iterator>>); // @E2312 type
struct E2313 : std::flat_multiset<int, std::less<>> { using std::flat_multiset<int, std::less<>>::container_type; }; // @E2313 name
static_assert(std::is_same_v<std::flat_multiset<int, std::less<>>::container_type, std::vector<int>>); // @E2313 type
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>>); // @E2314 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, const std::flat_multiset<int, std::less<>>&>); // @E2315 call
static_assert(std::is_convertible_v<const std::flat_multiset<int, std::less<>>&, std::flat_multiset<int, std::less<>>>); // @E2315 implicit
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::flat_multiset<int, std::less<>>&&>); // @E2316 call
static_assert(std::is_convertible_v<std::flat_multiset<int, std::less<>>&&, std::flat_multiset<int, std::less<>>>); // @E2316 implicit
namespace E2317 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().operator=(std::declval<const std::flat_multiset<int, std::less<>>&>())); } // @E2317 call
static_assert(std::is_same_v<E2317::t, std::flat_multiset<int, std::less<>>&>); // @E2317 ret
namespace E2318 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().operator=(std::declval<std::flat_multiset<int, std::less<>>&&>())); } // @E2318 call
static_assert(std::is_same_v<E2318::t, std::flat_multiset<int, std::less<>>&>); // @E2318 ret
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, const std::flat_multiset<int, std::less<>>::key_compare&>); // @E2319 call
static_assert(!std::is_convertible_v<const std::flat_multiset<int, std::less<>>::key_compare&, std::flat_multiset<int, std::less<>>>); // @E2319 explicit
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::flat_multiset<int, std::less<>>::container_type, const std::flat_multiset<int, std::less<>>::key_compare&>); // @E2320 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::flat_multiset<int, std::less<>>::container_type>); // @E2320 defaults
static_assert(!std::is_convertible_v<std::flat_multiset<int, std::less<>>::container_type, std::flat_multiset<int, std::less<>>>); // @E2320 explicit
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::sorted_equivalent_t, std::flat_multiset<int, std::less<>>::container_type, const std::flat_multiset<int, std::less<>>::key_compare&>); // @E2321 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::sorted_equivalent_t, std::flat_multiset<int, std::less<>>::container_type>); // @E2321 defaults
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::type_identity_t<int*>, std::type_identity_t<int*>, const std::flat_multiset<int, std::less<>>::key_compare&>); // @E2322 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::type_identity_t<int*>, std::type_identity_t<int*>>); // @E2322 defaults
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::sorted_equivalent_t, std::type_identity_t<int*>, std::type_identity_t<int*>, const std::flat_multiset<int, std::less<>>::key_compare&>); // @E2323 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::sorted_equivalent_t, std::type_identity_t<int*>, std::type_identity_t<int*>>); // @E2323 defaults
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::from_range_t, std::vector<int>&&>); // @E2324 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::from_range_t, std::vector<int>&&, const std::flat_multiset<int, std::less<>>::key_compare&>); // @E2325 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::initializer_list<std::flat_multiset<int, std::less<>>::value_type>, const std::flat_multiset<int, std::less<>>::key_compare&>); // @E2326 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::initializer_list<std::flat_multiset<int, std::less<>>::value_type>>); // @E2326 defaults
static_assert(std::is_convertible_v<std::initializer_list<std::flat_multiset<int, std::less<>>::value_type>, std::flat_multiset<int, std::less<>>>); // @E2326 implicit
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::sorted_equivalent_t, std::initializer_list<std::flat_multiset<int, std::less<>>::value_type>, const std::flat_multiset<int, std::less<>>::key_compare&>); // @E2327 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::sorted_equivalent_t, std::initializer_list<std::flat_multiset<int, std::less<>>::value_type>>); // @E2327 defaults
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, const std::allocator<int>&>); // @E2328 call
static_assert(!std::is_convertible_v<const std::allocator<int>&, std::flat_multiset<int, std::less<>>>); // @E2328 explicit
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, const std::flat_multiset<int, std::less<>>::key_compare&, const std::allocator<int>&>); // @E2329 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, const std::flat_multiset<int, std::less<>>::container_type&, const std::allocator<int>&>); // @E2330 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, const std::flat_multiset<int, std::less<>>::container_type&, const std::flat_multiset<int, std::less<>>::key_compare&, const std::allocator<int>&>); // @E2331 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::sorted_equivalent_t, const std::flat_multiset<int, std::less<>>::container_type&, const std::allocator<int>&>); // @E2332 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::sorted_equivalent_t, const std::flat_multiset<int, std::less<>>::container_type&, const std::flat_multiset<int, std::less<>>::key_compare&, const std::allocator<int>&>); // @E2333 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, const std::flat_multiset<int, std::less<>>&, const std::allocator<int>&>); // @E2334 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::flat_multiset<int, std::less<>>&&, const std::allocator<int>&>); // @E2335 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::type_identity_t<int*>, std::type_identity_t<int*>, const std::allocator<int>&>); // @E2336 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::type_identity_t<int*>, std::type_identity_t<int*>, const std::flat_multiset<int, std::less<>>::key_compare&, const std::allocator<int>&>); // @E2337 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::sorted_equivalent_t, std::type_identity_t<int*>, std::type_identity_t<int*>, const std::allocator<int>&>); // @E2338 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::sorted_equivalent_t, std::type_identity_t<int*>, std::type_identity_t<int*>, const std::flat_multiset<int, std::less<>>::key_compare&, const std::allocator<int>&>); // @E2339 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::from_range_t, std::vector<int>&&, const std::allocator<int>&>); // @E2340 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::from_range_t, std::vector<int>&&, const std::flat_multiset<int, std::less<>>::key_compare&, const std::allocator<int>&>); // @E2341 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::initializer_list<std::flat_multiset<int, std::less<>>::value_type>, const std::allocator<int>&>); // @E2342 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::initializer_list<std::flat_multiset<int, std::less<>>::value_type>, const std::flat_multiset<int, std::less<>>::key_compare&, const std::allocator<int>&>); // @E2343 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::sorted_equivalent_t, std::initializer_list<std::flat_multiset<int, std::less<>>::value_type>, const std::allocator<int>&>); // @E2344 call
static_assert(std::is_constructible_v<std::flat_multiset<int, std::less<>>, std::sorted_equivalent_t, std::initializer_list<std::flat_multiset<int, std::less<>>::value_type>, const std::flat_multiset<int, std::less<>>::key_compare&, const std::allocator<int>&>); // @E2345 call
namespace E2346 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().operator=(std::declval<std::initializer_list<std::flat_multiset<int, std::less<>>::value_type>>())); } // @E2346 call
static_assert(std::is_same_v<E2346::t, std::flat_multiset<int, std::less<>>&>); // @E2346 ret
namespace E2347 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().begin()); } // @E2347 call
static_assert(std::is_same_v<E2347::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2347 ret
static_assert(!(true) || noexcept(std::declval<std::flat_multiset<int, std::less<>>&>().begin())); // @E2347 noexcept
namespace E2348 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().begin()); } // @E2348 call
static_assert(std::is_same_v<E2348::t, std::flat_multiset<int, std::less<>>::const_iterator>); // @E2348 ret
static_assert(!(true) || noexcept(std::declval<const std::flat_multiset<int, std::less<>>&>().begin())); // @E2348 noexcept
namespace E2349 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().end()); } // @E2349 call
static_assert(std::is_same_v<E2349::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2349 ret
static_assert(!(true) || noexcept(std::declval<std::flat_multiset<int, std::less<>>&>().end())); // @E2349 noexcept
namespace E2350 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().end()); } // @E2350 call
static_assert(std::is_same_v<E2350::t, std::flat_multiset<int, std::less<>>::const_iterator>); // @E2350 ret
static_assert(!(true) || noexcept(std::declval<const std::flat_multiset<int, std::less<>>&>().end())); // @E2350 noexcept
namespace E2351 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().rbegin()); } // @E2351 call
static_assert(std::is_same_v<E2351::t, std::flat_multiset<int, std::less<>>::reverse_iterator>); // @E2351 ret
static_assert(!(true) || noexcept(std::declval<std::flat_multiset<int, std::less<>>&>().rbegin())); // @E2351 noexcept
namespace E2352 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().rbegin()); } // @E2352 call
static_assert(std::is_same_v<E2352::t, std::flat_multiset<int, std::less<>>::const_reverse_iterator>); // @E2352 ret
static_assert(!(true) || noexcept(std::declval<const std::flat_multiset<int, std::less<>>&>().rbegin())); // @E2352 noexcept
namespace E2353 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().rend()); } // @E2353 call
static_assert(std::is_same_v<E2353::t, std::flat_multiset<int, std::less<>>::reverse_iterator>); // @E2353 ret
static_assert(!(true) || noexcept(std::declval<std::flat_multiset<int, std::less<>>&>().rend())); // @E2353 noexcept
namespace E2354 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().rend()); } // @E2354 call
static_assert(std::is_same_v<E2354::t, std::flat_multiset<int, std::less<>>::const_reverse_iterator>); // @E2354 ret
static_assert(!(true) || noexcept(std::declval<const std::flat_multiset<int, std::less<>>&>().rend())); // @E2354 noexcept
namespace E2355 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().cbegin()); } // @E2355 call
static_assert(std::is_same_v<E2355::t, std::flat_multiset<int, std::less<>>::const_iterator>); // @E2355 ret
static_assert(!(true) || noexcept(std::declval<const std::flat_multiset<int, std::less<>>&>().cbegin())); // @E2355 noexcept
namespace E2356 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().cend()); } // @E2356 call
static_assert(std::is_same_v<E2356::t, std::flat_multiset<int, std::less<>>::const_iterator>); // @E2356 ret
static_assert(!(true) || noexcept(std::declval<const std::flat_multiset<int, std::less<>>&>().cend())); // @E2356 noexcept
namespace E2357 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().crbegin()); } // @E2357 call
static_assert(std::is_same_v<E2357::t, std::flat_multiset<int, std::less<>>::const_reverse_iterator>); // @E2357 ret
static_assert(!(true) || noexcept(std::declval<const std::flat_multiset<int, std::less<>>&>().crbegin())); // @E2357 noexcept
namespace E2358 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().crend()); } // @E2358 call
static_assert(std::is_same_v<E2358::t, std::flat_multiset<int, std::less<>>::const_reverse_iterator>); // @E2358 ret
static_assert(!(true) || noexcept(std::declval<const std::flat_multiset<int, std::less<>>&>().crend())); // @E2358 noexcept
namespace E2359 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().empty()); } // @E2359 call
static_assert(std::is_same_v<E2359::t, bool>); // @E2359 ret
static_assert(!(true) || noexcept(std::declval<const std::flat_multiset<int, std::less<>>&>().empty())); // @E2359 noexcept
namespace E2360 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().size()); } // @E2360 call
static_assert(std::is_same_v<E2360::t, std::flat_multiset<int, std::less<>>::size_type>); // @E2360 ret
static_assert(!(true) || noexcept(std::declval<const std::flat_multiset<int, std::less<>>&>().size())); // @E2360 noexcept
namespace E2361 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().max_size()); } // @E2361 call
static_assert(std::is_same_v<E2361::t, std::flat_multiset<int, std::less<>>::size_type>); // @E2361 ret
static_assert(!(true) || noexcept(std::declval<const std::flat_multiset<int, std::less<>>&>().max_size())); // @E2361 noexcept
namespace E2362 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().emplace(std::declval<int&&>())); } // @E2362 call
static_assert(std::is_same_v<E2362::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2362 ret
namespace E2363 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().emplace_hint(std::declval<std::flat_multiset<int, std::less<>>::const_iterator>(), std::declval<int&&>())); } // @E2363 call
static_assert(std::is_same_v<E2363::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2363 ret
namespace E2364 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().insert(std::declval<const std::flat_multiset<int, std::less<>>::value_type&>())); } // @E2364 call
static_assert(std::is_same_v<E2364::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2364 ret
namespace E2365 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().insert(std::declval<std::flat_multiset<int, std::less<>>::value_type&&>())); } // @E2365 call
static_assert(std::is_same_v<E2365::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2365 ret
namespace E2366 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().insert(std::declval<std::flat_multiset<int, std::less<>>::const_iterator>(), std::declval<const std::flat_multiset<int, std::less<>>::value_type&>())); } // @E2366 call
static_assert(std::is_same_v<E2366::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2366 ret
namespace E2367 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().insert(std::declval<std::flat_multiset<int, std::less<>>::const_iterator>(), std::declval<std::flat_multiset<int, std::less<>>::value_type&&>())); } // @E2367 call
static_assert(std::is_same_v<E2367::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2367 ret
namespace E2368 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().insert(std::declval<std::type_identity_t<int*>>(), std::declval<std::type_identity_t<int*>>())); } // @E2368 call
static_assert(std::is_same_v<E2368::t, void>); // @E2368 ret
namespace E2369 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().insert(std::declval<std::sorted_equivalent_t>(), std::declval<std::type_identity_t<int*>>(), std::declval<std::type_identity_t<int*>>())); } // @E2369 call
static_assert(std::is_same_v<E2369::t, void>); // @E2369 ret
namespace E2370 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().insert_range(std::declval<std::vector<int>&&>())); } // @E2370 call
static_assert(std::is_same_v<E2370::t, void>); // @E2370 ret
namespace E2371 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().insert_range(std::declval<std::sorted_equivalent_t>(), std::declval<std::vector<int>&&>())); } // @E2371 call
static_assert(std::is_same_v<E2371::t, void>); // @E2371 ret
namespace E2372 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().insert(std::declval<std::initializer_list<std::flat_multiset<int, std::less<>>::value_type>>())); } // @E2372 call
static_assert(std::is_same_v<E2372::t, void>); // @E2372 ret
namespace E2373 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().insert(std::declval<std::sorted_equivalent_t>(), std::declval<std::initializer_list<std::flat_multiset<int, std::less<>>::value_type>>())); } // @E2373 call
static_assert(std::is_same_v<E2373::t, void>); // @E2373 ret
namespace E2374 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&&>().extract()); } // @E2374 call
static_assert(std::is_same_v<E2374::t, std::flat_multiset<int, std::less<>>::container_type>); // @E2374 ret
namespace E2375 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().replace(std::declval<std::flat_multiset<int, std::less<>>::container_type&&>())); } // @E2375 call
static_assert(std::is_same_v<E2375::t, void>); // @E2375 ret
template<class D> concept E2376_call = requires { p2::dv<D, std::flat_multiset<int, std::less<>>&>().erase(p2::dv<D, std::flat_multiset<int, std::less<>>::iterator>()); }; static_assert(!((!std::same_as<std::flat_multiset<int, std::less<>>::iterator,std::flat_multiset<int, std::less<>>::const_iterator>)) || E2376_call<void>); // @E2376 call
template<class D> concept E2376_ret = requires { { p2::dv<D, std::flat_multiset<int, std::less<>>&>().erase(p2::dv<D, std::flat_multiset<int, std::less<>>::iterator>()) } -> std::same_as<std::flat_multiset<int, std::less<>>::iterator>; }; static_assert(!((!std::same_as<std::flat_multiset<int, std::less<>>::iterator,std::flat_multiset<int, std::less<>>::const_iterator>)) || E2376_ret<void>); // @E2376 ret
namespace E2377 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().erase(std::declval<std::flat_multiset<int, std::less<>>::const_iterator>())); } // @E2377 call
namespace E2378 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().erase(std::declval<const std::flat_multiset<int, std::less<>>::key_type&>())); } // @E2378 call
namespace E2379 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().erase(std::declval<long&&>())); } // @E2379 call
namespace E2380 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().erase(std::declval<std::flat_multiset<int, std::less<>>::const_iterator>(), std::declval<std::flat_multiset<int, std::less<>>::const_iterator>())); } // @E2380 call
static_assert(std::is_same_v<E2380::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2380 ret
namespace E2381 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().swap(std::declval<std::flat_multiset<int, std::less<>>&>())); } // @E2381 call
static_assert(std::is_same_v<E2381::t, void>); // @E2381 ret
namespace E2382 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().clear()); } // @E2382 call
static_assert(std::is_same_v<E2382::t, void>); // @E2382 ret
static_assert(!(true) || noexcept(std::declval<std::flat_multiset<int, std::less<>>&>().clear())); // @E2382 noexcept
namespace E2383 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().key_comp()); } // @E2383 call
static_assert(std::is_same_v<E2383::t, std::flat_multiset<int, std::less<>>::key_compare>); // @E2383 ret
namespace E2384 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().value_comp()); } // @E2384 call
static_assert(std::is_same_v<E2384::t, std::flat_multiset<int, std::less<>>::value_compare>); // @E2384 ret
namespace E2385 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().find(std::declval<const std::flat_multiset<int, std::less<>>::key_type&>())); } // @E2385 call
static_assert(std::is_same_v<E2385::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2385 ret
namespace E2386 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().find(std::declval<const std::flat_multiset<int, std::less<>>::key_type&>())); } // @E2386 call
static_assert(std::is_same_v<E2386::t, std::flat_multiset<int, std::less<>>::const_iterator>); // @E2386 ret
namespace E2387 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().find(std::declval<const long&>())); } // @E2387 call
static_assert(std::is_same_v<E2387::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2387 ret
namespace E2388 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().find(std::declval<const long&>())); } // @E2388 call
static_assert(std::is_same_v<E2388::t, std::flat_multiset<int, std::less<>>::const_iterator>); // @E2388 ret
namespace E2389 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().count(std::declval<const std::flat_multiset<int, std::less<>>::key_type&>())); } // @E2389 call
static_assert(std::is_same_v<E2389::t, std::flat_multiset<int, std::less<>>::size_type>); // @E2389 ret
namespace E2390 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().count(std::declval<const long&>())); } // @E2390 call
static_assert(std::is_same_v<E2390::t, std::flat_multiset<int, std::less<>>::size_type>); // @E2390 ret
namespace E2391 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().contains(std::declval<const std::flat_multiset<int, std::less<>>::key_type&>())); } // @E2391 call
static_assert(std::is_same_v<E2391::t, bool>); // @E2391 ret
namespace E2392 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().contains(std::declval<const long&>())); } // @E2392 call
static_assert(std::is_same_v<E2392::t, bool>); // @E2392 ret
namespace E2393 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().lower_bound(std::declval<const std::flat_multiset<int, std::less<>>::key_type&>())); } // @E2393 call
static_assert(std::is_same_v<E2393::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2393 ret
namespace E2394 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().lower_bound(std::declval<const std::flat_multiset<int, std::less<>>::key_type&>())); } // @E2394 call
static_assert(std::is_same_v<E2394::t, std::flat_multiset<int, std::less<>>::const_iterator>); // @E2394 ret
namespace E2395 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().lower_bound(std::declval<const long&>())); } // @E2395 call
static_assert(std::is_same_v<E2395::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2395 ret
namespace E2396 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().lower_bound(std::declval<const long&>())); } // @E2396 call
static_assert(std::is_same_v<E2396::t, std::flat_multiset<int, std::less<>>::const_iterator>); // @E2396 ret
namespace E2397 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().upper_bound(std::declval<const std::flat_multiset<int, std::less<>>::key_type&>())); } // @E2397 call
static_assert(std::is_same_v<E2397::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2397 ret
namespace E2398 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().upper_bound(std::declval<const std::flat_multiset<int, std::less<>>::key_type&>())); } // @E2398 call
static_assert(std::is_same_v<E2398::t, std::flat_multiset<int, std::less<>>::const_iterator>); // @E2398 ret
namespace E2399 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().upper_bound(std::declval<const long&>())); } // @E2399 call
static_assert(std::is_same_v<E2399::t, std::flat_multiset<int, std::less<>>::iterator>); // @E2399 ret
namespace E2400 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().upper_bound(std::declval<const long&>())); } // @E2400 call
static_assert(std::is_same_v<E2400::t, std::flat_multiset<int, std::less<>>::const_iterator>); // @E2400 ret
namespace E2401 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().equal_range(std::declval<const std::flat_multiset<int, std::less<>>::key_type&>())); } // @E2401 call
static_assert(std::is_same_v<E2401::t, std::pair<std::flat_multiset<int, std::less<>>::iterator,std::flat_multiset<int, std::less<>>::iterator>>); // @E2401 ret
namespace E2402 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().equal_range(std::declval<const std::flat_multiset<int, std::less<>>::key_type&>())); } // @E2402 call
static_assert(std::is_same_v<E2402::t, std::pair<std::flat_multiset<int, std::less<>>::const_iterator,std::flat_multiset<int, std::less<>>::const_iterator>>); // @E2402 ret
namespace E2403 { using t = decltype(std::declval<std::flat_multiset<int, std::less<>>&>().equal_range(std::declval<const long&>())); } // @E2403 call
static_assert(std::is_same_v<E2403::t, std::pair<std::flat_multiset<int, std::less<>>::iterator,std::flat_multiset<int, std::less<>>::iterator>>); // @E2403 ret
namespace E2404 { using t = decltype(std::declval<const std::flat_multiset<int, std::less<>>&>().equal_range(std::declval<const long&>())); } // @E2404 call
static_assert(std::is_same_v<E2404::t, std::pair<std::flat_multiset<int, std::less<>>::const_iterator,std::flat_multiset<int, std::less<>>::const_iterator>>); // @E2404 ret
namespace E2405 { using t = decltype(operator==(std::declval<const std::flat_multiset<int, std::less<>>&>(), std::declval<const std::flat_multiset<int, std::less<>>&>())); } // @E2405 call
static_assert(std::is_same_v<E2405::t, bool>); // @E2405 ret
namespace E2406 { using t = decltype(operator<=>(std::declval<const std::flat_multiset<int, std::less<>>&>(), std::declval<const std::flat_multiset<int, std::less<>>&>())); } // @E2406 call
namespace E2407 { using t = decltype(swap(std::declval<std::flat_multiset<int, std::less<>>&>(), std::declval<std::flat_multiset<int, std::less<>>&>())); } // @E2407 call
static_assert(std::is_same_v<E2407::t, void>); // @E2407 ret
static_assert(!(noexcept(std::declval<std::flat_multiset<int, std::less<>>&>().swap(std::declval<std::flat_multiset<int, std::less<>>&>()))) || noexcept(swap(std::declval<std::flat_multiset<int, std::less<>>&>(), std::declval<std::flat_multiset<int, std::less<>>&>()))); // @E2407 noexcept
static_assert(std::is_same_v<decltype(std::flat_multiset(std::declval<std::vector<int>>(), std::declval<std::less<>>())), std::flat_multiset<typename std::vector<int>::value_type,std::less<>,std::vector<int>>>); // @E2408 guide
static_assert(std::is_same_v<decltype(std::flat_multiset(std::declval<std::vector<int>>(), std::declval<std::allocator<int>>())), std::flat_multiset<typename std::vector<int>::value_type,std::less<typename std::vector<int>::value_type>,std::vector<int>>>); // @E2409 guide
static_assert(std::is_same_v<decltype(std::flat_multiset(std::declval<std::vector<int>>(), std::declval<std::less<>>(), std::declval<std::allocator<int>>())), std::flat_multiset<typename std::vector<int>::value_type,std::less<>,std::vector<int>>>); // @E2410 guide
static_assert(std::is_same_v<decltype(std::flat_multiset(std::declval<std::sorted_equivalent_t>(), std::declval<std::vector<int>>(), std::declval<std::less<>>())), std::flat_multiset<typename std::vector<int>::value_type,std::less<>,std::vector<int>>>); // @E2411 guide
static_assert(std::is_same_v<decltype(std::flat_multiset(std::declval<std::sorted_equivalent_t>(), std::declval<std::vector<int>>(), std::declval<std::allocator<int>>())), std::flat_multiset<typename std::vector<int>::value_type,std::less<typename std::vector<int>::value_type>,std::vector<int>>>); // @E2412 guide
static_assert(std::is_same_v<decltype(std::flat_multiset(std::declval<std::sorted_equivalent_t>(), std::declval<std::vector<int>>(), std::declval<std::less<>>(), std::declval<std::allocator<int>>())), std::flat_multiset<typename std::vector<int>::value_type,std::less<>,std::vector<int>>>); // @E2413 guide
static_assert(std::is_same_v<decltype(std::flat_multiset(std::declval<std::type_identity_t<int*>>(), std::declval<std::type_identity_t<int*>>(), std::declval<std::less<>>())), std::flat_multiset<std::iter_value_t<std::type_identity_t<int*>>,std::less<>>>); // @E2414 guide
static_assert(std::is_same_v<decltype(std::flat_multiset(std::declval<std::sorted_equivalent_t>(), std::declval<std::type_identity_t<int*>>(), std::declval<std::type_identity_t<int*>>(), std::declval<std::less<>>())), std::flat_multiset<std::iter_value_t<std::type_identity_t<int*>>,std::less<>>>); // @E2415 guide
static_assert(std::is_same_v<decltype(std::flat_multiset(std::declval<std::sorted_equivalent_t>(), std::declval<std::initializer_list<int>>(), std::declval<std::less<>>())), std::flat_multiset<int,std::less<>>>); // @E2419 guide
