// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [forward.list.overview] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
namespace E157 { using std::forward_list; } // @E157 name
struct E158 : std::forward_list<int> { using std::forward_list<int>::value_type; }; // @E158 name
static_assert(std::is_same_v<std::forward_list<int>::value_type, int>); // @E158 type
struct E159 : std::forward_list<int> { using std::forward_list<int>::allocator_type; }; // @E159 name
static_assert(std::is_same_v<std::forward_list<int>::allocator_type, std::allocator<int>>); // @E159 type
struct E160 : std::forward_list<int> { using std::forward_list<int>::pointer; }; // @E160 name
static_assert(std::is_same_v<std::forward_list<int>::pointer, std::allocator_traits<std::allocator<int>>::pointer>); // @E160 type
struct E161 : std::forward_list<int> { using std::forward_list<int>::const_pointer; }; // @E161 name
static_assert(std::is_same_v<std::forward_list<int>::const_pointer, std::allocator_traits<std::allocator<int>>::const_pointer>); // @E161 type
struct E162 : std::forward_list<int> { using std::forward_list<int>::reference; }; // @E162 name
static_assert(std::is_same_v<std::forward_list<int>::reference, std::forward_list<int>::value_type&>); // @E162 type
struct E163 : std::forward_list<int> { using std::forward_list<int>::const_reference; }; // @E163 name
static_assert(std::is_same_v<std::forward_list<int>::const_reference, const std::forward_list<int>::value_type&>); // @E163 type
struct E164 : std::forward_list<int> { using std::forward_list<int>::size_type; }; // @E164 name
struct E165 : std::forward_list<int> { using std::forward_list<int>::difference_type; }; // @E165 name
struct E166 : std::forward_list<int> { using std::forward_list<int>::iterator; }; // @E166 name
struct E167 : std::forward_list<int> { using std::forward_list<int>::const_iterator; }; // @E167 name
static_assert(std::is_constructible_v<std::forward_list<int>>); // @E168 call
static_assert(std::is_constructible_v<std::forward_list<int>, const std::allocator<int>&>); // @E169 call
static_assert(!std::is_convertible_v<const std::allocator<int>&, std::forward_list<int>>); // @E169 explicit
static_assert(std::is_constructible_v<std::forward_list<int>, std::forward_list<int>::size_type, const std::allocator<int>&>); // @E170 call
static_assert(std::is_constructible_v<std::forward_list<int>, std::forward_list<int>::size_type>); // @E170 defaults
static_assert(!std::is_convertible_v<std::forward_list<int>::size_type, std::forward_list<int>>); // @E170 explicit
static_assert(std::is_constructible_v<std::forward_list<int>, std::forward_list<int>::size_type, const int&, const std::allocator<int>&>); // @E171 call
static_assert(std::is_constructible_v<std::forward_list<int>, std::forward_list<int>::size_type, const int&>); // @E171 defaults
static_assert(std::is_constructible_v<std::forward_list<int>, std::type_identity_t<int*>, std::type_identity_t<int*>, const std::allocator<int>&>); // @E172 call
static_assert(std::is_constructible_v<std::forward_list<int>, std::type_identity_t<int*>, std::type_identity_t<int*>>); // @E172 defaults
static_assert(std::is_constructible_v<std::forward_list<int>, std::from_range_t, std::vector<int>&&, const std::allocator<int>&>); // @E173 call
static_assert(std::is_constructible_v<std::forward_list<int>, std::from_range_t, std::vector<int>&&>); // @E173 defaults
static_assert(std::is_constructible_v<std::forward_list<int>, const std::forward_list<int>&>); // @E174 call
static_assert(std::is_convertible_v<const std::forward_list<int>&, std::forward_list<int>>); // @E174 implicit
static_assert(std::is_constructible_v<std::forward_list<int>, std::forward_list<int>&&>); // @E175 call
static_assert(std::is_convertible_v<std::forward_list<int>&&, std::forward_list<int>>); // @E175 implicit
static_assert(std::is_constructible_v<std::forward_list<int>, const std::forward_list<int>&, const std::type_identity_t<std::allocator<int>>&>); // @E176 call
static_assert(std::is_constructible_v<std::forward_list<int>, std::forward_list<int>&&, const std::type_identity_t<std::allocator<int>>&>); // @E177 call
static_assert(std::is_nothrow_destructible_v<std::forward_list<int>>); // @E179 noexcept
namespace E180 { using t = decltype(std::declval<std::forward_list<int>&>().operator=(std::declval<const std::forward_list<int>&>())); } // @E180 call
static_assert(std::is_same_v<E180::t, std::forward_list<int>&>); // @E180 ret
namespace E181 { using t = decltype(std::declval<std::forward_list<int>&>().operator=(std::declval<std::forward_list<int>&&>())); } // @E181 call
static_assert(std::is_same_v<E181::t, std::forward_list<int>&>); // @E181 ret
static_assert(!(std::allocator_traits<std::allocator<int>>::is_always_equal::value) || noexcept(std::declval<std::forward_list<int>&>().operator=(std::declval<std::forward_list<int>&&>()))); // @E181 noexcept
namespace E183 { using t = decltype(std::declval<std::forward_list<int>&>().assign(std::declval<std::type_identity_t<int*>>(), std::declval<std::type_identity_t<int*>>())); } // @E183 call
static_assert(std::is_same_v<E183::t, void>); // @E183 ret
namespace E184 { using t = decltype(std::declval<std::forward_list<int>&>().assign_range(std::declval<std::vector<int>&&>())); } // @E184 call
static_assert(std::is_same_v<E184::t, void>); // @E184 ret
namespace E185 { using t = decltype(std::declval<std::forward_list<int>&>().assign(std::declval<std::forward_list<int>::size_type>(), std::declval<const int&>())); } // @E185 call
static_assert(std::is_same_v<E185::t, void>); // @E185 ret
namespace E187 { using t = decltype(std::declval<const std::forward_list<int>&>().get_allocator()); } // @E187 call
static_assert(std::is_same_v<E187::t, std::forward_list<int>::allocator_type>); // @E187 ret
static_assert(!(true) || noexcept(std::declval<const std::forward_list<int>&>().get_allocator())); // @E187 noexcept
namespace E188 { using t = decltype(std::declval<std::forward_list<int>&>().before_begin()); } // @E188 call
static_assert(std::is_same_v<E188::t, std::forward_list<int>::iterator>); // @E188 ret
static_assert(!(true) || noexcept(std::declval<std::forward_list<int>&>().before_begin())); // @E188 noexcept
namespace E189 { using t = decltype(std::declval<const std::forward_list<int>&>().before_begin()); } // @E189 call
static_assert(std::is_same_v<E189::t, std::forward_list<int>::const_iterator>); // @E189 ret
static_assert(!(true) || noexcept(std::declval<const std::forward_list<int>&>().before_begin())); // @E189 noexcept
namespace E190 { using t = decltype(std::declval<std::forward_list<int>&>().begin()); } // @E190 call
static_assert(std::is_same_v<E190::t, std::forward_list<int>::iterator>); // @E190 ret
static_assert(!(true) || noexcept(std::declval<std::forward_list<int>&>().begin())); // @E190 noexcept
namespace E191 { using t = decltype(std::declval<const std::forward_list<int>&>().begin()); } // @E191 call
static_assert(std::is_same_v<E191::t, std::forward_list<int>::const_iterator>); // @E191 ret
static_assert(!(true) || noexcept(std::declval<const std::forward_list<int>&>().begin())); // @E191 noexcept
namespace E192 { using t = decltype(std::declval<std::forward_list<int>&>().end()); } // @E192 call
static_assert(std::is_same_v<E192::t, std::forward_list<int>::iterator>); // @E192 ret
static_assert(!(true) || noexcept(std::declval<std::forward_list<int>&>().end())); // @E192 noexcept
namespace E193 { using t = decltype(std::declval<const std::forward_list<int>&>().end()); } // @E193 call
static_assert(std::is_same_v<E193::t, std::forward_list<int>::const_iterator>); // @E193 ret
static_assert(!(true) || noexcept(std::declval<const std::forward_list<int>&>().end())); // @E193 noexcept
namespace E194 { using t = decltype(std::declval<const std::forward_list<int>&>().cbegin()); } // @E194 call
static_assert(std::is_same_v<E194::t, std::forward_list<int>::const_iterator>); // @E194 ret
static_assert(!(true) || noexcept(std::declval<const std::forward_list<int>&>().cbegin())); // @E194 noexcept
namespace E195 { using t = decltype(std::declval<const std::forward_list<int>&>().cbefore_begin()); } // @E195 call
static_assert(std::is_same_v<E195::t, std::forward_list<int>::const_iterator>); // @E195 ret
static_assert(!(true) || noexcept(std::declval<const std::forward_list<int>&>().cbefore_begin())); // @E195 noexcept
namespace E196 { using t = decltype(std::declval<const std::forward_list<int>&>().cend()); } // @E196 call
static_assert(std::is_same_v<E196::t, std::forward_list<int>::const_iterator>); // @E196 ret
static_assert(!(true) || noexcept(std::declval<const std::forward_list<int>&>().cend())); // @E196 noexcept
namespace E197 { using t = decltype(std::declval<const std::forward_list<int>&>().empty()); } // @E197 call
static_assert(std::is_same_v<E197::t, bool>); // @E197 ret
static_assert(!(true) || noexcept(std::declval<const std::forward_list<int>&>().empty())); // @E197 noexcept
namespace E198 { using t = decltype(std::declval<const std::forward_list<int>&>().max_size()); } // @E198 call
static_assert(std::is_same_v<E198::t, std::forward_list<int>::size_type>); // @E198 ret
static_assert(!(true) || noexcept(std::declval<const std::forward_list<int>&>().max_size())); // @E198 noexcept
namespace E199 { using t = decltype(std::declval<std::forward_list<int>&>().front()); } // @E199 call
static_assert(std::is_same_v<E199::t, std::forward_list<int>::reference>); // @E199 ret
namespace E200 { using t = decltype(std::declval<const std::forward_list<int>&>().front()); } // @E200 call
static_assert(std::is_same_v<E200::t, std::forward_list<int>::const_reference>); // @E200 ret
namespace E201 { using t = decltype(std::declval<std::forward_list<int>&>().emplace_front(std::declval<int&&>())); } // @E201 call
static_assert(std::is_same_v<E201::t, std::forward_list<int>::reference>); // @E201 ret
namespace E202 { using t = decltype(std::declval<std::forward_list<int>&>().push_front(std::declval<const int&>())); } // @E202 call
static_assert(std::is_same_v<E202::t, void>); // @E202 ret
namespace E203 { using t = decltype(std::declval<std::forward_list<int>&>().push_front(std::declval<int&&>())); } // @E203 call
static_assert(std::is_same_v<E203::t, void>); // @E203 ret
namespace E204 { using t = decltype(std::declval<std::forward_list<int>&>().prepend_range(std::declval<std::vector<int>&&>())); } // @E204 call
static_assert(std::is_same_v<E204::t, void>); // @E204 ret
namespace E205 { using t = decltype(std::declval<std::forward_list<int>&>().pop_front()); } // @E205 call
static_assert(std::is_same_v<E205::t, void>); // @E205 ret
namespace E206 { using t = decltype(std::declval<std::forward_list<int>&>().emplace_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<int&&>())); } // @E206 call
static_assert(std::is_same_v<E206::t, std::forward_list<int>::iterator>); // @E206 ret
namespace E207 { using t = decltype(std::declval<std::forward_list<int>&>().insert_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<const int&>())); } // @E207 call
static_assert(std::is_same_v<E207::t, std::forward_list<int>::iterator>); // @E207 ret
namespace E208 { using t = decltype(std::declval<std::forward_list<int>&>().insert_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<int&&>())); } // @E208 call
static_assert(std::is_same_v<E208::t, std::forward_list<int>::iterator>); // @E208 ret
namespace E209 { using t = decltype(std::declval<std::forward_list<int>&>().insert_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<std::forward_list<int>::size_type>(), std::declval<const int&>())); } // @E209 call
static_assert(std::is_same_v<E209::t, std::forward_list<int>::iterator>); // @E209 ret
namespace E210 { using t = decltype(std::declval<std::forward_list<int>&>().insert_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<std::type_identity_t<int*>>(), std::declval<std::type_identity_t<int*>>())); } // @E210 call
static_assert(std::is_same_v<E210::t, std::forward_list<int>::iterator>); // @E210 ret
namespace E211 { using t = decltype(std::declval<std::forward_list<int>&>().insert_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<std::initializer_list<int>>())); } // @E211 call
static_assert(std::is_same_v<E211::t, std::forward_list<int>::iterator>); // @E211 ret
namespace E212 { using t = decltype(std::declval<std::forward_list<int>&>().insert_range_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<std::vector<int>&&>())); } // @E212 call
static_assert(std::is_same_v<E212::t, std::forward_list<int>::iterator>); // @E212 ret
namespace E213 { using t = decltype(std::declval<std::forward_list<int>&>().erase_after(std::declval<std::forward_list<int>::const_iterator>())); } // @E213 call
static_assert(std::is_same_v<E213::t, std::forward_list<int>::iterator>); // @E213 ret
namespace E214 { using t = decltype(std::declval<std::forward_list<int>&>().erase_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<std::forward_list<int>::const_iterator>())); } // @E214 call
static_assert(std::is_same_v<E214::t, std::forward_list<int>::iterator>); // @E214 ret
namespace E215 { using t = decltype(std::declval<std::forward_list<int>&>().swap(std::declval<std::forward_list<int>&>())); } // @E215 call
static_assert(std::is_same_v<E215::t, void>); // @E215 ret
static_assert(!(std::allocator_traits<std::allocator<int>>::is_always_equal::value) || noexcept(std::declval<std::forward_list<int>&>().swap(std::declval<std::forward_list<int>&>()))); // @E215 noexcept
namespace E216 { using t = decltype(std::declval<std::forward_list<int>&>().resize(std::declval<std::forward_list<int>::size_type>())); } // @E216 call
static_assert(std::is_same_v<E216::t, void>); // @E216 ret
namespace E217 { using t = decltype(std::declval<std::forward_list<int>&>().resize(std::declval<std::forward_list<int>::size_type>(), std::declval<const std::forward_list<int>::value_type&>())); } // @E217 call
static_assert(std::is_same_v<E217::t, void>); // @E217 ret
namespace E218 { using t = decltype(std::declval<std::forward_list<int>&>().clear()); } // @E218 call
static_assert(std::is_same_v<E218::t, void>); // @E218 ret
static_assert(!(true) || noexcept(std::declval<std::forward_list<int>&>().clear())); // @E218 noexcept
namespace E219 { using t = decltype(std::declval<std::forward_list<int>&>().splice_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<std::forward_list<int>&>())); } // @E219 call
static_assert(std::is_same_v<E219::t, void>); // @E219 ret
namespace E220 { using t = decltype(std::declval<std::forward_list<int>&>().splice_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<std::forward_list<int>&&>())); } // @E220 call
static_assert(std::is_same_v<E220::t, void>); // @E220 ret
namespace E221 { using t = decltype(std::declval<std::forward_list<int>&>().splice_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<std::forward_list<int>&>(), std::declval<std::forward_list<int>::const_iterator>())); } // @E221 call
static_assert(std::is_same_v<E221::t, void>); // @E221 ret
namespace E222 { using t = decltype(std::declval<std::forward_list<int>&>().splice_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<std::forward_list<int>&&>(), std::declval<std::forward_list<int>::const_iterator>())); } // @E222 call
static_assert(std::is_same_v<E222::t, void>); // @E222 ret
namespace E223 { using t = decltype(std::declval<std::forward_list<int>&>().splice_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<std::forward_list<int>&>(), std::declval<std::forward_list<int>::const_iterator>(), std::declval<std::forward_list<int>::const_iterator>())); } // @E223 call
static_assert(std::is_same_v<E223::t, void>); // @E223 ret
namespace E224 { using t = decltype(std::declval<std::forward_list<int>&>().splice_after(std::declval<std::forward_list<int>::const_iterator>(), std::declval<std::forward_list<int>&&>(), std::declval<std::forward_list<int>::const_iterator>(), std::declval<std::forward_list<int>::const_iterator>())); } // @E224 call
static_assert(std::is_same_v<E224::t, void>); // @E224 ret
namespace E225 { using t = decltype(std::declval<std::forward_list<int>&>().remove(std::declval<const int&>())); } // @E225 call
static_assert(std::is_same_v<E225::t, std::forward_list<int>::size_type>); // @E225 ret
namespace E226 { using t = decltype(std::declval<std::forward_list<int>&>().remove_if(std::declval<p2::AnyFn>())); } // @E226 call
static_assert(std::is_same_v<E226::t, std::forward_list<int>::size_type>); // @E226 ret
namespace E227 { using t = decltype(std::declval<std::forward_list<int>&>().unique()); } // @E227 call
static_assert(std::is_same_v<E227::t, std::forward_list<int>::size_type>); // @E227 ret
namespace E228 { using t = decltype(std::declval<std::forward_list<int>&>().unique(std::declval<p2::AnyFn>())); } // @E228 call
static_assert(std::is_same_v<E228::t, std::forward_list<int>::size_type>); // @E228 ret
namespace E229 { using t = decltype(std::declval<std::forward_list<int>&>().merge(std::declval<std::forward_list<int>&>())); } // @E229 call
static_assert(std::is_same_v<E229::t, void>); // @E229 ret
namespace E230 { using t = decltype(std::declval<std::forward_list<int>&>().merge(std::declval<std::forward_list<int>&&>())); } // @E230 call
static_assert(std::is_same_v<E230::t, void>); // @E230 ret
namespace E231 { using t = decltype(std::declval<std::forward_list<int>&>().merge(std::declval<std::forward_list<int>&>(), std::declval<p2::AnyFn>())); } // @E231 call
static_assert(std::is_same_v<E231::t, void>); // @E231 ret
namespace E232 { using t = decltype(std::declval<std::forward_list<int>&>().merge(std::declval<std::forward_list<int>&&>(), std::declval<p2::AnyFn>())); } // @E232 call
static_assert(std::is_same_v<E232::t, void>); // @E232 ret
namespace E233 { using t = decltype(std::declval<std::forward_list<int>&>().sort()); } // @E233 call
static_assert(std::is_same_v<E233::t, void>); // @E233 ret
namespace E234 { using t = decltype(std::declval<std::forward_list<int>&>().sort(std::declval<p2::AnyFn>())); } // @E234 call
static_assert(std::is_same_v<E234::t, void>); // @E234 ret
namespace E235 { using t = decltype(std::declval<std::forward_list<int>&>().reverse()); } // @E235 call
static_assert(std::is_same_v<E235::t, void>); // @E235 ret
static_assert(!(true) || noexcept(std::declval<std::forward_list<int>&>().reverse())); // @E235 noexcept
static_assert(std::is_same_v<decltype(std::forward_list(std::declval<std::type_identity_t<int*>>(), std::declval<std::type_identity_t<int*>>(), std::declval<std::allocator<int>>())), std::forward_list<std::iter_value_t<std::type_identity_t<int*>>,std::allocator<int>>>); // @E236 guide
static_assert(std::is_same_v<decltype(std::forward_list(std::declval<std::from_range_t>(), std::declval<std::vector<int>&&>(), std::declval<std::allocator<int>>())), std::forward_list<std::ranges::range_value_t<std::vector<int>>,std::allocator<int>>>); // @E237 guide
