// Generated by tools/spec_audit/gen_probes.py; do not edit. Names of [generator.syn] with only <generator> included.
#include <generator>
namespace E4548_h { using std::generator; } // @E4548 header
namespace E4549_h { using std::pmr::generator; } // @E4549 header
