// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [mdspan.accessor.aligned.overview] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
namespace E2675 { using std::aligned_accessor; } // @E2675 name
struct E2676 : std::aligned_accessor<int, 16> { using std::aligned_accessor<int, 16>::offset_policy; }; // @E2676 name
static_assert(std::is_same_v<std::aligned_accessor<int, 16>::offset_policy, std::default_accessor<int>>); // @E2676 type
struct E2677 : std::aligned_accessor<int, 16> { using std::aligned_accessor<int, 16>::element_type; }; // @E2677 name
static_assert(std::is_same_v<std::aligned_accessor<int, 16>::element_type, int>); // @E2677 type
struct E2678 : std::aligned_accessor<int, 16> { using std::aligned_accessor<int, 16>::reference; }; // @E2678 name
static_assert(std::is_same_v<std::aligned_accessor<int, 16>::reference, int&>); // @E2678 type
struct E2679 : std::aligned_accessor<int, 16> { using std::aligned_accessor<int, 16>::data_handle_type; }; // @E2679 name
static_assert(std::is_same_v<std::aligned_accessor<int, 16>::data_handle_type, int*>); // @E2679 type
struct E2680 : std::aligned_accessor<int, 16> { using std::aligned_accessor<int, 16>::byte_alignment; }; // @E2680 name
static_assert(requires { sizeof(std::aligned_accessor<int, 16>); }); // @E2681 name
static_assert(std::is_constructible_v<std::aligned_accessor<int, 16>, std::aligned_accessor<int,16>>); // @E2682 call
static_assert(!(true) || std::is_nothrow_constructible_v<std::aligned_accessor<int, 16>, std::aligned_accessor<int,16>>); // @E2682 noexcept
static_assert(std::is_convertible_v<std::aligned_accessor<int,16>, std::aligned_accessor<int, 16>>); // @E2682 implicit
static_assert(std::is_constructible_v<std::aligned_accessor<int, 16>, std::default_accessor<int>>); // @E2683 call
static_assert(!(true) || std::is_nothrow_constructible_v<std::aligned_accessor<int, 16>, std::default_accessor<int>>); // @E2683 noexcept
static_assert(!std::is_convertible_v<std::default_accessor<int>, std::aligned_accessor<int, 16>>); // @E2683 explicit
namespace E2685 { using t = decltype(std::declval<const std::aligned_accessor<int, 16>&>().access(std::declval<std::aligned_accessor<int, 16>::data_handle_type>(), std::declval<std::size_t>())); } // @E2685 call
static_assert(std::is_same_v<E2685::t, std::aligned_accessor<int, 16>::reference>); // @E2685 ret
static_assert(!(true) || noexcept(std::declval<const std::aligned_accessor<int, 16>&>().access(std::declval<std::aligned_accessor<int, 16>::data_handle_type>(), std::declval<std::size_t>()))); // @E2685 noexcept
namespace E2686 { using t = decltype(std::declval<const std::aligned_accessor<int, 16>&>().offset(std::declval<std::aligned_accessor<int, 16>::data_handle_type>(), std::declval<std::size_t>())); } // @E2686 call
static_assert(std::is_same_v<E2686::t, std::aligned_accessor<int, 16>::offset_policy::data_handle_type>); // @E2686 ret
static_assert(!(true) || noexcept(std::declval<const std::aligned_accessor<int, 16>&>().offset(std::declval<std::aligned_accessor<int, 16>::data_handle_type>(), std::declval<std::size_t>()))); // @E2686 noexcept
