// Generated by tools/spec_audit/gen_probes.py; do not edit. Freestanding names of [mdspan.syn]
// (-ffreestanding, [compliance]).
#include <mdspan>
namespace E2482_f { using std::extents; } // @E2482 freestanding
namespace E2483_f { using std::dextents; } // @E2483 freestanding
namespace E2484_f { using std::dims; } // @E2484 freestanding
namespace E2485_f { using std::layout_left; } // @E2485 freestanding
namespace E2486_f { using std::layout_right; } // @E2486 freestanding
namespace E2487_f { using std::layout_stride; } // @E2487 freestanding
namespace E2488_f { using std::layout_left_padded; } // @E2488 freestanding
namespace E2489_f { using std::layout_right_padded; } // @E2489 freestanding
namespace E2490_f { using std::default_accessor; } // @E2490 freestanding
namespace E2491_f { using std::aligned_accessor; } // @E2491 freestanding
namespace E2492_f { using std::mdspan; } // @E2492 freestanding
namespace E2493_f { using std::extent_slice; } // @E2493 freestanding
namespace E2494_f { using std::range_slice; } // @E2494 freestanding
namespace E2495_f { using std::submdspan_mapping_result; } // @E2495 freestanding
namespace E2496_f { using std::full_extent_t; } // @E2496 freestanding
namespace E2498_f { using std::full_extent; } // @E2498 freestanding
namespace E2499_f { using std::subextents; } // @E2499 freestanding
namespace E2500_f { using std::canonical_slices; } // @E2500 freestanding
namespace E2501_f { using std::submdspan; } // @E2501 freestanding
namespace E2502_f { using std::copy; } // @E2502 freestanding
namespace E2503_f { using std::copy; } // @E2503 freestanding
namespace E2504_f { using std::fill; } // @E2504 freestanding
namespace E2505_f { using std::fill; } // @E2505 freestanding
