// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [multiset.overview] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
namespace E1086 { using std::multiset; } // @E1086 name
struct E1087 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::key_type; }; // @E1087 name
static_assert(std::is_same_v<std::multiset<int, std::less<>>::key_type, int>); // @E1087 type
struct E1088 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::key_compare; }; // @E1088 name
static_assert(std::is_same_v<std::multiset<int, std::less<>>::key_compare, std::less<>>); // @E1088 type
struct E1089 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::value_type; }; // @E1089 name
static_assert(std::is_same_v<std::multiset<int, std::less<>>::value_type, int>); // @E1089 type
struct E1090 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::value_compare; }; // @E1090 name
static_assert(std::is_same_v<std::multiset<int, std::less<>>::value_compare, std::less<>>); // @E1090 type
struct E1091 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::allocator_type; }; // @E1091 name
static_assert(std::is_same_v<std::multiset<int, std::less<>>::allocator_type, std::allocator<int>>); // @E1091 type
struct E1092 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::pointer; }; // @E1092 name
static_assert(std::is_same_v<std::multiset<int, std::less<>>::pointer, std::allocator_traits<std::allocator<int>>::pointer>); // @E1092 type
struct E1093 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::const_pointer; }; // @E1093 name
static_assert(std::is_same_v<std::multiset<int, std::less<>>::const_pointer, std::allocator_traits<std::allocator<int>>::const_pointer>); // @E1093 type
struct E1094 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::reference; }; // @E1094 name
static_assert(std::is_same_v<std::multiset<int, std::less<>>::reference, std::multiset<int, std::less<>>::value_type&>); // @E1094 type
struct E1095 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::const_reference; }; // @E1095 name
static_assert(std::is_same_v<std::multiset<int, std::less<>>::const_reference, const std::multiset<int, std::less<>>::value_type&>); // @E1095 type
struct E1096 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::size_type; }; // @E1096 name
struct E1097 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::difference_type; }; // @E1097 name
struct E1098 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::iterator; }; // @E1098 name
struct E1099 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::const_iterator; }; // @E1099 name
struct E1100 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::reverse_iterator; }; // @E1100 name
static_assert(std::is_same_v<std::multiset<int, std::less<>>::reverse_iterator, std::reverse_iterator<std::multiset<int, std::less<>>::iterator>>); // @E1100 type
struct E1101 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::const_reverse_iterator; }; // @E1101 name
static_assert(std::is_same_v<std::multiset<int, std::less<>>::const_reverse_iterator, std::reverse_iterator<std::multiset<int, std::less<>>::const_iterator>>); // @E1101 type
struct E1102 : std::multiset<int, std::less<>> { using std::multiset<int, std::less<>>::node_type; }; // @E1102 name
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>>); // @E1103 call
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, const std::less<>&, const std::allocator<int>&>); // @E1104 call
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, const std::less<>&>); // @E1104 defaults
static_assert(!std::is_convertible_v<const std::less<>&, std::multiset<int, std::less<>>>); // @E1104 explicit
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, std::type_identity_t<int*>, std::type_identity_t<int*>, const std::less<>&, const std::allocator<int>&>); // @E1105 call
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, std::type_identity_t<int*>, std::type_identity_t<int*>>); // @E1105 defaults
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, std::from_range_t, std::vector<int>&&, const std::less<>&, const std::allocator<int>&>); // @E1106 call
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, std::from_range_t, std::vector<int>&&>); // @E1106 defaults
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, const std::multiset<int, std::less<>>&>); // @E1107 call
static_assert(std::is_convertible_v<const std::multiset<int, std::less<>>&, std::multiset<int, std::less<>>>); // @E1107 implicit
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, std::multiset<int, std::less<>>&&>); // @E1108 call
static_assert(std::is_convertible_v<std::multiset<int, std::less<>>&&, std::multiset<int, std::less<>>>); // @E1108 implicit
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, const std::allocator<int>&>); // @E1109 call
static_assert(!std::is_convertible_v<const std::allocator<int>&, std::multiset<int, std::less<>>>); // @E1109 explicit
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, const std::multiset<int, std::less<>>&, const std::type_identity_t<std::allocator<int>>&>); // @E1110 call
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, std::multiset<int, std::less<>>&&, const std::type_identity_t<std::allocator<int>>&>); // @E1111 call
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, std::initializer_list<std::multiset<int, std::less<>>::value_type>, const std::less<>&, const std::allocator<int>&>); // @E1112 call
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, std::initializer_list<std::multiset<int, std::less<>>::value_type>>); // @E1112 defaults
static_assert(std::is_convertible_v<std::initializer_list<std::multiset<int, std::less<>>::value_type>, std::multiset<int, std::less<>>>); // @E1112 implicit
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, std::type_identity_t<int*>, std::type_identity_t<int*>, const std::allocator<int>&>); // @E1113 call
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, std::from_range_t, std::vector<int>&&, const std::allocator<int>&>); // @E1114 call
static_assert(std::is_constructible_v<std::multiset<int, std::less<>>, std::initializer_list<std::multiset<int, std::less<>>::value_type>, const std::allocator<int>&>); // @E1115 call
static_assert(std::is_nothrow_destructible_v<std::multiset<int, std::less<>>>); // @E1116 noexcept
namespace E1117 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().operator=(std::declval<const std::multiset<int, std::less<>>&>())); } // @E1117 call
static_assert(std::is_same_v<E1117::t, std::multiset<int, std::less<>>&>); // @E1117 ret
namespace E1118 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().operator=(std::declval<std::multiset<int, std::less<>>&&>())); } // @E1118 call
static_assert(std::is_same_v<E1118::t, std::multiset<int, std::less<>>&>); // @E1118 ret
static_assert(!(std::allocator_traits<std::allocator<int>>::is_always_equal::value&&std::is_nothrow_move_assignable_v<std::less<>>) || noexcept(std::declval<std::multiset<int, std::less<>>&>().operator=(std::declval<std::multiset<int, std::less<>>&&>()))); // @E1118 noexcept
namespace E1119 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().operator=(std::declval<std::initializer_list<std::multiset<int, std::less<>>::value_type>>())); } // @E1119 call
static_assert(std::is_same_v<E1119::t, std::multiset<int, std::less<>>&>); // @E1119 ret
namespace E1120 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().get_allocator()); } // @E1120 call
static_assert(std::is_same_v<E1120::t, std::multiset<int, std::less<>>::allocator_type>); // @E1120 ret
static_assert(!(true) || noexcept(std::declval<const std::multiset<int, std::less<>>&>().get_allocator())); // @E1120 noexcept
namespace E1121 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().begin()); } // @E1121 call
static_assert(std::is_same_v<E1121::t, std::multiset<int, std::less<>>::iterator>); // @E1121 ret
static_assert(!(true) || noexcept(std::declval<std::multiset<int, std::less<>>&>().begin())); // @E1121 noexcept
namespace E1122 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().begin()); } // @E1122 call
static_assert(std::is_same_v<E1122::t, std::multiset<int, std::less<>>::const_iterator>); // @E1122 ret
static_assert(!(true) || noexcept(std::declval<const std::multiset<int, std::less<>>&>().begin())); // @E1122 noexcept
namespace E1123 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().end()); } // @E1123 call
static_assert(std::is_same_v<E1123::t, std::multiset<int, std::less<>>::iterator>); // @E1123 ret
static_assert(!(true) || noexcept(std::declval<std::multiset<int, std::less<>>&>().end())); // @E1123 noexcept
namespace E1124 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().end()); } // @E1124 call
static_assert(std::is_same_v<E1124::t, std::multiset<int, std::less<>>::const_iterator>); // @E1124 ret
static_assert(!(true) || noexcept(std::declval<const std::multiset<int, std::less<>>&>().end())); // @E1124 noexcept
namespace E1125 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().rbegin()); } // @E1125 call
static_assert(std::is_same_v<E1125::t, std::multiset<int, std::less<>>::reverse_iterator>); // @E1125 ret
static_assert(!(true) || noexcept(std::declval<std::multiset<int, std::less<>>&>().rbegin())); // @E1125 noexcept
namespace E1126 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().rbegin()); } // @E1126 call
static_assert(std::is_same_v<E1126::t, std::multiset<int, std::less<>>::const_reverse_iterator>); // @E1126 ret
static_assert(!(true) || noexcept(std::declval<const std::multiset<int, std::less<>>&>().rbegin())); // @E1126 noexcept
namespace E1127 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().rend()); } // @E1127 call
static_assert(std::is_same_v<E1127::t, std::multiset<int, std::less<>>::reverse_iterator>); // @E1127 ret
static_assert(!(true) || noexcept(std::declval<std::multiset<int, std::less<>>&>().rend())); // @E1127 noexcept
namespace E1128 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().rend()); } // @E1128 call
static_assert(std::is_same_v<E1128::t, std::multiset<int, std::less<>>::const_reverse_iterator>); // @E1128 ret
static_assert(!(true) || noexcept(std::declval<const std::multiset<int, std::less<>>&>().rend())); // @E1128 noexcept
namespace E1129 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().cbegin()); } // @E1129 call
static_assert(std::is_same_v<E1129::t, std::multiset<int, std::less<>>::const_iterator>); // @E1129 ret
static_assert(!(true) || noexcept(std::declval<const std::multiset<int, std::less<>>&>().cbegin())); // @E1129 noexcept
namespace E1130 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().cend()); } // @E1130 call
static_assert(std::is_same_v<E1130::t, std::multiset<int, std::less<>>::const_iterator>); // @E1130 ret
static_assert(!(true) || noexcept(std::declval<const std::multiset<int, std::less<>>&>().cend())); // @E1130 noexcept
namespace E1131 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().crbegin()); } // @E1131 call
static_assert(std::is_same_v<E1131::t, std::multiset<int, std::less<>>::const_reverse_iterator>); // @E1131 ret
static_assert(!(true) || noexcept(std::declval<const std::multiset<int, std::less<>>&>().crbegin())); // @E1131 noexcept
namespace E1132 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().crend()); } // @E1132 call
static_assert(std::is_same_v<E1132::t, std::multiset<int, std::less<>>::const_reverse_iterator>); // @E1132 ret
static_assert(!(true) || noexcept(std::declval<const std::multiset<int, std::less<>>&>().crend())); // @E1132 noexcept
namespace E1133 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().empty()); } // @E1133 call
static_assert(std::is_same_v<E1133::t, bool>); // @E1133 ret
static_assert(!(true) || noexcept(std::declval<const std::multiset<int, std::less<>>&>().empty())); // @E1133 noexcept
namespace E1134 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().size()); } // @E1134 call
static_assert(std::is_same_v<E1134::t, std::multiset<int, std::less<>>::size_type>); // @E1134 ret
static_assert(!(true) || noexcept(std::declval<const std::multiset<int, std::less<>>&>().size())); // @E1134 noexcept
namespace E1135 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().max_size()); } // @E1135 call
static_assert(std::is_same_v<E1135::t, std::multiset<int, std::less<>>::size_type>); // @E1135 ret
static_assert(!(true) || noexcept(std::declval<const std::multiset<int, std::less<>>&>().max_size())); // @E1135 noexcept
namespace E1136 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().emplace(std::declval<int&&>())); } // @E1136 call
static_assert(std::is_same_v<E1136::t, std::multiset<int, std::less<>>::iterator>); // @E1136 ret
namespace E1137 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().emplace_hint(std::declval<std::multiset<int, std::less<>>::const_iterator>(), std::declval<int&&>())); } // @E1137 call
static_assert(std::is_same_v<E1137::t, std::multiset<int, std::less<>>::iterator>); // @E1137 ret
namespace E1138 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().insert(std::declval<const std::multiset<int, std::less<>>::value_type&>())); } // @E1138 call
static_assert(std::is_same_v<E1138::t, std::multiset<int, std::less<>>::iterator>); // @E1138 ret
namespace E1139 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().insert(std::declval<std::multiset<int, std::less<>>::value_type&&>())); } // @E1139 call
static_assert(std::is_same_v<E1139::t, std::multiset<int, std::less<>>::iterator>); // @E1139 ret
namespace E1140 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().insert(std::declval<std::multiset<int, std::less<>>::const_iterator>(), std::declval<const std::multiset<int, std::less<>>::value_type&>())); } // @E1140 call
static_assert(std::is_same_v<E1140::t, std::multiset<int, std::less<>>::iterator>); // @E1140 ret
namespace E1141 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().insert(std::declval<std::multiset<int, std::less<>>::const_iterator>(), std::declval<std::multiset<int, std::less<>>::value_type&&>())); } // @E1141 call
static_assert(std::is_same_v<E1141::t, std::multiset<int, std::less<>>::iterator>); // @E1141 ret
namespace E1142 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().insert(std::declval<std::type_identity_t<int*>>(), std::declval<std::type_identity_t<int*>>())); } // @E1142 call
static_assert(std::is_same_v<E1142::t, void>); // @E1142 ret
namespace E1143 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().insert_range(std::declval<std::vector<int>&&>())); } // @E1143 call
static_assert(std::is_same_v<E1143::t, void>); // @E1143 ret
namespace E1144 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().insert(std::declval<std::initializer_list<std::multiset<int, std::less<>>::value_type>>())); } // @E1144 call
static_assert(std::is_same_v<E1144::t, void>); // @E1144 ret
namespace E1145 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().extract(std::declval<std::multiset<int, std::less<>>::const_iterator>())); } // @E1145 call
static_assert(std::is_same_v<E1145::t, std::multiset<int, std::less<>>::node_type>); // @E1145 ret
namespace E1146 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().extract(std::declval<const std::multiset<int, std::less<>>::key_type&>())); } // @E1146 call
static_assert(std::is_same_v<E1146::t, std::multiset<int, std::less<>>::node_type>); // @E1146 ret
namespace E1147 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().extract(std::declval<long&&>())); } // @E1147 call
static_assert(std::is_same_v<E1147::t, std::multiset<int, std::less<>>::node_type>); // @E1147 ret
namespace E1148 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().insert(std::declval<std::multiset<int, std::less<>>::node_type&&>())); } // @E1148 call
static_assert(std::is_same_v<E1148::t, std::multiset<int, std::less<>>::iterator>); // @E1148 ret
namespace E1149 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().insert(std::declval<std::multiset<int, std::less<>>::const_iterator>(), std::declval<std::multiset<int, std::less<>>::node_type&&>())); } // @E1149 call
static_assert(std::is_same_v<E1149::t, std::multiset<int, std::less<>>::iterator>); // @E1149 ret
template<class D> concept E1150_call = requires { p2::dv<D, std::multiset<int, std::less<>>&>().erase(p2::dv<D, std::multiset<int, std::less<>>::iterator>()); }; static_assert(!((!std::same_as<std::multiset<int, std::less<>>::iterator,std::multiset<int, std::less<>>::const_iterator>)) || E1150_call<void>); // @E1150 call
template<class D> concept E1150_ret = requires { { p2::dv<D, std::multiset<int, std::less<>>&>().erase(p2::dv<D, std::multiset<int, std::less<>>::iterator>()) } -> std::same_as<std::multiset<int, std::less<>>::iterator>; }; static_assert(!((!std::same_as<std::multiset<int, std::less<>>::iterator,std::multiset<int, std::less<>>::const_iterator>)) || E1150_ret<void>); // @E1150 ret
namespace E1151 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().erase(std::declval<std::multiset<int, std::less<>>::const_iterator>())); } // @E1151 call
namespace E1152 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().erase(std::declval<const std::multiset<int, std::less<>>::key_type&>())); } // @E1152 call
namespace E1153 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().erase(std::declval<long&&>())); } // @E1153 call
namespace E1154 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().erase(std::declval<std::multiset<int, std::less<>>::const_iterator>(), std::declval<std::multiset<int, std::less<>>::const_iterator>())); } // @E1154 call
static_assert(std::is_same_v<E1154::t, std::multiset<int, std::less<>>::iterator>); // @E1154 ret
namespace E1155 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().swap(std::declval<std::multiset<int, std::less<>>&>())); } // @E1155 call
static_assert(std::is_same_v<E1155::t, void>); // @E1155 ret
static_assert(!(std::allocator_traits<std::allocator<int>>::is_always_equal::value&&std::is_nothrow_swappable_v<std::less<>>) || noexcept(std::declval<std::multiset<int, std::less<>>&>().swap(std::declval<std::multiset<int, std::less<>>&>()))); // @E1155 noexcept
namespace E1156 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().clear()); } // @E1156 call
static_assert(std::is_same_v<E1156::t, void>); // @E1156 ret
static_assert(!(true) || noexcept(std::declval<std::multiset<int, std::less<>>&>().clear())); // @E1156 noexcept
namespace E1157 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().merge(std::declval<std::multiset<int,std::greater<>,std::allocator<int>>&>())); } // @E1157 call
static_assert(std::is_same_v<E1157::t, void>); // @E1157 ret
namespace E1158 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().merge(std::declval<std::multiset<int,std::greater<>,std::allocator<int>>&&>())); } // @E1158 call
static_assert(std::is_same_v<E1158::t, void>); // @E1158 ret
namespace E1159 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().merge(std::declval<std::set<int,std::greater<>,std::allocator<int>>&>())); } // @E1159 call
static_assert(std::is_same_v<E1159::t, void>); // @E1159 ret
namespace E1160 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().merge(std::declval<std::set<int,std::greater<>,std::allocator<int>>&&>())); } // @E1160 call
static_assert(std::is_same_v<E1160::t, void>); // @E1160 ret
namespace E1161 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().key_comp()); } // @E1161 call
static_assert(std::is_same_v<E1161::t, std::multiset<int, std::less<>>::key_compare>); // @E1161 ret
namespace E1162 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().value_comp()); } // @E1162 call
static_assert(std::is_same_v<E1162::t, std::multiset<int, std::less<>>::value_compare>); // @E1162 ret
namespace E1163 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().find(std::declval<const std::multiset<int, std::less<>>::key_type&>())); } // @E1163 call
static_assert(std::is_same_v<E1163::t, std::multiset<int, std::less<>>::iterator>); // @E1163 ret
namespace E1164 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().find(std::declval<const std::multiset<int, std::less<>>::key_type&>())); } // @E1164 call
static_assert(std::is_same_v<E1164::t, std::multiset<int, std::less<>>::const_iterator>); // @E1164 ret
namespace E1165 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().find(std::declval<const long&>())); } // @E1165 call
static_assert(std::is_same_v<E1165::t, std::multiset<int, std::less<>>::iterator>); // @E1165 ret
namespace E1166 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().find(std::declval<const long&>())); } // @E1166 call
static_assert(std::is_same_v<E1166::t, std::multiset<int, std::less<>>::const_iterator>); // @E1166 ret
namespace E1167 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().count(std::declval<const std::multiset<int, std::less<>>::key_type&>())); } // @E1167 call
static_assert(std::is_same_v<E1167::t, std::multiset<int, std::less<>>::size_type>); // @E1167 ret
namespace E1168 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().count(std::declval<const long&>())); } // @E1168 call
static_assert(std::is_same_v<E1168::t, std::multiset<int, std::less<>>::size_type>); // @E1168 ret
namespace E1169 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().contains(std::declval<const std::multiset<int, std::less<>>::key_type&>())); } // @E1169 call
static_assert(std::is_same_v<E1169::t, bool>); // @E1169 ret
namespace E1170 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().contains(std::declval<const long&>())); } // @E1170 call
static_assert(std::is_same_v<E1170::t, bool>); // @E1170 ret
namespace E1171 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().lower_bound(std::declval<const std::multiset<int, std::less<>>::key_type&>())); } // @E1171 call
static_assert(std::is_same_v<E1171::t, std::multiset<int, std::less<>>::iterator>); // @E1171 ret
namespace E1172 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().lower_bound(std::declval<const std::multiset<int, std::less<>>::key_type&>())); } // @E1172 call
static_assert(std::is_same_v<E1172::t, std::multiset<int, std::less<>>::const_iterator>); // @E1172 ret
namespace E1173 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().lower_bound(std::declval<const long&>())); } // @E1173 call
static_assert(std::is_same_v<E1173::t, std::multiset<int, std::less<>>::iterator>); // @E1173 ret
namespace E1174 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().lower_bound(std::declval<const long&>())); } // @E1174 call
static_assert(std::is_same_v<E1174::t, std::multiset<int, std::less<>>::const_iterator>); // @E1174 ret
namespace E1175 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().upper_bound(std::declval<const std::multiset<int, std::less<>>::key_type&>())); } // @E1175 call
static_assert(std::is_same_v<E1175::t, std::multiset<int, std::less<>>::iterator>); // @E1175 ret
namespace E1176 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().upper_bound(std::declval<const std::multiset<int, std::less<>>::key_type&>())); } // @E1176 call
static_assert(std::is_same_v<E1176::t, std::multiset<int, std::less<>>::const_iterator>); // @E1176 ret
namespace E1177 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().upper_bound(std::declval<const long&>())); } // @E1177 call
static_assert(std::is_same_v<E1177::t, std::multiset<int, std::less<>>::iterator>); // @E1177 ret
namespace E1178 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().upper_bound(std::declval<const long&>())); } // @E1178 call
static_assert(std::is_same_v<E1178::t, std::multiset<int, std::less<>>::const_iterator>); // @E1178 ret
namespace E1179 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().equal_range(std::declval<const std::multiset<int, std::less<>>::key_type&>())); } // @E1179 call
static_assert(std::is_same_v<E1179::t, std::pair<std::multiset<int, std::less<>>::iterator,std::multiset<int, std::less<>>::iterator>>); // @E1179 ret
namespace E1180 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().equal_range(std::declval<const std::multiset<int, std::less<>>::key_type&>())); } // @E1180 call
static_assert(std::is_same_v<E1180::t, std::pair<std::multiset<int, std::less<>>::const_iterator,std::multiset<int, std::less<>>::const_iterator>>); // @E1180 ret
namespace E1181 { using t = decltype(std::declval<std::multiset<int, std::less<>>&>().equal_range(std::declval<const long&>())); } // @E1181 call
static_assert(std::is_same_v<E1181::t, std::pair<std::multiset<int, std::less<>>::iterator,std::multiset<int, std::less<>>::iterator>>); // @E1181 ret
namespace E1182 { using t = decltype(std::declval<const std::multiset<int, std::less<>>&>().equal_range(std::declval<const long&>())); } // @E1182 call
static_assert(std::is_same_v<E1182::t, std::pair<std::multiset<int, std::less<>>::const_iterator,std::multiset<int, std::less<>>::const_iterator>>); // @E1182 ret
static_assert(std::is_same_v<decltype(std::multiset(std::declval<std::type_identity_t<int*>>(), std::declval<std::type_identity_t<int*>>(), std::declval<std::less<int>>(), std::declval<std::allocator<int>>())), std::multiset<std::iter_value_t<std::type_identity_t<int*>>,std::less<int>,std::allocator<int>>>); // @E1183 guide
static_assert(std::is_same_v<decltype(std::multiset(std::declval<std::from_range_t>(), std::declval<std::vector<int>&&>(), std::declval<std::less<int>>(), std::declval<std::allocator<int>>())), std::multiset<std::ranges::range_value_t<std::vector<int>>,std::less<int>,std::allocator<int>>>); // @E1184 guide
static_assert(std::is_same_v<decltype(std::multiset(std::declval<std::type_identity_t<int*>>(), std::declval<std::type_identity_t<int*>>(), std::declval<std::allocator<int>>())), std::multiset<std::iter_value_t<std::type_identity_t<int*>>,std::less<std::iter_value_t<std::type_identity_t<int*>>>,std::allocator<int>>>); // @E1186 guide
static_assert(std::is_same_v<decltype(std::multiset(std::declval<std::from_range_t>(), std::declval<std::vector<int>&&>(), std::declval<std::allocator<int>>())), std::multiset<std::ranges::range_value_t<std::vector<int>>,std::less<std::ranges::range_value_t<std::vector<int>>>,std::allocator<int>>>); // @E1187 guide
