// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [range.as.const.view] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
namespace E3969 { using std::ranges::as_const_view; } // @E3969 name
static_assert(requires { sizeof(std::ranges::as_const_view<p2::V>); }); // @E3970 name
static_assert(std::is_constructible_v<std::ranges::as_const_view<p2::V>, p2::V>); // @E3971 call
static_assert(!std::is_convertible_v<p2::V, std::ranges::as_const_view<p2::V>>); // @E3971 explicit
template<class D> concept E3972_call = requires { p2::dv<D, const std::ranges::as_const_view<p2::V>&>().base(); }; static_assert(!(std::copy_constructible<p2::V>) || E3972_call<void>); // @E3972 call
template<class D> concept E3972_ret = requires { { p2::dv<D, const std::ranges::as_const_view<p2::V>&>().base() } -> std::same_as<p2::V>; }; static_assert(!(std::copy_constructible<p2::V>) || E3972_ret<void>); // @E3972 ret
namespace E3973 { using t = decltype(std::declval<std::ranges::as_const_view<p2::V>&&>().base()); } // @E3973 call
struct E3974 : std::ranges::as_const_view<p2::V> { using std::ranges::as_const_view<p2::V>::begin; }; // @E3974 name
template<class D> concept E3975_call = requires { p2::dv<D, const std::ranges::as_const_view<p2::V>&>().begin(); }; static_assert(!(std::ranges::range<const p2::V>) || E3975_call<void>); // @E3975 call
struct E3976 : std::ranges::as_const_view<p2::V> { using std::ranges::as_const_view<p2::V>::end; }; // @E3976 name
template<class D> concept E3977_call = requires { p2::dv<D, const std::ranges::as_const_view<p2::V>&>().end(); }; static_assert(!(std::ranges::range<const p2::V>) || E3977_call<void>); // @E3977 call
template<class D> concept E3978_call = requires { p2::dv<D, std::ranges::as_const_view<p2::V>&>().size(); }; static_assert(!(std::ranges::sized_range<p2::V>) || E3978_call<void>); // @E3978 call
template<class D> concept E3979_call = requires { p2::dv<D, const std::ranges::as_const_view<p2::V>&>().size(); }; static_assert(!(std::ranges::sized_range<const p2::V>) || E3979_call<void>); // @E3979 call
template<class D> concept E3980_call = requires { p2::dv<D, std::ranges::as_const_view<p2::V>&>().reserve_hint(); }; static_assert(!(std::ranges::approximately_sized_range<p2::V>) || E3980_call<void>); // @E3980 call
template<class D> concept E3981_call = requires { p2::dv<D, const std::ranges::as_const_view<p2::V>&>().reserve_hint(); }; static_assert(!(std::ranges::approximately_sized_range<const p2::V>) || E3981_call<void>); // @E3981 call
static_assert(std::is_same_v<decltype(std::ranges::as_const_view(std::declval<std::vector<int>&&>())), std::ranges::as_const_view<std::views::all_t<std::vector<int>>>>); // @E3982 guide
