// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [range.iota.sentinel] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
static_assert(requires { sizeof(std::ranges::sentinel_t<std::ranges::iota_view<int, long>>); }); // @E3523 name
namespace E3524 { using t = decltype(operator==(std::declval<const std::ranges::iterator_t<std::ranges::iota_view<int, long>>&>(), std::declval<const std::ranges::sentinel_t<std::ranges::iota_view<int, long>>&>())); } // @E3524 call
static_assert(std::is_same_v<E3524::t, bool>); // @E3524 ret
template<class D> concept E3525_call = requires { operator-(p2::dv<D, const std::ranges::iterator_t<std::ranges::iota_view<int, long>>&>(), p2::dv<D, const std::ranges::sentinel_t<std::ranges::iota_view<int, long>>&>()); }; static_assert(!(std::sized_sentinel_for<long,int>) || E3525_call<void>); // @E3525 call
template<class D> concept E3525_ret = requires { { operator-(p2::dv<D, const std::ranges::iterator_t<std::ranges::iota_view<int, long>>&>(), p2::dv<D, const std::ranges::sentinel_t<std::ranges::iota_view<int, long>>&>()) } -> std::same_as<std::iter_difference_t<int>>; }; static_assert(!(std::sized_sentinel_for<long,int>) || E3525_ret<void>); // @E3525 ret
template<class D> concept E3526_call = requires { operator-(p2::dv<D, const std::ranges::sentinel_t<std::ranges::iota_view<int, long>>&>(), p2::dv<D, const std::ranges::iterator_t<std::ranges::iota_view<int, long>>&>()); }; static_assert(!(std::sized_sentinel_for<long,int>) || E3526_call<void>); // @E3526 call
template<class D> concept E3526_ret = requires { { operator-(p2::dv<D, const std::ranges::sentinel_t<std::ranges::iota_view<int, long>>&>(), p2::dv<D, const std::ranges::iterator_t<std::ranges::iota_view<int, long>>&>()) } -> std::same_as<std::iter_difference_t<int>>; }; static_assert(!(std::sized_sentinel_for<long,int>) || E3526_ret<void>); // @E3526 ret
