// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [range.single.view] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
namespace E3472 { using std::ranges::single_view; } // @E3472 name
static_assert(requires { sizeof(std::ranges::single_view<int>); }); // @E3473 name
static_assert(!(std::copy_constructible<int>) || std::is_constructible_v<std::ranges::single_view<int>, const int&>); // @E3474 call
static_assert(std::is_constructible_v<std::ranges::single_view<int>, int&&>); // @E3475 call
static_assert(!std::is_convertible_v<int&&, std::ranges::single_view<int>>); // @E3475 explicit
namespace E3477 { using t = decltype(std::declval<std::ranges::single_view<int>&>().begin()); } // @E3477 call
static_assert(std::is_same_v<E3477::t, int*>); // @E3477 ret
static_assert(!(true) || noexcept(std::declval<std::ranges::single_view<int>&>().begin())); // @E3477 noexcept
namespace E3478 { using t = decltype(std::declval<const std::ranges::single_view<int>&>().begin()); } // @E3478 call
static_assert(std::is_same_v<E3478::t, const int*>); // @E3478 ret
static_assert(!(true) || noexcept(std::declval<const std::ranges::single_view<int>&>().begin())); // @E3478 noexcept
namespace E3479 { using t = decltype(std::declval<std::ranges::single_view<int>&>().end()); } // @E3479 call
static_assert(std::is_same_v<E3479::t, int*>); // @E3479 ret
static_assert(!(true) || noexcept(std::declval<std::ranges::single_view<int>&>().end())); // @E3479 noexcept
namespace E3480 { using t = decltype(std::declval<const std::ranges::single_view<int>&>().end()); } // @E3480 call
static_assert(std::is_same_v<E3480::t, const int*>); // @E3480 ret
static_assert(!(true) || noexcept(std::declval<const std::ranges::single_view<int>&>().end())); // @E3480 noexcept
namespace E3481 { using t = decltype(std::ranges::single_view<int>::empty()); } // @E3481 call
static_assert(std::is_same_v<E3481::t, bool>); // @E3481 ret
static_assert(!(true) || noexcept(std::ranges::single_view<int>::empty())); // @E3481 noexcept
namespace E3482 { using t = decltype(std::ranges::single_view<int>::size()); } // @E3482 call
static_assert(std::is_same_v<E3482::t, std::size_t>); // @E3482 ret
static_assert(!(true) || noexcept(std::ranges::single_view<int>::size())); // @E3482 noexcept
namespace E3483 { using t = decltype(std::declval<std::ranges::single_view<int>&>().data()); } // @E3483 call
static_assert(std::is_same_v<E3483::t, int*>); // @E3483 ret
static_assert(!(true) || noexcept(std::declval<std::ranges::single_view<int>&>().data())); // @E3483 noexcept
namespace E3484 { using t = decltype(std::declval<const std::ranges::single_view<int>&>().data()); } // @E3484 call
static_assert(std::is_same_v<E3484::t, const int*>); // @E3484 ret
static_assert(!(true) || noexcept(std::declval<const std::ranges::single_view<int>&>().data())); // @E3484 noexcept
static_assert(std::is_same_v<decltype(std::ranges::single_view(std::declval<int>())), std::ranges::single_view<int>>); // @E3485 guide
