// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [range.enumerate.iterator] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
struct E4048 : std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>> { using std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::iterator_category; }; // @E4048 name
static_assert(std::is_same_v<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::iterator_category, std::input_iterator_tag>); // @E4048 type
struct E4049 : std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>> { using std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::iterator_concept; }; // @E4049 name
struct E4050 : std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>> { using std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type; }; // @E4050 name
static_assert(std::is_same_v<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type, std::ranges::range_difference_t<p2::V>>); // @E4050 type
struct E4051 : std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>> { using std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::value_type; }; // @E4051 name
static_assert(std::is_same_v<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::value_type, std::tuple<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type,std::ranges::range_value_t<p2::V>>>); // @E4051 type
static_assert(requires { sizeof(std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>); }); // @E4052 name
namespace E4054 { using t = decltype(std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().base()); } // @E4054 call
static_assert(std::is_same_v<E4054::t, const std::ranges::iterator_t<p2::V>&>); // @E4054 ret
static_assert(!(true) || noexcept(std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().base())); // @E4054 noexcept
namespace E4055 { using t = decltype(std::declval<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&&>().base()); } // @E4055 call
static_assert(std::is_same_v<E4055::t, std::ranges::iterator_t<p2::V>>); // @E4055 ret
namespace E4056 { using t = decltype(std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().index()); } // @E4056 call
static_assert(std::is_same_v<E4056::t, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type>); // @E4056 ret
static_assert(!(true) || noexcept(std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().index())); // @E4056 noexcept
namespace E4057 { using t = decltype(std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().operator*()); } // @E4057 call
namespace E4058 { using t = decltype(std::declval<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().operator++()); } // @E4058 call
static_assert(std::is_same_v<E4058::t, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>); // @E4058 ret
namespace E4059 { using t = decltype(std::declval<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().operator++(std::declval<int>())); } // @E4059 call
template<class D> concept E4060_call = requires { p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().operator++(p2::dv<D, int>()); }; static_assert(!(std::ranges::forward_range<p2::V>) || E4060_call<void>); // @E4060 call
template<class D> concept E4060_ret = requires { { p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().operator++(p2::dv<D, int>()) } -> std::same_as<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>>; }; static_assert(!(std::ranges::forward_range<p2::V>) || E4060_ret<void>); // @E4060 ret
template<class D> concept E4061_call = requires { p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().operator--(); }; static_assert(!(std::ranges::bidirectional_range<p2::V>) || E4061_call<void>); // @E4061 call
template<class D> concept E4061_ret = requires { { p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().operator--() } -> std::same_as<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>; }; static_assert(!(std::ranges::bidirectional_range<p2::V>) || E4061_ret<void>); // @E4061 ret
namespace E4062 { using t = decltype(std::declval<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().operator--(std::declval<int>())); } // @E4062 call
static_assert(std::is_same_v<E4062::t, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>>); // @E4062 ret
template<class D> concept E4063_call = requires { p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().operator+=(p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type>()); }; static_assert(!(std::ranges::random_access_range<p2::V>) || E4063_call<void>); // @E4063 call
template<class D> concept E4063_ret = requires { { p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().operator+=(p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type>()) } -> std::same_as<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>; }; static_assert(!(std::ranges::random_access_range<p2::V>) || E4063_ret<void>); // @E4063 ret
template<class D> concept E4064_call = requires { p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().operator-=(p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type>()); }; static_assert(!(std::ranges::random_access_range<p2::V>) || E4064_call<void>); // @E4064 call
template<class D> concept E4064_ret = requires { { p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().operator-=(p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type>()) } -> std::same_as<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>; }; static_assert(!(std::ranges::random_access_range<p2::V>) || E4064_ret<void>); // @E4064 ret
template<class D> concept E4065_call = requires { p2::dv<D, const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>().operator[](p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type>()); }; static_assert(!(std::ranges::random_access_range<p2::V>) || E4065_call<void>); // @E4065 call
namespace E4066 { using t = decltype(operator==(std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>(), std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>())); } // @E4066 call
static_assert(std::is_same_v<E4066::t, bool>); // @E4066 ret
static_assert(!(true) || noexcept(operator==(std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>(), std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>()))); // @E4066 noexcept
namespace E4067 { using t = decltype(operator<=>(std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>(), std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>())); } // @E4067 call
static_assert(std::is_same_v<E4067::t, std::strong_ordering>); // @E4067 ret
static_assert(!(true) || noexcept(operator<=>(std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>(), std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>()))); // @E4067 noexcept
template<class D> concept E4068_call = requires { operator+(p2::dv<D, const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>(), p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type>()); }; static_assert(!(std::ranges::random_access_range<p2::V>) || E4068_call<void>); // @E4068 call
template<class D> concept E4068_ret = requires { { operator+(p2::dv<D, const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>(), p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type>()) } -> std::same_as<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>>; }; static_assert(!(std::ranges::random_access_range<p2::V>) || E4068_ret<void>); // @E4068 ret
template<class D> concept E4069_call = requires { operator+(p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type>(), p2::dv<D, const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>()); }; static_assert(!(std::ranges::random_access_range<p2::V>) || E4069_call<void>); // @E4069 call
template<class D> concept E4069_ret = requires { { operator+(p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type>(), p2::dv<D, const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>()) } -> std::same_as<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>>; }; static_assert(!(std::ranges::random_access_range<p2::V>) || E4069_ret<void>); // @E4069 ret
template<class D> concept E4070_call = requires { operator-(p2::dv<D, const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>(), p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type>()); }; static_assert(!(std::ranges::random_access_range<p2::V>) || E4070_call<void>); // @E4070 call
template<class D> concept E4070_ret = requires { { operator-(p2::dv<D, const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>(), p2::dv<D, std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>::difference_type>()) } -> std::same_as<std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>>; }; static_assert(!(std::ranges::random_access_range<p2::V>) || E4070_ret<void>); // @E4070 ret
namespace E4071 { using t = decltype(operator-(std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>(), std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>())); } // @E4071 call
namespace E4072 { using t = decltype(iter_move(std::declval<const std::ranges::iterator_t<std::ranges::enumerate_view<p2::V>>&>())); } // @E4072 call
