// Generated by tools/spec_audit/gen_probes.py; do not edit. Freestanding names of [span.syn]
// (-ffreestanding, [compliance]).
#include <span>
namespace E2424_f { using std::dynamic_extent; } // @E2424 freestanding
namespace E2426_f { using std::span; } // @E2426 freestanding
namespace E2429_f { using std::as_bytes; } // @E2429 freestanding
namespace E2430_f { using std::as_writable_bytes; } // @E2430 freestanding
