// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [span.overview] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
namespace E2431 { using std::span; } // @E2431 name
struct E2432 : std::span<int> { using std::span<int>::element_type; }; // @E2432 name
static_assert(std::is_same_v<std::span<int>::element_type, int>); // @E2432 type
struct E2433 : std::span<int> { using std::span<int>::value_type; }; // @E2433 name
static_assert(std::is_same_v<std::span<int>::value_type, std::remove_cv_t<int>>); // @E2433 type
struct E2434 : std::span<int> { using std::span<int>::size_type; }; // @E2434 name
static_assert(std::is_same_v<std::span<int>::size_type, std::size_t>); // @E2434 type
struct E2435 : std::span<int> { using std::span<int>::difference_type; }; // @E2435 name
static_assert(std::is_same_v<std::span<int>::difference_type, std::ptrdiff_t>); // @E2435 type
struct E2436 : std::span<int> { using std::span<int>::pointer; }; // @E2436 name
static_assert(std::is_same_v<std::span<int>::pointer, std::span<int>::element_type*>); // @E2436 type
struct E2437 : std::span<int> { using std::span<int>::const_pointer; }; // @E2437 name
static_assert(std::is_same_v<std::span<int>::const_pointer, const std::span<int>::element_type*>); // @E2437 type
struct E2438 : std::span<int> { using std::span<int>::reference; }; // @E2438 name
static_assert(std::is_same_v<std::span<int>::reference, std::span<int>::element_type&>); // @E2438 type
struct E2439 : std::span<int> { using std::span<int>::const_reference; }; // @E2439 name
static_assert(std::is_same_v<std::span<int>::const_reference, const std::span<int>::element_type&>); // @E2439 type
struct E2440 : std::span<int> { using std::span<int>::iterator; }; // @E2440 name
struct E2441 : std::span<int> { using std::span<int>::const_iterator; }; // @E2441 name
static_assert(std::is_same_v<std::span<int>::const_iterator, std::const_iterator<std::span<int>::iterator>>); // @E2441 type
struct E2442 : std::span<int> { using std::span<int>::reverse_iterator; }; // @E2442 name
static_assert(std::is_same_v<std::span<int>::reverse_iterator, std::reverse_iterator<std::span<int>::iterator>>); // @E2442 type
struct E2443 : std::span<int> { using std::span<int>::const_reverse_iterator; }; // @E2443 name
static_assert(std::is_same_v<std::span<int>::const_reverse_iterator, std::const_iterator<std::span<int>::reverse_iterator>>); // @E2443 type
struct E2444 : std::span<int> { using std::span<int>::extent; }; // @E2444 name
static_assert(std::is_constructible_v<std::span<int>>); // @E2445 call
static_assert(!(true) || std::is_nothrow_constructible_v<std::span<int>>); // @E2445 noexcept
static_assert(std::is_constructible_v<std::span<int>, std::type_identity_t<int*>, std::span<int>::size_type>); // @E2446 call
static_assert(std::is_constructible_v<std::span<int>, std::type_identity_t<int*>, std::type_identity_t<int*>>); // @E2447 call
static_assert(std::is_constructible_v<std::span<int>, std::type_identity_t<std::span<int>::element_type>(&)[3]>); // @E2448 call
static_assert(!(true) || std::is_nothrow_constructible_v<std::span<int>, std::type_identity_t<std::span<int>::element_type>(&)[3]>); // @E2448 noexcept
static_assert(std::is_convertible_v<std::type_identity_t<std::span<int>::element_type>(&)[3], std::span<int>>); // @E2448 implicit
static_assert(std::is_constructible_v<std::span<int>, std::array<int,3>&>); // @E2449 call
static_assert(!(true) || std::is_nothrow_constructible_v<std::span<int>, std::array<int,3>&>); // @E2449 noexcept
static_assert(std::is_convertible_v<std::array<int,3>&, std::span<int>>); // @E2449 implicit
static_assert(std::is_constructible_v<std::span<int>, std::type_identity_t<std::vector<int>&>&&>); // @E2451 call
static_assert(requires { sizeof(std::span<int>); }); // @E2452 name
static_assert(std::is_constructible_v<std::span<int>, const std::span<int,std::dynamic_extent>&>); // @E2453 call
static_assert(!(true) || std::is_nothrow_constructible_v<std::span<int>, const std::span<int,std::dynamic_extent>&>); // @E2453 noexcept
namespace E2454 { using t = decltype(std::declval<std::span<int>&>().operator=(std::declval<const std::span<int>&>())); } // @E2454 call
static_assert(std::is_same_v<E2454::t, std::span<int>&>); // @E2454 ret
static_assert(!(true) || noexcept(std::declval<std::span<int>&>().operator=(std::declval<const std::span<int>&>()))); // @E2454 noexcept
namespace E2455 { using t = decltype(std::declval<const std::span<int>&>().template first<1>()); } // @E2455 call
static_assert(std::is_same_v<E2455::t, std::span<std::span<int>::element_type,1>>); // @E2455 ret
namespace E2456 { using t = decltype(std::declval<const std::span<int>&>().template last<1>()); } // @E2456 call
static_assert(std::is_same_v<E2456::t, std::span<std::span<int>::element_type,1>>); // @E2456 ret
namespace E2457 { using t = decltype(std::declval<const std::span<int>&>().template subspan<0>()); } // @E2457 call
namespace E2458 { using t = decltype(std::declval<const std::span<int>&>().first(std::declval<std::span<int>::size_type>())); } // @E2458 call
static_assert(std::is_same_v<E2458::t, std::span<std::span<int>::element_type,std::dynamic_extent>>); // @E2458 ret
namespace E2459 { using t = decltype(std::declval<const std::span<int>&>().last(std::declval<std::span<int>::size_type>())); } // @E2459 call
static_assert(std::is_same_v<E2459::t, std::span<std::span<int>::element_type,std::dynamic_extent>>); // @E2459 ret
namespace E2460 { using t = decltype(std::declval<const std::span<int>&>().subspan(std::declval<std::span<int>::size_type>(), std::declval<std::span<int>::size_type>())); } // @E2460 call
static_assert(std::is_same_v<E2460::t, std::span<std::span<int>::element_type,std::dynamic_extent>>); // @E2460 ret
namespace E2460 { using t2 = decltype(std::declval<const std::span<int>&>().subspan(std::declval<std::span<int>::size_type>())); } // @E2460 defaults
namespace E2461 { using t = decltype(std::declval<const std::span<int>&>().size()); } // @E2461 call
static_assert(std::is_same_v<E2461::t, std::span<int>::size_type>); // @E2461 ret
static_assert(!(true) || noexcept(std::declval<const std::span<int>&>().size())); // @E2461 noexcept
namespace E2462 { using t = decltype(std::declval<const std::span<int>&>().size_bytes()); } // @E2462 call
static_assert(std::is_same_v<E2462::t, std::span<int>::size_type>); // @E2462 ret
static_assert(!(true) || noexcept(std::declval<const std::span<int>&>().size_bytes())); // @E2462 noexcept
namespace E2463 { using t = decltype(std::declval<const std::span<int>&>().empty()); } // @E2463 call
static_assert(std::is_same_v<E2463::t, bool>); // @E2463 ret
static_assert(!(true) || noexcept(std::declval<const std::span<int>&>().empty())); // @E2463 noexcept
namespace E2464 { using t = decltype(std::declval<const std::span<int>&>().operator[](std::declval<std::span<int>::size_type>())); } // @E2464 call
static_assert(std::is_same_v<E2464::t, std::span<int>::reference>); // @E2464 ret
namespace E2465 { using t = decltype(std::declval<const std::span<int>&>().at(std::declval<std::span<int>::size_type>())); } // @E2465 call
static_assert(std::is_same_v<E2465::t, std::span<int>::reference>); // @E2465 ret
namespace E2466 { using t = decltype(std::declval<const std::span<int>&>().front()); } // @E2466 call
static_assert(std::is_same_v<E2466::t, std::span<int>::reference>); // @E2466 ret
namespace E2467 { using t = decltype(std::declval<const std::span<int>&>().back()); } // @E2467 call
static_assert(std::is_same_v<E2467::t, std::span<int>::reference>); // @E2467 ret
namespace E2468 { using t = decltype(std::declval<const std::span<int>&>().data()); } // @E2468 call
static_assert(std::is_same_v<E2468::t, std::span<int>::pointer>); // @E2468 ret
static_assert(!(true) || noexcept(std::declval<const std::span<int>&>().data())); // @E2468 noexcept
namespace E2469 { using t = decltype(std::declval<const std::span<int>&>().begin()); } // @E2469 call
static_assert(std::is_same_v<E2469::t, std::span<int>::iterator>); // @E2469 ret
static_assert(!(true) || noexcept(std::declval<const std::span<int>&>().begin())); // @E2469 noexcept
namespace E2470 { using t = decltype(std::declval<const std::span<int>&>().end()); } // @E2470 call
static_assert(std::is_same_v<E2470::t, std::span<int>::iterator>); // @E2470 ret
static_assert(!(true) || noexcept(std::declval<const std::span<int>&>().end())); // @E2470 noexcept
namespace E2471 { using t = decltype(std::declval<const std::span<int>&>().cbegin()); } // @E2471 call
static_assert(std::is_same_v<E2471::t, std::span<int>::const_iterator>); // @E2471 ret
static_assert(!(true) || noexcept(std::declval<const std::span<int>&>().cbegin())); // @E2471 noexcept
namespace E2472 { using t = decltype(std::declval<const std::span<int>&>().cend()); } // @E2472 call
static_assert(std::is_same_v<E2472::t, std::span<int>::const_iterator>); // @E2472 ret
static_assert(!(true) || noexcept(std::declval<const std::span<int>&>().cend())); // @E2472 noexcept
namespace E2473 { using t = decltype(std::declval<const std::span<int>&>().rbegin()); } // @E2473 call
static_assert(std::is_same_v<E2473::t, std::span<int>::reverse_iterator>); // @E2473 ret
static_assert(!(true) || noexcept(std::declval<const std::span<int>&>().rbegin())); // @E2473 noexcept
namespace E2474 { using t = decltype(std::declval<const std::span<int>&>().rend()); } // @E2474 call
static_assert(std::is_same_v<E2474::t, std::span<int>::reverse_iterator>); // @E2474 ret
static_assert(!(true) || noexcept(std::declval<const std::span<int>&>().rend())); // @E2474 noexcept
namespace E2475 { using t = decltype(std::declval<const std::span<int>&>().crbegin()); } // @E2475 call
static_assert(std::is_same_v<E2475::t, std::span<int>::const_reverse_iterator>); // @E2475 ret
static_assert(!(true) || noexcept(std::declval<const std::span<int>&>().crbegin())); // @E2475 noexcept
namespace E2476 { using t = decltype(std::declval<const std::span<int>&>().crend()); } // @E2476 call
static_assert(std::is_same_v<E2476::t, std::span<int>::const_reverse_iterator>); // @E2476 ret
static_assert(!(true) || noexcept(std::declval<const std::span<int>&>().crend())); // @E2476 noexcept
static_assert(std::is_same_v<decltype(std::span(std::declval<int(&)[3]>())), std::span<int,3>>); // @E2478 guide
static_assert(std::is_same_v<decltype(std::span(std::declval<std::array<int,3>&>())), std::span<int,3>>); // @E2479 guide
static_assert(std::is_same_v<decltype(std::span(std::declval<const std::array<int,3>&>())), std::span<const int,3>>); // @E2480 guide
static_assert(std::is_same_v<decltype(std::span(std::declval<std::type_identity_t<std::vector<int>&>&&>())), std::span<std::remove_reference_t<std::ranges::range_reference_t<std::type_identity_t<std::vector<int>&>>>>>); // @E2481 guide
