// Generated by tools/spec_audit/gen_probes.py; do not edit. Names of [span.syn] with only <span> included.
#include <span>
namespace E2424_h { using std::dynamic_extent; } // @E2424 header
namespace E2426_h { using std::span; } // @E2426 header
namespace E2429_h { using std::as_bytes; } // @E2429 header
namespace E2430_h { using std::as_writable_bytes; } // @E2430 header
