// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [string.view.synop] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
namespace E5434 { using std::basic_string_view; } // @E5434 name
static_assert(std::ranges::enable_view<std::basic_string_view<char,std::char_traits<char>>> == true); // @E5435 spec
static_assert(std::ranges::enable_borrowed_range<std::basic_string_view<char,std::char_traits<char>>> == true); // @E5436 spec
namespace E5437 { using t = decltype(std::operator==(std::declval<std::basic_string_view<char,std::char_traits<char>>>(), std::declval<std::type_identity_t<std::basic_string_view<char,std::char_traits<char>>>>())); } // @E5437 call
static_assert(std::is_same_v<E5437::t, bool>); // @E5437 ret
static_assert(!(true) || noexcept(std::operator==(std::declval<std::basic_string_view<char,std::char_traits<char>>>(), std::declval<std::type_identity_t<std::basic_string_view<char,std::char_traits<char>>>>()))); // @E5437 noexcept
namespace E5438 { using t = decltype(std::operator<=>(std::declval<std::basic_string_view<char,std::char_traits<char>>>(), std::declval<std::type_identity_t<std::basic_string_view<char,std::char_traits<char>>>>())); } // @E5438 call
static_assert(!(true) || noexcept(std::operator<=>(std::declval<std::basic_string_view<char,std::char_traits<char>>>(), std::declval<std::type_identity_t<std::basic_string_view<char,std::char_traits<char>>>>()))); // @E5438 noexcept
namespace E5439 { using t = decltype(std::operator<<(std::declval<std::basic_ostream<char,std::char_traits<char>>&>(), std::declval<std::basic_string_view<char,std::char_traits<char>>>())); } // @E5439 call
static_assert(std::is_same_v<E5439::t, std::basic_ostream<char,std::char_traits<char>>&>); // @E5439 ret
namespace E5440 { using std::string_view; } // @E5440 name
static_assert(std::is_same_v<std::string_view, std::basic_string_view<char>>); // @E5440 type
namespace E5441 { using std::u8string_view; } // @E5441 name
static_assert(std::is_same_v<std::u8string_view, std::basic_string_view<char8_t>>); // @E5441 type
namespace E5442 { using std::u16string_view; } // @E5442 name
static_assert(std::is_same_v<std::u16string_view, std::basic_string_view<char16_t>>); // @E5442 type
namespace E5443 { using std::u32string_view; } // @E5443 name
static_assert(std::is_same_v<std::u32string_view, std::basic_string_view<char32_t>>); // @E5443 type
namespace E5444 { using std::wstring_view; } // @E5444 name
static_assert(std::is_same_v<std::wstring_view, std::basic_string_view<wchar_t>>); // @E5444 type
namespace E5445 { using std::hash; } // @E5445 name
static_assert(sizeof(std::hash<std::string_view>) > 0); // @E5446 spec
static_assert(sizeof(std::hash<std::u8string_view>) > 0); // @E5447 spec
static_assert(sizeof(std::hash<std::u16string_view>) > 0); // @E5448 spec
static_assert(sizeof(std::hash<std::u32string_view>) > 0); // @E5449 spec
static_assert(sizeof(std::hash<std::wstring_view>) > 0); // @E5450 spec
namespace E5451 { using t = decltype(std::literals::string_view_literals::operator "" sv(std::declval<const char*>(), std::declval<std::size_t>())); } // @E5451 call
static_assert(std::is_same_v<E5451::t, std::string_view>); // @E5451 ret
static_assert(!(true) || noexcept(std::literals::string_view_literals::operator "" sv(std::declval<const char*>(), std::declval<std::size_t>()))); // @E5451 noexcept
namespace E5452 { using t = decltype(std::literals::string_view_literals::operator "" sv(std::declval<const char8_t*>(), std::declval<std::size_t>())); } // @E5452 call
static_assert(std::is_same_v<E5452::t, std::u8string_view>); // @E5452 ret
static_assert(!(true) || noexcept(std::literals::string_view_literals::operator "" sv(std::declval<const char8_t*>(), std::declval<std::size_t>()))); // @E5452 noexcept
namespace E5453 { using t = decltype(std::literals::string_view_literals::operator "" sv(std::declval<const char16_t*>(), std::declval<std::size_t>())); } // @E5453 call
static_assert(std::is_same_v<E5453::t, std::u16string_view>); // @E5453 ret
static_assert(!(true) || noexcept(std::literals::string_view_literals::operator "" sv(std::declval<const char16_t*>(), std::declval<std::size_t>()))); // @E5453 noexcept
namespace E5454 { using t = decltype(std::literals::string_view_literals::operator "" sv(std::declval<const char32_t*>(), std::declval<std::size_t>())); } // @E5454 call
static_assert(std::is_same_v<E5454::t, std::u32string_view>); // @E5454 ret
static_assert(!(true) || noexcept(std::literals::string_view_literals::operator "" sv(std::declval<const char32_t*>(), std::declval<std::size_t>()))); // @E5454 noexcept
namespace E5455 { using t = decltype(std::literals::string_view_literals::operator "" sv(std::declval<const wchar_t*>(), std::declval<std::size_t>())); } // @E5455 call
static_assert(std::is_same_v<E5455::t, std::wstring_view>); // @E5455 ret
static_assert(!(true) || noexcept(std::literals::string_view_literals::operator "" sv(std::declval<const wchar_t*>(), std::declval<std::size_t>()))); // @E5455 noexcept
