// Generated by tools/spec_audit/gen_probes.py; do not edit. Names of [unord.map.syn] with only <unordered_map> included.
#include <unordered_map>
namespace E1191_h { using std::unordered_map; } // @E1191 header
namespace E1192_h { using std::unordered_multimap; } // @E1192 header
namespace E1195_h { using std::swap; } // @E1195 header
namespace E1196_h { using std::swap; } // @E1196 header
namespace E1197_h { using std::erase_if; } // @E1197 header
namespace E1198_h { using std::erase_if; } // @E1198 header
namespace E1199_h { using std::pmr::unordered_map; } // @E1199 header
namespace E1200_h { using std::pmr::unordered_multimap; } // @E1200 header
namespace E1189_h { using t = std::strong_ordering; } // @E1189 include
namespace E1190_h { using t = std::initializer_list<int>; } // @E1190 include
