// Generated by tools/spec_audit/gen_probes.py from the working draft; do not edit.
// Spec-coverage probe of [unord.multiset.overview] (docs/SPEC_COVERAGE.md, part 2). Compile only: each line ending
// in `// @E<n> <aspect>` checks one aspect of one entity (tools/spec_audit/part2/entities.tsv).
#include <algorithm>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <generator>
#include <hive>
#include <inplace_vector>
#include <iterator>
#include <list>
#include <map>
#include <mdspan>
#include <numeric>
#include <queue>
#include <ranges>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstring>
#include <memory>
#include <execution>
#include <random>
#include <format>
#include <sstream>
#include <istream>
#include <ostream>
#include <tuple>
#include <functional>
#include <utility>
#include <concepts>
#include <type_traits>
#include <cstddef>
namespace p2 {
  // a callable that accepts anything: a predicate, a comparison, a projection, a function
  struct AnyFn { template<class... A> constexpr int operator()(A&&...) const noexcept { return 0; } };
  // a mapped type constructible from one or two ints (emplace, try_emplace)
  struct M {
    int v = 0;
    constexpr M() = default;
    constexpr M(int a) : v(a) {}
    constexpr M(int a, int b) : v(a + b) {}
    friend constexpr bool operator==(const M&, const M&) = default;
    friend constexpr auto operator<=>(const M&, const M&) = default;
  };
  struct THash {
    using is_transparent = void;
    std::size_t operator()(long) const noexcept;
  };
  // a declval whose type depends on D: a deleted function's use in a template is a substitution failure
  template<class D, class T> std::add_rvalue_reference_t<T> dv() noexcept;
  struct ResizeOp { std::size_t operator()(char*, std::size_t n) const { return n; } };
  struct Sent { friend constexpr bool operator==(const int*, Sent) noexcept { return false; } };
  struct SentV { friend constexpr bool operator==(const std::vector<int>*, SentV) noexcept { return false; } };
  struct SentT { friend constexpr bool operator==(const std::tuple<int, int>*, SentT) noexcept { return false; } };
  using V = std::ranges::ref_view<std::vector<int>>;
  using NCV = std::ranges::subrange<int*, Sent>;
  using VV = std::ranges::ref_view<std::vector<std::vector<int>>>;
  using NCVV = std::ranges::subrange<std::vector<int>*, SentV>;
  using TV = std::ranges::ref_view<std::vector<std::tuple<int, int>>>;
  using NCTV = std::ranges::subrange<std::tuple<int, int>*, SentT>;
  using IV = std::ranges::basic_istream_view<int, char>;
  using MDS = std::mdspan<int, std::dextents<std::size_t, 2>>;
  // exposition-only aliases, as [ranges.syn], [associative.general] and [container.alloc.reqmts] define them
  template<bool Const, class T> using maybe_const = std::conditional_t<Const, const T, T>;
  template<class I> using iter_key_type = std::remove_const_t<std::tuple_element_t<0, std::iter_value_t<I>>>;
  template<class I> using iter_mapped_type = std::tuple_element_t<1, std::iter_value_t<I>>;
  template<class I> using iter_to_alloc_type =
    std::pair<const std::tuple_element_t<0, std::iter_value_t<I>>, std::tuple_element_t<1, std::iter_value_t<I>>>;
  template<class R> using range_key_type = std::remove_const_t<typename std::ranges::range_value_t<R>::first_type>;
  template<class R> using range_mapped_type = typename std::ranges::range_value_t<R>::second_type;
  template<class R> using range_to_alloc_type =
    std::pair<const typename std::ranges::range_value_t<R>::first_type, typename std::ranges::range_value_t<R>::second_type>;
}
namespace E1592 { using std::unordered_multiset; } // @E1592 name
struct E1593 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_type; }; // @E1593 name
static_assert(std::is_same_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_type, int>); // @E1593 type
struct E1594 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type; }; // @E1594 name
static_assert(std::is_same_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type, int>); // @E1594 type
struct E1595 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::hasher; }; // @E1595 name
static_assert(std::is_same_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>::hasher, p2::THash>); // @E1595 type
struct E1596 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_equal; }; // @E1596 name
static_assert(std::is_same_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_equal, std::equal_to<>>); // @E1596 type
struct E1597 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type; }; // @E1597 name
static_assert(std::is_same_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type, std::allocator<int>>); // @E1597 type
struct E1598 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::pointer; }; // @E1598 name
static_assert(std::is_same_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>::pointer, std::allocator_traits<std::allocator<int>>::pointer>); // @E1598 type
struct E1599 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_pointer; }; // @E1599 name
static_assert(std::is_same_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_pointer, std::allocator_traits<std::allocator<int>>::const_pointer>); // @E1599 type
struct E1600 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::reference; }; // @E1600 name
static_assert(std::is_same_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>::reference, std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type&>); // @E1600 type
struct E1601 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_reference; }; // @E1601 name
static_assert(std::is_same_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_reference, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type&>); // @E1601 type
struct E1602 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type; }; // @E1602 name
struct E1603 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::difference_type; }; // @E1603 name
struct E1604 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator; }; // @E1604 name
struct E1605 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator; }; // @E1605 name
struct E1606 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::local_iterator; }; // @E1606 name
struct E1607 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_local_iterator; }; // @E1607 name
struct E1608 : std::unordered_multiset<int, p2::THash, std::equal_to<>> { using std::unordered_multiset<int, p2::THash, std::equal_to<>>::node_type; }; // @E1608 name
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>>); // @E1609 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::hasher&, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_equal&, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type&>); // @E1610 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>); // @E1610 defaults
static_assert(!std::is_convertible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type, std::unordered_multiset<int, p2::THash, std::equal_to<>>>); // @E1610 explicit
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::type_identity_t<int*>, std::type_identity_t<int*>, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::hasher&, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_equal&, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type&>); // @E1611 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::type_identity_t<int*>, std::type_identity_t<int*>>); // @E1611 defaults
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::from_range_t, std::vector<int>&&, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::hasher&, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_equal&, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type&>); // @E1612 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::from_range_t, std::vector<int>&&>); // @E1612 defaults
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>); // @E1613 call
static_assert(std::is_convertible_v<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&, std::unordered_multiset<int, p2::THash, std::equal_to<>>>); // @E1613 implicit
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::unordered_multiset<int, p2::THash, std::equal_to<>>&&>); // @E1614 call
static_assert(std::is_convertible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>&&, std::unordered_multiset<int, p2::THash, std::equal_to<>>>); // @E1614 implicit
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, const std::allocator<int>&>); // @E1615 call
static_assert(!std::is_convertible_v<const std::allocator<int>&, std::unordered_multiset<int, p2::THash, std::equal_to<>>>); // @E1615 explicit
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, const std::unordered_multiset<int, p2::THash, std::equal_to<>>&, const std::type_identity_t<std::allocator<int>>&>); // @E1616 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::unordered_multiset<int, p2::THash, std::equal_to<>>&&, const std::type_identity_t<std::allocator<int>>&>); // @E1617 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::initializer_list<std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type>, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::hasher&, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_equal&, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type&>); // @E1618 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::initializer_list<std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type>>); // @E1618 defaults
static_assert(std::is_convertible_v<std::initializer_list<std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type>, std::unordered_multiset<int, p2::THash, std::equal_to<>>>); // @E1618 implicit
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type&>); // @E1619 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::hasher&, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type&>); // @E1620 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::type_identity_t<int*>, std::type_identity_t<int*>, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type&>); // @E1621 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::type_identity_t<int*>, std::type_identity_t<int*>, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::hasher&, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type&>); // @E1622 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::from_range_t, std::vector<int>&&, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type&>); // @E1623 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::from_range_t, std::vector<int>&&, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::hasher&, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type&>); // @E1624 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::initializer_list<std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type>, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type&>); // @E1625 call
static_assert(std::is_constructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>, std::initializer_list<std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type>, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::hasher&, const std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type&>); // @E1626 call
static_assert(std::is_nothrow_destructible_v<std::unordered_multiset<int, p2::THash, std::equal_to<>>>); // @E1627 noexcept
namespace E1628 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().operator=(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>())); } // @E1628 call
static_assert(std::is_same_v<E1628::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>&>); // @E1628 ret
namespace E1629 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().operator=(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&&>())); } // @E1629 call
static_assert(std::is_same_v<E1629::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>&>); // @E1629 ret
static_assert(!(std::allocator_traits<std::allocator<int>>::is_always_equal::value&&std::is_nothrow_move_assignable_v<p2::THash>&&std::is_nothrow_move_assignable_v<std::equal_to<>>) || noexcept(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().operator=(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&&>()))); // @E1629 noexcept
namespace E1630 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().operator=(std::declval<std::initializer_list<std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type>>())); } // @E1630 call
static_assert(std::is_same_v<E1630::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>&>); // @E1630 ret
namespace E1631 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().get_allocator()); } // @E1631 call
static_assert(std::is_same_v<E1631::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::allocator_type>); // @E1631 ret
static_assert(!(true) || noexcept(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().get_allocator())); // @E1631 noexcept
namespace E1632 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().begin()); } // @E1632 call
static_assert(std::is_same_v<E1632::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>); // @E1632 ret
static_assert(!(true) || noexcept(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().begin())); // @E1632 noexcept
namespace E1633 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().begin()); } // @E1633 call
static_assert(std::is_same_v<E1633::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>); // @E1633 ret
static_assert(!(true) || noexcept(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().begin())); // @E1633 noexcept
namespace E1634 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().end()); } // @E1634 call
static_assert(std::is_same_v<E1634::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>); // @E1634 ret
static_assert(!(true) || noexcept(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().end())); // @E1634 noexcept
namespace E1635 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().end()); } // @E1635 call
static_assert(std::is_same_v<E1635::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>); // @E1635 ret
static_assert(!(true) || noexcept(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().end())); // @E1635 noexcept
namespace E1636 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().cbegin()); } // @E1636 call
static_assert(std::is_same_v<E1636::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>); // @E1636 ret
static_assert(!(true) || noexcept(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().cbegin())); // @E1636 noexcept
namespace E1637 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().cend()); } // @E1637 call
static_assert(std::is_same_v<E1637::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>); // @E1637 ret
static_assert(!(true) || noexcept(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().cend())); // @E1637 noexcept
namespace E1638 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().empty()); } // @E1638 call
static_assert(std::is_same_v<E1638::t, bool>); // @E1638 ret
static_assert(!(true) || noexcept(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().empty())); // @E1638 noexcept
namespace E1639 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().size()); } // @E1639 call
static_assert(std::is_same_v<E1639::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>); // @E1639 ret
static_assert(!(true) || noexcept(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().size())); // @E1639 noexcept
namespace E1640 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().max_size()); } // @E1640 call
static_assert(std::is_same_v<E1640::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>); // @E1640 ret
static_assert(!(true) || noexcept(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().max_size())); // @E1640 noexcept
namespace E1641 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().emplace(std::declval<int&&>())); } // @E1641 call
static_assert(std::is_same_v<E1641::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>); // @E1641 ret
namespace E1642 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().emplace_hint(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>(), std::declval<int&&>())); } // @E1642 call
static_assert(std::is_same_v<E1642::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>); // @E1642 ret
namespace E1643 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().insert(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type&>())); } // @E1643 call
static_assert(std::is_same_v<E1643::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>); // @E1643 ret
namespace E1644 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().insert(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type&&>())); } // @E1644 call
static_assert(std::is_same_v<E1644::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>); // @E1644 ret
namespace E1645 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().insert(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>(), std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type&>())); } // @E1645 call
static_assert(std::is_same_v<E1645::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>); // @E1645 ret
namespace E1646 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().insert(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>(), std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type&&>())); } // @E1646 call
static_assert(std::is_same_v<E1646::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>); // @E1646 ret
namespace E1647 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().insert(std::declval<std::type_identity_t<int*>>(), std::declval<std::type_identity_t<int*>>())); } // @E1647 call
static_assert(std::is_same_v<E1647::t, void>); // @E1647 ret
namespace E1648 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().insert_range(std::declval<std::vector<int>&&>())); } // @E1648 call
static_assert(std::is_same_v<E1648::t, void>); // @E1648 ret
namespace E1649 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().insert(std::declval<std::initializer_list<std::unordered_multiset<int, p2::THash, std::equal_to<>>::value_type>>())); } // @E1649 call
static_assert(std::is_same_v<E1649::t, void>); // @E1649 ret
namespace E1650 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().extract(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>())); } // @E1650 call
static_assert(std::is_same_v<E1650::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::node_type>); // @E1650 ret
namespace E1651 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().extract(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_type&>())); } // @E1651 call
static_assert(std::is_same_v<E1651::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::node_type>); // @E1651 ret
namespace E1652 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().extract(std::declval<long&&>())); } // @E1652 call
static_assert(std::is_same_v<E1652::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::node_type>); // @E1652 ret
namespace E1653 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().insert(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::node_type&&>())); } // @E1653 call
static_assert(std::is_same_v<E1653::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>); // @E1653 ret
namespace E1654 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().insert(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>(), std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::node_type&&>())); } // @E1654 call
static_assert(std::is_same_v<E1654::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>); // @E1654 ret
template<class D> concept E1655_call = requires { p2::dv<D, std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().erase(p2::dv<D, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>()); }; static_assert(!((!std::same_as<std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator,std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>)) || E1655_call<void>); // @E1655 call
template<class D> concept E1655_ret = requires { { p2::dv<D, std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().erase(p2::dv<D, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>()) } -> std::same_as<std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>; }; static_assert(!((!std::same_as<std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator,std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>)) || E1655_ret<void>); // @E1655 ret
namespace E1656 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().erase(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>())); } // @E1656 call
namespace E1657 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().erase(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_type&>())); } // @E1657 call
namespace E1658 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().erase(std::declval<long&&>())); } // @E1658 call
namespace E1659 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().erase(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>(), std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>())); } // @E1659 call
static_assert(std::is_same_v<E1659::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>); // @E1659 ret
namespace E1660 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().swap(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>())); } // @E1660 call
static_assert(std::is_same_v<E1660::t, void>); // @E1660 ret
static_assert(!(std::allocator_traits<std::allocator<int>>::is_always_equal::value&&std::is_nothrow_swappable_v<p2::THash>&&std::is_nothrow_swappable_v<std::equal_to<>>) || noexcept(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().swap(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>()))); // @E1660 noexcept
namespace E1661 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().clear()); } // @E1661 call
static_assert(std::is_same_v<E1661::t, void>); // @E1661 ret
static_assert(!(true) || noexcept(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().clear())); // @E1661 noexcept
namespace E1662 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().merge(std::declval<std::unordered_multiset<int,std::hash<int>,std::equal_to<int>,std::allocator<int>>&>())); } // @E1662 call
static_assert(std::is_same_v<E1662::t, void>); // @E1662 ret
namespace E1663 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().merge(std::declval<std::unordered_multiset<int,std::hash<int>,std::equal_to<int>,std::allocator<int>>&&>())); } // @E1663 call
static_assert(std::is_same_v<E1663::t, void>); // @E1663 ret
namespace E1664 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().merge(std::declval<std::unordered_set<int,std::hash<int>,std::equal_to<int>,std::allocator<int>>&>())); } // @E1664 call
static_assert(std::is_same_v<E1664::t, void>); // @E1664 ret
namespace E1665 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().merge(std::declval<std::unordered_set<int,std::hash<int>,std::equal_to<int>,std::allocator<int>>&&>())); } // @E1665 call
static_assert(std::is_same_v<E1665::t, void>); // @E1665 ret
namespace E1666 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().hash_function()); } // @E1666 call
static_assert(std::is_same_v<E1666::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::hasher>); // @E1666 ret
namespace E1667 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().key_eq()); } // @E1667 call
static_assert(std::is_same_v<E1667::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_equal>); // @E1667 ret
namespace E1668 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().find(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_type&>())); } // @E1668 call
static_assert(std::is_same_v<E1668::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>); // @E1668 ret
namespace E1669 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().find(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_type&>())); } // @E1669 call
static_assert(std::is_same_v<E1669::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>); // @E1669 ret
namespace E1670 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().find(std::declval<const long&>())); } // @E1670 call
static_assert(std::is_same_v<E1670::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>); // @E1670 ret
namespace E1671 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().find(std::declval<const long&>())); } // @E1671 call
static_assert(std::is_same_v<E1671::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>); // @E1671 ret
namespace E1672 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().count(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_type&>())); } // @E1672 call
static_assert(std::is_same_v<E1672::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>); // @E1672 ret
namespace E1673 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().count(std::declval<const long&>())); } // @E1673 call
static_assert(std::is_same_v<E1673::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>); // @E1673 ret
namespace E1674 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().contains(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_type&>())); } // @E1674 call
static_assert(std::is_same_v<E1674::t, bool>); // @E1674 ret
namespace E1675 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().contains(std::declval<const long&>())); } // @E1675 call
static_assert(std::is_same_v<E1675::t, bool>); // @E1675 ret
namespace E1676 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().equal_range(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_type&>())); } // @E1676 call
static_assert(std::is_same_v<E1676::t, std::pair<std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator,std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>>); // @E1676 ret
namespace E1677 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().equal_range(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_type&>())); } // @E1677 call
static_assert(std::is_same_v<E1677::t, std::pair<std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator,std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>>); // @E1677 ret
namespace E1678 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().equal_range(std::declval<const long&>())); } // @E1678 call
static_assert(std::is_same_v<E1678::t, std::pair<std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator,std::unordered_multiset<int, p2::THash, std::equal_to<>>::iterator>>); // @E1678 ret
namespace E1679 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().equal_range(std::declval<const long&>())); } // @E1679 call
static_assert(std::is_same_v<E1679::t, std::pair<std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator,std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_iterator>>); // @E1679 ret
namespace E1680 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().bucket_count()); } // @E1680 call
static_assert(std::is_same_v<E1680::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>); // @E1680 ret
static_assert(!(true) || noexcept(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().bucket_count())); // @E1680 noexcept
namespace E1681 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().max_bucket_count()); } // @E1681 call
static_assert(std::is_same_v<E1681::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>); // @E1681 ret
static_assert(!(true) || noexcept(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().max_bucket_count())); // @E1681 noexcept
namespace E1682 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().bucket_size(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>())); } // @E1682 call
static_assert(std::is_same_v<E1682::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>); // @E1682 ret
namespace E1683 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().bucket(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>::key_type&>())); } // @E1683 call
static_assert(std::is_same_v<E1683::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>); // @E1683 ret
namespace E1684 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().bucket(std::declval<const long&>())); } // @E1684 call
static_assert(std::is_same_v<E1684::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>); // @E1684 ret
namespace E1685 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().begin(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>())); } // @E1685 call
static_assert(std::is_same_v<E1685::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::local_iterator>); // @E1685 ret
namespace E1686 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().begin(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>())); } // @E1686 call
static_assert(std::is_same_v<E1686::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_local_iterator>); // @E1686 ret
namespace E1687 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().end(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>())); } // @E1687 call
static_assert(std::is_same_v<E1687::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::local_iterator>); // @E1687 ret
namespace E1688 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().end(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>())); } // @E1688 call
static_assert(std::is_same_v<E1688::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_local_iterator>); // @E1688 ret
namespace E1689 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().cbegin(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>())); } // @E1689 call
static_assert(std::is_same_v<E1689::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_local_iterator>); // @E1689 ret
namespace E1690 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().cend(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>())); } // @E1690 call
static_assert(std::is_same_v<E1690::t, std::unordered_multiset<int, p2::THash, std::equal_to<>>::const_local_iterator>); // @E1690 ret
namespace E1691 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().load_factor()); } // @E1691 call
static_assert(std::is_same_v<E1691::t, float>); // @E1691 ret
static_assert(!(true) || noexcept(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().load_factor())); // @E1691 noexcept
namespace E1692 { using t = decltype(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().max_load_factor()); } // @E1692 call
static_assert(std::is_same_v<E1692::t, float>); // @E1692 ret
static_assert(!(true) || noexcept(std::declval<const std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().max_load_factor())); // @E1692 noexcept
namespace E1693 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().max_load_factor(std::declval<float>())); } // @E1693 call
static_assert(std::is_same_v<E1693::t, void>); // @E1693 ret
namespace E1694 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().rehash(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>())); } // @E1694 call
static_assert(std::is_same_v<E1694::t, void>); // @E1694 ret
namespace E1695 { using t = decltype(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>&>().reserve(std::declval<std::unordered_multiset<int, p2::THash, std::equal_to<>>::size_type>())); } // @E1695 call
static_assert(std::is_same_v<E1695::t, void>); // @E1695 ret
static_assert(std::is_same_v<decltype(std::unordered_multiset(std::declval<std::from_range_t>(), std::declval<std::vector<int>&&>(), std::declval<std::allocator<int>>())), std::unordered_multiset<std::ranges::range_value_t<std::vector<int>>,std::hash<std::ranges::range_value_t<std::vector<int>>>,std::equal_to<std::ranges::range_value_t<std::vector<int>>>,std::allocator<int>>>); // @E1702 guide
