// Generated by tools/spec_audit/gen_probes.py; do not edit. Names of [vector.syn] with only <vector> included.
#include <vector>
namespace E443_h { using std::vector; } // @E443 header
namespace E446_h { using std::swap; } // @E446 header
namespace E447_h { using std::erase; } // @E447 header
namespace E448_h { using std::erase_if; } // @E448 header
namespace E449_h { using std::pmr::vector; } // @E449 header
namespace E451_h { using std::hash; } // @E451 header
namespace E441_h { using t = std::strong_ordering; } // @E441 include
namespace E442_h { using t = std::initializer_list<int>; } // @E442 include
