// Generated by tools/spec_audit/gen_probes.py; do not edit. [version.syn] macros of <forward_list>.
#include <forward_list>
#if !defined(__cpp_lib_algorithm_default_value_type)
#error "__cpp_lib_algorithm_default_value_type is not defined" // @E5873 macro
#elif __cpp_lib_algorithm_default_value_type != 202603L
#error "__cpp_lib_algorithm_default_value_type is not 202603L" // @E5873 macro
#endif
#if !defined(__cpp_lib_allocator_traits_is_always_equal)
#error "__cpp_lib_allocator_traits_is_always_equal is not defined" // @E5883 macro
#elif __cpp_lib_allocator_traits_is_always_equal != 201411L
#error "__cpp_lib_allocator_traits_is_always_equal is not 201411L" // @E5883 macro
#endif
#if !defined(__cpp_lib_constexpr_forward_list)
#error "__cpp_lib_constexpr_forward_list is not defined" // @E5917 macro
#elif __cpp_lib_constexpr_forward_list != 202502L
#error "__cpp_lib_constexpr_forward_list is not 202502L" // @E5917 macro
#endif
#if !defined(__cpp_lib_containers_ranges)
#error "__cpp_lib_containers_ranges is not defined" // @E5947 macro
#elif __cpp_lib_containers_ranges != 202202L
#error "__cpp_lib_containers_ranges is not 202202L" // @E5947 macro
#endif
#if !defined(__cpp_lib_erase_if)
#error "__cpp_lib_erase_if is not defined" // @E5959 macro
#elif __cpp_lib_erase_if != 202002L
#error "__cpp_lib_erase_if is not 202002L" // @E5959 macro
#endif
#if !defined(__cpp_lib_incomplete_container_elements)
#error "__cpp_lib_incomplete_container_elements is not defined" // @E6001 macro
#elif __cpp_lib_incomplete_container_elements != 201505L
#error "__cpp_lib_incomplete_container_elements is not 201505L" // @E6001 macro
#endif
#if !defined(__cpp_lib_list_remove_return_type)
#error "__cpp_lib_list_remove_return_type is not defined" // @E6009 macro
#elif __cpp_lib_list_remove_return_type != 201806L
#error "__cpp_lib_list_remove_return_type is not 201806L" // @E6009 macro
#endif
#if !defined(__cpp_lib_nonmember_container_access)
#error "__cpp_lib_nonmember_container_access is not defined" // @E6033 macro
#elif __cpp_lib_nonmember_container_access != 201411L
#error "__cpp_lib_nonmember_container_access is not 201411L" // @E6033 macro
#endif
