// Generated by tools/spec_audit/gen_probes.py; do not edit. [version.syn] macros of <inplace_vector> (hardened implementation: compiled with -DYCXX_HARDENED=1).
#include <inplace_vector>
#if !defined(__cpp_lib_hardened_inplace_vector)
#error "__cpp_lib_hardened_inplace_vector is not defined" // @E6153 macro
#elif __cpp_lib_hardened_inplace_vector != 202502L
#error "__cpp_lib_hardened_inplace_vector is not 202502L" // @E6153 macro
#endif
