// Generated by tools/spec_audit/gen_probes.py; do not edit. [version.syn] macros of <map>.
#include <map>
#if !defined(__cpp_lib_allocator_traits_is_always_equal)
#error "__cpp_lib_allocator_traits_is_always_equal is not defined" // @E5886 macro
#elif __cpp_lib_allocator_traits_is_always_equal != 201411L
#error "__cpp_lib_allocator_traits_is_always_equal is not 201411L" // @E5886 macro
#endif
#if !defined(__cpp_lib_associative_heterogeneous_erasure)
#error "__cpp_lib_associative_heterogeneous_erasure is not defined" // @E5894 macro
#elif __cpp_lib_associative_heterogeneous_erasure != 202110L
#error "__cpp_lib_associative_heterogeneous_erasure is not 202110L" // @E5894 macro
#endif
#if !defined(__cpp_lib_associative_heterogeneous_insertion)
#error "__cpp_lib_associative_heterogeneous_insertion is not defined" // @E5899 macro
#elif __cpp_lib_associative_heterogeneous_insertion != 202306L
#error "__cpp_lib_associative_heterogeneous_insertion is not 202306L" // @E5899 macro
#endif
#if !defined(__cpp_lib_constexpr_map)
#error "__cpp_lib_constexpr_map is not defined" // @E5925 macro
#elif __cpp_lib_constexpr_map != 202502L
#error "__cpp_lib_constexpr_map is not 202502L" // @E5925 macro
#endif
#if !defined(__cpp_lib_containers_ranges)
#error "__cpp_lib_containers_ranges is not defined" // @E5948 macro
#elif __cpp_lib_containers_ranges != 202202L
#error "__cpp_lib_containers_ranges is not 202202L" // @E5948 macro
#endif
#if !defined(__cpp_lib_erase_if)
#error "__cpp_lib_erase_if is not defined" // @E5962 macro
#elif __cpp_lib_erase_if != 202002L
#error "__cpp_lib_erase_if is not 202002L" // @E5962 macro
#endif
#if !defined(__cpp_lib_generic_associative_lookup)
#error "__cpp_lib_generic_associative_lookup is not defined" // @E5993 macro
#elif __cpp_lib_generic_associative_lookup != 201304L
#error "__cpp_lib_generic_associative_lookup is not 201304L" // @E5993 macro
#endif
#if !defined(__cpp_lib_map_lookup)
#error "__cpp_lib_map_lookup is not defined" // @E6014 macro
#elif __cpp_lib_map_lookup != 202606L
#error "__cpp_lib_map_lookup is not 202606L" // @E6014 macro
#endif
#if !defined(__cpp_lib_map_try_emplace)
#error "__cpp_lib_map_try_emplace is not defined" // @E6018 macro
#elif __cpp_lib_map_try_emplace != 201411L
#error "__cpp_lib_map_try_emplace is not 201411L" // @E6018 macro
#endif
#if !defined(__cpp_lib_node_extract)
#error "__cpp_lib_node_extract is not defined" // @E6026 macro
#elif __cpp_lib_node_extract != 201606L
#error "__cpp_lib_node_extract is not 201606L" // @E6026 macro
#endif
#if !defined(__cpp_lib_nonmember_container_access)
#error "__cpp_lib_nonmember_container_access is not defined" // @E6036 macro
#elif __cpp_lib_nonmember_container_access != 201411L
#error "__cpp_lib_nonmember_container_access is not 201411L" // @E6036 macro
#endif
#if !defined(__cpp_lib_tuple_like)
#error "__cpp_lib_tuple_like is not defined" // @E6132 macro
#elif __cpp_lib_tuple_like != 202311L
#error "__cpp_lib_tuple_like is not 202311L" // @E6132 macro
#endif
