// Generated by tools/spec_audit/gen_probes.py; do not edit. [version.syn] macros of <vector>.
#include <vector>
#if !defined(__cpp_lib_algorithm_default_value_type)
#error "__cpp_lib_algorithm_default_value_type is not defined" // @E5874 macro
#elif __cpp_lib_algorithm_default_value_type != 202603L
#error "__cpp_lib_algorithm_default_value_type is not 202603L" // @E5874 macro
#endif
#if !defined(__cpp_lib_allocator_traits_is_always_equal)
#error "__cpp_lib_allocator_traits_is_always_equal is not defined" // @E5885 macro
#elif __cpp_lib_allocator_traits_is_always_equal != 201411L
#error "__cpp_lib_allocator_traits_is_always_equal is not 201411L" // @E5885 macro
#endif
#if !defined(__cpp_lib_constexpr_vector)
#error "__cpp_lib_constexpr_vector is not defined" // @E5943 macro
#elif __cpp_lib_constexpr_vector != 201907L
#error "__cpp_lib_constexpr_vector is not 201907L" // @E5943 macro
#endif
#if !defined(__cpp_lib_containers_ranges)
#error "__cpp_lib_containers_ranges is not defined" // @E5945 macro
#elif __cpp_lib_containers_ranges != 202202L
#error "__cpp_lib_containers_ranges is not 202202L" // @E5945 macro
#endif
#if !defined(__cpp_lib_erase_if)
#error "__cpp_lib_erase_if is not defined" // @E5961 macro
#elif __cpp_lib_erase_if != 202002L
#error "__cpp_lib_erase_if is not 202002L" // @E5961 macro
#endif
#if !defined(__cpp_lib_incomplete_container_elements)
#error "__cpp_lib_incomplete_container_elements is not defined" // @E6003 macro
#elif __cpp_lib_incomplete_container_elements != 201505L
#error "__cpp_lib_incomplete_container_elements is not 201505L" // @E6003 macro
#endif
#if !defined(__cpp_lib_nonmember_container_access)
#error "__cpp_lib_nonmember_container_access is not defined" // @E6041 macro
#elif __cpp_lib_nonmember_container_access != 201411L
#error "__cpp_lib_nonmember_container_access is not 201411L" // @E6041 macro
#endif
