// Generated by tools/spec_audit/gen_probes.py; do not edit. [version.syn] macros of <span> (hardened implementation: compiled with -DYCXX_HARDENED=1).
#include <span>
#if !defined(__cpp_lib_hardened_span)
#error "__cpp_lib_hardened_span is not defined" // @E6159 macro
#elif __cpp_lib_hardened_span != 202502L
#error "__cpp_lib_hardened_span is not 202502L" // @E6159 macro
#endif
