// Generated by tools/spec_audit/gen_probes.py; do not edit. [version.syn] macros of <unordered_set>.
#include <unordered_set>
#if !defined(__cpp_lib_allocator_traits_is_always_equal)
#error "__cpp_lib_allocator_traits_is_always_equal is not defined" // @E5889 macro
#elif __cpp_lib_allocator_traits_is_always_equal != 201411L
#error "__cpp_lib_allocator_traits_is_always_equal is not 201411L" // @E5889 macro
#endif
#if !defined(__cpp_lib_associative_heterogeneous_erasure)
#error "__cpp_lib_associative_heterogeneous_erasure is not defined" // @E5897 macro
#elif __cpp_lib_associative_heterogeneous_erasure != 202110L
#error "__cpp_lib_associative_heterogeneous_erasure is not 202110L" // @E5897 macro
#endif
#if !defined(__cpp_lib_associative_heterogeneous_insertion)
#error "__cpp_lib_associative_heterogeneous_insertion is not defined" // @E5902 macro
#elif __cpp_lib_associative_heterogeneous_insertion != 202306L
#error "__cpp_lib_associative_heterogeneous_insertion is not 202306L" // @E5902 macro
#endif
#if !defined(__cpp_lib_constexpr_unordered_set)
#error "__cpp_lib_constexpr_unordered_set is not defined" // @E5941 macro
#elif __cpp_lib_constexpr_unordered_set != 202502L
#error "__cpp_lib_constexpr_unordered_set is not 202502L" // @E5941 macro
#endif
#if !defined(__cpp_lib_containers_ranges)
#error "__cpp_lib_containers_ranges is not defined" // @E5951 macro
#elif __cpp_lib_containers_ranges != 202202L
#error "__cpp_lib_containers_ranges is not 202202L" // @E5951 macro
#endif
#if !defined(__cpp_lib_erase_if)
#error "__cpp_lib_erase_if is not defined" // @E5965 macro
#elif __cpp_lib_erase_if != 202002L
#error "__cpp_lib_erase_if is not 202002L" // @E5965 macro
#endif
#if !defined(__cpp_lib_generic_unordered_lookup)
#error "__cpp_lib_generic_unordered_lookup is not defined" // @E5997 macro
#elif __cpp_lib_generic_unordered_lookup != 201811L
#error "__cpp_lib_generic_unordered_lookup is not 201811L" // @E5997 macro
#endif
#if !defined(__cpp_lib_node_extract)
#error "__cpp_lib_node_extract is not defined" // @E6029 macro
#elif __cpp_lib_node_extract != 201606L
#error "__cpp_lib_node_extract is not 201606L" // @E6029 macro
#endif
#if !defined(__cpp_lib_nonmember_container_access)
#error "__cpp_lib_nonmember_container_access is not defined" // @E6040 macro
#elif __cpp_lib_nonmember_container_access != 201411L
#error "__cpp_lib_nonmember_container_access is not 201411L" // @E6040 macro
#endif
