// Generated by tools/spec_audit/gen_probes.py; do not edit. [version.syn] macros of <mdspan>.
#include <mdspan>
#if !defined(__cpp_lib_aligned_accessor)
#error "__cpp_lib_aligned_accessor is not defined" // @E5879 macro
#elif __cpp_lib_aligned_accessor != 202411L
#error "__cpp_lib_aligned_accessor is not 202411L" // @E5879 macro
#endif
#if !defined(__cpp_lib_freestanding_mdspan)
#error "__cpp_lib_freestanding_mdspan is not defined" // @E5981 macro
#elif __cpp_lib_freestanding_mdspan != 202311L
#error "__cpp_lib_freestanding_mdspan is not 202311L" // @E5981 macro
#endif
#if !defined(__cpp_lib_mdspan)
#error "__cpp_lib_mdspan is not defined" // @E6020 macro
#elif __cpp_lib_mdspan != 202406L
#error "__cpp_lib_mdspan is not 202406L" // @E6020 macro
#endif
#if !defined(__cpp_lib_mdspan_copy)
#error "__cpp_lib_mdspan_copy is not defined" // @E6022 macro
#elif __cpp_lib_mdspan_copy != 202606L
#error "__cpp_lib_mdspan_copy is not 202606L" // @E6022 macro
#endif
#if !defined(__cpp_lib_submdspan)
#error "__cpp_lib_submdspan is not defined" // @E6126 macro
#elif __cpp_lib_submdspan != 202603L
#error "__cpp_lib_submdspan is not 202603L" // @E6126 macro
#endif
