// Generated by tools/spec_audit/gen_probes.py; do not edit. [version.syn] macros of <iterator>.
#include <iterator>
#if !defined(__cpp_lib_array_constexpr)
#error "__cpp_lib_array_constexpr is not defined" // @E5891 macro
#elif __cpp_lib_array_constexpr != 201811L
#error "__cpp_lib_array_constexpr is not 201811L" // @E5891 macro
#endif
#if !defined(__cpp_lib_constexpr_iterator)
#error "__cpp_lib_constexpr_iterator is not defined" // @E5921 macro
#elif __cpp_lib_constexpr_iterator != 201811L
#error "__cpp_lib_constexpr_iterator is not 201811L" // @E5921 macro
#endif
#if !defined(__cpp_lib_freestanding_iterator)
#error "__cpp_lib_freestanding_iterator is not defined" // @E5979 macro
#elif __cpp_lib_freestanding_iterator != 202306L
#error "__cpp_lib_freestanding_iterator is not 202306L" // @E5979 macro
#endif
#if !defined(__cpp_lib_make_reverse_iterator)
#error "__cpp_lib_make_reverse_iterator is not defined" // @E6012 macro
#elif __cpp_lib_make_reverse_iterator != 201402L
#error "__cpp_lib_make_reverse_iterator is not 201402L" // @E6012 macro
#endif
#if !defined(__cpp_lib_move_iterator_concept)
#error "__cpp_lib_move_iterator_concept is not defined" // @E6024 macro
#elif __cpp_lib_move_iterator_concept != 202207L
#error "__cpp_lib_move_iterator_concept is not 202207L" // @E6024 macro
#endif
#if !defined(__cpp_lib_nonmember_container_access)
#error "__cpp_lib_nonmember_container_access is not defined" // @E6034 macro
#elif __cpp_lib_nonmember_container_access != 201411L
#error "__cpp_lib_nonmember_container_access is not 201411L" // @E6034 macro
#endif
#if !defined(__cpp_lib_null_iterators)
#error "__cpp_lib_null_iterators is not defined" // @E6043 macro
#elif __cpp_lib_null_iterators != 201304L
#error "__cpp_lib_null_iterators is not 201304L" // @E6043 macro
#endif
#if !defined(__cpp_lib_ranges)
#error "__cpp_lib_ranges is not defined" // @E6049 macro
#elif __cpp_lib_ranges != 202406L
#error "__cpp_lib_ranges is not 202406L" // @E6049 macro
#endif
#if !defined(__cpp_lib_ssize)
#error "__cpp_lib_ssize is not defined" // @E6108 macro
#elif __cpp_lib_ssize != 201902L
#error "__cpp_lib_ssize is not 201902L" // @E6108 macro
#endif
